### ISSUE TITLE
How does kvstore(memdb) sync in-memory data to disk?

### ISSUE THREAD

**Issue by cantincy** [tendermint/tendermint#10061]
I use memdb in kvstore (abci-cli kvstore). After I restart the machine, I can still get the submitted data successfully. But I don't find any functions or interfaces related to the in-memory data synchronization. Therefore, I want to ask how memdb in kvstore synchronize the in-memory data to disk?

**Comment by alijnmerchant21** [comment]
Have you tried - `abci-cli kvstore -persist=/path/to/db`

**Comment by cantincy** [comment]
No, I haven't. I know this cmd(goleveldb), it enables app to sync in-memory data to persist-dir in disk. But I do use the "abci-cli kvstore" cmd(memdb). What puzzles me is why does "abci-cli kvstore" cmd also able to persist in-memory data to disk, I don't find any functions or interfaces related to the in-memory data synchronization about "abci-cli kvstore".

**Comment by alijnmerchant21** [comment]
What version of Tendermint are you running?

**Comment by cantincy** [comment]
> What version of Tendermint are you running?

0.34.24 version
1. tendermint run
2. abci-cli kvstore
3. curl -s 'localhost:26657/broadcast_tx_async?tx="name=satoshi"'
4. restart the machine
5. curl -s 'localhost:26657/abci_query?data="name"' Then, I can get the corect value. So I think there is in-memory data synchronization mechanism in "abci-cli kvstore" like "abci-cli kvstore -persist=xxx" but I don't find any functions or interfaces about it.. XD

**Comment by alijnmerchant21** [comment]
Somethings that come to mind:

1. Even if the application (e.g., kvstore) uses an in-memory database, Tendermint itself persists blocks and other core data structures to disk. When a new block is proposed, it includes transactions, and upon block finalization, Tendermint invokes the Commit ABCI call to the application. The application is then supposed to return a hash that represents the application state after processing the transactions in that block. Even though kvstore with memdb does not persist the actual key-value pairs to disk, Tendermint persists the block and the state hash.

2. When you restart the node, Tendermint has a replay mechanism. It will replay blocks from the disk to get to the latest state. Since the blocks contain the transactions, the kvstore application will process them again (in memory) and reach the latest state. So, when you query after a restart, kvstore returns the value from the in-memory database, which was reconstructed by replaying the blocks.

3. The kvstore application does support persistence to disk using LevelDB when started with the -persistent flag. If you run abci-cli kvstore -persistent, the key-value pairs will be stored in LevelDB on disk and will persist across restarts without needing to replay blocks. (But you mentioned you didn't use the -persist flag, so this isn't the case for you.)

---------------------------------------------------------------------------------------------------------

Btw, tendermint has been frozen on 0.34.xx per Jae in the issue posted [here](https://github.com/tendermint/tendermint/issues/9972). So can't really help you. However Informal maintains their fork of Tendermint i.e. [CometBFT](http://github.com/cometbft/cometbft), which you can checkout.

**Comment by cantincy** [comment]
> Somethings that come to mind:
> 
> 1. Even if the application (e.g., kvstore) uses an in-memory database, Tendermint itself persists blocks and other core data structures to disk. When a new block is proposed, it includes transactions, and upon block finalization, Tendermint invokes the Commit ABCI call to the application. The application is then supposed to return a hash that represents the application state after processing the transactions in that block. Even though kvstore with memdb does not persist the actual key-value pairs to disk, Tendermint persists the block and the state hash.
> 2. When you restart the node, Tendermint has a replay mechanism. It will replay blocks from the disk to get to the latest state. Since the blocks contain the transactions, the kvstore application will process them again (in memory) and reach the latest state. So, when you query after a restart, kvstore returns the value from the in-memory database, which was reconstructed by replaying the blocks.
> 3. The kvstore application does support persistence to disk using LevelDB when started with the -persistent flag. If you run abci-cli kvstore -persistent, the key-value pairs will be stored in LevelDB on disk and will persist across restarts without needing to replay blocks. (But you mentioned you didn't use the -persist flag, so this isn't the case for you.)
> 
> Btw, tendermint has been frozen on 0.34.xx per Jae in the issue posted [here](https://github.com/tendermint/tendermint/issues/9972). So can't really help you. However Informal maintains their fork of Tendermint i.e. [CometBFT](https://github.com/cometbft/cometbft), which you can checkout.

Thank you very much for your help
