### ISSUE TITLE
Add events to results hash

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1007]
Should be in: https://github.com/tendermint/tendermint/pull/999

But waiting on possible changes to abci responses: https://github.com/tendermint/abci/issues/165

**Comment by ebuchman** [comment]
Instead, we should keep the tags in their own merkle tree so we can do proofs of inclusion/exclusion on the tags directly for a block

**Comment by ebuchman** [comment]
Noting that right now the results hash only includes the code and data, so we also need to accommodate the other response fields, like gas used/wanted.

**Comment by ValarDragon** [comment]
I have an idea for this described in https://github.com/tendermint/tendermint/pull/2314#discussion_r215092568, along with some ways to further compress it using accumulators.

I'll work on writing this up.

**Comment by ebuchman** [comment]
Should we consider just not merklizing the tags for now? At least until we sort out #1859 and clean up the lite client? This issue would then move from launch to first-hard-fork.

**Comment by melekes** [comment]
To give people more context (and to validate my assumptions), I will try to summarize what do we want and why:

Currently, Header#LastResultsHash only includes ResponseDeliverTx.Code and ResponseDeliverTx.Data.

We want to incorporate:

1) GasWanted and GasUsed fields from ResponseDeliverTx.
2) events (from ResponseBeginBlock, ResponseDeliverTx, and ResponseEndBlock) into LastResultsHash so that the clients were able to verify event X indeed happened in block Y. It's not clear whenever we should 

a) hash them directly OR 
b) have a separate Merkle tree hash (which gives clients proofs) OR 
c) have a separate Merkle tree hash w/ RSA accumulator.

**Comment by alexanderbez** [comment]
How does this currently work @melekes? Are the `Code` and `Data` values from each tx in a block simply concatenated?  Doesn't seem to useful atm, does it?

Also, why do options (b) and (c) add an additional 32 bytes? Would the merkle root simply replace the hash we have now yielding no effective change in size? Or am I missing something?

I'd opt for (b) as it's much simpler, and AFAIK, doesn't rely on a trusted setup. In addition, the key/value space in each of these trees should never be that too large either (unless you have hundreds of txs in a block?).

**Comment by melekes** [comment]
> How does this currently work @melekes?

we build a simple Merkle tree https://github.com/tendermint/tendermint/blob/master/types/results.go#L57

> Would the merkle root simply replace the hash we have now yielding no effective change in size? Or am I missing something?

no, they would add yet another hash - `LastEventsHash`. what you're describing is option (a)
