### ISSUE TITLE
Possibility of using Ethereum's DEVP2P for peer discovery and transport?

### ISSUE THREAD

**Issue by tymat** [tendermint/tendermint#101]
See: [this](https://github.com/ethereum/devp2p/blob/master/rlpx.md)  and [this](https://github.com/ethereum/wiki/wiki/libp2p-Whitepaper)

**Comment by jaekwon** [comment]
It's certainly possible.
What are the use-cases for switching over?

One question I have about the whole DEVP2P stack is, do we really want the following property?
>   Ubiquitous: The same peer-set/-network should be able to be used for all protocols.

So DEVP2P tries to cram an arbitrary collection of services into the same port.  Is that what we really want?

What I want, I think, is to have port connections dedicated for each decentralized-application (e.g. bitcoin, tendermint, ...), and to share the library amongst each application, but have separate connections for each decentralized-application.  And with fixed channel identities (instead of dynamically allocating them) each connection's read/write dump will be easier to debug.

Also, they use nibbles... which are half-bytes.  It makes reading hex dumps more confusing for me.  Am I the only one?

But that said, no reason why we couldn't speak DEVP2P if we needed to.

**Comment by tymat** [comment]
If you read carefully I don't think the idea is to put everything in one port.  

> Transport-layer Agnostic: TCP/IP v4 and v6 are provided with initial protocol specifications. Others should be able to be added on at later dates without altering the API. Mesh networking devices could even ultimately implement this natively.

What your quote says is that it should be the same set of peers talking different protocols and DEVP2P handles peer discovery.  If your client supports a set of sub-protocols  then it should be able to peer you up with those clients that also support the same set.

**Comment by ebuchman** [comment]
closing for now until there is sufficient reason/incentive to re-open. slash move to https://github.com/tendermint/go-p2p
