### ISSUE TITLE
consensus: enable >= 1/3 val set changes

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1022]
Let's say that every 1000 Ethereum blocks (1 epoch) an application wants to use the state of a smart contract to update the validator set. During the first epoch the validator set is `A B C`. Due to changes in the smart contract on Ethereum the validator set for the second epoch is `D E F`. Any user can submit the latest state of Ethereum to the Cosmos application to cause the change in validator set with a special transaction. The application now returns a validator set which is completely different (i.e. 100% change). According to #1004 Tendermint Core now rejects that block.

The options are that either the app receives that change transaction and then bisects it until it hopefully finds a way to do it in less than 1/3 or that the submitter has to split the transactions. The problem though is that in case there is no <1/3 an app has to reset it's entire state. The ideal solution would be to make #1004 a config option to enable apps that have delegation done outside of their chain.

Of course, light clients would have to reconfirm the validator hash.

**Comment by ebuchman** [comment]
I don't understand. Isn't this an app level thing? The app can return changes to the valset whenever it needs to. I don't see how this requires a change to tendermint. Please re-open with clarification if I'm misunderstanding.

**Comment by adrianbrink** [comment]
Let's say that every 1000 Ethereum blocks (1 epoch) an application wants to use the state of a smart contract to update the validator set. During the first epoch the validator set is `A B C`. Due to changes in the smart contract on Ethereum the validator set for the second epoch is `D E F`. Any user can submit the latest state of Ethereum to the Cosmos application to cause the change in validator set with a special transaction. The application now returns a validator set which is completely different (i.e. 100% change). According to #1004 Tendermint Core now rejects that block.

The options are that either the app receives that change transaction and then bisects it until it hopefully finds a way to do it in less than 1/3 or that the submitter has to split the transactions. The problem though is that in case there is no <1/3 an app has to reset it's entire state. The ideal solution would be to make #1004 a config option to enable apps that have delegation done outside of their chain.

**Comment by adrianbrink** [comment]
Of course, light clients would have to reconfirm the validator hash.

**Comment by ebuchman** [comment]
Ok - we can make that a configurable. But it's not safe (ie. light client cant verify) without making changes to the header that we dont really want to ...

**Comment by adrianbrink** [comment]
I think we can just force light clients to resync the validator set hash.

**Comment by adrianbrink** [comment]
Changes to header are going to involve setting a `NextValidatorSetHash` in the header. This way we can safely update 100% change in the validator set as long as enough old validators sign off on it.

**Comment by KrzysiekJ** [comment]
I second this issue. An application doesn’t need to limit degree of validator changes to allow light client syncing. Here is how it is done in Ercoin:

Blocks are divided into epochs and each epoch has a completely different validator set. When quarter of epoch passes, drawing of validators for the next epoch is spawned. When three quarters of epoch pass, results of drawing (which is going to use an external source of entropy) are yielded. From that point, set of validators in the next epoch is known and it is encompassed in the application hash. A light client can therefore fetch a block signed by old set of validators, fetch the set of future validators from elsewhere and confirm that that set is contained in the app hash signed by trusted validators. This requires likely less steps than in case of gradual changes (and there is no need to do bisecting, as block heights at which validators will change are known in advance — modulo there may eventually be some unplanned changes like slashing malicious validators).

Unfortunately, due to restriction imposed in #1004, such applications are banned now, which means that Ercoin basically stopped working in 0.15.0. So the most immediate need for me is to revert the restriction. If an application developer wants to limit changes to < 1⁄3 of votes, then he needs to implement it on the server side anyway. Checking it on the client side won’t change the actual logic of ABCI server and may act as a sanity check only… but if one wants to make assertions about state transitions of his application, then he may write a property test. Client software should not dictate applications, if it is not necessary, how they should behave (though the limitation of light client syncing should be documented, if it prevails). Furthermore, there may be cases where limiting the quantity of change may be a security issue. A key of validator that owns more than 1⁄3 of votes may be compromised and in such case there may be an urgent need to slash/replace that validator. Due to #1004, it now requires a hard fork (or doing this gradually) and furthermore it doesn’t prevent the chain from stopping in case an attacker decides to continue using the key.

There may also exist applications that don’t care about light client syncing at all.

Though Ercoin allows validating changes of validator set via its app hash, it may be a bit cumbersome as a client needs to implement custom logic and fetch validator set from elsewhere (it can’t be deducted from block, as there is some additional data hashed). Therefore adding `NextValidatorSetHash` is desirable.

**Comment by KrzysiekJ** [comment]
Another reason to revert #1004: it seems that the current implementation of < 1⁄3 restriction is buggy. That is, if we have the following validator set:

```
{"foo": 64}
```
and it transforms to the following:
```
{"foo": 52,
 "bar": 12}
```
, then calculated change is `((64 - 52) + 12) ⁄ 64 > 1⁄3`, whereas the real change is `12 ⁄ 64 < 1⁄3`.

Also if there is a change in total voting power, then it is not taken into account in `changeInVotingPowerMoreOrEqualToOneThird` , which may also lead to faulty results (in case when voting power scales).

**Comment by ebuchman** [comment]
> From that point, set of validators in the next epoch is known and it is encompassed in the application hash.

Right, that's great! But we also wanted to provide native support in Tendermint for the light-client proofs, and enable the validator set to change from one block to the next. 

But I see that it was not the right idea to put the restriction in on Tendermint side. Let's remove it!

**Comment by melekes** [comment]
> Also if there is a change in total voting power, then it is not taken into account in changeInVotingPowerMoreOrEqualToOneThird

what do you mean?

> then calculated change is ((64 - 52) + 12) ⁄ 64 > 1⁄3, whereas the real change is 12 ⁄ 64 < 1⁄3.

that depends on definition of change.

**Comment by KrzysiekJ** [comment]
Anton Kaliaev writes:

>> Also if there is a change in total voting power, then it is not taken into account in changeInVotingPowerMoreOrEqualToOneThird
>
> what do you mean?

Let’s say that validator A has power 1 and validator B has power 4, and that after EndBlock they have power 10 and 40, respectively. Then there is no change in relative voting power (in which we are interested), but there is change in absolute values (which doesn’t interest us per se).

>> then calculated change is ((64 - 52) + 12) ⁄ 64 > 1⁄3, whereas the real change is 12 ⁄ 64 < 1⁄3.
>
> that depends on definition of change.

With the current definition (removed in #1201), if voting power changes to a completely different set of validators, then the calculated change will be 200%.

**Comment by ebuchman** [comment]
Fixed in https://github.com/tendermint/tendermint/pull/1201. Thanks

**Comment by ebuchman** [comment]
ok NextvalidatorSetHash is backing a come back: https://github.com/tendermint/tendermint/issues/1313 @KrzysiekJ
