### ISSUE TITLE
Allow ABCI app to return three different statuses (reject, retry, okay)

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1062]
@paulperegud
  
This is related transaction ordering returned from the app.

**Comment by adrianbrink** [comment]
The reasoning for this feature is that a client may want to send many transactions at once. Currently only the transaction with the correct nonce is guaranteed to get accepted. If any other transaction was processed before (nonces are out of order) and the app rejects them they are ejected from the mempool.

It would be ideal if the app returns three different statuses:
Okay - Transaction was correct and has affected the state. **Transaction affected a change.**
Retry - Transaction is valid but cannot be processed at the moment. For example the nonce could be 5 too high but the tx is correctly signed. **Transaction is not yet accepted but should be retried.**
Reject - Transaction is bonkers and will never get accepted. **Transaction will never be accepted.**

**Comment by pdobacz** [comment]
For some background, the `retry` would be used when, for example, a particular transaction has its nonce too high, i.e. it evidently builds on top of an other transaction, that might have been received later, due to reordering in the network.

So an initial rough sketch that came to mind was to have "buckets" of transactions to be retried. Any transaction can be put off till later (`retry`) to a certain "bucket", e.g. one related to a particular sender's address. Also any transaction (considering it's an `okay`) can trigger a replay of a certain bucket. So, let's assume there's an account `0xabcd`, following transactions are `CheckTx`-ed:

`from: 0xabcd, nonce: 0` - `okay`
`from: 0xabcd, nonce: 0` - `reject` - nonce too low
`from: 0xabcd, nonce: 2` - `retry` - add to bucket `0xabcd`
`from: 0xabcd, nonce: 3` - `retry` - add to bucket `0xabcd`
`from: 0xabcd, nonce: 1` - `okay` - trigger bucket `0xabcd`
from bucket `from: 0xabcd, nonce: 2` - `okay` - trigger bucket `0xabcd`
from bucket `from: 0xabcd, nonce: 3` - `okay`

**NOTE 1**: the very first  and last `okay`s also trigger bucket `0xabcd` but are no-ops
**NOTE 2**: the happy assumption above is that `3` goes after `2`. In the real world, one probably would like to apply "ordered buckets" that are ordered by some key (in our scenario - by nonce)
**NOTE 3**: the process of adding to (ordered) bucket and triggering a bucket would be done via the return value of `CheckTx`
**NOTE 4**: I think one cannot just handle such buckets within the ABCI app, because it would break the notion of transaction correctness fed to Tendermint Core, transaction broadcast mechanism and alike
**NOTE 5**: `retry` doesn't cause rebroadcasting the tx

--

Having said all that, now I'm starting to wonder that maybe this isn't a problem at all for Tendermint (unlike for [Ethereum](https://ethereum.stackexchange.com/questions/2808/what-happens-when-a-transaction-nonce-is-too-high)), due to some differences in block formation and transaction gossiping? So to begin with, can someone confirm such transaction reordering is at all possible with Tendermint?

**Comment by ethanfrey** [comment]
In the absence of byzantine behavior by a node (different binary) all TX are processed Fifo in mempool. So if you broadcast a sequence with increasing nonce all to one node, they will be received in order by all nodes.

If you send the same sequence to different nodes, there is no guarantee, even if you send them in the same temporal order, we just guarantee Fifo in each connection

**Comment by mdyring** [comment]
Apart for the fact that it might not be an issue with Tendermint, an app that wish to be robust against reordering of TXs (up to some upper bound) could implement a nonce windowing mechanism similar to what we are doing:

https://github.com/block-finance/cb-ledger/blob/develop/business_logic/signer.hpp

This also allows for signing TXs out of order (as might be the case for multisig).

**Comment by pdobacz** [comment]
Thanks @mdyring, if retries of txs will turn out to be a no-go, then this definitely is an option worth considering

**Comment by ebuchman** [comment]
Allowing out of order nonce windowing in the app itself is an interesting idea. 

Unfortunately supporting `retry later` in Tendermint right now would add too much complexity to the mempool, especially as it adds new avenues for DoS. Ideally the mempool is kept simple so it can stay fast, and responsibility is delegated to the client to send their txs in order - they can use websockets to get relatively high throughput with a single node.

**Comment by pdobacz** [comment]
@ebuchman ok, I think I got confused on the term "broadcast to a single node". Let's assume I am X. I call `broadcast_tx_sync` on node `A`. `A` is connected to `B` and `C`. `B` and `C` are connected to validator `D` (diamond shape), who proposes a block (tx ordering).

If I do `broadcast_tx_sync` on A in order, is D guaranteed receive my txs in order?

First I thought that the answer is "no such guarantee", and thus continued the discussion. I am not sure anymore. Please confirm and thank you very much for your ongoing help and patience!

**Comment by adrianbrink** [comment]
The nodes gossip the transactions in order. So if node `A` has transaction `t, d, f, j` and then node `B` will also have the same ordering of transactions in its mempool and hence would propose them in the same order. @pdobacz
