### ISSUE TITLE
Allow ABCI application to handle fees

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#1065]
If Tendermint core handles the fees application developers will not be able to implement different fee strategies. However an application might not want to follow the fee mechanism that we decide on for Tendermint Core / Gaia.

Tendermint Core can implement a maximum blocksize via EndBlock. In EndBlock the application returns the next blocksize. This way an application can dynamically adjust the blocksize or have it be a consensus parameter which can be set through set_option. On CheckTx the application would return gasEstimated and Core would only propose blocks where `blocksize <= sum of gasEstimated for every TX`.

**Comment by ethanfrey** [comment]
We do return estimated gas and fee as part of checktx already (or at least on feature branches, scheduled for release with 0.15)

Proposal and implementation:
https://github.com/tendermint/abci/issues/57
https://github.com/tendermint/abci/pull/130

We also allow the application to set the blocksize, maxgas, etc in endblock as part of the consensus parameters:
https://github.com/tendermint/tendermint/pull/972
https://github.com/tendermint/tendermint/pull/972/files#diff-04bd9182a7e7ae3e99e54a96182ab90e

The issue is that mempool currently does nothing with this information currently, but I think this is a work in progress. In other words, the plumbing is done, let's see what the last functionality is needed in mempool to make this a reality.

The original proposal in https://github.com/tendermint/abci/issues/57 was to do a rough approximation of the napsack problem, sorting tx by fee/gas in the mempool and adding them until sum(gas) > max(gas). We have multiple dimensions, as there is a maxbytes as well, so maybe try both sortings to find which allows maximum fees in the block while respecting the limits.

**Comment by jaekwon** [comment]
Besides what @ethanfrey said,

> Tendermint Core can implement a maximum blocksize via EndBlock. In EndBlock the application returns the next blocksize. This way an application can dynamically adjust the blocksize or have it be a consensus parameter which can be set through set_option.

Consensus parameters are not set via set_option.  Set_option does not affect the behavior of the consensed app state.

> @ethanfrey: The original proposal in tendermint/abci#57 was to do a rough approximation of the napsack problem, sorting tx by fee/gas in the mempool and adding them until sum(gas) > max(gas). We have multiple dimensions, as there is a maxbytes as well, so maybe try both sortings to find which allows maximum fees in the block while respecting the limits.

Sounds like a fun problem to solve.
