### ISSUE TITLE
Option to disable date/time log prefixing

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1096]
from https://github.com/cosmos/gaia/issues/102

- this could be implemented as a `--log_level` option

cc @mdyring

**Comment by melekes** [comment]
we can add one more option: `--log_format` by analogy with Java's simple formatter https://stackoverflow.com/questions/194765/how-do-i-get-java-logging-output-to-appear-on-a-single-line

`--log_format="$severity[$time] $message"` // default
`--log_format="$severity $message"` // mrdyring

**Comment by mdyring** [comment]
+1 for flexibility of --log_format

**Comment by srmo** [comment]
signed, even if Java is the new COBOL, we can learn a thing or two ;)

**Comment by odeke-em** [comment]
Does this issue belong to tmlibs @melekes?

**Comment by odeke-em** [comment]
I've mailed the first part of it which is getting it first in tmlibs https://github.com/tendermint/tmlibs/pull/163

**Comment by xla** [comment]
Before we implement templating for logging, can we explore how severe the drawbacks are from having time prefixed log lines? The original issue states that systemds journaling already prefixes time, besides a couple more bytes in storage what is the issue with that?

**Comment by mdyring** [comment]
The main drawback (on systemd) is that it looks messy and is not "standard behavior" for console output AFAIK. 

Apart from that, yes it is just storing a few more bytes. It does make perfect sense to include the timestamp, if the output is piped to a log file somewhere. 

I like the flexibility of log_level suggested above, so that a sysadmin can decide what is appropriate.

**Comment by xla** [comment]
@mdyring Thanks for the insight, when you say messy looks is that for when examining the logs as a human?

Using log level as a way to control detail of log line sounds like a conflict as log leves are used to express severity. Formatting shouldn't be necessary if log lines are structured and have named fields as the position of each field is not of importance anymore. Instead of having a custom language for templating, the logger should have a standard set of fields which can be overwritten in the configuration. Which in turn sounds well-suited to be part of the bigger story of improving the logging in #1212. Would be good if we consolidate the requirements and discussions.

**Comment by mdyring** [comment]
log_level was a typo, meant log_format (fixed in above as well). 

I mean messy in a number of sense: Certainly, it would be confusing as a human to view the log with duplicate timestamps, but I also mean messy in the conceptual sense.

Basically, compare it to a syslog message. It contains an embedded timestamp, so it is redundant and confusing to see a timestamp appear in the text part (and perhaps formatted in a locale the viewer might not expect).

**Comment by xla** [comment]
> log_level was a typo, meant log_format (fixed in above as well).

Sorry, could have guessed. :)

> I mean messy in a number of sense: Certainly, it would be confusing as a human to view the log with duplicate timestamps, but I also mean messy in the conceptual sense.
> 
> Basically, compare it to a syslog message. It contains an embedded timestamp, so it is redundant and confusing to see a timestamp appear in the text part (and perhaps formatted in a locale the viewer might not expect).

Here be dragons, as you hint at duplication of information, but those are two different datapoints. It might not be apparent immediately but one is an application level observation while the other one is informing about when the log line entered the pipeline. In most cases they might be identical (assuming both rely on system clock), there might be scenarios where that isn't the case, remote log facilities, etc.

Not trying to make a point that the request is not valid, just want to raise awareness that the meaning of those bytes is more subtle and operators well deserve a way of controlling what pieces of info show up in the logs and I propose to consolidate requirements for logging improvements in #1212.

**Comment by ebuchman** [comment]
Thanks folks. Let's consolidate conversation in #1212 .

Will close this for that
