### ISSUE TITLE
Validator key rotation

### ISSUE THREAD

**Issue by nickray** [tendermint/tendermint#1136]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

The current implementation has the following definition of validator (according to [spec](https://github.com/tendermint/tendermint/blob/develop/docs/specification/new-spec/state.md))
```
type Validator struct {
    Address     []byte
    PubKey      PubKey
    VotingPower int64
}
```
This implies there is a corresponding private key which is **very valuable**. In production, either the key is copied to the validating server (at risk of theft), or according to current best practice the key pair is generated on a HSM. In which case the risk of theft is lowered, but still non-zero. Additionally, failover of the validating server becomes impossible unless one has a clone of the HSM pre-attached to a different machine. I remark that in case of theft, there is no on-chain mechanism to deal with this, except a slow painful death by slashing (in Cosmos) for those who do not unbond fast enough...

In order to be concrete, as a basis for discussion, **I propose changing the validator struct to** the following:
```
type Validator struct {
    Address       []byte
    OwningPubKey  PubKey  // used to authorize changes of SigningPubKey
    SigningPubKey PubKey  // used to sign proposals+votes
    VotingPower   int64
}
```
Where
* the `OwningPubKey` can send a transaction to change the `SigningPubKey` to an arbitary value
* the consensus protocol would generally accept such a transaction.

From my understanding of the [consensus reactor](https://github.com/tendermint/tendermint/blob/develop/docs/specification/new-spec/consensus.md), the `ProposalMessage` and `VoteMessage` would be signed by the current `SigningPubKey`, whereas a new "SigningKeyChangeMessage" would be added, to be signed by the `OwningPubKey`.

Effectively, the `OwningPubKey` becomes a certification authority for its `SigningPubKey`, taking cues from PKI theory:
* Setting the SigningPubKey to zero means revoking the key.
* Setting a new non-zero value means rotating the key.

I believe this change would not weaken the safety of the protocol, but I do not have a deep enough understanding to make such a claim. Does it?

This proposal allows keeping the `OwningPubKey` completely offline and separated from the operational setup. It also allows anonymous owners of bonded stake (in the Cosmos case) to listen to changes in the `SigningPubKey`.

Possible additional extensions (not proposed here, mentioned to illustrate the advantage of separating the roles of the current "one PubKey to rule them all"):
* field `Operational bool`, indicating if a validator is in operation. Alternatively, a zero `SigningPubKey` value could imply that a validator is not operational
* additional subkeys could be added, e.g. `MessagingPubKey`, with associated transaction types, communicating for instance various fees the validator extracts

**Comment by nickray** [comment]
Clarification in response to a question by "bascule" in the validator chat.

AFAIK how things currently work is:
* Tendermint currently has a list of (validator, weight) pairs (independently of ABCI apps like Cosmos)
* Initial distribution comes from the genesis block
* Updates to this list are generated by polling the app
* Cosmos updates the list according to when accounts bond or unbond Atoms to validator node pubkeys

So:
* the Cosmos app would need a concept of "owner" of a validator (the above owning key, maybe rather an owning address). This is the root key in other terminology.
* this owner can send a Cosmos message to replace the signing pubkey. This entails revoking the old key. 
* the Tendermint protocol technically only still only needs the signing pubkey. If it were aware of the owner concept however, it could maintain better continuity (e.g. for the round based proposer election)

**Comment by tarcieri** [comment]
A more traditional alternative approach to solving this problem is to use some sort of PKI with support for certificate chains and certificate revocation lists CRLs. When I say "some sort" it could be the X.509 PKI, but it doesn't have to be: several things use artisanal homebrew certificates, including dnscrypt and ØMQ.

You'd want to make sure whatever certificate system is deployed has a basic feature set, though:

- A root CA certificate/key, analogous to `OwningPubKey` above, ideally kept completely offline
- Leaf certificates, analogous to `SigningPubKey` above
- Certificate revocation lists (CRLs) containing a blacklist of previously issued keys which should no longer be trusted
- Optional: intermediate certificates, e.g. you could have an offline root, and an online intermediate. This would be helpful for replacing CRLs with online status checks or a "stapling" mechanism

The private key associated with the root certificate in such a system is used to sign both the leaf certificates and the CRL. The CRL needs to be online somewhere (in the X.509 PKI the root CA cert contains a URL where the CRL can be fetched from, for example). It can be fetched the first time a particular leaf certificate is seen and then cached until it expires.

If there is a need to rotate/revoke a key, a new leaf cert can be issued using the root CA, and a new CRL signed. When a new certificate is seen for the first time, the CRL should be re-fetched, and if it's newer than the old one used in its place.

An alternative approach to revocation is the one used by GPG: whenever a leaf is issued, a "revocation certificate" is also issued, which needs to be stored securely but is less sensitive than the root CA cert, so it can be kept online somewhere. If lost, it can be regenerated using the root CA cert. Once it's been published, anyone who sees it should disavow the key it identifies.

The main advantage of a PKI approach over the one @nickray gave is it doesn't require coordination with other validators to issue new leaf certificates, allowing validators to perform key rotations in a coordination-free manner. It's arguably a bit more complicated but stateless from the perspective of the other validators. It's also a more traditional approach to solving this particular problem, and therefore fairly well-studied with lots of precedent to draw on.

A disadvantage would be handling of certificate chains: to validate a signature now, you need the whole chain. Naively you'd have to store the whole chain with every signature, which would significantly increase the space required for signatures. In a more optimized approach, you could pass a certificate chain the first time it is ever used, and from then on refer to the entire chain using some compact identifier, which ideally should be no bigger than a hash.

I'm not saying you should use X.509 in particular,  but Go does happen to have one of the most fantastic X.509 libraries ever written built into its standard library:

https://golang.org/pkg/crypto/x509/

Cloudflare wrote a CA which is effectively just a wrapper around it:

https://github.com/cloudflare/cfssl

I think it wouldn't be too hard to write some cosmos-specific tooling for managing an offline CA and using X.509 in a not-completely-obnoxious manner. That is to say, rather than actually using cfssl, you can look to it for guidance about how to write an X.509 CA using the Go standard library, and then produce some cosmos-specific tooling which fits into the existing key generation workflow.

I can look into the state of specification work for using X.509 with Ed25519 but my understanding is it's in "rough consensus and running code" stage and it should just be a matter of using the proper OIDs to identify Ed25519.

With a hypothetical X.509 PKI, the validator struct would probably look like this:

```
type Validator struct {
    Address     []byte
    RootCert    []byte
    VotingPower int64
}
```

**Comment by nickray** [comment]
Oh my :)

What I don't like about this solution is the external URL it introduces to fetch and update the CRL. Have you thought through the failure modes of this?

It also seems as if one cannot simply start at the genesis block and iterate through the blocks and transactions to verify the chain?

I think we agree that the root key does not belong near any production node in a data center, and the question of what to do if a production signing key/leaf certificate is compromised needs to be thought out before rolling out Cosmos.

Would be good to have some feedback from @ebuchman

**Comment by tarcieri** [comment]
> What I don't like about this solution is the external URL it introduces to fetch and update the CRL. Have you thought through the failure modes of this?

Anyone dealing with an X.509 PKI which uses CRLs has thought through the failure modes of this, a line of inquiry which has lead to things like OCSP to replace CRLs. Failure to fetch the CRL fails closed. CRLs have a number of issues and may not be the best solution, but they're an easy enough one to get started with.

> It also seems as if one cannot simply start at the genesis block and iterate through the blocks and transactions to verify the chain?

This generally seems like a difficult problem unless you store the entire set of certificates which were valid at a given point in time on-chain. As it were, systems like Certificate Transparency and Revocation Transparency actually do that in practice, but implementing something like that out-of-the-gate sounds rather difficult.

In your proposal, how do you track which `SigningPubKey`s were valid at a given point in time? It seems like validators would only have a point-in-time view of which `SigningPubKey`s were valid, which runs afoul of the same issue that they have no context for how to interpret historical `SigningPubKey`s.

**Comment by nickray** [comment]
The validators are a dynamic set, defined by Cosmos app, right? The idea is to model the owner of a validator in the app. So the owner can send a transaction changing the signing key (similar to `gaia client tx declare-candidacy/delegate etc.). When this transaction is committed in a block, it takes effect. Am I missing something?

**Comment by tarcieri** [comment]
If that information is tracked on-chain, then great. I'm still unclear what the workflow for that would look like though, particularly in terms of using the offline root key to, in effect, certify a new signing key, and then publishing that information to the rest of the validators. Somewhere in there you will need to roll what is in effect a simple certificate system, and then publish those certifications.

**Comment by nickray** [comment]
It's a simplistic model.

Effectively, the private key of the "owning address" plays the role of certificate authority, having the same vulnerability as the private key of the current "validator PubKey" currently has, except it can be kept safely offline. Certifying a new signing key means a) generating a random new one, b) sending something like `gaia client tx set-signing-pubkey <validator identifier> <new pubkey>`.

I think my proposal evolved a little since formulated. There is no need for an OwningPubKey, just for a unique identifier to keep proposer right rotation consistent. Shall I try and rewrite it?

**Comment by tarcieri** [comment]
Yes, please do rewrite it, however I think your description above is missing a few steps. You need the following at a minimum to support an offline root:

1. Generate new signing private key (i.e. in an HSM) and obtain the pubkey
2. Copy (at a minimum) signing public key to offline root signer. In more traditional PKIX nomenclature the request copied to the offline signer would be a certificate signing request (CSR)
3. Sign the pubkey/CSR, obtaining a signature and/or certificate
4. Copy the signed certificate from the offline signer to the validator node
5.  Inform the other validators of the new signing key. Note this needs both the new public key and the signature from the root key.

One nice thing about certificates is they encapsulate both the public key and the signature in a single message. So you could do something like:

```
 gaia client tx set-signing-cert <validator identifier> <new certificate>
```

**Comment by tarcieri** [comment]
So based on this discussion, I'd recommend something like @nickray's approach, but in conjunction with some sort of simple, non-X.509 certificate system to encapsulate signing requests and signed public keys.

A certificate would need to include the `SigningPubKey` and signature from the `OwningPubKey` at a minimum.

I would strongly suggest they also contain the following:

- Algorithm identifiers: the algorithm ID + public key are known as Subject Public Key Info (SPKI) in X.509, and a "SPKI hash" identifies the key
- Nonce: I would recommend this be uniformly random, at least 128-bits, and located at the beginning of the certificate, as nonces of this nature can defend against chosen prefix collisions on whatever hash function is used to compute the certificate digest
- Issuer: the certificate itself commits to the signer

**Comment by nickray** [comment]
Coming back to this with full support! In my proposal, the mental model was that a Cosmos account "owned" the validator, and so the account's signature was part of the message sent. But I completely agree that the root key of the validator should be a separate entity (of any account key).

So with this, any account can send the signed certificate (which is also nice) and everything is recorded in the blockchain.

I hope this will make it into the launch release!

**Comment by jackzampolin** [comment]
Has any work been moved forward here @tarcieri ?

**Comment by tarcieri** [comment]
There's been a little recent discussion about this /cc @zaki @ebuchman

**Comment by marbar3778** [comment]
>1. problem definition
>- validators cannot rotate its consensus key
>- validators cannot rotate its validator operator control key(wallet key)
>2. new feature
>- validators can rotate its consensus key by transaction
>- validators can rotate its validator operator control key(wallet key) by transaction
>3. things to discuss
>- lots of location in current codebase should be revised to allow rotation of keys
>- blockchain should store such mapping of each key
>- mapping storage needs consideration of pruning strategy, related to slashing module
>**B-Harvest will tackle this issue after enough communication with tendermint devs.**
- from issue #4060 - @dlguddus

**Comment by dlguddus** [comment]
This thread is too old to have adaquate context I guess.. But because you already closed the new issue, let's continue the discussion here then.

**Comment by alexanderbez** [comment]
Has rotation limits been discussed yet? From the state-machine pov, it'll have to track every single key for an unbonding period duration.

**Comment by dlguddus** [comment]
From internal discussion, limit is inevitable, and default is # of days for unbonding period

**Comment by tarcieri** [comment]
> This thread is too old to have adaquate context I guess..

I'd agree with that. Reading some of my old comments, they seem a bit archaic.

I think the main thing to keep in mind is how this factors into IBC. For the security of the system, the key rotation interval needs to be equivalent to the unbonding period (which is equivalent to IBC's timeouts).

Large production KMS systems (e.g. Google Cloud KMS) have some insights as to the stages and cadences for key rotation:

https://rwc.iacr.org/2018/Slides/Kanagala.pdf

<img width="933" alt="Screen Shot 2019-10-15 at 5 19 30 PM" src="https://user-images.githubusercontent.com/797/66878708-0a518100-ef70-11e9-8241-78a177861eee.png">

In particular this staggered cadence has the following three stages:

- **active**: new key is recognized as valid, but not the primary one in service (i.e. old key is still recognized as valid). This is a transitional period between the old and new keys. 
- **primary**: new key enters service, old key is scheduled for revocation
- **scheduled for revocation**: previously active key is removed from service

You can imagine this mapping to Tendermint as:

- **bond**: validator's account key bonds a new `consvalpub` while an old one is **primary**, waits for the unbonding period (3 weeks)
- **active**: once new `consvalpub` is marked active, validator's account key can be used to schedule the new key to be set to **primary**, and the old key to **scheduled for revocation**. Out of paranoia I'd suggest waiting for the unbonding period again (3 weeks)
- **primary**: new key enters service, and old key is now scheduled to be revoked. Both keys are still valid for this timestep.

**Comment by dlguddus** [comment]
@tarcieri that is a great insight! Thank you for sharing that. Because mostly users do not need to rotate their keys more than one time in a unbonding period, limiting rotation to one time per unbonding period seems reasonable, considering suggested security risk.

Some questions arise.
1) many rotation usecases need immediate revocation of old key. If the old key is valid for unbonding period, it lose the most important advantage of this feature, immediate security fix by making old key useless instantly.(imagine stolen valconskey situation)

2) another thing to discuss : self-delegation control when a validator rotate the valoper control coldkey(wallet key). Self delegation will stay in old key so after rotation, the validator will have zero self-delegation, result in jailing. We can implement force transfer of this self delegation into new rotated key, but want to ask if there exists more elegant way.

**Comment by cwgoes** [comment]
> I think the main thing to keep in mind is how this factors into IBC. For the security of the system, the key rotation interval needs to be equivalent to the unbonding period (which is equivalent to IBC's timeouts).

This is not strictly necessary as long as old keys are kept around for the duration of the unbonding period so that the validator can be slashed if an equivocation within the unbonding period is discovered (IBC's security model is identical to the general light client's security model.

However, frequent key rotations will make bisection less efficient, since fewer headers will be able to be skipped by the light client, so limiting the rate of key change is prudent. I think it might be sufficient to charge validators some nominal amount for changing their key, which could be directed to the community pool - that would "internalize the externality" of more expensive light client verification. Rate limiting to once per unbonding period or comparable duration is also probably fine.

**Comment by dlguddus** [comment]
@cwgoes thanks for clarification. All clear now!

**Comment by dlguddus** [comment]
FYI, we want to separate the wallet key rotation and consensus key rotation because each of them has very high risk of security on codebase changes. We thought it is safer to implement consensus key rotation and then work on the wallet key rotation later.

Below is little bit more detailed specs on this topic

## 1. Objectives

- to provide validators ability to rotate their validator consensus key

## 2. Use-case Overview

- how to rotate consensus key mapping to validator operator?
    - create new random consensus key
    - create and broadcast a transaction(RotateValCons) that the new consensus key is coupled with the validator operator with signature from validator wallet key
    - old consensus key becomes useless after the update of key mapping state on-chain
    - start validating with new consensus key

## 3. Considerations

- consensus key mapping information management strategy
    - blockchain stores history of each key mapping changes.
    - gaiad can search (from kvstore) corresponding consensus key paired with given validator operator for any arbitrary height in recent unbonding period
    - gaiad does not need any historical mapping information which is more than unbonding period past
- limits
    - a validator cannot rotate its consensus key more than N time for any unbonding period, to prevent spams
    - a validator should contribute X atoms to community fund to rotate its consensus key, also to prevent spams
    - parameters can be decided by governance and stored in genesis file
- slash module
    - slash module can search corresponding consensus key for any height so that it can decide which consensus key is supposed to be used for given height
- pruning
    - blockchain does not need to keep the historical key mapping after unbonding period past.
    - when pruning is on, a node prunes all historical key mapping past unbonding period
- further implementation after this
    - rotation of validator wallet key
    - currently, validator wallet key and validator operator key is having identical root.
    - implementing rotation of validator wallet key will create a lot of necessary structural changes in original codebase

**Comment by dlguddus** [comment]
After some time of investigation on this topic, we realized that the implementation needs almost no codebase change in tendermint and most changes will be on cosmos-sdk. The reason is that tendermint only has consensus key and hold no information about valoper. Also slashing module is completely independent from tendermint.

Therefore we moved this issue to cosmos-sdk repo : https://github.com/cosmos/cosmos-sdk/issues/5231

**Comment by ebuchman** [comment]
Should we close this on the tendermint side then?

**Comment by dlguddus** [comment]
I think the issue is being solved by https://github.com/cosmos/cosmos-sdk/issues/5231 so I think we can close.

**Comment by dualsystems** [comment]
Hello,
what reason migrate that option from tendermint to cosmos-sdk ?
I think cosmos-sdk is for hi-level application develop.

**Comment by marbar3778** [comment]
> Hello,
> what reason migrate that option from tendermint to cosmos-sdk ?
> I think cosmos-sdk is for hi-level application develop.

Hey, 

The reason this is moved to the application is that the application controls who the validator set is and which keys are associated to these validators. Key rotation in Tendermint would require changes in the protocol, by moving it to the app, it can be done with no changes to Tendermint. 

Any application that would like to implement key rotation can already, there is no needed changes on Tendermints side.
