### ISSUE TITLE
consensus: spec and impl for BFT time

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1146]
Now that timestamps are included in votes, we can use them to construct a BFT time to be included in the next header

Need to write a spec for how to do this and then implement it.

**Comment by melekes** [comment]
@milosevic can you link a spec here?

**Comment by milosevic** [comment]
This is the spec: 
https://github.com/tendermint/tendermint/blob/master/docs/specification/new-spec/bft-time.md

**Comment by zmanian** [comment]
I have concerns about BFT time.

1. BFT time as per the spec doesn't appear to weighted by voting power. I believe contributions to BFT time should be weighted by voting power. You basically should get a number of entries in the least proportional to voting power.

2. I think there should be max variance/ std deviation for submitted times and if we cannot generate a consensus with 2/3rd of the voting power and low enough variance we should fail the round. If the variance exceeds the limits, outlier values should be removed from the vote and then we retests. `Remove(Max(median-min),(max-median)` but we also need to check if we still have 2/3rd voting power.

2. The BFT time spec does not define Byzatine behavior in regards to time in votes. I think if the delta between a confirmed time and your vote time is greater than some value it should be slashable.

**Comment by jlandrews** [comment]
I'm not caught up on all the backstory, but what's the argument against having the proposer set a timestamp, and the validators simply accept or reject it? Using some rule such as, reject if before previous, or ahead of validator local time by more than x.

Having the votes contain a timestamp and then taking the median seems more complicated. Also #1319 could be done much more efficiently if each validator is signing the same canonical piece of data for their prevotes/precommits, as we would only need one copy of the vote, a bitfield to specify validators signing, and the aggregated signature. With distinct timestamps in votes we will need to include each of them fully in the last commit set, while everything else can be aggregated or included as a single copy.

**Comment by ebuchman** [comment]
Great point @jlandrews . Timestamps in votes definitely make them more complicated, for instance we have to deal with the possibility of two distinct votes for the same Height/Round but with different timestamps, which has already led to more complexity in the privValidator.

That said, it does seem really valuable to have timestamps in the votes for debugging, though maybe they don't need to be signed.

A concern with letting the proposer just set the time, or with other forms of restrictions on time, is that we don't have any mechanism to resync clocks, so if the clocks drift apart, we might halt forever. 

The whole thing warrants a larger discussion. Perhaps we can convene a call.

**Comment by milosevic** [comment]
Thanks for great points @zmanian @jlandrews. Regarding @zmanian comments: fully agree regarding 1). The current version is not precise enough about media computation, and it sounds more like assuming uniform distribution of votes like in classical BFT. I believe it can be easily fixed by phrasing it in terms of voting power, as in Tendermint we can effectively see vote messages as aggregators of individual votes, where each voting power unit is one vote. So if you treat a vote msg (v1, ts1) with voting power 23 as 23 votes for value (v1,ts1) then median will also gives us the right value. Regarding 2) and 3), I believe it deserves a bit longer discussion. Having time as part of consensus mechanism can lead to termination issues, so we need to be very careful with this. It would be also great understanding the tradeoffs and design in the context of using BLS signatures in Tendermint (#1319), and we should probably not jump into the implementation before at least proper discussion and specification of the potential solution. I will propose a fix in the context of the current spec to precisely refer to voting power, and @ebuchman could maybe organise a call regarding broader discussion.

**Comment by ebuchman** [comment]
Thanks @milosevic.

Let's aim for a call later this week. We can co-ordinate on slack and write the results up here after.

**Comment by zmanian** [comment]
I think proposer selected timestamp is fine if the rest of the quorum will refused to prevote a block where the delta between validator system time and proposer time > x

**Comment by ebuchman** [comment]
Note re #320 we should also ensure that the genesis.json has a set time

**Comment by Chjango** [comment]
Notes from @chjj for @jlandrews:

I'm not sure I'm qualified to understand the full scope of what you guys need here, since it sounds like you want a truly consensus-based time mechanism, but if you want to go a more decentralized route, something similar to the way bitcoin calculates network adjusted time might be an option.

On the bitcoin p2p layer, time samples are gathered from every peer a node connects to and stored in a set. Every so often, the median time offset is pulled from that set and chosen as the network adjusted time offset. Whenever the system time is retrieved, the offset is applied against it. The system time, plus the adjusted offset, is used to ensure block timestamps are no more than 2 hours in the future. To verify block timestamps are not too far in the past, a median timestamp is pulled from a set of the previous 11 blocks and used as the oldest possible timestamp.

This may not be what you're looking for since it isn't a strictly "consensus" time mechanism: time is instead calculated as an emergent property of the network (and as such, it needs that 2 hour fudge window to guarantee the majority of nodes don't fall out of consensus). 

There's trade-offs for each method. Bitcoin's network adjusted time is definitely not exact, and there may be potential "time sample attacks" on the p2p layer (though, no one has ever successfully executed an attack of this nature on bitcoin), but I think it's probably more decentralized than leaving it up to the validators.

**Comment by ebuchman** [comment]
A number of discussions since have decided:

- dont sign the timestamp in votes (will allow for BLS compression)
- set rules for validity of timestamp included by proposal in block

I like the idea of incorporating something from the network into the system time before proposing it, but we don't currently have timestamped messages at the peer layer.

**Comment by jaekwon** [comment]
Here's a draft of the new proposed BFT time spec:

https://github.com/tendermint/tendermint/blob/jae/bft_time/docs/specification/new-spec/bft-time.md

**Comment by jaekwon** [comment]
New spec proposal: https://github.com/tendermint/tendermint/blob/jae/bft_time/docs/specification/new-spec/bft-time.md

**Comment by ebuchman** [comment]
@jaekwon can you help clarify a few things please:

- what is the relation between wiggle and timeout_propose?
- is the proposer expected to set her internal clock to last_time_stamp + iota if she is behind ?

**Comment by milosevic** [comment]
What if some height takes quite long time, for example 30 min (because there was less than +2/3 voting power on), then if the next instance does accept proposal in the first round, then the acceptable value for the next block would be lastblocktime + iota? This is pretty far from wall time.
With a sequence of faulty proposers it might take it pretty far from wall time for quite some time. Is this a problem? Should we adapt MinValidTime based on round number and wiggle_r similar as with MaxValidTime, for example minValidTime = maxTime(minValidTime, now.Add(-1*wiggle).Add(-1*wiggle*wiggle_r*round). This way we are eventually live, but we might be having a chance of being closer to wall time.    

@ebuchman Why you think there is a relation between wiggle and timeout_propose? These seems to be quite different mechanisms. My intuition for wiggle is acceptable clock drift between processes, which if validators use NTP (which should probably be recommended practice) shouldn't be pretty high, I guess order of hundreds of ms.

**Comment by ebuchman** [comment]
> BFT time should be eventual property and termination of Tendermint shouldn't depend on clock drifts of correct processes, i.e, we should terminate even if clocks of all correct processes are screwed. 

Agree here.

I'm a bit concerned again about this proposer-based BFT time. It seems it might be more ideal to try and have a background protocol to do BFT time with signed vote-like msgs just at a lower frequency - could be every minute or every few minutes.

Do we really need to try and get such high precision timestamps if it might slow down the chain or create significant dependence on synced clocks ? 

> Why do you think there is a relation between wiggle and timeout_propose? 

Because we admit that it might take timeoutPropose to receive a block, so we should always be willing to accept a block from `now-timeoutPropose`. But if `wiggle < timeoutPropose`, then we'd reject blocks even after waiting timoutPropose for them. So seems they may be related somewhat

**Comment by milosevic** [comment]
> I'm a bit concerned again about this proposer-based BFT time. It seems it might be more ideal to try and have a background protocol to do BFT time with signed vote-like msgs just at a lower frequency - could be every minute or every few minutes.

Agree. We could have very simple rule based on lastBlockTime in most of the cases just to enforce monotonicity and then periodically compute lastBlockTime based on signed time field from precommits (note that this will require having time field inside the Vote but not set most of the time).

**Comment by jaekwon** [comment]
Implementation is complete: https://github.com/tendermint/tendermint/issues/1146

I haven't read the comments, but I'm pretty confident about this algorithm and will address comments as I read them.

**Comment by jaekwon** [comment]
> what is the relation between wiggle and timeout_propose

Since you mention it, I think MinValidTime should incorporate timeout_propose (or rather round_start_time-wiggle).  Otherwise, they're independent.

> is the proposer expected to set her internal clock to last_time_stamp + iota if she is behind ?

No.

> Note that we don't use lastBlockTime in the computation of the MaxValidTime, so we could have MaxValidTime < MinValidTime.

Good point, but I think that's OK.  That just means that no block can satisfy the subjective time validity property, which can happen if your clock is far behind what it should be.

> In your example with 100 validators, should we consider a process with a faulty clock as a correct one? As a more general question, do we assume some clock drift between (some number, for example f+1) of correct processes as a correctness requirement?

I think we should!

As Bucky mentioned, I agree that we should implement an "emergent" "background" (to borrow Zarko and Ethan's words) BFT protocol that will periodically sync clocks.

But I think we should also have a different BFT between these sync periods... during which there are higher requirements on what is considered "correct", namely, that each correct validators' clocks are within "wiggle" of each other.  So they're clustered together within a span of "wiggle".  This shouldn't be difficult as long as wiggle is large enough, and we do the "background" BFT syncing often enough, and assume in our model that the machine clocks are sufficiently accurate such that drift happens within "wiggle".

What I've implemented is this second BFT system.  I think we should launch with this system (cuz I think it works better than similar alternatives), and also initially require that Cosmos Hub validators need to have their clocks synced with global time using existing tools and services... which doesn't seem like the worst thing to require of our validators.

Then, after launch, we can work on the "background" BFT sync system, which would automatically ensure that everyone's clocks are within wiggle.

> BFT time should be eventual property and termination of Tendermint shouldn't depend on clock drifts of correct processes, i.e, we should terminate even if clocks of all correct processes are screwed.

Before I mentioned two BFT systems... the first is the "background" BFT process that syncs everyone's clocks to be within "wiggle", and the second is the "foreground" BFT process tht assumes everyone's clocks are going to be within "wiggle".

While I agree that the "background" BFT system can be purely emergent, I think even the best computers with even the best BFT time algo will still eventually drift away from "global real time" as measured by atomic clocks.  So in that sense maybe we need something more than just "emergent"... Also, the reality of hardware clocks is that, while they do drift, they tend to drift slowly over time.  The proposed algorithm takes this into account, which IMO results in a better overall blockchain.

Anyways, given the above mentioned intended design of BFT time design, I'd say that my proposed spec meets the requirements.

The "foreground" BFT time algo assumes that clocks are within some reasonasble bounds of each other (e.g. "wiggle"), but even if they aren't, it's still fine.  I can prove this here's a proof-segment for brevity.  Lets just consider the "MaxValidTime" condition.  If a proposer's clocks is way ahead than it should be, then that proposer's block will get rejected.  However, that doesn't defeat liveness, because we will go on to future rounds, and some of those validators will have their clocks set more behind than others, and since (except the first round) we have a permissive MinValidTime, eventually soon a block will be committed.

The benefit of having this "foreground" BFT time system is that the blockchain's time more accurately reflects the real time.  I think this makes for a better blockchain, and may be critical in applications that involve, say, betting.

> One approach would be trying to enforce strict time only in the first round and then for higher rounds requiring only that time for the block h + 1 is in the range (lastBlockTime + iota, lastBlockTime + k* iota), where k and iota are configuration parameters. This will ensure that eventually time is close to clock time as we will during good period probably be accepting first round Proposal as correct processes will synchronise their clocks during good period.

That sounds like more or less what I'm suggesting, except instead of `k*iota` I'm calling it `wiggle+(wiggle*wiggle_r*round)`.  The only difference is the variable component `wiggle*wiggle_r*round`, which is makes it even more permissive even when more than 1/3 are not time-correct -- i.e. the drift was so bad that the tolerance bounds for the "foreground" BFT failed.  Without the `wiggle*wiggle_r*round` component, consensus can practically hang much more seriously in the case of BFT-time failure.  So I believe it is an important addition.

If +2/3 were spread out more than `wiggle` but some finite amount, then assuming that clock drift is not significant within the short-term (e.g. during the rounds of a height), then at least eventually we can terminate.  Intuitively, we need to provide some safety bounds on how much of a future block time we're willing to tolerate, but that tolerance bound needs to become more permissive over rounds somehow.

> One concern I am having with the current proposal is how long it will take for a process to accept proposal if his clock is drifted forward significantly (with wiggle_r mechanism)? This directly affects termination of the consensus. I would prefer to minimise stuff that affect termination.

The idea with "background"/"foreground" is that it (1) it won't drift significantly if the process is correct, and (2) even when it does, it won't drift much... which is modeled after physical computers and how their clocks tend to work.  So the wiggle_r mechanism is there in case the "wiggle" tolerance bounds are violated in some limited way.  It's not perfect, but it's just better than without it.

> I'm a bit concerned again about this proposer-based BFT time. It seems it might be more ideal to try and have a background protocol to do BFT time with signed vote-like msgs just at a lower frequency - could be every minute or every few minutes.

That's what I'm suggesting, but the background protocol should still have a foreground component imo, and what I've implemented is the foreground component to be as simple and awesome as possible, + will work perfectly fine when supplemented with global time syncing (which is a solved problem practically) for now until we get background syncing implemented after launch.

> Agree. We could have very simple rule based on lastBlockTime in most of the cases just to enforce monotonicity and then periodically compute lastBlockTime based on signed time field from precommits (note that this will require having time field inside the Vote but not set most of the time).

That's what my PR does, with better protection against the block time from jumping forward too quickly, which could be abused by validators in applications that are time sensitive.

**Comment by jaekwon** [comment]
Updated the PR to remove round=0 exception logic.

https://github.com/tendermint/tendermint/commit/4ec86eea397f354009bd5127aa593483cf2c7f31

**Comment by ebuchman** [comment]
I think ideally if we're going to impose this extra requirement on Tendermint liveness it should be optional per network - not everyone using Tendermint will need or want this, so it would be unfortunate to subject them to it since it could actually compromise their liveness. Maybe it goes in ConsensusParams ?

**Comment by ebuchman** [comment]
Replaced by https://github.com/tendermint/tendermint/issues/2013
