### ISSUE TITLE
Tendermint Testnet Node flags moniker and seed do not overwrite as expected

### ISSUE THREAD

**Issue by ltfschoen** [tendermint/tendermint#1167]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.15.0

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):
N/A

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS 10.12.6
- **Install tools**: `brew`, Go, etc. See Installation steps in Readme at the project repository https://github.com/ltfschoen/tendermint-elixir
- **Others**:
Elixir v1.6.0 `elixir --version`
Erlang v9.2 `erl --version`
Make 4.2.1 `make --version`

**What happened**:

I followed the Tendermint docs to create config.toml files. In [this section](http://tendermint.readthedocs.io/projects/tools/en/master/using-tendermint.html#configuration) of the docs it says _"Some fields from the config file can be overwritten with flags"_.
In ~/.tendermint folder my config.toml file is:
```
proxy_app = "tcp://0.0.0.0:46658"
moniker = "MP.local"
fast_sync = true
db_backend = "leveldb"
log_level = "state:info,*:error"

# Allow Tendermint p2p library to make connections to peers with the same IP address
# https://tendermint.readthedocs.io/en/master/using-tendermint.html#local-network
addrbook_strict = false

[rpc]
laddr = "tcp://0.0.0.0:46657"

[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "0.0.0.0:46656,0.0.0.0:46666,0.0.0.0:46676,0.0.0.0:46686"
```

I've written a Shell Script to create a Tendermint Testnet with four (4) Nodes here https://github.com/ltfschoen/tendermint-elixir/blob/master/launch_testnet_nodes.sh.

In the Shell Script some of the flags `tendermint node` flags I've used include `--moniker=<NODE_NAME>` for each Node Name and `--p2p.seeds="0.0.0.0:46656,0.0.0.0:46666,0.0.0.0:46676,0.0.0.0:46686"`

In the Shell Script I've passed flags to `tendermint testnet`, which generates subfolders for each Nodes (i.e. mach0, mach1, mach2, mach3) inside "mytestnet" folder.

But everytime I run the Shell Script, the value of the `moniker` property gets overwritten with the same value for that property that's in the ~/.tendermint/config.toml file (i.e. `"MP.local"`), instead of the value of the `--moniker=` flag (i.e. value of "mach0" for the 1st Node) so I can give each node a specific Node Name (i.e. so `moniker = "mach0"` appears in mytestnet/mach0/config.toml for the 1st Node) 

The other problems is that even though in ~/.tendermint/config.toml I have set the `seeds` as follows:
```
[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "0.0.0.0:46656,0.0.0.0:46666,0.0.0.0:46676,0.0.0.0:46686"
```
When I run the Shell Script each time it creates a Node with `tendermint node ...` (i.e. the 1st Node is created in mytestnet/mach0 folder), when I view the generated mytestnet/mach0/config.toml file, it shows the value of the p2p seeds as an empty string `""`, even though I pass the flag `--p2p.seeds="0.0.0.0:46656,0.0.0.0:46666,0.0.0.0:46676,0.0.0.0:46686"` with each of the `tendermint node ...` commands, and even though ~/.tendermint/config.toml contains the desired `seeds` value, i.e. extract from mytestnet/mach0/config.toml is:
```
[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = ""
```

According to the Tendermint Documentation here https://tendermint.readthedocs.io/en/master/using-tendermint.html#adding-a-non-validator, if `seeds = ""` then it is a Non-Validator Node, which means the node will not make any blocks, since it is not a validator. I believe I need at least one other Node (other than the initial Node that's configured in ~/.tendermint/config.toml) to be able to create new blocks using PoS

**What you expected to happen**:

I expected the flag `--p2p.seeds="0.0.0.0:46656,0.0.0.0:46666,0.0.0.0:46676,0.0.0.0:46686"` that was passed to `tendermint node ...` for each Node to add a value for the p2p seeds property in the generate a config.toml file that corresponds to the value passed into the flag (instead of just an empty string `""`, i.e.
```
[p2p]
laddr = "tcp://0.0.0.0:46656"
seeds = "0.0.0.0:46656,0.0.0.0:46666,0.0.0.0:46676,0.0.0.0:46686"
```

I also expected the flag `--moniker="mach0"` that was passed into `tendermint node ...` for each Node to add a value for the `moniker` property in the generate a config.toml file for each respective Node that corresponds to the value passed into the flag (instead of the same moniker value for every Node being set to the same value as the moniker value in ~/.tendermint/config.toml of `"MP.local"`

I believe this may be part of the underlying reason why I can't communicate with my Elixir ABCI Application, as highlighted in this separate issue https://github.com/tendermint/tendermint/issues/1166

**How to reproduce it** (as minimally and precisely as possible):

Please follow the setup instructions in my Tendermint Elixir repository. I have tried to make them as concise as possible to encourage open source development https://github.com/ltfschoen/tendermint-elixir

**Anything else do we need to know**:

Many thanks in advance for however you can help

**Comment by ebuchman** [comment]
Some notes:

- passing flags does not physically overwrite the config file on the disk, just the config value for the running process. If the moniker in the config file is X and you pass --moniker=Y, then for that running node the moniker will be Y but next time you run it if you don't use --moniker it will go back to whatever is in the config file. If you want to update the config file you need to do so manually. You can check the flags work by seeing the `localhost:46657/status` endpoint and checking the moniker there. 

- Same goes for the seeds - you either need to edit the config file manually or pass --p2p.seeds every time. Passing the --p2p.seeds won't update the config file itself, just the config value for that process

- it doesnt matter what's in `~/.tendermint/config.toml` unless you're running a node with the default home directory. if you're using custom home directories then this ~/.tendermint will be ignored.

> According to the Tendermint Documentation here 
https://tendermint.readthedocs.io/en/master/using-tendermint.html#adding-a-non-validator, if seeds = "" then it is a Non-Validator Node, which means the node will not make any blocks

This is not correct. The value of `seeds` has nothing to do with being a validator. `seeds` is just a list of peers to connect to. Whether they're validators is totally orthogonal. Being a validator means your key is in the genesis file or you were added later on explicitly with a transaction

I'm going to close this because as far as I can tell Tendermint is working correctly and the expectations (ie. that flags will overwrite the config file on disk) are incorrect.

Please open new issues if you're still having trouble or convinced something is broken :)

Thanks.
