### ISSUE TITLE
Run integration tests nightly and on release

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1252]
Remove the integration tests from regular CI in https://github.com/tendermint/tendermint/issues/1251

Once we have new Jenkins working, we should run the integration tests nightly (and make sure we get pinged somewhere if they fail). This way we get the best of both worlds - we don't block on the long tests and we wont have big surprises come release time.

**Comment by ebuchman** [comment]
Related: https://github.com/tendermint/tendermint/issues/1249

**Comment by xla** [comment]
We can have nightlies even before Jenkins is in effect with the [workflow schedules](https://circleci.com/docs/2.0/workflows/#scheduling-a-workflow) introduced by Circle with their latest version.

**Comment by melekes** [comment]
> and make sure we get pinged somewhere if they fail

who will be responsible for fixing them? this will require "on-call" person, but I would rather prefer dev who broke code fixing it...

**Comment by ebuchman** [comment]
>  I would rather prefer dev who broke code fixing it...

I think it should be the PMs responsibility to assign the relevant dev to fix it when it breaks. 

You don't want faster test cycles @melekes  ?

**Comment by melekes** [comment]
> I think it should be the PMs responsibility to assign the relevant dev to fix it when it breaks.

but how would he know who's responsible? we can try of course. I am up for experiments. but my prediction is this won't work.

> You don't want faster test cycles @melekes ?

I want faster cycles.

**Comment by zramsay** [comment]
yeah, i agree with anton.

Example: 

Day 1: a handful of PRs are made from multiple devs. All tests pass (but not integration b/c not run)
Day 2: Bucky wakes up, reviews PRs, merges them, goes to sleep
Day 2-night: integrations tests fails
Day 3: everyone wakes up, no one knows who to blame for failed integration tests

**Comment by zramsay** [comment]
BTW, I had Jenkins very close to being useable, asked all the tendermint devs to start branching from the Jenkins branch and PR'ing to it, so that we could flesh out the bugs, but no one ever did :(

**Comment by xla** [comment]
The reason faster cycles are desirable is to gain confidence quickly if the unit of work (PR) is ready to be handed-off (review) and for the reviewer if it full-fills our set of machine verifiable acceptance requirements. If a developer has to wait for long periods of times it results in very disrupted workflows and will lead to context switches, which are expensive, reducing those will help with personal and project velocity. What those requirements are needs be agreed on at every stage of our workflow (develop, release, etc.) and from there on invest the energy to have those run as quickly as possible and make sure we don't regress over time (as in longer and longer build times).

Another sentiment seems to be who is responsible/who to blame, which I personally find very irritating. This is a collaborative effort, no matter what the origin of a singular problem is. Additionally, informed by own experience, some of the issues that surface on the integration level can often only be fixed by a developer with extremely deep knowledge of the system, so it often requires expert help anyway. Work that stems from a break in a higher level test run should be simply be incorporated in our work process and be picked up by whoever feels confident and has time to deal with it.

**Comment by xla** [comment]
> BTW, I had Jenkins very close to being useable, asked all the tendermint devs to start branching from the Jenkins branch and PR'ing to it, so that we could flesh out the bugs, but no one ever did :(

@zramsay Could you expand on the reasoning the switch to Jenkins is desirable and what gains we expect to see?

**Comment by melekes** [comment]
> If a developer has to wait for long periods

why he has to wait? he can run test_integrations on his machine, which will be faster. Or if he does not want to do it, he can switch to another task.

> Another sentiment seems to be who is responsible/who to blame, which I personally find very irritating. This is a collaborative effort, no matter what the origin of a singular problem is

while I agree with what you're saying, it's not about blaming. you see, developer 1 working on feature/X has necessary knowledge in X. If develop 2 was assigned (or volunteered) to fix the bug introduced by feature/X, it will most probably take her more time.

**Comment by xla** [comment]
> why he has to wait? he can run test_integrations on his machine, which will be faster. Or if he does not want to do it, he can switch to another task.

Why you assume the integration tests run faster on a developers machine? To your second point, that is exactly what I was referring to when talking about disruptive workflows, switching context is quite taxing and if we have to do it a lot because of when and how we get feedback it will lead to time lost.

> while I agree with what you're saying, it's not about blaming. you see, developer 1 working on feature/X has necessary knowledge in X. If develop 2 was assigned (or volunteered) to fix the bug introduced by feature/X, it will most probably take her more time.

Very valid point, maybe we can redirect the conversation and talk about the things we like to see being tested before a feature PR is considered ready-for-merge. Could you list the things you find important?

**Comment by ebuchman** [comment]
Thanks for the thoughts and work on this @xla.

We need to find the right balance between time and extent of testing. A big chunk of the integrations tests are for things that almost never change / get worked on, so shouldn't be tested every time. We just never put in the effort to sort this out better than "test it all at once". So thanks for zeroing in on it. 

Your point about "who should fix it" is spot on too. If our nightlies fail, it also suggests we dont have enough or the right kind of coverage in our unit tests. In any case, its a new ticket like any other to be worked on by the team.

 > @zramsay Could you expand on the reasoning the switch to Jenkins is desirable and what gains we expect to see?

Given the complexity of our code, the number of repos, the desire to control the build and release process, and an overall feeling that more flexibility and tooling in our CI/CD would be valuable, we decided to go to Jenkins. Perhaps it would be valuable to gather thoughts and discuss this in next Tendermint meeting - it's worthy of an ADR. 

> Why you assume the integration tests run faster on a developers machine? 

Circle is slow.
 
> redirect the conversation and talk about the things we like to see being tested before a feature PR is considered ready-for-merge. Could you list the things you find important?

This will probably be context dependent, but overall testing strategy could use more thought and discipline. In particular (and we're already getting better at this), we should be writing clear detailed specifications for everything and tests that reflect those specifications.

**Comment by melekes** [comment]
> Circle is slow, another motivator to move to self hosted.

Not anymore! thanks to excellent work by @xla 

Can we close this issue now?

**Comment by xla** [comment]
Let’s reopen if this is not solved.
