### ISSUE TITLE
PrivValidator follow up

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1255]
- [x] https://github.com/tendermint/tendermint/pull/1203 has been merged but please follow up on Anton's review re `pvsc.Stop()`, `panic`, and `sign_bytes`
- [x] Tendermint is dialing the signer, but we need the signer to dial Tendermint. Perhaps we can have the SocketClient take a `conn` directly to avoid the confusion around a client doing the listening (the ADR did not specify this well, my bad - see https://github.com/tendermint/tendermint/pull/1256 for a start)
- [x] Some more review follow up from https://github.com/tendermint/tendermint/pull/1286#pullrequestreview-103093019
- [ ] priv_val_server needs to be updated 
- [ ] authenticate against `ID@host:port` in the RemoteSigner, check that `id` matches configured 
- [ ] Persist PrivKey the SocketClient uses for external signers to authenticate properly
- [ ] full integration and deprecate the old PrivValidator

**Comment by xla** [comment]
*added TODO*

**Comment by tarcieri** [comment]
If it's too much work for the signing service to connect to Tendermint, we can go back to the original plan of having Tendermint call out to the signer.

Having the signer connect rather than listen is a little bit of defense-in-depth, but so long as both sides are mutually authenticating each other, they should be equivalent from a security perspective, barring some sort of pre-auth vulnerability in the signing service.

**Comment by xla** [comment]
@tarcieri See #1286 we going to stick to the original plan and have the signer(s) connect to Tendermint.

**Comment by tarcieri** [comment]
@xla great!

**Comment by silasdavis** [comment]
I've kind of lost track of where some of this had gone, but at one point we had some extracted signing logic for `PrivValidator` which is now private to `FilePV`. For mean this means I have to maintain this: https://github.com/hyperledger/burrow/blob/develop/consensus/tendermint/sign_info.go so that I can use my in-memory `PrivValidator`. That logic would really much better reside with Tendermint.

I'm not sure why the decision was made to remove `LastSignInfo` from Tendermint, but I think it may have been lost as collateral to: https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-008-priv-validator.md. But making the validation logic its own exported class is orthogonal to supporting just two validators - that decision makes sense, but why prevent others from building from the validation logic which is separable and could live in its own exported type or just exported methods.

**Comment by ebuchman** [comment]
Closing for #2549
