### ISSUE TITLE
ABCI Validator Keys

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1272]
There is some concern about the mix between protobuf and go-wire in the ABCI Pubkey type, eg. https://github.com/tendermint/abci/issues/169

Perhaps a solution is to define a Pubkey message:

```
message Pubkey {
    bytes type
    bytes data
}
```

Where the `type` is the go-wire type bytes and `data` is the raw pubkey bytes.

Then we can support a default behaviour where empty `type` means `ED25519`, so users don't have to worry about go-wire until they want more types.

Alternatively, we keep pubkey as just bytes, and make very clear that users must encode them the way go-wire does with the correct prefix bytes.

I think the proposed `message Pubkey` may achieve the best of both worlds, but supporting it properly may require some convenience functions from go-wire to split an encoding into its prefix-bytes and data-bytes. Also I'm not exactly sure what to do about the length-encoding part.

**Comment by jaekwon** [comment]
We shouldn't be maintaining two versions of the same thing if we can avoid it.
Golang interfaces are well suited for the task so we should use those rather than implementing our own interface-like-thing using Protobuf messages (structs).  So basically, go-crypto has it right.  We don't need to re-implement it in protobuf.

If people complain, we should point them to go-wire docs and explain why we're investing in go-wire.

**Comment by xla** [comment]
@jaekwon Do we have a canonical answer we can point people to, which explains why we invest in go-wire?

**Comment by ebuchman** [comment]
WIP: https://github.com/jaekwon/go-wire/tree/marshalwire#why-wire

**Comment by ebuchman** [comment]
wire is now called amino! https://github.com/tendermint/go-amino#why-amino
