### ISSUE TITLE
p2p: loopbacks should be detected and ignored instead of dialling self infinitely

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#1275]
from: https://github.com/cosmos/gaia/issues/127

**Comment by odeke-em** [comment]
Articulated by @zmanian offline in the engineering channel, this issue is about ensuring that a loopback should be detected and dropped; that is if your own IP is in your list of persistent peers, a node shouldn't dial back to itself infinitely.

**Comment by ebuchman** [comment]
Not just loopback - it might be a public IP and we may not detect that it's us until we see the ID. Once we identify it as ourselves we should record the address as our own and avoid trying to connect to it again

**Comment by odeke-em** [comment]
In deed @ebuchman, not just localhost loopbacks, I was using "loopback" generally to mean a connection back to self.

**Comment by ebuchman** [comment]
Basically we should have the following behaviour:

for each of our addresses:

- we should only dial it once (if at all), after which we will know it's us (because it has the same ID) and we can avoid ever dialling it again :D
- but, it's possible after a lot of time that we change IPs and someone else takes our IP ... so we need to ensure we don't persist our IPs and we just find out every time we restart (I think we already do this)

**Comment by amrali** [comment]
> Not just loopback - it might be a public IP and we may not detect that it's us until we see the ID. Once we identify it as ourselves we should record the address as our own and avoid trying to connect to it again.

If a node detects that the ID belongs to itself would it stop redialing the <IP, port> combination or just the IP address?

**Comment by melekes** [comment]
@amrali combination of IP and port, otherwise we're losing the ability to run many Tendermints on one machine
