### ISSUE TITLE
Docker: automate build & push on release

### ISSUE THREAD

**Issue by t-bast** [tendermint/tendermint#1288]
Hey guys,

It looks like you have only publish 0.15.0 on Docker and not 0.16.0.
Could you please publish 0.16.0?
Or is there a reason why it was skipped?

Thanks!

**Comment by greg-szabo** [comment]
I wasn't planning on going back to deploy old releases but since 0.17.1 I took over deployment and we have 0.17.1 and 0.18.0 and soon 0.19.0 is coming (as soon as it's merged to master). You can easily create your own version from any tendermint binary using the [Dockerfile](https://github.com/tendermint/tendermint/blob/greg/devopstools/DOCKER/Dockerfile) (still under review). There is a `make build-docker` command added to the main Makefile (also still under review in the `greg/devopstools` branch) in case you want to create a special version that you built. (It takes the binary from the build folder.)
