### ISSUE TITLE
Validator logging and a strange file

### ISSUE THREAD

**Issue by nickray** [tendermint/tendermint#1294]
The origin of these questions is running `make test` in https://github.com/validstate/sentry-test (assumes you have `multitail` installed, otherwise comment out in `hack/run-test.sh`). The commited binary `gaia-0.5.0` is a static build of release v0.5.0.

The test is about whether running a validator that communicates via a sentry proxy works (this failed for me for testnets gaia-3003 and inofficial-101; there I was additionally running multiple sentries behind a cloud loadbalancer).

Basically, it seems to work, but:

* as-is, the sentries log `err=EOF`, while the validators log `err="Unknown channel 0"` (see e.g. `multitail sample-logs/*.log`). Does this mean that my setting `pex = false` causes the validators to drop connection requests (setting `pex = false` in the sentries makes the errors go away). If yes, the error logs are confusing, and "not searching peers" and "not accepting P2P requests" should be separate options.

* what is the file `sentry-b/373633717`? Is it a result of interrupting all the nodes with Ctrl-C (i.e. SIGINT)? Any other temporary files outside of those deleted in `make clean` that I should be aware of?

* which signals are supported? It would be good to have nodes do a clean shutdown on SIGINT and SIGTERM, is this the case? My main concern here is **stopping a validator via SIGTERM** to e.g. move it to another machine.

* it would be nice if the `--home` flag did shell expansion of paths

**Comment by ebuchman** [comment]
1) this should be fixed in v0.16, though unfortunately we don't have a gaia release for that yet. We're expecting to have at least some form of staking on the new SDK with v0.16 tendermint this week. Sorry for delays!

2) I believe it's left over from the WriteFileAtomic used by the priv-validator - it make's a back up of itself and perhaps isn't completing in time and isnt getting the signal. I've opened a new issue: https://github.com/tendermint/tendermint/issues/1329

3) We catch SIGINT and SIGTERM and try to clean up nicely. It's possible we miss some things. For other signals we use the default behaviour in Go: https://golang.org/pkg/os/signal/#hdr-Default_behavior_of_signals_in_Go_programs. This should be better documented https://github.com/tendermint/tendermint/issues/1330

4) opened a new issue: https://github.com/tendermint/tmlibs/issues/173

Thanks Nick! I'm going to close this in favour of the new issues
