### ISSUE TITLE
Broadcast vote routine and add vote logic conflicting with each other

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#1364]
https://github.com/tendermint/tendermint/blob/43ac92b615f95da8288020944a34346440119da3/consensus/reactor.go#L655-L665

https://github.com/tendermint/tendermint/blob/43ac92b615f95da8288020944a34346440119da3/consensus/state.go#L1381-L1385

Broadcast logic and addVote logic are conflicting with each other. It's quite hard to keep sending and receiving side aligned with the current implementation. Maybe we need to reconsider design. Ideally, logic should be expressed at one place, and then be used at sending and receiving side.

**Comment by odeke-em** [comment]
@milosevic thank you for filling this issue. For posterity, please post permalinks as the code in the branches changes rapidly and just in case you need to, here's how
<img width="968" alt="screen shot 2018-03-26 at 8 41 08 pm" src="https://user-images.githubusercontent.com/4898263/37943757-20ee4b86-3136-11e8-8b70-7e93cf9d2246.png">

Just like the the links you posted, you could select multiline on them, and then on the Github UI, left click on the selection top hamburger menu, and select "Copy Permalink"
to give something like this
https://github.com/tendermint/tendermint/blob/43ac92b615f95da8288020944a34346440119da3/consensus/state.go#L1379-L1385

**Comment by ebuchman** [comment]
@milosevic not sure I understand the problem here. 

Suppose we're looking at the reactor of peer1 and the state of peer2. The peer1.Reactor tracks the state of peer2. If peer1 is at H+100 and peer2 is at H, peer1 will send votes for H. peer2 will then receive votes for H, which corresponds to it's current height, so the vote.Height == cs.Height passes. If by the time it receives the vote for H, it's already moved onto H+7, then it will ignore the vote, as it doesn't care about it anymore.

I see how this is confusing (since it looks like the heights of the two peers have to agree, which they don't) and I agree we could improve a lot about the way the code is written but I'm not seeing anything explicitly incorrect about this as is.

I'm going to close this issue. If you still think there's an issue, please re-open and clarify. Thanks!
