### ISSUE TITLE
tendermint suddenly stop connecting to peers

### ISSUE THREAD

**Issue by SaifRehman** [tendermint/tendermint#1397]
<img width="1440" alt="screen shot 2018-03-31 at 1 49 17 pm" src="https://user-images.githubusercontent.com/18755233/38162016-8750f3da-34ea-11e8-8278-3b82be89e181.png">

**Comment by ebuchman** [comment]
What version is this ? Any other info about the setup and what happened ?

**Comment by ebuchman** [comment]
Looks like it's using tendermint version 0.15.0, which has some known bugs at the p2p layer that have since been fixed. 

Does it work if you restart the node ? 

> In addition to that, I want to understand how do we query leveldb in tendermint?

This is a more complicated question. Best thing to do is setup in Go like Tendermint does to read the database. Otherwise you have to figure out how to do generic queries of leveldb

**Comment by SaifRehman** [comment]
Yes when we restart the node it works! blocks get synch again, then after sometime it fails

**Comment by ebuchman** [comment]
Hmm ok. Hard to try and work on this given how much was changed and fixed in the p2p layer during the upgrade from 0.15 -> 0.16. 

I think we'll need to wait for lotion to upgrade to 0.16 (well, now 0.17, soon higher), and see if the issue persists. @keppel

**Comment by ebuchman** [comment]
Closing this - should be fixed since v0.16
