### ISSUE TITLE
Mark Tendermint peer as good fails

### ISSUE THREAD

**Issue by kidinamoto01** [tendermint/tendermint#1460]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report 

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

v0.18

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

**Merkleeyes version** (use `git rev-parse --verify HEAD`, skip if you don't use it):

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS
- **Install tools**:
- **Others**:

**What happened**:
Right now, if we have received >10000 validate votes from a certain peer, we mark it as `Good`. But the             corresponding [function](https://github.com/tendermint/tendermint/blob/4930b61a381b9fb9bc530eb5deb56ea6429a1c3a/p2p/pex/known_address.go#L62) only change the address attempts to 0. This is not designed behavior as illustrated in this [spec](https://github.com/tendermint/tendermint/blob/develop/docs/specification/new-spec/reactors/pex/pex.md).  

**What you expected to happen**:
we should add a field in the address book to reflect the quality of peers. 

**How to reproduce it** (as minimally and precisely as possible):
When you query the address book, you can only distinguish peer from `old` to `new`, not `good` to `bad`. 

**Logs (you can paste a part showing an error or attach the whole file)**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:

**Comment by kidinamoto01** [comment]
@melekes yeah,
but when the `old` bucket is full, it will demote the oldest one to a "new" bucket. in this way both the `old` and `new` buckets are for `good` peers.
And, the criteria we use now is confusing. A full node may not be able to connect with a validator node because the validator is with max connection. in this case, the validator node is both bad and good.

**Comment by ebuchman** [comment]
The definition of a good peer is one in an `old` bucket.

If a peer gets demoted from `old` to `new` because we're making room for a fresher good peer, that's fine - the peer that was previously marked Good is now not considered Good since he's back in the `new` bucket - he'll need to prove himself again!

See the MarkGood here: https://github.com/tendermint/tendermint/blob/4930b61a381b9fb9bc530eb5deb56ea6429a1c3a/p2p/pex/addrbook.go#L266

It seems the spec you reference also does cover the behaviour correctly: 
"If a peer becomes vetted but there are already too many vetted peers, a randomly selected one of the vetted peers becomes unvetted."

Here, "vetted = good = old".

I'm going to close this. Please re-open or open a new one if you still have concerns
