### ISSUE TITLE
Removing a peer from tendermint 

### ISSUE THREAD

**Issue by jerrinjames1107** [tendermint/tendermint#1557]
I had created a multi-node setup using tendermint consensus.Is there a possible way to remove or isolate the added  peer from the multinode setup.

**Comment by ebuchman** [comment]
Not really within Tendermint. You can use iptables or other networking /firewall software to do this. Or you can take down a node. 

You can also filter in the ABCI application if you want, but that's more involved: https://github.com/tendermint/tendermint/blob/develop/docs/specification/new-spec/abci.md#peer-filtering.

We don't expose an rpc to disconnect from current nodes, because the Peer-Exchange Reactor is constantly trying to connect to nodes - so it wouldn't make sense. Could be an administrative feature but not a current priority.

Will close this for now, thanks!
