### ISSUE TITLE
Broadcasting transactions via a POST request ?

### ISSUE THREAD

**Issue by Bric3d** [tendermint/tendermint#1566]
Is there any way to send a transaction via the body of a POST request instead of the URL of a GET request ?

Leaving alone semantics of using a get to post data, using the URL might cause length issues with big transactions.

**Comment by ebuchman** [comment]
Yes, all endpoints are exposed via JSON RPC.

This somehow managed to be removed from the published documentation, but you can see it here: https://github.com/tendermint/tendermint/blob/master/docs/specification/rpc.rst

@zramsay ^^

**Comment by zramsay** [comment]
it's there http://tendermint.readthedocs.io/en/master/specification/rpc.html#jsonrpc-http

The confusion is because the ABCI spec has the same name in the header, so the docs look like:

![screenshot from 2018-05-14 12-25-48](https://user-images.githubusercontent.com/8304391/40010174-ff2a24ea-5771-11e8-8c30-6d1e714c03d0.png)

fixed in https://github.com/tendermint/abci/commit/52d6dfe074c6dbb67c420d78bff32b26dcb7a8e9
