### ISSUE TITLE
Consider changing semantics of unbonding period to "live time", not "clock time"

### ISSUE THREAD

**Issue by cwgoes** [tendermint/tendermint#1592]
Per discussion with @rigelrozanski - consider the following scenario:

**Problem**

1. All communication between >= 2/3 of the validator set at some block halts for a month ("worldwide internet outage"), causing no network progress (as intended).
1. After a month, communication resumes. As the unbonding period of three weeks has passed, the following happens:
    1. All validators are automatically unbonded for being down, and the network can make no more progress.
    1. (presuming that the network somehow resumes) All validators who begun the unbonding process prior to the halt can double-sign any number of blocks previous to the halt without penalty, even though those blocks are "recent" in logical time.

**(possible) Solution**

Maybe validators could vote on some kind of a "halted time", in addition to the BFT timestamp (using a similar mechanism), if the timestamp of the block `n+1` were greater than the timestamp of the block `n` by some threshold. The specified "halted time" should not contribute to the time counted for unbonding, thus resolving both issues above.

**Comment by rigelrozanski** [comment]
👍

**Comment by ebuchman** [comment]
Interesting. We could also consider enforcing a minimum number of blocks before unbonding, even if a month of clock time has gone by. Would this be different than the proposed "halted time" ?

**Comment by cwgoes** [comment]
Maybe a bit more approximate, but a minimum block count seems like it would have roughly the same effect.

**Comment by rigelrozanski** [comment]
How about this:
we could just let unbonding always take a certain amount of blocks and have the protocol update the number of block based on two weeks... If the time-per-number of blocks suddenly really really slow (such as a halted network) aka the time per block is statistically unexpected given the previous X number of blocks, then we just don't count it towards this calculation 

:)

This way we're consistent with the variable which unbonding depends on (blocks in this proposal) - but it still targets two weeks

**Comment by amrali** [comment]
Buchman's approach is simple and easy to reason about (e.g., How long is the unbonding period: it depends on the speed of the network, but it will be the time the network takes to generate a 100 blocks). But @rigelrozanski windowing approach for determining the temporal dimension of the unbonding period is more desirable if the unbonding period, in addition to blocks, should also have a temporal reference/meaning against the BFT clock; why 2 weeks and not 5?

Given this comment by Zaki (https://github.com/tendermint/tendermint/issues/1146#issuecomment-373441451), I'm not sure associating a temporal meaning based on the BFT clock is desirable or useful in that case, or that I understand the utility of the unbonding period being associated with a clock that could drift within bounds (i.e., `min_acceptable_time` and `max_acceptable_time`, see https://github.com/tendermint/tendermint/issues/1146#issuecomment-388981917).

For example, documenting the unbonding period of being wall clock based would encourage developers to use time to trigger events for when the period ends which will be quite error prone due to drift and having to retry failed attempt(s) at moving/delegating yet-to-fully-unbond-atoms. While having 100 or 1000 blocks as the unbonding period is crisp clear and would be very simple to build on top of. Also as Goes described initially you'd have to document how in the event that >=2/3 of nodes are not able to communicate, the unbonding period could take indefinitely and go back to explaining how it is really based on the number of blocks anyway.

**Comment by rigelrozanski** [comment]
@ebuchman  
- The plan has always to have a temporal reference, and also to have BFT time
 - I was about to suggest we implement bucky's soln because I like the simplicity. but there is a loophole in it, which IMO is enough is enough to justify something else... consider the scenario:
    - the "magic" number of blocks which must be fulfilled in addition to unbonding time is LESS than typical number of blocks within two weeks during normal operation (constraint this case MUST always be true or unbonding time wouldn't make any sense ever haha)
    - malicious actor begins unbonding
    - magic number of blocks passes
    - the network halts 
    - malicious actor completes unbonding (despite uptime - halted time < 3 weeks)
    - bug found (boo hoo nothing to do about it)

**Comment by jaekwon** [comment]
According to Ethan's proposal, the "minimum number of blocks before unbonding" condition would apply but so would the original, and so it requires at least 3 weeks for unbonding.  So the malicious actor can't complete the unbonding.

I believe Ethan's idea is to use block time as well as # of blocks in case there are issues like temporary halting.

I think it's a good idea.  In the future I think it might get a little more elaborate, but it seems to be a sufficiently good solution for most problems, including unbonding, and it's relatively easy.

**Comment by rigelrozanski** [comment]
@jaekwon I think we're on slightly different pages, the scenario I've raised is not addressed by Ethan's mechanism or your comment - I DO however agree it's a good mechanism, we just have to be aware that there is this edge case which has a weakened security (although I imagine it would be incredibly hard to pull off and thus not a huge concern)

**Comment by ebuchman** [comment]
@cwgoes can we close this issue / move it to the SDK if we still think its relevant?

**Comment by cwgoes** [comment]
I think it's relevant if we care about this case - which admittedly is a very unusual one. We can probably close this for now, and just assume that if a network is down for a month it is no longer secure.
