### ISSUE TITLE
Can we remove pubkeys from the ABCI all together and instead put them in votes ? 

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#1625]
Nice discussion thread in https://github.com/tendermint/abci/pull/245#discussion_r189504378

@b00f is requesting to not have to think about pubkeys at all at the application layer - only addresses.

This would actually be awesome because it would eliminate the entire discussion around how to encode pubkey types in ABCI (https://github.com/tendermint/tendermint/issues/1524), since addresses are untyped!

The challenge of course is that Tendermint needs to know the pubkey to verify the vote signature - if the app doesn't provide it, then it has to come from somewhere else.

One option is to require the pubkey come with the vote. We already include the address, so we could just instead include the PubKey.

This actually seems incredibly reasonable - it would increase the size of each vote msg by about 15 bytes. Note that this means the size of blocks will be increased by 15*N_VALIDATORS

An alternative is try to have a scheme where the pubkey only has to be sent in the vote "the first time" (or some variation of that) and then will be stored by Tendermint, but this is more subtle and difficult.

Note we don't need to sign the pubkey (we don't currently sign the address), and wouldn't want to since that would interfere with signature aggregation (I believe).

**Comment by mdyring** [comment]
Very nice, would be great if this can elegantly solve the pubkey types!

I wonder if this would this work in a proof-of-authority deployment, with no staking concept or natural link between a validator and address/account...

Probably yes, since the ABCI app could trivially calculate the address as SHA256(pubkey) and just use this is a handle to a validator?

> One option is to require the pubkey come with the vote. We already send the address, so we could just instead send the PubKey.

Did this change recently - my previous understanding was that votes contained pubkeys, since Tendermint doesn't have a native account concept?

**Comment by ebuchman** [comment]
> Did this change recently - my previous understanding was that votes contained pubkeys, since Tendermint doesn't have a native account concept?

Tendermint doesn't have accounts, but go-crypto defines Address() for each pubkey.

> Probably yes, since the ABCI app could trivially calculate the address as SHA256(pubkey) and just use this is a handle to a validator?

Well, it would have to know how to get the address from the pubkey, which is a go-crypto thing. Ideally the app wouldn't need to see pubkeys at all, and just work with addresses, and Tendermint figures out the rest!

**Comment by mdyring** [comment]
AFAICS, as long as:
- A new validator can be spun up and generate its own pubkey (currently Ed25519) for signing
- Return the address of that pubkey via the cli (or output to logs)

.. then the ABCI application should be able to receive that address in a TX (as raw bytes or whatever is appropriate) and then eventually return it to Tendermint via ABCI to update the validator set. 

This is probably what you meant by "Tendermint figures out the rest", but just want to be sure?

As long as Tendermint provides an easy way to obtain this address, I believe it should work fine.

**Comment by silasdavis** [comment]
I am slightly circumspect about this change - the public key is the primary artefact for signature verification whereas the address is there for book-keeping. By having both we can have a sanity check on the Address and we help mitigate issues where Tendermint changes they way it calculates addresses. For example first with a type byte and length prefix, then with plain ripemd160, and shortly with the first 20 bytes of sha256 (though I know the point of the final change is to rationalise this).

I'm a fan of redundancy and self description of data - where the performance implication is minimal. So including address and pubkey and also finding a way to transmit the signing algorithm along with the key seems like a good idea to me. Seems like it makes it easier to understand a message when divorced from it's context, for instance in logs or other debugging.

>This would actually be awesome because it would eliminate the entire discussion around how to encode pubkey types in ABCI (#1524), since addresses are untyped!

Similary, I'm not sure it's such a great idea that addresses are untyped (particularly if provided alone). If I'm trying to figure out whether a pubkey evaluates to an address in a particular version of Tendermint it's useful to know how the address was generated.

Suppose I want to keep track of my accounts and I want to use an addressing scheme different to go-crypto now we have keep track of a mapping between our addressing and tendermint's since we don't work with pubkeys. In some ways I think the cleaner separate would have ABCI deal exclusively in pubkeys from which  an addressing scheme can be derived.

**Comment by ebuchman** [comment]
Thanks for raising great concerns. It's probably overly restrictive to move forward with this, but I wanted to bring it up to gather some thoughts and clarify use-cases and needs.

In an ideal world, devs will receive more from Tendermint, and be required to provide less. I think this means:

- in ABCI requests, include address and pubkey together
- in ABCI response, allow apps to return address OR pubkey - though if they return both, Tendermeint will throw an error if it doesnt agree.
- put the pubkey in the vote instead of the address

> In some ways I think the cleaner separate would have ABCI deal exclusively in pubkeys from which an addressing scheme can be derived.

Funny, we were thinking the same thing the other day. The issue is that we use the address liberally in Tendermint RPC, and its a much simpler UX experience than a pubkey (no type, significantly shorter, now hex while pubkeys are json/base64 ...). Thus its also nice if they don't have to worry about pubkeys either, and just work in addresses.  Of course if they want the pubkey, it should be available to them, even to operate exclusively with it and not think about addresses.

How does all that sound ?

**Comment by ebuchman** [comment]
> Similary, I'm not sure it's such a great idea that addresses are untyped (particularly if provided alone). If I'm trying to figure out whether a pubkey evaluates to an address in a particular version of Tendermint it's useful to know how the address was generated.

Nice point. Maybe we can use amino type names now to include version information - eg. `tendermint/PubKeyEd25519/v1`

**Comment by jaekwon** [comment]
I'm not in favor due to the size.  I also don't see why the pubkey would be in the vote and what that is solving.

> The challenge of course is that Tendermint needs to know the pubkey to verify the vote signature - if the app doesn't provide it, then it has to come from somewhere else.

If the App is modifying the validator set, I want the App to tell Tendermint the pubkey directly, *not* indirectly via the address.

**Comment by b00f** [comment]
Just a hint. Public_key are necessarily 32 bytes always, but addresses shouldn't be necessarily 16 (or 17) bytes, It can have some tailing information, such as version, publick_key type, or even a checksum to make sure the address itself is valid.
so I believe address can be 20 bytes as below:
```
 0                                   15             20      
+--------------------------------+-+-+----+--+
| pk_hash                        |t|v|crc |r |
+--------------------------------+-+-+----+--+

t: type (8 bits)
v: version (8 bits)
crc: checksum[0:15] (16 bits)
r: reserved (8 bits)
```
|

**Comment by ebuchman** [comment]
I agree, from Tendermint's perspective, it's much better for the app to return the pubkey, especially since some pubkey types may be much larger.

A big part of the problem has been lack of clarity/documentation around pubkeys and requirements to use wire/amino. Hopefully by removing all that from ABCI and documenting it well, this will be much less of an issue.

I'm going to close this for now and we'll move forward with what's currently on ABCI develop.

We should still consider putting version information in Amino names.

Thanks everyone for your input!

**Comment by b00f** [comment]
To reduce the block size, why don't you just put only validator index (or maybe a 32 bits unique id) instead of validator address or public key?

**Comment by ebuchman** [comment]
Thanks, opened an issue about it : https://github.com/tendermint/tendermint/issues/1648
