### ISSUE TITLE
Change Amount to Power in genesis.json

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#166]
"Amount" doesn't mean anything.  Lets call it "Power" as in voting power.

**Comment by adrianbrink** [comment]
The fix lies in types/genesis.go. Is this still relevant, because it seems like an easy unless we also have to change the field name from Amount to Power.

**Comment by adrianbrink** [comment]
@ebuchman Should this be fixed or are we happy with 'Amount'?

**Comment by zramsay** [comment]
ping @ebuchman

**Comment by ebuchman** [comment]
Would be a breaking change. Added to the 0.11 docket.

**Comment by odeke-em** [comment]
@ebuchman for some reason, now it displays milestone `0.12.0` instead of `0.11.0`
<img width="226" alt="screen shot 2017-09-15 at 2 05 48 pm" src="https://user-images.githubusercontent.com/4898263/30501263-0085d0fc-9a1f-11e7-84ab-6ba51f09435f.png">


Perhaps we changed the name of `0.11.0` to `0.12.0`?

**Comment by ebuchman** [comment]
We did. Moved back to 0.11. Thanks.
