### ISSUE TITLE
What is mean "in-process" in document?

### ISSUE THREAD

**Issue by xblocksys** [tendermint/tendermint#1685]
I read [tendermint abci](https://github.com/tendermint/abci)

**What does the sentence mean?**
This means ABCI applications written in Golang can be compiled with TendermintCore and run as a single binary.

I think TendermintCore includes ABCI applications.
I think that building the TendermintCore to run the ABCI application is the idea?

**Comment by zramsay** [comment]
if you write an ABCI app in golang (e.g., the example applications `kvstore` and `persistent_kvstore`) and compile Tendermint Core with that app (like those two app), then the app is said to be running "in-process". If you write/use an ABCI server (and app) in another language, then the app can't be compiled with Tendermint Core (it's a different programming language), so instead of running in-process, the app must connect to Tendermint Core via the socket. Hope that helps.

**Comment by SeongJongJeon** [comment]
@zramsay 
Thank you for your advice has been a great help.

**Comment by zramsay** [comment]
You're welcome :+1:
