### ISSUE TITLE
If there is a better way  when  ABCI app failed to update application state machine 

### ISSUE THREAD

**Issue by solderain** [tendermint/tendermint#1707]
Basically, restart  tendermint  is  effective way   when  encounter exception for  receive deliverTx request then update application state machine. If i don't want to do like that ,   Is there a better way to deal with it ?

**Comment by solderain** [comment]
Duo to some reasons failed to update application state machine (eg : failed to connect backgraound database ... ) , ABCI need to redo that DeliverTx .  Application return a non-OK code to Tendermint Core , if Tendermint core will deliver  that transaction  again ?

**Comment by ebuchman** [comment]
No it will not be replayed.

You would have to use an external client to detect if DeliverTx fails and resend the tx from the client.

If you can't connect to the database from the ABCI app, technically you should panic/exit/fail since you can't process transactions properly. If other nodes can connect to their databases, but you can't, they will process the tx correctly, and you will disagree. 

So this is part of the design of Tendermint.

Does that make sense?

**Comment by solderain** [comment]
Got it . 
"You would have to use an external client to detect if DeliverTx fails and resend the tx from the client".
You advise "resend the tx from the client " , for my understanding , if 2/3+ validator precommit the  block involve the tx at height .  Resend , tx will be processed twice times . (packaged in another block at height + 1 )  right ?

**Comment by ebuchman** [comment]
Yes that's correct. If the tx is committed but is invalid, you will have to resend it again and get it committed again. It's up to the application to determine how to handle repeats of the same transaction. 

Can we close this ?
