### ISSUE TITLE
Tendermint lite client concurrency issue

### ISSUE THREAD

**Issue by HaoyangLiu** [tendermint/tendermint#1897]
I noticed that tendermint lite client use InquiringCertifier to track the validatorset evolution and verify commits. When it is running, InquiringCertifier will frequently change its own states, such as validatorset. However, it seems that InquiringCertifier doesn't take concurrency issue into consideration.  
So far,  I have done any concurrency tests against tendermint lite client. I'm not sure if lite client can work well under big concurrency. Does anyone have done similar tests?

**Comment by xla** [comment]
@jaekwon Still relevant after refactors?

**Comment by jaekwon** [comment]
A lot of the implementation has changed since this issue was created.  InquiringCertifier is now DynamicVerifier, and it creates a new instance of BaseVerifier as needed.  I'm not sure whether it's fully concurrency safe.  Most of the operations are safe, for example usage of tendermint/libs/db batch for certain writes (and tendermint/libs/db is concurrency safe), but it hasn't been tested yet for concurrency safety.

Fundamentally, the logic for DynamicVerifier isn't optimized for concurrent usage.  If you have many concurrent requests, you're going to get duplicate "source" provider calls, i think for the same block height even.  It's not designed for that kind of operation, and I don't think it needs to be.

While DynamicVerifier is good for ultimately syncing to the latest header, if you want to start serving concurrent requests that depend on verification, it seems like the best choice will be to sync to the latest block using DyanmicVerifier, then sync all the headers backwards in the block-chain, (without intermediate signature verification because the hash-chain provides the verification).  That logic should exist in lite/*...

**Comment by ebuchman** [comment]
Thanks @jaekwon - @HaoyangLiu can we close this ?

**Comment by cwgoes** [comment]
We decided that we do need to address this - discussed in person with @jaekwon - closing in favor of https://github.com/tendermint/tendermint/issues/2386.
