### ISSUE TITLE
Should mutex in consensus state can be removed?

### ISSUE THREAD

**Issue by Hugo-Huang** [tendermint/tendermint#1963]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
latest

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
irrelevant

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:
irrelevant

**What happened**:

I think the mutex in ConsensusState struct can be removed or replaced by a small RWLock to prevent the cs.RoundState from being changed unexpectedly, because in receiveRoutine of ConsensusState each case of select can only entered at one time, so I think the mutex to avoid handleTxsAvailable(), handleMsg(), handleTimeout() may be redundant.  A demo test as below:
https://play.golang.org/p/CChDyf3roJu
The mutex(lock) is too big, it may slowdown the gossip routines in ConsensusReactor when calling GetRoundState().

**What you expected to happen**:
maybe can optimize the code

**How to reproduce it** (as minimally and precisely as possible):

**Logs (you can paste a small part showing an error or link a pastebin, gist, etc. containing more of the log file)**:

**Config (you can paste only the changes you've made)**:

**`/dump_consensus_state` output for consensus bugs**

**Anything else do we need to know**:

**Comment by ebuchman** [comment]
> so I think the mutex to avoid handleTxsAvailable(), handleMsg(), handleTimeout() may be redundant

We need the mutex here because the ConsensusState is accessed by the RPC to get the latest state. Since the RPC runs concurrently with the consensus routines, we need the mutex to ensure it doesn't try to read from the ConsensusState while it's being updated!

We could potentially change to a RWMutex, but I don't think it's worth it here since all the internal functions need to be able to update the ConsensusState, so they would all need the more expensive mutex anyways. So it's not worth the extra cognitive/maintenance overhead. 

Also, there's no evidence that the locking is a performance issue yet (maybe you can prove that wrong!) 

Thanks very much for reading the code and suggesting possible improvements!

**Comment by Hugo-Huang** [comment]
Thanks for your reply!

**Comment by Hugo-Huang** [comment]
I have another question, what is the meaning of the comment "if the timeout is relevant to the rs go to the next step" upon cs.handleTimeout(ti, rs) in func (cs *ConsensusState) receiveRoutine(maxSteps int), why not get the run-time RoundState when dealing the timeout function? @ebuchman

**Comment by ebuchman** [comment]
Good question. I think its just so we can check whether the timeout is still valid given the round state without locking.
