### ISSUE TITLE
Relationship between core and tmsp

### ISSUE THREAD

**Issue by ltzMaxwell** [tendermint/tendermint#197]
Hi ,
    I've read documents and tutorials , but still confused about the relationship between tendermint core and tmsp ,
    1.  What role are they playing seperately, why they are seperated in two parts?
    2.  How they communicate with each other? followed with toutorial, dummy server didn't receive any message when core node made a transaction via curl.
    3.  what is the full flow of one "transaction", say I bought a car , how to store the full transaction via tendermint?
    4. How many core nodes and tmsp apps do I need?

Thanks.

**Comment by ebuchman** [comment]
Hi! Thanks for your questions. 

Much like web services are divided between an application and a server that talk over a socket (think a php app talking CGI to apache), Tendermint divides its blockchain service between an application and a consensus server. The consensus server is github.com/tendermint/tendermint: it's responsible for ordering transactions in a Byzantine fault tolerant manner (meaning it can handle up to 1/3 of validators acting maliciously). The application is a separate process that handles the actual logic of the application state, whether its a currency, supply chain manager, governance module, or otherwise.

Having the application in a separate process gives us enormous flexibility because it can be written in any language. Compare that to writing Bitcoin scripts or solidity for Ethereum.

They communicate over a socket using a simple protocol called TMSP. It has a few message types, defined using protobufs. When you curl a transaction to the core, it should put it in a block and send it via tmsp to the app; the app will update its internal state, and respond back to the core.

The transactions themselves are stored in blocks managed by the core. The blocks form a chain (blockchain!). The logic resulting from the transaction, and any effects on state, are handled by the app. 

The current model is that every validator or peer on the network runs one core and one tmsp app. However, since apps can be modular, a single app may consist of multiple tmsp modules, each of which could be its own app. A network requires at least 4 validators to be able to tolerate one fault.

Hope that helps!

**Comment by ltzMaxwell** [comment]
Hi ,thank you for your reply,
        I launched a tmsp-cli, a dummy app , and a tendermint core node, then curl a transaction to the core , but dummy app didn't receive any message , I checked with tmsp-cli , the info command returned  data: {size:0}.
       I don't know where went wrong.
       I read some source code , tried to find a flow  : curl transaction -> propose ->vote-> appendTx(in dummy app) , still in progress .
        Would you please give me some guide so that I can dive in quickly.
Thanks.

**Comment by ebuchman** [comment]
Is the core making blocks? You should see the height incrementing in the logs if it is. If not, then of course no blocks are being committed. You may need to start the core with `--fast_sync=false` to get it to make blocks if there's only one node.

**Comment by ltzMaxwell** [comment]
Hi,
    I tried to send a transaction via : curl http://localhost:46657/broadcast_tx?tx=\"abcd\" , these methods is called :
    "BroadcastTxAsyncResult(rpn/core/routes.go)->BroadcastTxAsync(rpc/core/mempool.go)->BroadcastTx(mempool.reactor.go)->CheckTx(mempool/mempool.go)-mem.proxyAppConn.CheckTxAsync(mempool/mempool.go),
     I found it nothing to do with propose, vote , consensus ,
     Where is the entry that I can make a transaction in real?     
Thanks.

**Comment by ebuchman** [comment]
Yup - the transaction gets put in the mempool. consensus runs consistently in the background and will grab txs from the mempool when its time to propose: https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L881
