### ISSUE TITLE
Analyze cost to attack truncated SHA256

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#1990]
There is concern that 80 bits of security with truncated 20 byte sha256 is insufficient. We need to do a cost analysis of the cost to break truncated levels of sha256 (i.e. cost per asic + electricity) and figure out exactly what margin between 20 byte and 32 byte hashes we want to use. (As the space savings are worth considering) Its important to note that you can't reuse bitcoin asics, since we have domain seperators on the hashes.

Ideally at the end of it, we should create an ADR for this.

**Comment by ValarDragon** [comment]
Actually I think we should just use full Sha2. While we do get space improvements per the above analysis, I imagine many people will want to fork and use a faster hash, e.g. blake2. The security trade-off for faster hashes is much different if ASICS develop, and therefore the above analysis is invalidated. (We can't assume they'd take the same size) 

To avoid the concern of having to deal with communicating not only the hash, but what size the output is (And if its truncation, or an adaptation to the algorithm itself as in blake2), I think we should just use full 32 bytes.

**Comment by ValarDragon** [comment]
Talked to @jaekwon, he said 32 bytes seemed fine for launch. We should keep the code in such a way that it is easy to update the size (so keeping the tmhash and tmhash.Size concepts). He suggested that #postlaunch we benchmark impacts changing the hash size will have on IAVL and proofs, and reconsider lowering it then. 

Jae also had an interesting idea to keep the address hash as 20 bytes. (\end Jae quotations)

This makes alot of sense to me, since attacking an address would be a pre-image attack. For a single user, the difficulty at 17 bytes should be roughly equivalent to the difficulty of finding a 32 byte sha2 collision. We have to be careful here, and be sure to account for batch attacks properly. Math for batch attacks security being equivalent to find a random collision in sha2.

Finding a random collision in sha2 takes `sqrt(pi/2) * sqrt(2^(256)) ~= 1.25 * 2^128 `.
Finding a pre-image of one of `n` hashes of length `b` bits takes `2^(b-1)/n` hashes. Setting these equal, 
`b = log_2(1.25 * n * 2^129)`. Thus if we assume there are `2**40 = 1 trillion` accounts, security is equivalent if `b = 169.3` bits, or `22 bytes`. (We actually get security up to 70 trillion with 22 bytes) If we go to `23` bytes for account size, we get equivalent security up to 18 quadrillion accounts.

Not sure what number of accounts we want to make the trade-off for (or if its even worth the mental complexity), though I feel like both 22 bytes and 23 bytes are safe.

**Comment by xla** [comment]
@ValarDragon From your last comment this sounds like a post-launch concern, unless the findings from the benchmarking will result in actionable changes. Should we move this issue?

**Comment by ValarDragon** [comment]
Changing the tmhash to 32 bytes is prelaunch, and I think was agreed on? (We can then reduce it postlaunch) I think we also want the address size to be constant post launch, so we need to decide the actual size parameter  there. So right now we should probably make a second `addrhash`, and switch usage in Tendermint/SDK accordingly, along with resizing tmhash.

**Comment by ebuchman** [comment]
Should we adopt multihash?

**Comment by ValarDragon** [comment]
I think multihash formats should only be used to communicate the state-tree hash in an initial ibc level handshake, and not in the actual merkle tree, address hashes or intra-signature hashes. The latter is going to be insanely hard to do. There isn't really a need for this extra data in the address hash, since you should know the chain its coming from. Within the merkle tree, it would increase proof size, and break rfc compatibility.

**Comment by ebuchman** [comment]
Isn't the RFC generic w.r.t the hash function chosen? Effectively multihash defines a single hash function, so I would think it could fit into the RFC format fine. 

With multihash, we could upgrade the hash function again in the future without breaking everything.

**Comment by ValarDragon** [comment]
> Isn't the RFC generic w.r.t the hash function chosen? Effectively multihash defines a single hash function, so I would think it could fit into the RFC format fine.

Maybe were not talking about the same multihash. https://github.com/multiformats/multihash is not defining a single hash. It is defining a standard set of prefixes to infer the hash function from a given hash digest. The reason it is not accurate to call this a single hash function in the same way the rfc describes is because you'd have to treat the first couple bytes of input the hash as a protocol specifier. The RFC doesn't do that, so you are back to different hash function definitions. While this is semantics, it also breaks compatibility with RFC 6962 libs. (not a super big deal though)

> With multihash, we could upgrade the hash function again in the future without breaking everything.

We get that same upgradability with what I described. My opposition is using this everywhere, I am fine with using multi-hash formats as prefixes. (Though I am unhappy that the size is always included)

You only need to be aware of what hash function was used where in an initial hand-shake (for IBC), or at the node where it changes in a given tree. I don't think we need live-upgrades of hash functions, I think we should instead re-compute the state root. (Otherwise we are doubling are security assumptions, not reducing them) There are cases where IBC may be concerned where you do want multiple hash functions in the single IBC store. However you would then define another substore for each change of hash function, which would then specify the sub-trees hash function using such a multi hash format specifier.

**Comment by ebuchman** [comment]
> you'd have to treat the first couple bytes of input the hash as a protocol specifier. The RFC doesn't do that, so you are back to different hash function definitions. While this is semantics, 

Fair enough.

I think this means Tendermint should have one hash function, `TMHash == SHA256`, used for all Merkle hashing and identifiers (eg. block hash, tx hash), while address hashes can be determined by their respective pubkeys. For launch, for secp, its the RIPEMD(SHA2()) because Bitcoin and the Fundraiser, but for ED25519 the question is open. Note if we go with SHA256 it will have no benefit over using the pubkey because they're both 32 bytes. We can always introduce new pubkey types at a later date which use different address schemes if we deem necessary. 

We only use ED25519 keys now for Tendermint validators and node ids, so let's look at the risk of collisions in SHA256[:20] there. If/when we want to add ED25519 support for users and txs, we can introduce a new pubkey type with a different address scheme.

##  Tendermint Validator Addresses

Since Tendermint validators can not be created without knowing the pubkey, it should be possible to largely eliminate the impact of collisions in addresses, though it will require care.

Tendermint indexes the validator set by Address, while updates from the app are communicated using only the pubkey, and the ValidatorSetHash is computed using just Address and VotingPower (we recently removed pubkey!). 

For the ValidatorSetHash, collisions would be a serious attack on lite clients, but we can solve it by just adding the pubkey back to Validators.Hash().

For validator set updates, the app only returns pubkeys in EndBlock. Tendermint then computes the Addresses, and for each update, checks if the address already exists as a validator, but it will not "update its pubkey". So the worst a collision could do during an update is change the validators power to zero. The App could also be written to prevent this from happening in the first place.

I don't think its unreasonable to launch with this, and to plan for an upgrade to the validator pubkeys a few months hence, but I'd also be in favour of adding the PubKey back to the Validator.Hash().

## Tendermint Node IDs (ie. p2p addresses)

We use ED25519 addresses to avoid MITM on the peer network. If Bitcoin miners want to waste money attacking this, c'est la vie


# Summary TODO:

- [ ] change TMHash to full SHA256
- [ ] use SHA256[:20] instead of TMHash in ED25519.Address()
- [ ] add PubKey back to Validator.Hash()

**Comment by ValarDragon** [comment]
I agree fully with the first section and the TM node ids.
 
> I don't think its unreasonable to launch with this, and to plan for an upgrade to the validator pubkeys a few months hence, but I'd also be in favour of adding the PubKey back to the Validator.Hash().

I don't think theres a concern with the address scheme here for us when we launch. The concern addresses is just that batch attacks become possible / more easy than a full sha2 pre-image. At validator sets of size less than 2^15 with 20 byte addresses, the security is equivalent to breaking full sha2. I guess adding the pubkey back doesn't harm anything though. So I agree with you, as its better to not have this problem when someone wants to have a larger validator set.

**Comment by ValarDragon** [comment]
Since were adding the pubkey back to Validator.Hash, we should remove the address from it. There is no new entropy there, and it just unnecessarily increases message size / hashing time.
