### ISSUE TITLE
Handle fork (1/3+ byzantine failure) gracefully

### ISSUE THREAD

**Issue by Latrasis** [tendermint/tendermint#200]
Hello, i was wondering if tendermint has an option to store orphaned blocks or if it utilizes uncle blocks similar to Ethereum?

**Comment by ebuchman** [comment]
Nope! There is no such thing as an orphaned block in tendermint. Once a block is committed, it is final! An orphan implies two or more competing chains and that is simply not possible unless a third or more validators are byzantine

**Comment by Latrasis** [comment]
So from my understanding, if more than 1/3 are byzantine - what happens? Do the other nodes delete their data? Is there any way to log a shorter chain before they delete it?

**Comment by ebuchman** [comment]
good question. we haven't defined this behaviour yet, but we are working on what this should look like. the software will panic before anything is overwritten, but it will keep a log of having received eg conflicting proposals, so that someone can come in and take a look. really we need to boot into a "recovery mode" protocol so validators can publish evidence, find out who shit the bed, kick them out and restart, but this is very much work to do. want to help?!

**Comment by jackzampolin** [comment]
Closing this as we prefer safety over liveness. Chain will halt in this scenario. Please reopen if I'm wrong.

**Comment by ebuchman** [comment]
In the event of +1/3 but -2/3 attacking the network, we should do something intelligent, ie. a "fork accountability" protocol, which Zarko and others are working on - see https://github.com/tendermint/tendermint/issues/1466. Maybe we keep this open until it's implemented.

**Comment by jackzampolin** [comment]
Sounds good! Thank you for the info @ebuchman

**Comment by melekes** [comment]
Closing in favor of https://github.com/tendermint/tendermint/issues/4189
