### ISSUE TITLE
crypto: remove pubkey from hash inside of ed25519 generate

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2000]
This is in regards to the generate function for determinstic ed25519 privkey generation. 

The latter 32 bytes of the privkey are just the cached pubkey. Currently we're hashing the entire privkey, which includes the pubkey being hashed. This seems unneccessary. The canonical form of the private keys is just these first 32 bytes. (Therefore if we use our current method, it may not fit with other language implementations) I believe that the pubkey is cached in the private key in order to make it fit the relevant API. 

/cc @Liamsi , @ebuchman

**Comment by Liamsi** [comment]
Everything you write makes sense and is correct. 
> (Therefore if we use our current method, it may not fit with other language implementations)

Although, I do not think we diverge from other implementations here, as hashing the private-key isn't part of any spec / draft rfc (at least I'm not aware if it is). Semantically, it is indeed a bit weird that we also hash the pub-key  / last 32 byte. On the other hand, it guarantees that the private-key is in a common form for ed25519: https://github.com/golang/crypto/blob/a49355c7e3f8fe157a85be2f77e6e269a0f89602/ed25519/ed25519.go#L99-L118 
I think it depends what we do with this hash in the end. Any context?

**Comment by Liamsi** [comment]
Thanks @ValarDragon! I saw your reply a few seconds after I commented.

Is this our own scheme to derive new private keys from an existing one?! Anyways, you are right that hashing the latter 32 bytes seems not necessary here but it doesn't harm either. There might even be some benefit in including the pub-key as the internal "blocksize" of sha256 is 64 bytes (the message will be padded otherwise). I'm more worried about this whole approach. Is this to derive a private key from an existing (priv) master key? Is this a common way to do this?
