### ISSUE TITLE
ErrInvalidProposalSignature Question

### ISSUE THREAD

**Issue by Deegrin** [tendermint/tendermint#2158]
In `consensus/state.go`, `cs.defaultSetProposal` could return a `ErrInvalidProposalSignature` error, but `cs.handleMsg` only catches that with a `cs.Logger.Error` message and it appears the block can still be committed. Where are invalid proposal signatures caught and blocked? Are they not a concern? Thanks!

Note: I'm looking at a downlevel master branch, but it looks like the latest master has the same logic.

**Comment by ebuchman** [comment]
The important thing is the that if defaultSetProposal returns an error, the Proposal doesn't get set on the ConsensusState and the ProposalBlockParts are not initialized. Unless we receive a valid proposal and block parts, we won't vote for one.

If others see a valid proposal and commit it, and we just see an invalid one, we'll see the valid commit from the others and commit as well.

Note that it's possible to commit a block even if you never got the proposal, as long as you got the block parts. 

You're right in pointing this out though because we should probably disconnect from peers that are sending us bunk proposals !

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/2871
