### ISSUE TITLE
mempool: punish peers sending txs that return certain ABCI codes in mempool

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2185]
Currently we just ignore invalid txs sent in the mempool since an honest peer could send txs that are invalid according to our local mempool state. 

However some txs may be invalid no matter what the state, like invalid encoding, and perhaps invalid signature (though careful with how you define signature).

Perhaps we could consider punishing peers for sending us txs that are invalid in this way by making better use of standardized ABCI codes.

This was brought up in https://github.com/tendermint/tendermint/issues/2175

**Comment by 1kevinxu1** [comment]
Is it possible to establish a "threshold" of invalid/valid messages that resets/decays per "threshold period", in such a way that if a validator ever crosses the "threshold" set by the network, they are slashed?

**Comment by ValarDragon** [comment]
The easiest way to logically separate these may be declaring a set of ABCI error codes for "This tx was invalid, and never could have been valid". (e.g. bad signature, bad amino encoding)

Then if we get that error code, it stays in the mempool cache, and your peer score is reduced. Otherwise its removed from the mempool. It means that spamming attacks have to have a valid signature at minimum, and therefore can be related to an on-chain identity.

> Is it possible to establish a "threshold" of invalid/valid messages that resets/decays per "threshold period", in such a way that if a validator ever crosses the "threshold" set by the network, they are slashed?

That sounds more related to

**Comment by marbar3778** [comment]
Open Question:

- When and under what circumstances should we disconnect from a peer or mark as a bad peer?
