### ISSUE TITLE
crypto: Switch pubkeys to protobuf oneof

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2204]
Issue is described here: https://github.com/tendermint/tendermint/pull/2164

Basically, we don't expose a way for people to add pubkeys with our current crypto API. Therefore its not the convenient permisionless addition system, so we should consider using the protobuf `oneof` for this, rather than amino interface types.

/cc @ebuchman

**Comment by ebuchman** [comment]
I would go a step further and consider making tendermint-core completely free of amino-interface-types since there is no known use case for them. eg. all reactor messages could/should be done with one-of since it's unclear how/why someone would need the global name spacing here (reactor msgs are already namespaced by the reactors channel bytes). Having amino here just gets in the way of alternative implementations
