### ISSUE TITLE
introduce ValidateBasic methods to config

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2232]
Config data should be validated as soon as possible for internal inconsistencies like negative numbers and badly formatted addresses.

Eg. see https://github.com/tendermint/tendermint/pull/2169#discussion_r209539331

**Comment by melekes** [comment]
FIXME:
- [ ] If `priv_validator_file` does not exist, the node does not produce any blocks

**Comment by melekes** [comment]
We now check negative numbers - https://github.com/tendermint/tendermint/pull/2485

As for badly formatted addresses, if we add checks to ValidateBasic methods, we introduce duplication because right now addresses are checked right before they are used.

Btw, I went through all the config options and tried to mess with them. I haven't been able to crash or deviate Tendermint's behaviour from a normal one.

**Comment by ebuchman** [comment]
Shall we close this then?

**Comment by melekes** [comment]
Yes. Let's close this for now.
