### ISSUE TITLE
ASL 2.0 | MIT | BSD

### ISSUE THREAD

**Issue by sirinath** [tendermint/tendermint#225]
Is it possible to move to a more permissive license?

**Comment by ebuchman** [comment]
Can I ask the use case? The core consensus engine is GPLv3 but all libraries (ie. for building applications) are Apache. Is there some reason you need the core to be more permissive?

**Comment by sirinath** [comment]
GPL License is not generally whitelisted. Having a GPL component in a solution gives additional hurdles.

**Comment by ebuchman** [comment]
I'd be very interested to understand those hurdles more. Our contention is that Tendermint Core is effectively a public good and no one should be able to modify it without the rest of the community benefiting from those modifications. Of course all the libraries and any application logic are free of the GPL and may be modified at will. We hoped that would be sufficient to alleviate such concerns, since most users of the software will be interested in proprietary application states rather than proprietary modifications to the core consensus engine. That said, if this is actually a blocking issue for you, clearly we may need another strategy, and we'd be happy to discuss further.

**Comment by sirinath** [comment]
What we do is to do a PoC or some demo solution which we can show to clients. If the client likes it they give us work using the technologies demoed or may be something entirely different. There are some clients who do not want to use GPL or high level of scrutiny and analysis if there is GPL code. For small times like us this is a risk as if we cannot win a project our time and money is wasted. The issues and queries we have to go through when sticking to more liberal licenses proportionally less which frees us for more income generating work. Also whether we can give back is based on what the client allows us though generally we do not modify any other project code we use.

**Comment by mdyring** [comment]
Since you won't be linking in any tendermint code, I don't see how license should be a problem...
You can keep your client's (or PoC) code close source if you so desire?

**Comment by jaekwon** [comment]
When you create your PoC (or even your production system), the app itself won't be link-compiled, but connected to TendermintCore via TMSP which is a network interface.  So it won't matter that TendermintCore is GPLv3.  Your PoC app can be in any license.

**Comment by ebuchman** [comment]
Tendermint is now Apache 2.0

**Comment by porkchop** [comment]
If god existed she would bend over out of the clouds and nuzzle you tendermint boys into her giant boozum.

**Comment by jaekwon** [comment]
Lol.
