### ISSUE TITLE
more than 100 validator peers support

### ISSUE THREAD

**Issue by bradyjoestar** [tendermint/tendermint#2257]
The perfomance of BFT algorithm drop rapidly , is there any ways for us to support more than 100 tendermint validator peers?
Thank you for your reply!

**Comment by ValarDragon** [comment]
I don't really understand what you mean by "perfomance of BFT algorithm drop rapidly". Do you mean that the block processing time is slow? Do you mean that new peers aren't connecting?

AFAIK, Tendermint itself does not enforce a max number of validators. This is enforced somewhere in the SDK iirc.

**Comment by bradyjoestar** [comment]
In our scene, we want to support more than 100 validators. If all these peers participate in “prevote-precommit-commit” period, it will cost more time to reach an agreement, just like the `pbft` in the `hyperledger fabric`,I think.
But sorry for my issue without credible test.
 
I will renew it when I have a perfomance test report in this scenario.:smile:
By  the way, I'm a chinese and my english is not very well. Sorry for your confuse .

**Comment by melekes** [comment]
I'll close this for now since there is nothing concrete or anything we can turn into action items. Of course, it's our goal to make Tendermint as fast as possible and scale well up to 1000 validators. If you want to help us out, check the issues labeled with `perf` https://github.com/tendermint/tendermint/issues?q=is%3Aopen+is%3Aissue+label%3Aperf

**Comment by ebuchman** [comment]
Have you benchmarked with more than 100 validators? We have well over 100 on our gaia-8001 testnet!
