### ISSUE TITLE
tx indexing / client receipts

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#237]
[EDIT: Actually wrote something]

Currently, there are three ways to broadcast a tx: `_async`, `_sync`, and `_commit`.
The first returns immediately (with no result), the second returns after CheckTx (and with the result of the CheckTx), and the third returns after the tx is included in a block (and with the result of both CheckTx and DeliverTx).

Using `_commit` is mostly for development stages. The more common usage is going to be firing off txs via `_async` or `_sync`, and checking up on the actual result of the DeliverTx later.

This calls into question a few issues. First, a user needs to be able to monitor the status of a transaction - is it still in the mempool, did it recently become invalid (and hence dropped from the mempool), or has it been committed? Second, if it's been committed, or even become invalid, we need to be able to fetch the result.

Seems in both cases we should have a way to query txs by their hash, which by the expected "only-once" semantics of ABCI apps, should be a unique indicator for every tx. The result of query should include the block it was committed in, the tx bytes themselves, and the ABCI response data. Alternatively we can split that into two calls, one for the tx-bytes and one for the response (aka receipt). A tx that was committed should be queryable forever; a tx that was invalidated should return why it was invalidated (the replay CheckTx result) for say up to 12 hours (configurable I guess). 

Note this means we have to save the response data, which we currently do not do! This can go in the blockstore when blocks are saved, but shouldn't be included in the block itself. It is additional data that is stored for convenience so we don't have to go recompute the whole blockchain with every query.

**Comment by jaekwon** [comment]
Just making a note that I think we decide to build indexing into TendermintCore.

**Comment by melekes** [comment]
I am lacking the information here.

1) Does `tx indexing` mean we want to give sequence numbers to transactions? 1, 2, 3, ... N

If I imagine creating the RPC call "tx_info", to get information about the transaction from the `blockStore` the client will need to send: 

a) Tx []byte
b) height of the block, in which that transaction was commited

Or maybe the task itself is to build a map `[Tx] => height` so the client does not have to know a particular block's height?

2) from an app point of view, should we add new message type to abci? Say, `TxInfo` or `InfoTx` that will be used by an app to query info about the given transaction?

**Comment by ethanfrey** [comment]
From my point of view, something like the second option would be very useful.

Use case: As a client I have some tx I (or someone else) sent to the network, but I don't want to search all blocks for the commit statement.  Some way to provide the tx bytes (or a hash of those bytes?) and get either the height, or the block itself would be great.

I have very little idea how the structs and format should look, just that it should let a light client easily verify the state of a tx without subscribing to all blocks.  Your proposed `TxInfoResponse` proposal LGTM.

**Comment by ethanfrey** [comment]
Also I think this is out of scope of this issue, but AFAIK the result from the DeliverTx call is never stored anywhere.  Only if you listen to the event when it is processed.

I don't know the concrete use here, but if we do return a result from a Tx, it should somehow be usable.... or we just return success/error?

**Comment by ebuchman** [comment]
> Also I think this is out of scope of this issue, but AFAIK the result from the DeliverTx call is never stored anywhere. Only if you listen to the event when it is processed.

This is a critical element of this issue. Why don't I fill in a description for it :)

**Comment by ebuchman** [comment]
Ok, see updated opening description. 

Also, feel free to look to ethereum for inspiration (https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethgettransaction and related)

**Comment by melekes** [comment]
TODO:

[ ] save DeliverTx response data along with tx data and block index in the blockstore
[ ] implement `get_tx` RPC call

more details will appear along the way...

**Comment by ebuchman** [comment]
Ok some more thoughts. I think in addition to the Responses, we want to save all results returned in the processing of a block, and possibly additional information as well, in something like a BlockExtra struct. eg:

```
type BlockExtra struct{
  ConsensusData ConsensusData // about how the block was decided
  ApplicationData ApplicationData // about the results of processing the block
}

type ConsensusData struct{
  Proposer *types.Proposer
  // etc.
}

type ApplicationData struct {
  Responses []types.TxResponse // from DeliverTx
  ValidatorDiffs []types.Validator // from EndBlock
}
```

We should save this info after we finish processing a block.

Then for transactions, all we need to save is, for each tx hash, the pair (block height, tx index in block).

**Comment by melekes** [comment]
Okay, that could be done obviously. But what about responses from CheckTx. I guess if we want to store this also, "all we need to save is, for each tx hash, the pair (block height, tx index in block)" becomes "all we need to save is, for each tx hash, the block height, tx index in block and the ResponseCheckTx.

Current structure I am working with:

```
type TxResult struct {
	Tx              Tx
	CheckTxResponse *abci.ResponseCheckTx
	// block height where this transaction was in. nil when it is in the mempool or invalidated
	BlockHeight       int
	DeliverTxResponse *abci.ResponseDeliverTx
}
```

**Comment by ebuchman** [comment]
I wonder if we should even save the CheckTx? There is some motivation not too: it's not deterministic across nodes, whereas everything else we've discussed so far is. So maybe the CheckTx needs only be stored in memory, and some amount of time after its committed we can purge it?

**Comment by jaekwon** [comment]
> from an app point of view, should we add new message type to abci? Say, TxInfo or InfoTx that will be used by an app to query info about the given transaction?

Probably not, I think we should solve this in Tendermint first without introducing a new ABCI message type.  The less new ABCI message types the better.  If apps start building their own tx indices, maybe we should let them expose their own RPC system, rather than trying to predict what kind of search features we'd want from the app.  Also, there's the ABCI Query message as well for general querying.

> First, a user needs to be able to monitor the status of a transaction - is it still in the mempool, did it recently become invalid (and hence dropped from the mempool), or has it been committed? 
> I wonder if we should even save the CheckTx?

This is the purpose of broadcast_tx_sync.  That should be sufficient, no?

> Second, if it's been committed, or even become invalid, we need to be able to fetch the result.

There are three ways to do this.
1. An index of committed txs
2. broadcast_tx_commit
3. The events system

2 seems sufficient for most use-cases, but connections can die, and not everyone wants to hang around to wait for a tx.  So 1 seems like a good idea for this purpose too.  3 seems important as well, but maybe not for most users.

> BlockExtra

I don't think this necessarily needs to be stored in a block structure.

---------------

One way to solve this is to let DeliverTx return a few tags for that tx, which isn't stored in the blockchain, but is only used to index txs.  That way we let the ABCI app run the transaction to completion, and aggregate any information as needed, and returns it in the DeliverTx response.

TendermintCore can then connect to an external general indexer like a SQL database to manage those tags.  An external indexing service would allow us to keep Tendermint dependencies to a minimum.  A simple KVStore would not be sufficient/efficient, and a SQL store would require a join table to join the TxTable and TagsTable.  Are there other ways to index tags?  Lucene/Solar?

(Notice this doesn't require the BlockExtra block structure.  We'd just store DeliverTx results in the external indexing system)

We should figure out performance characteristics of various indexing strategies.  We should also ensure that we can easily search for txs under some height, and delete/garbage-collect old information.

What use-cases are we missing with this indexing system?  Is it useful and general enough to commit to maintaining it?

**Comment by ebuchman** [comment]
> This is the purpose of broadcast_tx_sync. That should be sufficient, no?

Not really. What if it passes CheckTx, but then something else gets committed, and it becomes invalid during the CheckTx replay?

> 2 seems sufficient for most use-cases

Not sure I agree. `broadcast_tx_commit` seems mostly useful for very-low-throughput users and for development. Any case where they want to sent higher throughput and/or not wait a second or a few between each send will require they use broadcast_tx_sync. So I think we should expect that to be the standard for production use cases.

> I don't think this necessarily needs to be stored in a block structure.

We once talked about storing all the info from processing a block, as well as meta info (eg like the proposer). What's the reason for not wanting to do this? Why not be able to fetch a block and all the results from processing it? You think the overhead of writing the TxResults is too high? 

> One way to solve this is to let DeliverTx return a few tags for that tx, which isn't stored in the blockchain, but is only used to index txs

I like this idea. Just suggested it in #basecoin. Not sure about the details re connecting to an external db to manage this though.

**Comment by ebuchman** [comment]
All in all, I think having built in simple tx indexing in tendermint would be a benefit. we can make it optional so users can turn it off if they want tendermint to go as-fast-as-possible

**Comment by jaekwon** [comment]
>> This is the purpose of broadcast_tx_sync. That should be sufficient, no?
> Not really. What if it passes CheckTx, but then something else gets committed, and it becomes invalid during the CheckTx replay?

Then there's broadcast_tx_commit?  I'm not opposed to providing CheckTx data, I'm just not sure we should be supporting an API for this data in the form of a GET TX_ID request, because it's an odd way to program it for the client, and inefficient.  Broadcast_tx_commit and wait for the response, is 1 request and simple.  Broadcast_tx_* and GET TX_ID query to get the mempool CheckTx result, seems convoluted.

And if broadcast_tx_commit is not efficient enough (e.g. too high a throughput) then subscribing to an event would be better.  We don't support getting CheckTx this way yet, but my point is a streaming events API would be better than supporting this information via GET.

If the connection gets lost because of any reason, the broadcast_tx_commit can just be retried.

>> 2 seems sufficient for most use-cases
> Not sure I agree. broadcast_tx_commit seems mostly useful for very-low-throughput users and for development. Any case where they want to sent higher throughput and/or not wait a second or a few between each send will require they use broadcast_tx_sync. So I think we should expect that to be the standard for production use cases.

If broadcast_tx_commit is not sufficient, they should use broadcast_tx_async and subscribe to websocket events.

**Comment by jaekwon** [comment]
Maybe we're talking past each other.  My only point is, users shouldn't have to make a second RPC request to get the current CheckTx status, because it could be done in 1 request.  And if it can't because it's too inefficient to do so, they prob should just implement a streaming listener.

On another note, we could rename broadcast_tx_sync to broadcast_tx_check.

**Comment by melekes** [comment]
Hm.. I've read all the comments and discussion on basecoin channel. It seems we didn't reach consensus here.

If my reading on this is correct, 

1) we do want to have a simple indexer for DeliverTx responses (stored in levelDB until we prune blocks), as a separate module (plus benchmarking of how it affects executing the block).

2) we are not sure about a simple indexer for CheckTx responses (stored in-memory for some configurable amount of time), given `get_tx` will return this if we have a CheckTx response, but do not have a DeliverTx yet (I doubt that somebody will want CheckTx response if DeliverTx is available)

**Comment by melekes** [comment]
3. we are not sure about `BlockExtra` structures. I think we do want to provide as much info to the user as we can, but we should be extra careful how it would affect transaction throughput. Do we have such benchmark?

**Comment by ethanfrey** [comment]
One more thought here, after reading #423 

When I query based on the tx (or tx hash) to find what block (and index) it was in.  Is there a proof there?

I mean, I get an answer, I can make a separate call to check if it is actually at that location with a proof (see #423)  If the node lies, I can detect that. But... what if the node says it was not committed?  Do I need to check with all nodes before believing that?

If the tx index had a merkle hash in the header, I could get a proof that this tx was in the location, or a proof of non-inclusion (this tx never made it into the blockchain). Maybe this is overkill, but I am thinking about proof trails for everything these days...

If this is too much work or out of scope, ignore my comment for now.  But by 1.0, more proofs are good.

**Comment by srmo** [comment]
@ethanfrey I find that very valuable. It's too easy to fall back into old patterns, were we didn't bother about correctness and just assumed it. But Blockchain needs a different way of thinking about that. So yes, having a proof that this is actually the TX I was looking for is important.
