### ISSUE TITLE
docs: explain that we use chacha20poly1305 (in secure-p2p.md)

### ISSUE THREAD

**Issue by zramsay** [tendermint/tendermint#2421]
https://github.com/tendermint/tendermint/pull/2181#discussion_r208425659

**Comment by xla** [comment]
@ValarDragon Does it make this issue obsolete?

**Comment by ebuchman** [comment]
The issue is to note what we use for authenticated encryption in the docs at https://github.com/tendermint/tendermint/blob/develop/docs/tendermint-core/secure-p2p.md#secure-p2p

We changed it, and in doing so removed it from the documentation, instead of changing it to reflect the new code. See https://github.com/tendermint/tendermint/pull/2181/files#diff-e06fd9f10cc82a180a6399273b496698L6. @ValarDragon mind bringing it back with explanation of how its different?

**Comment by ValarDragon** [comment]
Oh didn't realize there were docs for this lol, I was only aware of the spec. (Which I changed here: https://github.com/tendermint/tendermint/commit/7bf28af590018491606bfd5fa4e4aa0c3b91708e)

I'll write a PR to fix this :+1:

**Comment by xla** [comment]
Follow-up in #2454
