### ISSUE TITLE
Evidence Deserialization

### ISSUE THREAD

**Issue by zmanian** [tendermint/tendermint#2423]
It looks like we still have an unfixed deserialization bug.

https://github.com/cosmos/cosmos-sdk/issues/2031

**Comment by ebuchman** [comment]
Right. Evidence isn't registered on the amino codec in `blockchain`. https://github.com/tendermint/tendermint/issues/2083 strikes again

**Comment by ebuchman** [comment]
Was wrong here - evidence is decoded properly in Tendermint as far as I can tell. 

The bug at https://forum.cosmos.network/t/syncing-stopped-panic-unkown-pub-key-type/838/8 seems to be an SDK error - it's expecting evidence to come through ABCI with a pubkey, but since v0.23, Tendermint doesnt send the pubkey there (I see now this was poorly documented in the CHANGELOG).
