### ISSUE TITLE
consensus: cap evidence age

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#2447]
We should cap evidence age at 10_000_000 (assuming 1 sec. blocks - 110 days). The same thing we do for `BlockSize.MaxBytes` (100MB) https://github.com/tendermint/tendermint/blob/d2d729ab76550a73c7a8f9f47913616c63e49d64/types/params.go#L11.

**Comment by ValarDragon** [comment]
I'm a bit confused, are we setting an upperbound on how high you can set the max evidence age to? This seems odd to me. Or is this about actually parameterizing a maximum evidence age, which will have a default config value of 10k. That makes a lot of sense to me.

Though if this is measured in blocks, 10k seems too small. (1 block per 5 seconds * 10k blocks means we only track double signs within the last 13 hours)

**Comment by melekes** [comment]
> are we setting an upperbound on how high you can set the max evidence age to? This seems odd to me.

why? because you can't change it?

10k is indeed small. 10m should be ok

**Comment by ValarDragon** [comment]
Yeah. It feels like an unnecessary restriction. I think it is quite reasonable that a chain may want evidence that a double sign happened <x> months ago to appear on chain, even if they don't want to slash for it. (It will burn the double signers reputation / reveal information about them) I don't see what we gain by upperbounding the maximum parameter if theres no technical reason why we must. Is there some benefit which I'm not seeing?

**Comment by melekes** [comment]
To be consistent with MaxBytes restriction. Although, the latter now seems a bit artificial too. We use MaxBlockSizeBytes to limit maxMsgSize in blockchain/reactor.go https://github.com/tendermint/tendermint/blob/d2d729ab76550a73c7a8f9f47913616c63e49d64/blockchain/reactor.go#L35. It seems what we really need is to use ConsensusParams there too. Maybe even using the same technique we've used for the mempool tx filtering.

**Comment by ebuchman** [comment]
These are sanity checks on user input and upper bounds on DoS vulnerabilities. 

An alternative to these checks would be careful and clear documentation about what happens if your blocks are too big or your evidence is too old. In doing so we'd probably want to mention the upper bounds that shouldn't be exceeded. Might as well build it in as a validity check, no?

**Comment by ValarDragon** [comment]
Theres no upper bound that shouldn't be exceeded here. What I mean is that there is no technical reason why you can't have evidence propagated / included from a year ago. 

> In doing so we'd probably want to mention the upper bounds that shouldn't be exceeded.

The only reason there would be an upperbound that shouldn't be exceeded is if there was a technical reason for it. (e.g. in chacha20poly1305, you can't encrypt a message over 256 GiB. Why? Because doing so would overflow the block counter field used internally, and that field can't be increased due to another nested technical reason) Unless I'm missing something, for any "maximum evidence age" we set, I could in fact have set it to "maximum evidence age + 1", it was arbitrary, and there is no reason for it.

> These are sanity checks on user input

We can assume someone making a chain will read through and set the parameters carefully. I'm fine with having a "validate" config method which prints stuff like "[Warning] are you sure you want this big of an evidence age". Blocking it seems unnecessary though.

> upper bounds on DoS vulnerabilities.

An upperbound on DoS vulnerabilities should be parameterized in terms of these constants. That seems independent of creating an arbitrary maximum in the config.

**Comment by ebuchman** [comment]
Done in #2560

**Comment by ebuchman** [comment]
Oh nvm, this is about capping the actual value that can be set for the cap!

**Comment by melekes** [comment]
https://github.com/tendermint/spec/blob/45bbbb6317260ac6d70a450746e3219b485c3d65/spec/core/state.md#evidence
