### ISSUE TITLE
KV indexer should return no more than per_page records

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#2492]
https://github.com/tendermint/tendermint/blob/4c4a95ca53b17dd3a73eb03669cf6013d46e1bdf/rpc/core/tx.go#L175-L186

Current indexer may do a full scan and return all the records, from which we select only `per_page` results. It would be much better if the indexer knew about the limit and scanned up to that amount (i.e. when it finds N records matching a query, it returns immediately instead of continuing scanning).

The solution is to either append `"LIMIT 0, %d", per_page` to a Query or modify Search method signature.

**Comment by goolAdapter** [comment]
if LIMIT specified，it can improve good search performance，but a malicious client also can perform a invalid ‘OpContains‘ search, which cause full scan.

https://github.com/tendermint/tendermint/blob/0c9c3292c918617624f6f3fbcd95eceade18bcd5/state/txindex/kv/kv.go#L342-L351

I still consider tendermint core to expose complicated search without fee is easy to DDOS.

**Comment by melekes** [comment]
> a malicious client also can perform a invalid ‘OpContains‘ search, which cause full scan.

great point @goolAdapter ! that's why I added "security" label and 1.0 milestone.

**Comment by goolAdapter** [comment]
got it，thanks for your reply.

**Comment by goolAdapter** [comment]
yes, I think it hard to solve this by technique, my consider on this issue is：
a. use sentry node to protect producer node from DDOS attack
b. use fee to avoid malicious query
c. use Badger(https://github.com/dgraph-io/badger) to replace leveldb, as Badger implemented "Key-Value separation", it's much quickly when range iteration (see https://blog.dgraph.io/post/badger-lmdb-boltdb/), is this look like a good idea?

**Comment by melekes** [comment]
This might work.

Check out the benchmarks I did not so long ago
https://github.com/tendermint/tendermint/issues/1835#issuecomment-421062709
