### ISSUE TITLE
Check evidence by validator address

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2561]
There's no value in tracking multiple pieces of evidence for the same validator with the same height and round. See https://github.com/tendermint/tendermint/pull/592#discussion_r154095775.

Also, we may want to limit the amount of evidence we'll process for a single validator at different height/round within a single unbonding period.

**Comment by ValarDragon** [comment]
Since `evidence.MaxAge = 2 * unbonding period`, we divide up the evidence age categories into periods `p1`, and `p2`. `p1` is the really old ages, the time range: `[MaxAge, 1 * Unbonding Period]`. `p2` is the more recent period, `[Unbonding period, now]`. We only need the latest evidence within `p1`. The reason being, anyone who leaves the `completeUnbondingQueue` will be slashed for the latest slash within `p1`. Its less clear to me how much we need to keep in `p2`, since those will eventually become the latest elements of `p1`.

If we go with the tombstone approach, https://github.com/cosmos/cosmos-sdk/issues/2363, then this gets radically simplified and we'd take in at most 3 evidences. (Latest in `p1`, latest in `p2`, and if the distance between the `p1` and `p2` evidence points are greater than 1 unbonding period, a single evidence that covers the range not previously covered.)

**Comment by ebuchman** [comment]
Also see related https://github.com/tendermint/tendermint/issues/2590

**Comment by Slamper** [comment]
I think this is really important since otherwise, a malicious actor could include the same evidence in multiple blocks.
In cosmos-sdk the jail period could thereby be extended by an attacker by ```maxEvidenceAge``` and any other application built directly on Tendermint would have to keep track of duplicate evidence itself or multiple pieces of the same evidence could also cause multiple slashings.

**Comment by marbar3778** [comment]
@cmwaters I believe you mentioned something in the last dev calls in regards to saving evidence so it could not be resubmitted. Does that overlap with this issue?

**Comment by cmwaters** [comment]
No this is slightly different. In my case I just meant to stop identical evidence from being different but this is about stopping multiple attacks by the same validator in the same height by just saving the first one and ignoring the rest. I was planning on doing this issue in the near future but just hadn't got around to it. I don't think it's vital.

**Comment by liamsi** [comment]
> I don't think we need evidence from the same validator at the same height, but different rounds.

I agree with this.
