### ISSUE TITLE
Cap evidence by absolute number instead of relative size

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2590]
As of #2560, we cap the amount of evidence allowed in a valid block based on the `types.MaxEvidenceBytesPerBlock`, which limits it to 1/10 the size of the block.

As discussed in https://github.com/tendermint/tendermint/issues/1637#issuecomment-425736069, we should consider limiting it to an absolute number of pieces of evidence, rather than allocating such a large chunk of the block space.

**Comment by cmwaters** [comment]
So my understanding of this is that pinning the size relative to 1/10th of the allocated block size is relatively arbitrary and it would be better to allocate it based on an absolute number. My intuition is that this should be just the size of the validator set as all evidence is proposed individually which indicates that the average expected number would be somewhat proportional to the validator set size and in any case, I'd imagine it is extremely rare that more then the validator set size could be submitted (in which, even then, moving it to the next round wouldn't be too problematic). 

I don't think in the current state that there is much of a DDoS vector (evidence has to be valid and new). My implementation would be simply to modify BlockExecutor#CreateProposalBlock to use the validator set size instead of `maxNumEvidence`.

Is anyone in opposition to that or wants to discuss/propose alternative ideas?
(cc @ebuchman @melekes)

**Comment by melekes** [comment]
> I'd imagine it is extremely rare that more then the validator set size could be submitted

As rare as 1/3+ cabal group attacks. It can be bigger than the valset size if validators from past heights (which are still bonded) conduct phantom validator attack on some light client.

The discussion here https://github.com/tendermint/tendermint/issues/1637#issuecomment-427539882 seems to suggest we should either cap by a fixed number (2) or a percentage of the valset (5%).

We'll also need to implement smarter evidence sorting in the evidence pool https://github.com/tendermint/tendermint/issues/2561 to prevent single validator occupying all the slots for a few consecutive blocks.

**Comment by cmwaters** [comment]
why not 100% of the val set - this is just the max (it's fine if it's not filled) and it is in our interest to get all the evidence submitted on the chain as soon as possible - I imagine this makes recovery (whatever that really means easier) and reduces the window of opportunity that a malicious node can do something with the fork. If not 100% what do you suggest then (I don't think it should be a fixed number)

>  We'll also need to implement smarter evidence sorting in the evidence pool #2561 to prevent single validator occupying all the slots for a few consecutive blocks.

Yes, this makes sense - if the punishment is constant then we should only propose one evidence per validator per height.

Just had a side thought. We generally check to see whether evidence is within some period that allows us to enact a punishment as one of the measures to check it's validity. But if an earlier evidence is approved and the validator slashed than all following evidence against the validator is now invalid simply because there's nothing to slash them with.

**Comment by melekes** [comment]
> Just had a side thought. We generally check to see whether evidence is within some period that allows us to enact a punishment as one of the measures to check it's validity. But if an earlier evidence is approved and the validator slashed than all following evidence against the validator is now invalid simply because there's nothing to slash them with.

yeah, after each block, we should remove evidence from validators who are no longer part of validator set (i.e. those who've been slashed in that block)

**Comment by melekes** [comment]
> why not 100% of the val set - this is just the max (it's fine if it's not filled) and it is in our interest to get all the evidence submitted on the chain as soon as possible

not sure. maybe to keep the block size small.

**Comment by cmwaters** [comment]
How about the partially arbitrary number of 1/3+ of the validator set (where each piece of evidence has a unique validator)?
