### ISSUE TITLE
metrics: remove peer id label from p2p metrics to prevent cardinality explosion.

### ISSUE THREAD

**Issue by hendrikhofstadt** [tendermint/tendermint#2600]
I just reviewed the PR #2425.

The metrics introduced are very insightful and important for people running nodes. However the newly introduced p2p metrics somehow clash with Prometheus' guidelines.

A quote from their manual:

>Remember that every unique combination of key-value label pairs represents a new time series, which can dramatically increase the amount of data stored. Do not use labels to store dimensions with high cardinality (many different label values), such as user IDs, email addresses, or other unbounded sets of values.

With the new metric we are creating a label per peer ID which can easily grow up to a really high amount over time or under an intentional attack.

Normally these are not the kind of metrics you would track using Prometheus.

**Comment by melekes** [comment]
Good point

**Comment by mdyring** [comment]
Agree with @jackzampolin. They are rather useful for observing peer health/malicious activity on both private (relay/peering) and public settings.

![image](https://user-images.githubusercontent.com/18033781/50679516-0c130f00-1004-11e9-8c7c-3fa3c485814e.png)

If anything, perhaps a setting to disable it in the config if so desired. But I'd really hate to see it go all together.

**Comment by melekes** [comment]
The solution here may be to measure peer rotation over time (how many peers disconnected / connected). Hendrik's point about growing cardinality is valid, except the number of peers is capped. With the assumption that those peers are rotating slowly (say during a year 5-10% of peers disconnect and never connect again, 5-10% new peers join the node) we'd be safe to leave this metric. Otherwise, we remove it and find a way to "observing peer health/malicious activity" differently. The assumption needs to be validated, of course.

I'm against adding new setting. The current config is already too bloated with different settings imho.
