### ISSUE TITLE
Write a proof for our round-robin proposer selection algorithm

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2633]
We should write a proof of correctness for this algorithm. Its not immediate that this produces the correct distribution or has the expected period, given that new validators can enter and old ones can exit at any time. (From the view of TM)

We should formalize the notion of round-robin with validator set updates, and then prove correctness of the algorithm we use.

**Comment by ValarDragon** [comment]
I'm increasingly certain that our algorithm does not have the properties we want. As I understand the algorithm, theres a rather obvious attack on this to increase your distribution of being chosen. (I am unclear on how we initially set a validator's accum, so that may reduce the efficavity of this)

Suppose you split your stake amongst 2 validators, A, B. You see that A will propose at block `n`. You make a tx to unbond validator B which gets in block `n-2`. You also make a tx to bond validator `B` in block `n-1`. Due to the next validator offset stuff, `B` won't be part of the validator set in block `n`. This lowers the total amount of stake / the amount you have to subtract from `A`. `B` also ends being a validator in block `n+1`, so their stake is being decremented from everyone else's accum. So suppose there is `t` total bonded stake, you have `2p` stake, `p` in A and `p` in B. Then your chance of proposing is now `2(p / (t - p))`. (The coefficient of 2 comes from this being applicable by both `A` and `B`)

I also think this will be profitable on the cosmos hub for a long time. (As I think the bulk of the reward will be block reward, but even if it was tx fees, the skew in distribution is significant) Thankfully this is detectable. Delegators shouldn't even really get upset here, since even though the unbond stuff is confusing, it is likely much more profitable.

**Comment by cwgoes** [comment]
Several more points of possible interest from further discussion between @ValarDragon and myself:

- The potential profitability here is mitigated somewhat by most of the reward being stake-proportional instead of directly to the proposer (in the current Gaia implementation, could vary for other Tendermint users), but it's still nontrivial because the chance of proposing changes proportionally to the fraction of the total stake you can use in the attack. Asymmetric proposer election is problematic even if it didn't directly cause reward issues - proposers have the power to censor transactions and precommits, for example.
- If validator `B` is reset to the "bottom of the pack" when it re-bonds, it helps but I don't think it fully mitigates the problem - there could still be cases when B's accum was low enough anyways that the attack is still profitable. This *isn't* true at the moment - instead the validator accum is reset to `0`, which will put them near the top of the pack (and leads to a second profitable attack, see #2718).
- The "difficulty to delegators" isn't really an effective mitigation. Any individual or coordinated entity with a few percent of stake can definitely be in the validator set even when splitting their stake and could individually pull this off. Even if that weren't the case or the requisite threshold were higher, if it's profitable enough tit-for-tat agreements between validators and off-chain "stake pools" would probably emerge.

**Comment by ebuchman** [comment]
Should we close this for https://github.com/tendermint/tendermint/issues/2890 ?

**Comment by ValarDragon** [comment]
Sure! We should just keep in mind that the attacks specified here may still be profitable in certain scenarios.
