### ISSUE TITLE
Remove POLInfo and simplify Proposal message

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#2646]
According to the spec, Proposal message has the following format: 
⟨PROPOSAL, height , round , proposal, validRound⟩ where proposal corresponds to the id of the block proposal (BlockID). Currently, Proposal message has the following format:
https://github.com/tendermint/tendermint/blob/80562669bfc0ad56d9d37662407c60661fdf476b/types/proposal.go#L22-L30

We could simplify Proposal message as done in spec by removing BlockPartsHeader and only having a single field that is BlockID of the proposed block. Furthermore, we currently rely on function POLInfo to decide what is POLRound and POLBlockID that goes into Proposal message. See https://github.com/tendermint/tendermint/blob/80562669bfc0ad56d9d37662407c60661fdf476b/consensus/types/height_vote_set.go#L148-L159

This is not needed as ValidRound, ValidBlock and ValidBlockParts keep equivalent of those information. Therefore, we could completely remove POLInfo function.

**Comment by ebuchman** [comment]
> removing BlockPartsHeader and only having a single field that is BlockID

Do you mean instead of having BlockPartsHeader and POLBlockID, just have one BlockID?

I think the reason they're separate is because you don't need a BlockID.Hash for proposals in the happy path, which is why we just have the BlockPartsHeader, but you do need them for verifying POLs, since votes sign BlockIDs (BlockID.Hash is more convenient for lite-clients than BlockID.PartsHeader). 

Was it always the case that if POLRound is set, `POLBlockID.PartsHeader == BlockPartsHeader` ?

If we do this, it would add ~33 bytes per proposal on the happy path, but it's probably worth the alignment.

Note the spec doesn't treat the block gossipping mechanism, so it has no concept of the Hash vs PartsHeader yet.

> Therefore, we could completely remove POLInfo function.

Maybe we can keep it for now but run sanity checks to ensure when we make a proposal that our valid round/value match what we get from POLInfo.

**Comment by milosevic** [comment]
> Do you mean instead of having BlockPartsHeader and POLBlockID, just have one BlockID?

Yes. 

> Was it always the case that if POLRound is set, POLBlockID.PartsHeader == BlockPartsHeader ?

Yes. 

Could we avoid setting Hash in case POLRound is not set? Would this help?

> Maybe we can keep it for now but run sanity checks to ensure when we make a proposal that our valid round/value match what we get from POLInfo.

What are the benefit of doing it? Note the issue https://github.com/tendermint/tendermint/issues/2702 we are having as we rely on POLInfo instead of ValidRound.

**Comment by ebuchman** [comment]
> Could we avoid setting Hash in case POLRound is not set? Would this help?

Yeh, but seems like a micro optimization.

> What are the benefits of keeping it? Note the issue #2702 we are having as we rely on POLInfo instead of ValidRound. Maybe it makes sense to keep it as test helper function.

Yeh, let's just use it for testing. We just want some assurance that the ValidRound/Block we have in the ConsensusState matches whatever you would compute from looking at the HeightVoteSet

**Comment by ebuchman** [comment]
Done!
