### ISSUE TITLE
Add Version to ConsensusParams

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#2671]
Follow up to #2468, this is the final piece of [ADR-016](https://github.com/tendermint/tendermint/blob/develop/docs/architecture/adr-016-protocol-versions.md), to allow apps to update their version without a restart. 

Originally ADR-016 proposed adding a new field to EndBlock for updating versions, but it was realized in https://github.com/tendermint/tendermint/pull/2636#discussion_r225602628 that it might make more sense to just add it directly to the ConsensusParams.

Note we forgot to update the changelog in ADR-016 when it was updated for this change in #2667

**Comment by ebuchman** [comment]
#3152 makes this non protocol breaking. Bumping it back

**Comment by b00f** [comment]
I have an idea. Out of box idea, Instead of changing protocol. What we need is an external application, lets call it `AppSelector`.
Changing protocol to support possible fork or updates will make codebase nasty. This messy code currently is applied Ethereum. Look [here](https://github.com/ethereum/go-ethereum/blob/f4094d09cd3bf4c1420f358d77b803d5d84d0994/params/config.go#L35)

AppSelector will run the application but it can manage versioning. AppSelector:
- Monitor the blockchain. Anytime the AppVersion changes it will automatically find the new version (possibly from GitHub release page) and run the required verision
- It can be programmed to start new version at a certain height.
