### ISSUE TITLE
consensus: proposal#POLRound checking code might be incorrect

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#2702]
https://github.com/tendermint/tendermint/blob/bbf15b3d09ac05ff2cfd58b53313ec612e1a9b07/consensus/state.go#L1428-L1432

Refs https://github.com/tendermint/tendermint/issues/2392#issuecomment-427775713
In `log-node2.txt` I found 

```
Okt 01 15:50:24 ip-172-31-9-150.us-east-2.compute.internal thorchaind[20170]: E[10-01|15:50:24.490] Error with msg                               module=consensus height=366511 round=0 type=*consensus.ProposalMessage peer= err="Error invalid proposal POL round" msg="[Proposal Proposal{366511/0 1:707EC619D399 (0,:0:000000000000) /EA1BAEEF4B7D.../ @ 2018-10-01T15:50:24.485Z}]"
```

Can't `POLRound` be 0? If not, what could've led the honest node to create such a proposal?

In any case, I'd prefer the above code to be rewritten:

```go
	if !(proposal.POLRound == -1 ||
		(proposal.POLRound > 0 && proposal.POLRound < proposal.Round)) {
		return ErrInvalidProposalPOLRound
	}
```

**Comment by melekes** [comment]
Note here

```
Okt 01 15:50:24 ip-172-31-9-150.us-east-2.compute.internal thorchaind[20170]: E[10-01|15:50:24.490] Error with msg                               module=consensus height=366511 round=0 type=*consensus.ProposalMessage peer= err="Error invalid proposal POL round" msg="[Proposal Proposal{366511/0 1:707EC619D399 (0,:0:000000000000) /EA1BAEEF4B7D.../ @ 2018-10-01T15:50:24.485Z}]"
```

proposal.Round == proposal.POLRound

**Comment by ebuchman** [comment]
```go
	if !(proposal.POLRound < -1 ||
		(proposal.POLRound >= 0 && proposal.POLRound >= proposal.Round)) {
		return ErrInvalidProposalPOLRound
	}
```

This doesn't look right - wouldn't this return an error if POLRound == -1 ?

I think perhaps what's happening is that the proposer is receiving +2/3 prevotes for nil for the round before they even get a chance to make a proposal. So then POLInfo returns a 0 for POLRound since it's seen a +2/3 prevotes

**Comment by milosevic** [comment]
@ebuchman You are right, it returns error for POLRound == -1; the original condition is correct. Regarding your other comment, it will not be a concern after we modify Proposal to use ValidRound instead of computing POLInfo (https://github.com/tendermint/tendermint/issues/2646).  
We could potentially change condition slightly to make it more explicit:

```go
	if (proposal.POLRound < 0 && proposal.POLRound != -1)  || proposal.POLRound >= proposal.Round {
		return ErrInvalidProposalPOLRound
	}
```

**Comment by ebuchman** [comment]
Let's close this for #2646
