### ISSUE TITLE
Network stalls after 2-5 min of average load

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#2709]
From Riot:

cryptoji:
Hello to all.
We have been trying to deploy and configure a private network for use in production for a couple of months. Our project is very large and the expected average load is about 100-200 transactions per second (only for the near future).
We have a lot of problems with blockchain. But one from those completely blocks us and makes it impossible to deploy in production.
Problem:
We have a network of 15 validators, the load on each of them is distributed by the balancer. After testing 100-200 tx / per second, sooner or later (usualy 2-5 minutes), the state of consensus comes to the fact that > 50% of validators will keep a large number of transactions in a mempool (and validators vote for them) but since there are no validators of these transactions for the most part, there are not enough votes to get into the network. New transactions enter the network only through validators where the mempool is not clogged. That is, we just fall off half the network anyway.
Our prototype ABCI is written in Python. All that it does is index the all tags in the deliver_tx handler. We use GRPC as a communication mechanism for TM and ABCI.
Maybe we are doing the wrong load testing. We do not know at all what hardware resources should be and what can be the permissible load on them.
We really need help, since we have already gone too far and the problem cannot be solved on our own. I am online ready to provide all the necessary information (configs, etc.). We are ready to pay for advice and assistance.
Thanks guys)

On test cases we used TM version 0.23.0-013b9cef, but yesterday we switched to version 0.25

**Comment by melekes** [comment]
We need to recheck https://github.com/tendermint/tendermint/issues/1394.

**Comment by ebuchman** [comment]
@cryptoji can we get more info on this please? What kind of machines are you using, how big are the txs, can we see some logs? Any other settings in the config I should know about?

You were able to replicate with v0.25?

**Comment by curicm** [comment]
We are also testing performance of our basecoin app (cloned from the latest master branch of cosmos-sdk) In our test setup there are 4 validator nodes in cloud (running modified basecoind). We're sending transactions via basecoincli from 5 VM's, each VM sending approx 100Tx/sec. 

With 4 VM's we have achieved a consistent Tx Throughput rate of ~380Tx/sec (as reported by tm-monitor). When adding another traffic generating VM, the mempool starts growing exponentaly, hitting the 100.000 Txs in a minute. Sending any further Tx is resulting in mempool full error. I can send logs if needed for investigation (I'm not sure if this is already fixed?) Thanks.

This behaviour can be seen in following graphs:

![image](https://user-images.githubusercontent.com/42861837/47609199-93f40000-da3a-11e8-844b-9713ad86a965.png)

**Comment by ebuchman** [comment]
@curicm what version are you running ? We've changed some default settings and the way we determine the number of txs that go in a block (now based on block size in bytes, instead of number of txs)

**Comment by curicm** [comment]
@ebuchman we're at 0.24.2 (Cosmos-SDK), which uses Tendermint version 0.23.1

**Comment by ebuchman** [comment]
Ok right. In v0.24 we:

- reduced the default mempool size
- switch from using "BlockSize.MaxTxs" to "BlockSize.MaxBytes"
- fix a few memory issues in the mempool

Taken together they may help with the issue you're seeing. We should have a new SDK release out next week that updates to the latest Tendermint.

Also, I think the bottom two graphs are the same - they both look like "Tx per block", since the max in that version was 10k.

**Comment by curicm** [comment]
Thanks for help. The bottom graphs are indeed linked to same prometheus metric, have corrected it.

**Comment by cryptoji** [comment]
@melekes thanks for the support
@ebuchman
Unfortunately I can only provide more info tomorrow: Prometheus logs, nodes logs, dump_consensus, node configurations, and etc.

The network continues to form blocks while we have more than 2/3 validators available. But those validators where the mempool stopped - they voting for the fork, but they are in the minority. Further, as soon as more than 2/3 of the validators failed, the network stops.

By the way, we still have open questions, we have formed them for ourselves, but maybe you can help us answer them:
1. How many transactions per second are we expecting? - 2000 TPS is needed for our project (min 1000+).
2. Generate empty blocks or not? - not.
3. How often are blocks generated? - default.
4. Do we need all the validators or add also light nodes, etc? - as we understand our validators should not directly accept requests for the formation of transactions, this will be due to the proxying nodes (full nodes), see item 5
5. DDOS protection is a proxy (https://tendermint.com/docs/interviews/tendermint-bft.html). What is the functionality of this proxy? Examples of implementation, etc.
6. ABCI statefull - best practices how to implement?
7. Example of reference architecture (testnet / mainnet) with indicators. How many transactions, what resources: number of nodes, their characteristics: kernels, memory, disks, network
8. Best practice on tuning (config TM, OC kernel parameters)
9. Backup / restore / verify - without this, you cannot go to the prod at all.
10. Upgrading TM versions (data migration)
11. Dynamic addition of validators - based on the documentation, this is done using the ABCI State and EndBlock handler.
12. How change ABCI (socket to grpc and back) without re-initializing the network? - no answer

Sorry, if some questions seem incompetent, we are just starting to understand all this)

**Comment by cryptoji** [comment]
We use Tendermint core without Cosmos SDK.
But at the moment we are guiding by this document https://bubowerks.io/blog/2018/07/19/cosmos-tendermint-network-architecture/

**Comment by srmo** [comment]
Interesting thread. From the initial post: why use grpc? Isn’t it slow by default?

Also, what was used to generate the graphs and was the data collected from prometheus endpoint only?

**Comment by curicm** [comment]
I can confirm that the mempool issue does not appear on the Cosmos-SDK 0.25.0/Tendermint 0.25.1-rc0 using the same setup and described above. The Tx throughput rate and mempool are stable even under heavy load.
![image](https://user-images.githubusercontent.com/42861837/48343386-89f51280-e672-11e8-87ad-1a2f7d698125.png)

**Comment by ebuchman** [comment]
Awesome! Thanks for the report. Can we close this issue then?

@cryptoji would you mind opening a new issue summarizing your questions or what you'd like to see clarified in the documentation?

Thanks!

**Comment by melekes** [comment]
> How many transactions per second are we expecting? - 2000 TPS is needed for our project (min 1000+).

I'd recommend you to do your own benchmark. We have [tm-bench](https://tendermint.com/docs/tools/benchmarking.html). It only works with kvstore build-in application, but can be changed to support your application pretty easily (if you know Golang). You will need to change generateTx method https://github.com/tendermint/tendermint/blob/d9a1aad5c559ebd4b3382ad54290ecb16079b7ea/tools/tm-bench/transacter.go#L260-L274. Or you can write a simple script and use Prometheus to measure the performance.

> Do we need all the validators or add also light nodes, etc? - as we understand our validators should not directly accept requests for the formation of transactions, this will be due to the proxying nodes (full nodes), see item 5

This depends whenever your network is public or private. If it's private, validators can accept txs themselves. If it's public, then you will need a way to protect your validators from various attacks. Sentry architecture https://forum.cosmos.network/t/sentry-node-architecture-overview/454 is one of them.

> DDOS protection is a proxy (https://tendermint.com/docs/interviews/tendermint-bft.html). What is the functionality of this proxy? Examples of implementation, etc.

Read https://forum.cosmos.network/t/sentry-node-architecture-overview/454
For visuals, see https://github.com/bitfishlabs/cosmos-validator-design

> ABCI statefull - best practices how to implement?

Could you clarify the question?

> Example of reference architecture (testnet / mainnet) with indicators. How many transactions, what resources: number of nodes, their characteristics: kernels, memory, disks, network

Read 
- https://kb.certus.one/
- https://tendermint.com/docs/tendermint-core/running-in-production.html#hardware

> Best practice on tuning (config TM, OC kernel parameters)

See https://tendermint.com/docs/tendermint-core/running-in-production.html

> Upgrading TM versions (data migration)

https://github.com/tendermint/tendermint/blob/master/UPGRADING.md
Going forward we'll try to provide tools for upgrading the data.

> How change ABCI (socket to grpc and back) without re-initializing the network? - no answer

Why do need that?

**Comment by melekes** [comment]
Also, please join our chat: https://riot.im/app/#/room/#tendermint:matrix.org

> But those validators where the mempool stopped - they voting for the fork, but they are in the minority. 

What was the reason for mempool stopping? Any errors, panics in the log? Why are those nodes voting for the fork?

> Further, as soon as more than 2/3 of the validators failed, the network stops.

That's a fundamental property of our consensus algorithm. Network halts if less than 2/3 of the voting power is online. Read https://arxiv.org/abs/1807.04938

**Comment by melekes** [comment]
@cryptoji ^^

**Comment by cryptoji** [comment]
@melekes thank you for answers))

But I don't what happen with our Tendermint. When we start tm-bench on localhost (with kvstore abci) we have maximum 800 TPS. And I freeze TM research because of my experience as a nub. Now it is not my head pain...))

Basically, our network stopped due to: At one point, the number of rounds of voting starts to grow, this happens immediately after some validator goes offline. It may take about 30 minutes or an hour and then everything resolves itself ...
With update 0.26, we immediately came up the replay protection, that is, tx_count reaches 100k and that's network is stoped ...

And as for the ABCI state - I figured it out already, it was fun to discover for myself that as soon as the Abci connects to the network, he alternately gets the transactions and we can calculate the current state.
-----------------
My colleague got in touch with the guys from your team and I hope you will be able to agree to help us.
I myself am very interested in what we are doing wrong, but honestly, I don’t have the energy to understand this. As soon as we solve the problem, I will send a detailed report here so that people with a similar problem can deal with it.
Although honestly, it seems to me that in the whole community we are the only one who 200 TPS and all falls)))

In future, I plan will create Tendermint explorer on base Tendermint JavaScript libs with BlackJack and bitches. I have templates and groundwork from work project... Maybe someone will need it.

**Comment by melekes** [comment]
> At one point, the number of rounds of voting starts to grow, this happens immediately after some validator goes offline. It may take about 30 minutes or an hour and then everything resolves itself ...

I believe it's known issue https://github.com/tendermint/tendermint/issues/1496, but sync shouldn't take that long.

> In future, I plan will create Tendermint explorer on base Tendermint JavaScript libs

awesome!

**Comment by melekes** [comment]
Closing this since there's not enough information (logs, configs, clear description). @cryptoji if you have any other question, feel free to ask them in the chat https://riot.im/app/#/room/#tendermint:matrix.org or StackOverflow or our forum https://forum.cosmos.network/c/tendermint.
