### ISSUE TITLE
Add CI testing for dynamic peer discovery

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#2795]
Moved from https://github.com/cosmos/cosmos-sdk/issues/2755

Currently we test creating a local network where all of the peers connect to each other in a hard coded way. We should add a test where the peers discover each other automatically through `pex`

cc @melekes @cwgoes

**Comment by ebuchman** [comment]
I believe such a test already exists: https://github.com/tendermint/tendermint/blob/develop/test/p2p/pex/test_addrbook.sh#L11

Some reason to think it does not? Perhaps we need to enhance them.

Also, I'd really like to move the tests over to use the `make localnet` instead of these janky bash scripts for setup, ie. https://github.com/tendermint/tendermint/issues/2805
