### ISSUE TITLE
Peer MarkBad() for bad behavior

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#28]
In the various reactors (consensus/pex/mempool etc), bad behavior should be reported and eventually trickle to the addrbook somehow and call MarkBad() so we know not to dial the peer again.  Or not to dial the peer again for a while.  Not sure what the addrbook does but we should make sure the behavior is reasonable.

We should discuss the overall strategy of peer ethics before hastily disconnecting/banning nodes (or even being too lenient) because it could cause the network to fragment.  Maybe we should err on the side of being lenient (and suffer some spam)?

In any case we should keep a good record of things so when things change (e.g. a peer is marked bad, banned, etc) we know how to debug it.  It could be as simple as a log.Info().

**Comment by ebuchman** [comment]
We may want to consider adding some proof of work to each transaction as spam prevention, like it's supposed to be used for. Could go so far as having a required difficulty that the validators can vote to update in times of greater spam. Peers that don't do the proof of work can be flat out banned (we can tune the required proof of work to be approximately the cpu cycles not being used for tendermint protocol and tx processing since we're not running at capacity probably)
