### ISSUE TITLE
fast_sync etc confusion

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#281]
1. `--fast_sync false` doesn't work, you have to type `--fast_sync=false`.  This is contrary to what `tendermint node --help` says
2. `tendermint init` is not documented
3. fast_sync auto-off behavior should be documented
4. I think there should be some warning message when ~/.tendermint/data exists from some prior setup, (e.g. state was persisted and exists), it doesn't match ~/.tendermint/genesis.json . e.g. I think we should maybe save the contents of genesis.json in the state, and print a warning if mismatched.
5. Likewise, maybe `tendermint init` should do something about a preexisting `data` directory.

**Comment by ebuchman** [comment]
1. It's not really contrary to what it says. The library we use treats boolean flags special so that `--bool_flag` means true, so `--bool_flag false` looks like setting the `bool_flag` and passing an argument value `false`. We should just note in documentation to use `=`

2. https://github.com/tendermint/tendermint/wiki/CLI

3. https://github.com/tendermint/tendermint/wiki/Fast-sync

will move 4 and 5 to their own issue
