### ISSUE TITLE
Peer consensus state may can not sync to other peers in some condition

### ISSUE THREAD

**Issue by adamchen0510** [tendermint/tendermint#2812]
I'm using tendermint as our project's consensus core, I've found an issue with tendemint core, would you please help to double check if this an issue.

I'm using five peers to test, named as A,B,C,D and E, and their voting power are the same with each other.
At height n round 0, A/B/C/D rollback and start at n/1(as A/B/C precommit the blockID and peer D precommit nil and they rollback as precommit wait timeout).
But peer E enterCommit at n/0 as later than other peers a little and precommit the blockID, so itself get +2/3 precommit of the blockID.
And then the peers A/B/C/D consensus success at n/1 during peer E committing(so E dont have enough time to gossip it's n/0 +2/3 precommit to other peers), and E would not commit the n/1 as height n already committed.
In this condition, E's state is different from other peers and it can not sync to the same state as other peers's state.

I'm using tendermint v0.15, it's difficult for me to test in the newest version,I read the codes of the newest version, I think it's the same as v0.15.

Would you please help to check this issue? Thanks!

**Comment by ebuchman** [comment]
Keep in mind that precommitting for a block is only supposed to be possible if you've seen +2/3 of prevotes for the block. Also, once you precommit, you're considered "locked", so you can only vote for the same block again in a future round (unless you see a +2/3 prevotes for a different block that unlocks you). If 3/5 precommit for a block, it wont be possible for an alternative block to get committed without 2/5 of them being malicious (ie. more than 1/3).

So in the scenario you're describing, its possible E comes on late and commits the block he saw in round 0, but because there's already +1/3 validators locked on that block, they have no choice but to commit the same block in the future, so A/B/C will agree with E, even though they commit the block at a later round.

Does that make sense?

Also, v0.15 is incredibly old and unsupported. It's highly recommended you upgrade. Let us know if you have any trouble or something doesn't make sense.

But I would be highly surprised to find a safety violation like you're describing. Have you actually detected this, or this issue is just from analysis?

I'm going to pre-emptively close this issue. Let us know if we should re-open it, especially if you've seen this safety violation in practice.

**Comment by adamchen0510** [comment]
e..sorry I was wong.
It was an issue in my project and I thought there was some issue in Tendermint. I only focued on the gossip votes logic but ignore the locked block￣□￣｜｜

Thanks for your reply!
