### ISSUE TITLE
Prioritize validator nodes in p2p communications

### ISSUE THREAD

**Issue by danil-lashin** [tendermint/tendermint#2860]
### Problem
During high load validator nodes may not be able to download block from proposer _in time_ to sign it. This often happens because too many nodes (mostly non-validator nodes) are connected to the network and block propagation time becomes very huge. 

This is unpleasant problem, because even if validator has powerful server and good network channel it will miss a block and receive penalty (depends on application).

### Proposal
Prioritize active validator nodes in p2p communications, so they can sign block in time. I think that non-validator nodes can tolerate some delay.

**Comment by ebuchman** [comment]
This is difficult because in general we don't know which nodes are validators and validators don't want to advertise who/where they are. 

We can have a config option for peers that get prioritized - for instance we can use persistent_peers, but figuring out exactly how to prioritize them might take some work

**Comment by danil-lashin** [comment]
I think config option would be more than sufficient. Validators can share their ips with each other easily.

**Comment by milosevic** [comment]
The scope of this problem is a bit bigger. In case a node is overloaded with traffic, having prioritised traffic at the application level might help, but the question is to which extent. To address this properly we probably need several things:

1) having a way to quantify peer behaviour so we can disconnect from bad peers (see https://github.com/tendermint/tendermint/issues/2896 and https://github.com/tendermint/tendermint/issues/2871)

2) possibility to configure at the high level percentage of node resources (for example bandwidth) used for each module (reactor) of the system.
