### ISSUE TITLE
Receive should not execute in p2p recv routine as a blocking call

### ISSUE THREAD

**Issue by milosevic** [tendermint/tendermint#2888]
Currently, reactor.Receive method runs in the same thread as the p2p recv routine, i.e., p2p recv routine makes a blocking call to the corresponding reactor.Receive method. There are several issues with this design: 
1) failure in any reactor.Receive method (for example in mempool or blockchain reactor) might lead to network stopping to produce blocks.
2) while we are blocked on reactor.Receive that is sometimes quite costly (see for example respondToPeer method of blockchain reactor as part of bcBlockRequestMessage handling) no other message from that peer connection is being processed (although it might be completely received).

Is there any good reasons why we shouldn't enqueue message upon reception to a corresponding reactor so it can be processed in parallel with delivery of new message and with message handling of other messages from different reactors? It feels like this will be more secure design (regarding 1)) and potentially lead to overall better performance (regarding 2)).  

https://github.com/tendermint/tendermint/issues/1210.

**Comment by ebuchman** [comment]
Maybe you meant related to https://github.com/tendermint/tendermint/issues/1210 ?

I tend to agree - we could consider having a queue for each reactor, and queueing up the messages there so the reactors can process them independently. This would require a new routine for each reactor to run Receive in a loop after reading off some channel. 

But if the queue is full, we'd probably still need the recvRoutine to block so that it doesn't discard messages that TCP said we received.

**Comment by milosevic** [comment]
> But if the queue is full, we'd probably still need the recvRoutine to block so that it doesn't discard messages that TCP said we received.

Agree. The difference is that we have a possibility to configure the size of the buffer. Size of those buffer during runtime is also a nice metric regarding processing speed of each reactor, and also in case a buffer is full it creates some kind of back-pressure mechanism to slow down message reception.
