### ISSUE TITLE
docs: explain how transaction ordering works

### ISSUE THREAD

**Issue by pavlovdog** [tendermint/tendermint#2904]
I need to specify the order of the transactions into the block. In my understanding, for now there's a `fee` field into the `ResponseCheckTx` message. So, inside the block, the transactions are ordered according to it. Am I right?

Does it mean, that e.g. I have 10 transactions: `Tx_1, Tx_2, Tx_3, ..., Tx_10`.

1. I'm broadcasting them in a random way, for example
2. Each transaction has a field with it's order in sequence (e.g. `Tx_1.order = 1`, `Tx_2.order = 2` and so on)
3. During the `CheckTx`call for each of them, I'm specifying the `fee` field of the `ResponseCheckTx` message equal to the `order` field of the transaction.

Am I right, that, if they all will be placed into the same block, their order will be `Tx_1, Tx_2, Tx_3, ..., Tx_4`? If not, how can I implement the specific order into the block?

**Comment by ebuchman** [comment]
Currently, the only way to specify the order is to send them to a single node in order. Nodes will propose txs in a block in the order they received them. If the txs are split up across different nodes, there's no way to ensure they are processed in the expected order. The mempool contains no additional logic to reorder txs.

That said, if the txs contain some internal value, like an order/nonce/sequence number, the application can reject txs that are out of order. So if a node receives tx3, then tx1, it can reject tx3 and then accept tx1. The sender can then retry sending tx3, which should probably be rejected until the node has seen tx2. 

I'll leave this issue open and change the title to indicate we need better documentation around this.

**Comment by RomanBrodetski** [comment]
Does it mean  that essentially it is up to the block proposer to define the order of the transactions? Other nodes don't know in which order those transactions were received by the proposer, so they don't have a reason to reject the block. So, a single byzantine validator, being a proposer, can essentially define the transaction order?

**Comment by melekes** [comment]
Merged to develop.

**Comment by dakom** [comment]
@ebuchman I realize this issue is old, but it seems to be the same now as it was when this issue was first opened.

I am still not clear on where this sequence number is determined.

I understand that a tx sequence number can help all nodes agree on order, but this still means that the original node which receives the tx from the client can lie about the tx order, before broadcasting, correct?

("lie" is not necessarily a fair term here, since it can also just be the actual fair order it received, and only seems out of order from a client perspective due to network latency, but my question is whether the node can also intentionally doctor the sequence order before broadcasting to its peers)
