### ISSUE TITLE
Change txindex internal field separator to NUL

### ISSUE THREAD

**Issue by feldgendler** [tendermint/tendermint#2907]
Currently, tags are entered in the transaction index using the following format:

`fmt.Sprintf("%s/%s/%d/%d", tag.Key, tag.Value, result.Height, result.Index)`

This unfortunately removes `/` from the set of allowed characters for keys and values. Please consider using `\0` instead, which is what some other databases do for compound indexes.

**Comment by melekes** [comment]
I think this is accepted.

**Comment by erikgrinaker** [comment]
We shouldn't use strings for database keys, because of this problem and also since they don't preserve the lexicographical ordering of the elements (see #4567). Using `NUL` as a terminator doesn't solve this problem, since byte strings now cannot contain `0x00`.

One naïve and space-inefficient encoding example which would both allow all byte slice values and preserve lexicographical ordering is:

* `[]byte`: escape `0x00` with `0x00ff`, terminate with `0x0000`.
* `int`: big-endian byte representation.

We should find or design a similar encoding that is both space-efficient, lexicographically ordered, and allows arbitrary values without limitations.

**Comment by tessr** [comment]
@erikgrinaker would this issue be resolved if #4567 were resolved?

**Comment by erikgrinaker** [comment]
Yeah, we could choose to use the same encoding for both, if that makes sense. Implementing them here is probably a different task from implementing them in the databases though (I don't know how the tx indexer works), so we should make sure we fix both.
