### ISSUE TITLE
mempool lock can cause induce adversarial large delay in block reap functions

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2972]
Currently the mempool places a mutex lock on every CheckTx (https://github.com/tendermint/tendermint/blob/master/mempool/mempool.go#L300), and Reap (https://github.com/tendermint/tendermint/blob/master/mempool/mempool.go#L467).

However reap has no prioritization in selection once the lock is free. There will be contention between all queued check tx processes and the queued reap process. There can be a large number of queued CheckTx processes. In the cosmos-sdk, tendermint is ran in process, and CheckTx's happen synchronously. So the CheckTx mutex lock will not unlock until this computation (i.e. signature verification) is complete. Secp256k1 in the golang implementation takes ~250 microseconds to verify a signature. Since a cosmos tx can be made at ~150 bytes such that signature verification would get ran, this implies that a 1 MBit/s line would allow an adversary to cause 218 ms of verification time in txs to the validator, per second. Linearly scaling the connections throughput to 10 Mbit/s implies 2.18 seconds of delay induced per second. (This is assuming that exponential back-off on the mutexes doesn't further increase the time) Note that the attacker can keep scaling the amount of txs they send with network throughput, since the check for mempool already being full happens after the mutex lock.

Supposing no new check tx contentions were made, since the reap process has no prioritization over CheckTxs, one would expect it to occur around the halfway mark. (So with 1 seconds worth of induced validator delay, this could be delayed by 1.09 seconds) However the attacker would continue their check tx spam, further increasing this bound.\* Additionally, the newer check txs will have faster "refresh rates", since their exponential back-off is smaller, whereas the reap's refresh rate will have become longer. Thus this further increases the delay.

There are numerous solutions and stop gaps. The fundamental problem is the need for locking in the mempool, which can be addressed via #2147 , #2484. However those are more long term solutions.

Currently the maximum mempool size was decreased to mitigate also large delays on rechecking within Update. We don't check the maximum mempool size before locking, we should do so. Then the attackers power no longer scales with their internet connection to you, it is blocked by your mempool size plus the number of txs you already have. This is still highly applicable, since a small mempool size of `5000` txs still opens you up to `5000 * 250microseconds = 1.2` seconds of delay and at least `.6` seconds of delay in expectation to reap. This also doesn't solve an attacker being able to constantly send more txs, so that `.6` can still probably be increased.

Making the check txs actually asyncronous such that the mempool doesn't lock over its execution time would remove this problem, however the delays that may induce in normal execution may not be worth it.

In a similar theme to recent discussions deliver tx vs deliver block, making a batch check tx would strongly alleviate this problem, if the mempool buffered its check txs before engaging in a lock.

\* We should do the math with it in the continually refreshed case, it may be that the above solutions don't actually solve it, and the removal of mutexes should happen relatively soon.

**Comment by ValarDragon** [comment]
Just realized, we can actually probably remove the lock between CheckTx and Reap, and that would solve the problem. Reap in the current implementation is non-mutative, and begins its search from the beginning of the mempool linked list, while Check tx appends to the end. (CheckTx may mutate txs in between, but its okay if the mempoolTx reap pulls is not the latest mempoolTx from checkTx, as checkTx is just changing metadata) Reap doesn't actually remove the txs. Thus Reap and CheckTx could happen concurrently. What can't happen concurrently is Update and CheckTx, and Update and Reap.

**Comment by gamarin2** [comment]
This was exploited during GoS. With a mempool of `5000` txs and a block time of ~10sec, we missed 90% of blocks. Constantly flushing the mempool did not help. 

Note that our mempool grew very large because we set min fees in `gaiad.toml` which was not working at the time. This has been fixed since then. The problem is not apparent right now because everyone is running with high min fees and therefore mempool size remains small. 

If we expect to have large mempool in mainnet (thousdands of txs), which I think is a reasonable expectation, this indeed needs to be fixed.

**Comment by ValarDragon** [comment]
This was not the problem in game of stakes. In game of stakes the problem was https://github.com/tendermint/tendermint/issues/2127, which at a mempool of 5000 txs can cause 9 seconds of delay.

**Comment by gamarin2** [comment]
This attack vector has been exploited successfully a second time and led to https://github.com/tendermint/tendermint/issues/3302. 

The first time, it was successful because there was a bug in `gaiad.toml` which caused `min-fees` not to work and the mempool to be unprotected.

This time, it's the change from `AND` to the `OR` semantic that was exploited. `photinos` are worthless in Game of Stakes, and without `stake` being required, it was "free" to spam the mempool.

One thing to note is that the attack was successful because a lot of validators did not put a high-enough `min-gas-prices` in `photinos`. Nevertheless, **the fact remains that the current implementation seems unable to handle mempool size of several hundreds of txs.** In GoS, there is no requirement of throughput, so this is not a problem. However, in mainnet, it definitely sounds like an issue.

**Comment by ValarDragon** [comment]
I do want to point out that this attack is not "mempool can't handle large mempool sizes", that is the recheck issue. #2127 This is specifically about the rate of mempool spam prevents you from joining consensus. (I have no idea what was actually the problem, its just that there are two separate problems here)

**Comment by ebuchman** [comment]
From what I can tell re the way this was exploited, this will not be costless in early mainnet since folks will have to actually spend atoms in fees (not free photinos). For v0.31, we're going to bound the mempool size in bytes (#3079), giving users even more ways to limit their mempool resource usage. Between that and the cost in atoms, I think it's ok to move this to v0.33 to be addressed with other mempool/abci issues. Let me know if I'm mistaken.
