### ISSUE TITLE
change pex addressbooks bucket selection hash

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#2998]
Currently the pex address book uses double sha256. However this is essentially distributing buckets for a hashmap. It should instead be like typical hashmaps and use AESHash (this is in the stdlib so can just be copy pasta'd) or use high way hash #2187, it definitely doesn't need the overhead of two cryptographic hashes. (If we really wanted a cryptographic hash, then lets use a fast hash here, like blake2{b,s})

**Comment by tessr** [comment]
In the issue that's linked (#2187), @ebuchman expressed some healthy hesitation about adopting highway hash quickly:

> That said, HighwayHash is young, and while collisions are unlikely and not consensus critical, if they ever do happen they may be difficult to detect and hard to debug. So at least I wouldn't think it's worth considering until its proven to be a significant resource hog in the profiler, and there's probably lots of other things to address in the mempool first.

I generally agree with this kind of thinking. Obviously Bucky is talking about the mempool cache in that case rather than the pex addr book, but I think the same logic applies here--do we know that sha256 is actually creating a bottleneck in the addr book? And if not, is it worth taking on the (small) risk of using a relatively new hash function?

**Comment by ValarDragon** [comment]
This hash is for bucketing, not for uniqueness. Collisions are fine (and in fact should be parameterized such that they occur with non-negligible probability) for efficiency.
