### ISSUE TITLE
Liveness failure on community testnet genki-3000

### ISSUE THREAD

**Issue by zmanian** [tendermint/tendermint#3003]
We have a liveness regression on `genki-3000` a community testnet for Cosmos SDK v0.28.

What happened was the proposer proposed an invalid block because they were running SDK v0.28-rc2, the network completed the prevote round and then voted nil in the precommit. Polka on nil for the prevote round happened.

Then then everyone got stuck and the next round didn't start.

Restarting validator and sentry nodes causes the votes to progress to the next round.

**Comment by milosevic** [comment]
Can you provide a bit more info as proposing a wrong block should not block us. Do you have some logs?

**Comment by zmanian** [comment]
Currently focusing on this PR as a cause.

https://github.com/tendermint/tendermint/pull/2540

**Comment by zmanian** [comment]
@Slamper says his node got stuck at step 7. PreVoteCommitWait

**Comment by milosevic** [comment]
This shouldn't be possible as we shouldn't normally enter step 7 (precommitwait).

**Comment by Slamper** [comment]
@milosevic I am not 100% sure. It was already late when I looked into it :) Take the info with a grain of salt.

**Comment by jaekwon** [comment]
Does anyone have debug logs from this run?

**Comment by Slamper** [comment]
@jaekwon We have a WAL to replay if you need it.

**Comment by Slamper** [comment]
I have replayed our WAL using the tendermint replay feature and this is the debug log of the state machine:

https://transfer.sh/LnSTF/log.out

**Comment by jaekwon** [comment]
@Slamper How did you get the latest wal file to parse at all?  From zaki's file provided of Certus.One, I get:

```
panic: failed to decode msg: DataCorruptionError[checksums do not match: (read: 284513104, actual: 1447060935)]

goroutine 1 [running]:
main.main()
	/Users/jae/gocode/src/github.com/tendermint/tendermint/scripts/wal2json/main.go:46 +0x5ee
exit status 2
```

shasum of the latest wal file: d37061072c9cefc453190c0716b21db82e3f9358

**Comment by ebuchman** [comment]
Looking into the Certus WAL file. Note it has a line:

```
ENDHEIGHT 36
```

Typically, this is immediately followed by a RoundStepNewHeight message, like eg. in the previous height:

```
ENDHEIGHT 35
{"time":"2018-12-11T16:38:34.461826774Z","msg":{"type":"tendermint/wal/EventDataRoundState","value":{"height":"36","round":"0","step":"RoundStepNewHeight"}}}
```

But after height 36, we never see the RoundStepNewHeight for height 37. This is corroborated in the replay log, where for all heights we have a sequence like:

```
```I[13126-12-13|00:03:10.854] Replay: New Step                             height=35 round=11 step=RoundStepCommit
I[13126-12-13|00:03:10.854] Replay: New Step                             height=36 round=0 step=RoundStepNewHeight```
```

followed shortly thereafter by a successful `enterNewRound`:

```
I[13126-12-13|00:03:10.855] enterNewRound(36/0). Current: 36/0/RoundStepNewHeight height=36 round=0
```

But after committing block 36, we have no such logs. If we don't succeed in calling `enterNewRound`, we will fail to reset `triggeredTimeoutPrecommit`, which explains why we later get stuck in the precommit step, because we never manage to schedule the precommit timeout. The question is, why did we not get the RoundStepNewHeight for height=37 and the corresponding `enterNewRound(37/0)`?

If we look at the code, the ENDHEIGHT is logged in `finalizeCommit` at https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1280

The RoundStepNewHeight is logged in updateToState at https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L539, where updateToState is called at  https://github.com/tendermint/tendermint/blob/master/consensus/state.go#L1306.

So there's not much code separating these two log events, but for some reason the latter one doesn't seem to happen. The only way that should be possible is if ApplyBlock failed, or if updateToState paniced, but in both cases we should have seen log messages at error level.

Afaik, there were no error logs. Can anyone confirm this?

**Comment by melekes** [comment]
Can we close this? given recent consensus https://github.com/tendermint/tendermint/pull/3310, https://github.com/tendermint/tendermint/pull/3197, wal, addrbook and p2p fixes.

**Comment by zmanian** [comment]
yes I think so

**Comment by ebuchman** [comment]
Awesome.
