### ISSUE TITLE
tendermint show_validator should query remote signer

### ISSUE THREAD

**Issue by liamsi** [tendermint/tendermint#3009]
`tendermint show_validator` reads the public key from the `priv_validator.json` config file: 
https://github.com/tendermint/tendermint/blob/9c236ffd6c56add84f3c17930ae75c26c68d61ec/cmd/tendermint/commands/show_validator.go#L18-L21
In case of a remote signer it should rather request the public key from the remote signer. 
This led to confusion while using the kms as a remote signer:
https://forum.cosmos.network/t/ann-tendermint-kms-v0-2-validator-signing-support/1361/31
ref https://github.com/tendermint/tendermint/pull/2948#discussion_r239028083
ref https://github.com/cosmos/cosmos-sdk/pull/2975

**Comment by Liamsi** [comment]
Thinking about this further, I'm not sure this is worth the effort: When the remote signer (kms / priv_val_server) is running *and* is already connected to tendermint, connecting to it to request the public key will fail with ` bind: address already in use`. This would only work when the remote signer isn't connected to tendermint already. An alternative would be to persist the pub-key somewhere (e.g. in priv_validator.json) when tendermint is run with the `priv_validator_laddr` and return this when running the show command. Note that the show_validator command currently doesn't read the pub-key from that file but derives it from the private key (in that file) instead.

**Comment by ebuchman** [comment]
Relates to https://github.com/tendermint/tendermint/pull/2870 since we can continue to have a config/priv_validator.json with just the meta info (pubkey)

**Comment by Liamsi** [comment]
So how about this: whenever `tendermint node` is run with the `--priv_validator_laddr` flag, it persists the remote signer key to `config/priv_validator.json` (will be renamed to `priv_validator_key.json` per  #2870). Then, we change the `LoadFilePV` or just the `showValidator` cmd to actually read the public key (instead of currently deriving it from the private key):
https://github.com/tendermint/tendermint/blob/0138530df202f5b8e8be1edb9c2f705e404a79cb/cmd/tendermint/commands/show_validator.go#L18-L19
https://github.com/tendermint/tendermint/blob/0138530df202f5b8e8be1edb9c2f705e404a79cb/privval/priv_validator.go#L87-L99

**Comment by Liamsi** [comment]
by changing `LoadFilePV` this would autom. resolve the same issue in gaia, too: https://github.com/cosmos/cosmos-sdk/pull/2975

**Comment by ebuchman** [comment]
Yup let's do it like that. Related to #1231

**Comment by ebuchman** [comment]
Bumping this from an immediate milestone
