### ISSUE TITLE
Consensus: Is the protocol safe if we increase the minimum agreement from 2/3 to some higher value like 80%?

### ISSUE THREAD

**Issue by arjunbazinga** [tendermint/tendermint#3074]
This is perhaps not the correct place to discuss this, I couldn't figure out where it might be.
I'd be glad to move this to the appropriate place.

Changing the minimum needed from 2/3 to some higher value, seems simple enough by modifying the 2/3 to whatever [here.](https://github.com/tendermint/tendermint/blob/80d0a362500fea2dd089258319075a54e5d40a2d/types/vote_set.go#L392)

Does the core consensus protocol remain correct if we do that?
Apart from the fact that it'll become easier to cause DOS attacks and some time increase in consensus  What are other disadvantages of such a system?

**Comment by ValarDragon** [comment]
This probably more suitable for the cosmos forums. https://forum.cosmos.network/ You definitely should read https://arxiv.org/abs/1807.04938 before doing any consensus changes as significant as this. 

You have decreased the liveness and censorship resistance of the network, since 20% of nodes can now halt the chain or censor anything on the chain / any other validator. People already find the 1/3rd censorship-bound of Async-BFT too bad, this is significantly worse. I don't have a proof of this, but it "feels" like you have increased difficulty to double spend in the model where an adversary has full network control. (It feels like the amount of stake required for equivocation with full nentwork control is now 60%) 

In my opinion (and AFAIU the direction ETH is going in), is that the model where an adversary has full network control is quite unreasonable / will not get practically instantiated, so increasing this bound is quite moot. It is far more interesting / valuable to do "parameterizable synchrony" or lower this bound for increased liveness / censorship resistance in partial synchrony without significant loss of safety. See https://github.com/ethereum/eth2.0-specs/issues/357 for more discussion on the latter point.
