### ISSUE TITLE
Prehash messages before signing for HSM compatibility

### ISSUE THREAD

**Issue by zmanian** [tendermint/tendermint#3095]
To better accommodate a wide range of HSMs(esp the ledger nano s), Tendermint  should to switch to prehashing consensus messages before voting so. ed25519sign(privkey, sha512(msg)),  and ed25519verify(pubkey,sha512(msg)) .

**Comment by ValarDragon** [comment]
Since we're explicitly trying to accomodate a single vendor, perhaps we make two pubkey types? We already have the support in TM for multiple consensus pubkey types. This would let the remainder of the ecosystem use the standard ed25519, but allow ledgers to also be used for validators.

This would allow fingerprinting whether a validator is using a ledger or another HSM, but I feel like it is on the HSM manufacturer to make their hardware comply with standards.

**Comment by mdyring** [comment]
I don't think this is specific for Ledger, most devices will have some constraints: ["EdDSA signing, including Ed22519, is limited to the size of one message to the YubiHSM: 2019 bytes."](https://developers.yubico.com/YubiHSM2/Releases/Known_issues.html)

Regardless of how this is implemented, it will be a breaking change. But my spider-senses tingle with the prospect of device-specific signatures, so I'd +1 to KISS and just standardize on SHA512(msg).

If a wide(r) range of signatures is decided, it makes better sense to make it specific to tie it to a hash algorithm instead of device. This way "ed25519" (as today), "sha512-ed25519" or, say, "blake2b-ed25519" signatures could be supported. Not sure the added work provides a lot of benefit, though.

**Comment by jleni** [comment]
App has been submitted to Ledger for review. 
Signatures produce by the app should be valid once this issue gets resolved.

**Comment by ebuchman** [comment]
> "EdDSA signing, including Ed22519, is limited to the size of one message to the YubiHSM: 2019 bytes."

This isn't quite a problem for us, as both votes and proposals max out around a couple hundred bytes.

Is there any evidence that other systems are also using `ed25519sign(privkey, sha512(msg))` to accommodate the ledgers?

For context, the Ed25519 API exposed by the ledger only accepts 32-byte inputs (ie. it expects messages to be prehashed). This is something that may be fixed later this year, but it's unclear when.

Given that this will probably be fixed, and we are currently using Ed25519 correctly, the preference would be to leave our current ed25519 signing as is.

In that case, we could support ledgers in the meantime by introducing a new pubkey type, say `ed25519-sha512`, which prehashes the msgs. We would have to add this type as an allowed pubkey in the consensus params. Note in the short term it would serve as an identifier of who is using ledger's (or at least who is using something that requires prehashing the input ...).

It would certainly be nicer if we could just have one ed25519 key type for now, but it doesn't feel right changing the correct and default implementation, especially if we may want to change it back at a future date. 

Thoughts?

**Comment by tarcieri** [comment]
> Given that this will probably be fixed, and we are currently using Ed25519 correctly, the preference would be to leave our current ed25519 signing as is.

I would definitely recommend avoiding using that particular construction if at all possible:

- `ed25519sign(privkey, msg)` would otherwise remain secure in the event of hypothetical (chosen prefix) collisions in the underlying SHA-512 hash function which is used to hash `msg`, as its construction hashes `msg` twice with two different prefixes. `ed25519sign(privkey, sha512(msg))` re-introduces the collision vulnerability.
- [Ed25519ph](https://tools.ietf.org/html/rfc8032#section-5.1) is specifically designed to be a "prehash" variant of Ed25519 with an Initialize-Update-Finalize (IUF) API intended precisely for these cases, but is internally domain separated from the original Ed25519 construction.  `ed25519sign(privkey, sha512(msg))` lacks this internal domain separation.

**Comment by jleni** [comment]
Yes, as we have already discussed Ed25519ph would be a good option but currently unsupported.
I also agree that changing things at this stage would be risky, in particular due to this incompatibility. 

Ledger should be able to fix this quite easily and add support for other Ed25519 use cases (rfc8032). 
In practice, this means a delay until Ledger releases their new firmware update (1.6.x) as this will probably won't be part of 1.5.x that is planned to be released very soon (this is not official, just my understanding of their roadmap).

**Comment by mdyring** [comment]
@ebuchman Just for clarity: If the Ledger is restricted to 32 bytes, then sha256 should be used not sha512? (32 == 256/8)

> This isn't quite a problem for us, as both votes and proposals max out around a couple hundred bytes.

I'd imagine most HSMs would support that, so +1 for keeping current impl. as default and introducing ed25519-sha256 (if the restriction is 32 bytes, not 64) as a bandaid for Ledger users.

**Comment by ebuchman** [comment]
> Just for clarity: If the Ledger is restricted to 32 bytes, then sha256 should be used not sha512? (32 == 256/8)

Right, or `SHA-512/256`, which is distinct from `SHA-256`. But maybe `SHA-256` should be preferred here since that's what we use everywhere else.

**Comment by Liamsi** [comment]
I'm also in favour of keeping the current implementation and adding a key type which does the pre-hashing as proposed in  https://github.com/tendermint/tendermint/issues/3095#issuecomment-454409499
(only if there is absolutely no way to get rid of the 32 byte limit imposed by ledger)

**Comment by jleni** [comment]
The limitation is that it needs a message hash, it is not about the number
of bytes.
Actually, ed25519 commonly uses sha512 internally. When the internal hash
is set to sha512, the input is expected to be also a sha512.
The API is odd, but that is how it is. Here is the function as a reference.

https://github.com/LedgerHQ/nanos-secure-sdk/blob/f9e1c7b8904df2eee0ae7e603f552b876c169334/include/cx.h#L2352

If the decision is not to modify, I would talk to ledger and try to discuss
with them when an update to their API can be made.

**Comment by ebuchman** [comment]
Since we're talking about edddsa: https://github.com/LedgerHQ/nanos-secure-sdk/blob/f9e1c7b8904df2eee0ae7e603f552b876c169334/include/cx.h#L2243

Is it possible to see into the SYSCALL_cx_eddsa_sign_ID_IN to know what it does? Are we sure it's hashing the input again internally?

The API for `cx_eddsa_sign` says:

```
 * @param [in] hash
 *   Input data to sign.
 *   The data should be the hash of the original message.
 *   The data length must be lesser than the curve size.
 *
 * @param [in] hash_len
 *   Length of input to data.
```

What enforced that `hash` is actually the hash of something? What happens if we just pass in arbitrary unhashed bytes?

What are the restrictions on `hash_len`? It says `The data length must be lesser than the curve size.`. Doesn't that mean 256 bits?

**Comment by ebuchman** [comment]
According to recent info from Ledger and @jleni , these API docs haven't been updated and the underlying code actually does allow a full message to be passed in. So it looks like we may not need to implement this at all!

**Comment by zmanian** [comment]
Closing this
