### ISSUE TITLE
How to use ConsensusParamUpdates in EndBlock

### ISSUE THREAD

**Issue by adamchen0510** [tendermint/tendermint#3098]
Hi:
I'm confused of the ConsensusParamUpdates in EndBlock, what's the design of it?
This param can affect the consensus, if it's not the same with each other, validators may not consider the proposal block as a valid block...
My question is how validators update the same ConsensusParam, need each application implement it? use Oracle to make sure each validator get the same consensus param or other method?

Thanks

**Comment by ebuchman** [comment]
The application can update the ConsensusParams deterministically, in the same way it can return updates to the validator set. It must be deterministically computed on all nodes, otherwise it will break consensus. It's up to the application to determine how this works, but it does need to be the same on every instance of the application.

Let me know if that's still not clear.
