### ISSUE TITLE
rpc: remove header from block_meta in /block method response and add size in bytes

### ISSUE THREAD

**Issue by nagarajmanjunath** [tendermint/tendermint#3188]
I am using the tendermint, I notice that  blockmeta and block both are generating same structure result, please let me know the difference between it.

**Comment by nagarajmanjunath** [comment]
when i query using  tendermint RPC,I ll get replica of  same has  blockmeta information in block also, 
please let me know why its required same information to display in "Blockmeta" and "Block".

**Comment by ebuchman** [comment]
Right. For `/block` we should just remove the `header` from the `block_meta` field. We need to keep the Header in the `types.BlockMeta` struct, but the rpc response can use a copy of that struct that only has the BlockID, since the header there is otherwise redundant. 

This will technically be breaking, but it's the least breaking thing we can do (the header is already in the response and most people are hopefully getting it from the block, not the block_meta!).

You can always query `/blockchain` to get just the BlockMeta (id and header) for a single height.

@nagarajmanjunath want to take this on?

**Comment by nagarajmanjunath** [comment]
@ebuchman Thanks for your response!!

**Comment by b00f** [comment]
> For /block we should just remove the header from the block_meta field. 

It is good idea to remove header from blockmeta since it's a little bit confusing. Thanks for your fast response.

**Comment by b00f** [comment]
In the [Gallactic](https://github.com/gallactic/gallactic) blockchain team we are a little busy right now. But we put it on our schedule to help you fixing this issue. Count on us @ebuchman .
