### ISSUE TITLE
Active network connections prior to genesis

### ISSUE THREAD

**Issue by defunctzombie** [tendermint/tendermint#3228]
I was fortunate to be able to participate in gaia-10k as a genesis validator. For my validation setup I chose to use the sentry architecture. I deployed 1 public facing node and 1 private validator only talking to the public facing node. Both gaiad processes launched without errors; however, because no network connections establish or rpc endpoints enable until the genesis time I was not able to fully validate the setup.

Unfortunately, my private validator instance was mis-configured leading to it not being able to properly talk to the public facing node. I was only able to start debugging this issue after genesis when I should have been validating blocks.

It would be a good enhancement for genesis if network connections or some basic diagnostics could be established prior to genesis. This would allow the network to become connected and ready to run the moment genesis starts. It would also allow for operators to diagnose and fix connectivity issues well in advance of genesis.

**Comment by ebuchman** [comment]
Currently we sleep until genesis time in the `node.OnStart`. Instead, we could probably move this into the `consensusState.OnStart`. That should solve this issue, ie. everything would start up and we'd connect to peers, we just wouldn't start the consensus stuff itself until genesis time. Note the consensusState.OnStart logic would have to move to a go-routine otherwise the Sleep would block everything else ...
