### ISSUE TITLE
PEX issues

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#335]
yeah, pex still has a problem with a former seed node not creating an adress book. therefor if you restart a seed node, it will not connect to the other peers.

you can manually work around by restarting the seed node with a list of seeds

**Comment by akalyaev** [comment]
So strange to see `pex` code in master branch, but no code in develop 😕

**Comment by ebuchman** [comment]
yes, I should have merged it to develop right after releasing 0.7.4 but did not for some reason. I did merge it to develop earlier today before the release-0.8.0 branch was pushed so should be there now

**Comment by akalyaev** [comment]
> so should be there now

nope

Last commit:

```
commit c1952523cdb42939a71143e47c283db952366db2
Author: Ethan Buchman <ethan@coinculture.info>
Date:   Thu Jan 12 19:20:26 2017 -0500

    update glide
```

**Comment by ebuchman** [comment]
Thanks, my bad - just pushed

**Comment by ebuchman** [comment]
sorry, I just forced push right away afterwards because I pushed one commit too many, in case that trips you up

**Comment by akalyaev** [comment]
Fixed the bug above by saving `seeds` to `addrBook`. But now I've encountered another bug: for some reason, when I restart the app with `--pex` flag (without `--seeds`), it keeps failing.

**Comment by melekes** [comment]
The problem above: I wasn’t running other peers with `—pex`, so they were failing upon receiving a message for an unknown channel [FIXED]

**Comment by faddat** [comment]
Is a peer exchange for all of Ur-Tendermint, voluntary society of aligned blockchains, or is it for a single blockchain?  

I ask because I'm still thinking about the DHT situation.  Imagine if genesis.json looked more like this instead:

chain=546cf15f724d19c4319cc17b179d7e035f89c1f4
billy=validatorpubkey
jimmy=validatorpubkey
sarah=validatorpubkey

Same technique as a magnet link, and when's the last time you had any trouble with one of those?  The nodes themselves should also have some sort of PEX that allows a single, connected node in the swarm to give all the needed information (IP addresses) to any new, "fresh" node that simply knows a list of keys & values and has the special key "chain" that is always used to get the addresses of the other peers.  

Operational simplicity is a feature and a virtue at the same time!

If you want to move chain bootstraps in this direction, I'll look into how to implement this.

**Comment by melekes** [comment]
@faddat what it does is during start up it saves the seeds/peers, which were provided via config or CLI and enables an exchange of known addresses between nodes. So, if the new node joins the network, given it provided at least one seed (a few is better), it should receive a bunch of new addresses from the seed.

Answering your question, I don't think we have a feature, where 2 nodes from different blockchain communicate with each other. What could be the reason to communicate in the first place?
