### ISSUE TITLE
tests: TestValSetUpdatePriorityOrderTests non-deterministic failure

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3383]
```
--- FAIL: TestValSetUpdatePriorityOrderTests (19.49s)
    assertions.go:247: ^M                          ^M   Error Trace:    validator_set_test.go:1223
        ^M                      ^M                      validator_set_test.go:1176
        ^M      Error:          Not equal:
        ^M                      expected: 7632
        ^M                      actual  : 7631
        ^M
        ^M                      Diff:
        ^M                      --- Expected
        ^M                      +++ Actual
        ^M                      @@ -1,2 +1,2 @@
        ^M                      -(common.HexBytes) (len=2) 7632
        ^M                      +(common.HexBytes) (len=2) 7631
        ^M
        ^M      Test:           TestValSetUpdatePriorityOrderTests
        ^M      Messages:       wrong priority order
    assertions.go:247: ^M                          ^M   Error Trace:    validator_set_test.go:1223
        ^M                      ^M                      validator_set_test.go:1176
        ^M      Error:          Not equal:
        ^M                      expected: 7631
        ^M                      actual  : 7632
        ^M
        ^M                      Diff:
        ^M                      --- Expected
        ^M                      +++ Actual
        ^M                      @@ -1,2 +1,2 @@
        ^M                      -(common.HexBytes) (len=2) 7631
        ^M                      +(common.HexBytes) (len=2) 7632
        ^M
        ^M      Test:           TestValSetUpdatePriorityOrderTests
        ^M      Messages:       wrong priority order
```

**Comment by melekes** [comment]
Refs https://github.com/tendermint/tendermint/pull/3301

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3407 to develop.

**Comment by ebuchman** [comment]
Since we solved this by removing a test, we should probably continue to track the issue to figure out if we can get tests back. So I'll reopn for now.

Would it be possible to fix the test as follows:
- assign each address an index according to their order in the set
- do this before and after the IncrementProposerPriority
- assert that the indices are the same before and after
  - if they're not, check if there are other addresses in the set with the same proposer priority, and assert that those addresses are ordered correctly with respect to eachother and that they have the correct indices with respect to the rest of the set 

?

**Comment by ancazamfir** [comment]
@ebuchman
Yes I was thinking along the same lines. The test already orders the validators by priorities.
A small note that IncrementProposerPriority is not a problem here as the test takes a validator set snapshot after the IncrementProposerPriority(times) is called. Then again after UpdateWithChangeSet().

Recap: The test tries to make sure that the priority of existing validators is not changed after UpdateWithChangeSet(). The problem:

When we rescale we divide priorities by "ratio". If the priority difference between two validators A and B is smaller than "ratio" then we endup with equal priorities. We could turn a blind eye to the changed priority order of A vs B in this case, i.e. if:
- p(A) < p(B) and p(B) - b(A) < ratio before updates, and
- p'(A) == p'(B) after

In general a failry good test would:
- find in the (priority ordered) list before updates the sequences p(Ai),..,p(Aj) with p(Aj)-p(Ai) < ratio
- if order is not perserved for this sequence then assert that after the updates p'(Ai)==p'(Ai+1)== ..==p'(Aj), i.e. assume this was caused by rescale.

There are a couple of problems:
1. in the test environment we do not know the "ratio" as it is locally computed in RescalePriorities(). Also with updates we cannot get easily a good approximation of the ratio.
2. we don't know if we overlook a bug or it is a genuine priority order change due to RescalePriorities().

We could do the following: if order is not preserved for a sequence i..j of priorities, just make sure that at least p'(Ai)==p'(Ai+1)== ..==p'(Aj) and skip the strict order check between "before" and "after" for these validators. It's not perfect but the validation we do for the other validators it's better than nothing.

**Comment by ebuchman** [comment]
> We could do the following: if order is not preserved for a sequence i..j of priorities, just make sure that at least p'(Ai)==p'(Ai+1)== ..==p'(Aj) and skip the strict order check between "before" and "after" for these validators. It's not perfect but the validation we do for the other validators it's better than nothing.

Yeh this is what I was thinking. Sounds like the best we can do unless we expose the ratio some how.
