### ISSUE TITLE
crypto: Recover public key from signature in secp256k1 

### ISSUE THREAD

**Issue by wupeaking** [tendermint/tendermint#3413]
I saw that Ethereum and Bitcoin use ```scepk256k1``` for crypto. They have the ability to recover public keys through content and signature. I think this feature is very useful, I don't know if you can consider adding this feature. BTW,  my English is poor and the expression may not be particularly accurate. sorry, 😀。

**Comment by ebuchman** [comment]
As far as I understand, while this is possible with secp256k1, it's generally considered bad design to depend on it (since it doesn't necessarily work with other curves), and only Ethereum explicitly depends on it in the protocol (since they don't include pubkeys in their txs). 

In the Cosmos SDK, we encourage a model where public keys are stored with the account, so they only need to be sent in the first tx, and otherwise not again.

In any case, since our secp256k1 lib is just using a standard underlying one, you should be able to do public key recover using that underlying lib.

If you can provide a strong justification for why you want this, and are willing to write the PR, we can consider including it.

**Comment by wupeaking** [comment]
Some developers I know will be happy to use the trendmint consensus engine and the Ethereum virtual machine to build their own private chain. This combination can achieve both good TPS and Ethereum's comprehensive ecological tools. This will refer to the trading model of Ethereum in many cases. I am happy to write PR. But my ability is not very strong, I will try to do it in my spare time.  😀

**Comment by wupeaking** [comment]
I have tried to submit a PR. 😁  #3440

**Comment by ebuchman** [comment]
Are you aware of the Ethermint project? https://github.com/cosmos/ethermint

It uses the go-ethereum state machine on top of the Cosmos SDK built on Tendermint Core :D

**Comment by wupeaking** [comment]
I have seen this project before, but I have not studied it in depth. This project seems to be still in the development stage. 😋

**Comment by marbar3778** [comment]
closing issue as secp keys have moved to the SDK

**Comment by ebuchman** [comment]
> I have seen this project before, but I have not studied it in depth. This project seems to be still in the development stage. 😋

Also would encourage you to look at ethermint again now that Chainsafe has taken over and its approaching a more production ready status: https://github.com/chainsafe/ethermint
