### ISSUE TITLE
docs: Fix incorrect note about header.Time in ABCI data types being the proposer's local time 

### ISSUE THREAD

**Issue by KrzysiekJ** [tendermint/tendermint#3514]
**Tendermint version** `v0.31.1` with the patch from #3118

**ABCI app**: [Ercoin](https://gitlab.com/Ercoin/ercoin)

**What happened**:

If `create_empty_blocks` is set to `false` and a block is created, then time of that block is not the current time, but it refers to the time at which the previous block was created.

**What you expected to happen**:

Block time should be current. Past time may make transactions invalid if their validity is time-dependent. If a transaction is created with a current timestamp, then a block in which that transaction is included must not contain a lower time value in block header.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

1. Set `create_empty_blocks` to `false` and `create_empty_blocks_interval` to a reasonably high value.
2. Observe the time of the block header.

**Comment by melekes** [comment]
Sorry about this! We're clearly could've done a better job documenting this feature. There are some bits here and there like https://tendermint.com/docs/spec/blockchain/blockchain.html#time-2, https://tendermint.com/docs/spec/consensus/bft-time.html#bft-time, but we say nothing about it here https://tendermint.com/docs/spec/blockchain/blockchain.html#time.

That said, we're planning to switch to proposer local time instead of bft. See https://github.com/tendermint/tendermint/issues/2840 for details.

Have a great day 🌞

**Comment by xla** [comment]
@melekes Can we close this one in favour of #2840?

**Comment by KrzysiekJ** [comment]
Thanks for the explanation. If #2840 is about implementing the new behaviour, then maybe this issue may be about documenting current behaviour. https://tendermint.com/docs/spec/abci/abci.html#header states that block time is “the proposer's local time when block was created”, which will be true when #2840 is implemented, but is not true now.

**Comment by ebuchman** [comment]
Oh man thanks for noting that. Definitely need to fix the documentation!

**Comment by melekes** [comment]
Merged https://github.com/tendermint/tendermint/pull/3529 to develop.
