### ISSUE TITLE
types: Encode empty votes differently than just nil 

### ISSUE THREAD

**Issue by Liamsi** [tendermint/tendermint#3591]
Suggested by @folex here: https://github.com/tendermint/go-amino/issues/260#issuecomment-486190616

**Comment by ebuchman** [comment]
Relevant: https://github.com/tendermint/tendermint/issues/3485#issuecomment-481926898

**Comment by ebuchman** [comment]
This is an issue with amino and should be tracked on the amino side to make sure the amino upgrades deal with this problem.

In the meantime, as per the ADR-25, it won't be a problem for Tendermint after #1648 because we will have a list of `CommitSig`, where each CommitSig has at least it's `BlockIDFlag` and `ValidatorAddress`  set.
