### ISSUE TITLE
help: why use SecretConnection in p2p

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#3624]
What is the concern of use `SecretConnection`? 
I can't figure out the reason to  encrypt the transport between peers.

**Comment by Liamsi** [comment]
We want to encrypting the transport because:
 - hide the content from everyone else besides the peer that is meant to receive it
 - to authenticate the identity of the corresponding peer
 - to guarantee message integrity

Note that while secret connection was designed with all these goals in mind,  the implementation does not properly guarantee those properties :-/ We hope to replace it with something like noise soon.

ref: #3315 #3010

**Comment by Liamsi** [comment]
Does this answer you question @guagualvcha?

**Comment by guagualvcha** [comment]
> Does this answer you question @guagualvcha?

I am ok with second point and third point. For `hide the content from everyone else besides the peer that is meant to receive it` why we need this, I think the delivery content is no secret?
