### ISSUE TITLE
use InitChain abci msg

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#367]

**Comment by ebuchman** [comment]
Should this happen only on genesis or every time we start up?

**Comment by adrianbrink** [comment]
As per the current [docs](https://github.com/tendermint/abci#initchain) this should only be called once upon genesis.

But most likely it will be useful to call it on startup, since the validator set might have changed and we want to let the ABCI app know about those changes.

**Comment by ethanfrey** [comment]
This is my understanding, though it should be double checked and documented. 

Upon a restart, Tendermint will call Info to find the apps current state. If no state, it will replay all blocks from genesis (including the InitChain) 

If the app responds with height 500 and the correct apphash for that block, Tendermint will replay all blocks from 501 to present, and then work normally once the app catches up. 

Since validator changes is only possible as a deterministic action based on the TXs in blocks, the abci app will get all info. 

There is an outstanding proposal, I believe, to allow some sort of fast sync for the app, to load the state at some height x along with the validator set from another node without doing a replay. But until that is added, I think the current process is totally correct, just needs to be documented better.

**Comment by ebuchman** [comment]
cool. @adrianbrink do you want to implement this ?

**Comment by ethanfrey** [comment]
@ebuchman Can you clarify what by "implement this"?

Docs?  Send InitChain once?  Send InitChain on every restart?

**Comment by ebuchman** [comment]
Yes sorry. Send InitChain only once, ie. if it's genesis time.

**Comment by adrianbrink** [comment]
@ebuchman Okay :-) Might take me a bit longer since I am celebrating easter for most of this weekend and next Monday :-)

Just to confirm: Currently the core node (tendermint node) tries to handshake with the ABCI app (proxy app) and then catches up by either replaying all blocks or only some blocks (as described by @ethanfrey). The goal however is that on genesis when the chain is initialised and only here, the core node sends the InitChain message to the ABCI app, correct?

**Comment by ebuchman** [comment]
That's right. This is independent of all the handshake stuff. It should probably happen after the handshake. Once we verify that everything is at block 0, send InitChain.

**Comment by adrianbrink** [comment]
Added in #463
