### ISSUE TITLE
cs/replay: address execCommitBlock PR comments

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#3685]
Original PR: https://github.com/tendermint/tendermint/pull/3067 (part of v0.31.6 release)
Review: https://github.com/tendermint/tendermint/pull/3067#pullrequestreview-232843320

**Comment by melekes** [comment]
Looping this into v0.32.0 milestone. Better to fix / refactor code before we forget how it works.

**Comment by melekes** [comment]
@james-ray maybe you want to work on this?

**Comment by james-ray** [comment]
OK.   As reviewer suggests, I do 2 main things:
1. Simplify SimulateTestChain() to without consensus process
2. Try another way to fetch stateDB instead of using blockDB

About the second one, I'm not sure how to do.
Should I add a global map variable in the test, the key of the map is the node address, the value is related stateDB?

**Comment by tessr** [comment]
@melekes, is this issue still relevant? 

> Better to fix / refactor code before we forget how it works.

😬

**Comment by melekes** [comment]
> @melekes, is this issue still relevant?

yes
