### ISSUE TITLE
Consider basing persistence just on ID

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#3692]
https://github.com/tendermint/tendermint/pull/3593 enabled us to treat inbound connections as persistent as well (ie. we'd try to reconnect).

But the new `isPeerPersistentFn` closure takes a NetAddress as input. We could perhaps simplify this by just accepting the ID instead.

See https://github.com/tendermint/tendermint/pull/3593/files#r280862208

**Comment by marbar3778** [comment]
In this approach how would someone connect to their validator? We would need a new field to provide netAddress for validators. 

The `persistence_peers` field in config.toml is also used to bootstrap a node with peers. If we made this field only be ids we would need to introduce a new field (`bootstrap_nodes`) in order to mimic the current behavior. Relying on seed nodes is a possibility but limitations may come about.

**Comment by ebuchman** [comment]
Oh you'd still specify the full address in the config but whether or not it should be persistent would just depend on the ID not the full address (so eg if it used DNS the address could change but we'd still be persistent to it, per the comment in the review ...)

**Comment by tessr** [comment]
I am pretty sure this proposal is made obsolete by [ADR 62](https://github.com/tendermint/tendermint/pull/5637). Can reopen if not.
