### ISSUE TITLE
testnet: add flexibility when creating and deploying a testnet

### ISSUE THREAD

**Issue by ancazamfir** [tendermint/tendermint#3734]
We should have a way to configure a testnet via some configuration file that would allow specifying things like:
- total number of nodes
- number of validators
- default image location and node configuration
- per node image and configuration (allow special images, different versions, etc)

We should also have the ability to add new nodes to an already deployed network.

Could be all based on 'tendermint testnet' command or other.

**Comment by thanethomson** [comment]
So @ancazamfir and I were discussing her needs with regards to creating configuration for Tendermint networks for her purposes, and it appears as though the `tendermint testnet` command is a little insufficient to be able to cater for the complexity of the network she wants to create.

For example, what if you needed to create three sets of nodes, where `set 1` has one base configuration template, and another `set 2` has a different configuration template, and `set 3` has the same configuration as `set 2` but the assumption is that `set 3` won't be joining the network from genesis (e.g. to test the blockchain reactor and fast sync).

Defining large networks of such complexity by hand could be incredibly tedious and time-consuming, and thus limits the variety of configurations that we could possibly test.

One suggestion here to speed this process up is to augment the `tendermint testnet` command to take a configuration file as a parameter, where one could specify the network topology (whether simple or complex).

The other issue is, does this perhaps warrant the creation of an external tool to accomplish this? (i.e. to move the `testnet` subcommand out to a separate repository?)

**Comment by tessr** [comment]
@erikgrinaker Did any of your work on E2E testing also happen to improve this? I know the E2E tests need networks to be very configurable, so it made me wonder if there was any overlap.

**Comment by erikgrinaker** [comment]
The E2E testnet runner is very geared towards generating networks for _local testing_, and not as a general-purpose system for configuring arbitrary production-grade networks. If the primary motivation for this issue is testing, then yes, I'd say the E2E testnet runner solves this. If the motivation is to configure actual networks running on hardware and/or in a cloud somewhere for purposes other than local testing, then no, the E2E runner is not intended to cover this use-case - that should really be handled by some widely-used deployment system, e.g. Puppet, Ansible, Kubernetes/Helm, Terraform, AWS CloudFormation, etc.
