### ISSUE TITLE
blocks lag when consensens reactor handle message for a long time

### ISSUE THREAD

**Issue by guagualvcha** [tendermint/tendermint#3767]
**The problem**
![WX20190701-195019](https://user-images.githubusercontent.com/7310198/60434343-8631f280-9c39-11e9-9605-49b29d10a847.png)

Every 5000 blocks, we have a special block that will take more than 20 seconds to commit. 
We observe that the sentry node or witness node can't receive 2/3 precommits until validator have finished `FinalizeCommit` the block.

**The reason** 
in the `gossipVotesRoutine` routine of consensus reactor:
```
for {
                ...
		rs := conR.conS.GetRoundState()
                 ...
}
```
however GetRoundState will fetch lock of `ConsensusState`.
```
func (cs *ConsensusState) GetRoundState() *cstypes.RoundState {
	cs.mtx.RLock()
	rs := cs.RoundState // copy
	cs.mtx.RUnlock()
	return &rs
}
```

while the lock have alreay fetched by `handleMsg` when validator receive the latest precommit:
```
func (cs *ConsensusState) handleMsg(mi msgInfo) {
	cs.mtx.Lock()
	defer cs.mtx.Unlock()
        ...
}
```
if the latest precommit make 2/3 precommits, `ConsensusState` will `enterCommit`.

Because `EndBlock ` and`CommitBlock` of our block will hold `mtx` of `ConsensusState` for about 20 second, it will cause the downstream node will not get the last precommit in time.

**Comment by melekes** [comment]
As a quick fix we can create yet another copy of `cs.RoundState` before we call `handleMsg` and use it in `gossipVotesRoutine`.

**Comment by guagualvcha** [comment]
> As a quick fix we can create yet another copy of `cs.RoundState` before we call `handleMsg` and use it in `gossipVotesRoutine`.

Hi, I can't really get this. Since only in `handleMsg` the `cs.RoundState`  will change, `gossipVotesRoutine ` copy a  `cs.RoundState` before `handleMsg` still can't get the latest precommit. Can you show me the code in a hot fix pr?

**Comment by ebuchman** [comment]
Huh. I wonder if we can just release the lock during ApplyBlock and re-acquire it immediately after? Need to carefully think through it but might be possible. Obviously that'd be kind of a hack and the real solution is to rearchitect the module. Some initial design work in [ADR-30](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-030-consensus-refactor.md)

**Comment by gterzian** [comment]
>  I wonder if we can just release the lock during ApplyBlock and re-acquire it immediately after?

A problem with that approach, essentially releasing the lock and hoping the other goroutine acquires it, is that you would not have guarantees that this would indeed happen. It probably would work most of the time, but you'd still get a similar failure from time to time, and in a way that would be essentially impossible to reproduce.

So it would be somewhat worse than "kind of a hack", it would be replacing one pretty clear bug that seems easy to reproduce, with something more intermittent and not reproducible.  

> Since only in handleMsg the cs.RoundState will change, gossipVotesRoutine copy a cs.RoundState before handleMsg still can't get the latest precommit.

So if I understand it correctly, you want the precommit to be gossiped before the node calls into the ABCI application?

The problem with that is that the `roundState` currently only is updated after the call into ABCI, I think, at https://github.com/tendermint/tendermint/blob/5ea1ff94d1317f9ea130a36333c27a7dc7a61186/consensus/state.go#L1450

So to me it appears that the solution, however implemented, would be to gossip the precommit earlier, before calling into https://github.com/tendermint/tendermint/blob/5ea1ff94d1317f9ea130a36333c27a7dc7a61186/consensus/state.go#L1431

**Comment by ebuchman** [comment]
> As a quick fix we can create yet another copy of cs.RoundState before we call handleMsg and use it in gossipVotesRoutine.

I don't think this helps because many of the fields of the RoundState are pointers, so unless we deep copy (expensive!), we would still have races (eg vote routine could be trying to read a vote while we're adding one in a handleMsg).

> A problem with that approach, essentially releasing the lock and hoping the other goroutine acquires it, is that you would not have guarantees that this would indeed happen. Another goroutine could acquire the lock, and perhaps even the consensus routine could re-acquire it before the gossip routine has had a chance to acquire it

That's all true, but we don't actually need those guarantees, we just need to make it possible for other things (gossip routines, RPC) to still function even during a long ApplyBlock.

> So if I understand it correctly, you want the precommit to be gossiped before the node calls into the ABCI application?

It's not just about the precommit, though that's what triggered this issue, but in general we don't want ApplyBlock to prevent other routines from reading the consensus just because ApplyBlock is taking a long time. Other routines include the vote and data gossiping routines (precommits are just one part of vote gossipping) as well as the RPC. We don't need to guarantee that any of these in particular do run, just that it's possible for them to - otherwise we get this performance/latency hit. 

----

From thinking a bit more about this, I don't see why the release/reacquire wouldn't be safe right now, though it's obviously a bad hack and could easily be overlooked in a modification down the road.

A better alternative might be something like moving the mutex into the RoundState object itself, though this would require making the RoundState a proper named field in the consensus.State instead of an embedded one, and adding a ton of getters/setters that grab the lock. It's possible this could be a net good thing, as embedded fields can be trouble for readability/maintainability any ways, even though they can be super convenient. We'd also need to do something similar for the `state` field (ie. a wrapper with a mtx). Then the locks would only be held when they're actually needed, and ApplyBlock wouldn't block the other routines from accessing the RoundState. I haven't really thought through this extensively yet, so not sure if I'm missing something, but it might be a less dangerous solution from the perspective of future modifications, and in some sense it's more precise about the where the mutex actually needs to be held (ie. only at the sites of reads and writes to the RoundState and State, rather than just globally for the entire duration of every handleMsg ...)

**Comment by melekes** [comment]
Thank you for taking the time @ebuchman 👍 

> A better alternative might be something like moving the mutex into the RoundState object itself

sounds good. I am concerned some funcs may depend on us holding a lock for the whole duration rather than locking only when RoundState/state is needed. So if we end up doing so, we'll need to check everything extensively.

+ I am not sure how much sense it makes (considering the effort) IF we're going to rewrite the consensus using the `blockchain v2` design in the future.

**Comment by melekes** [comment]
Attempted to fix here: https://github.com/tendermint/tendermint/pull/5035 (@guagualvcha feel free to apply this patch. I personally think it should be fine).
