### ISSUE TITLE
Use prototool to verify backwards compatibility of block format

### ISSUE THREAD

**Issue by aaronc** [tendermint/tendermint#4078]
One issue with non-destructively updating a live blockchain as being addressed in  https://github.com/cosmos/cosmos-sdk/pull/4233 is changes to the underlying tendermint block structure.

I know there are some pretty major changes to the block structure. If done carefully, this can be done in such a way that new versions of tendermint can still read the on-the-disk blocks created by old versions of tendermint. At least a partial translation of the tendermint disk format exists in protobuf format (https://github.com/tendermint/tendermint/tree/master/types/proto3). When upgrading, it is likely simply a matter of following good protobuf conventions on adding new fields (i.e. don't change the ID of an existing field, add new fields with new IDs - which in practice likely because of amino means don't reorder go struct fields haphazardly).

This can all be checked in CI using `prototool break check` (https://github.com/uber/prototool#prototool-break-check).

This approach was discussed in Berlin in June with @ebuchman and it sounded feasible at the time. If this still seems like a reasonable approach, we would like to cover this work within the scope of the ICF grant that Regen Network has to bring smooth upgrade support to Cosmos SDK. The scope of this would likely include both 1) making sure the block.proto file is complete and passes tests as well as 2) adding `prototool break check` to the CI script.

**Comment by ebuchman** [comment]
One note is that the protofile in that `types/proto3` pkg only contains the header, not the rest of the block, though the block is supposed to be a fully proto3 object (if it isn't already, will be soon), but canonically defined in Go. There have been discussions of Go->proto3 compilers, so using `prototool break check` could still help, but it would be a lot more involved.

Also, because we're using Go for canonical definitions, backwards compatibility means we'd have to be annotating all the struct fields to give them the right proto numbers. 

Meanwhile, for reasons like this, master is currently breaking on the block structure because it removed some header fields and changed all the field numbering to keep it clean cc @marbar3778

**Comment by marbar3778** [comment]
this is closed with: https://github.com/tendermint/tendermint/pull/4369, we decided on buf for linting and breakage checking
