### ISSUE TITLE
reject same txid 

### ISSUE THREAD

**Issue by tanhuiya** [tendermint/tendermint#4086]
steps :

* I signed my transaction off-line.
* Broadcast the raw transaction to tendermint node, and return the txid
* restart the tendermint node (clean the cache tx in memory)
* Broadcast the raw transaction again. the node didn't reject the tx.

expected: same txid should be rejected

**Comment by melekes** [comment]
https://tendermint.com/docs/app-dev/app-development.html#replay-protection

The app is responsible for replay protection. Tendermint only provides the first defense layer.

**Comment by ebuchman** [comment]
I was thinking recently about whether we should reconsider this since it's not that difficult to provide in tendermint and would strengthen the guarantees (ie. tendermint could be said to actually implement atomic broadcast, not "all of atomic broadcast minus at-most-once-delivery").

We would basically just need to keep a record of all tx hashes committed. This is currently possible to check using the indexer system, but indexing is optional, and we can probably implement something more efficient for this simpler set membership check. 

Should we re-open this?

**Comment by melekes** [comment]
> We would basically just need to keep a record of all tx hashes committed.

which could be millions of millions of transactions
