### ISSUE TITLE
https://tendermint.com/rpc/#/Info/blockchain "Try it out" functionality gives network error

### ISSUE THREAD

**Issue by PerMildner** [tendermint/tendermint#4092]
https://tendermint.com/rpc/#/Info/blockchain has a "Try it out"-button. Clicking it and then pressing the blue "Execute"-button spins a "LOADING" thing for a while and then says "TypeError: NetworkError when attempting to fetch resource.".

(This may be the wrong place to report problem  but there is no obvious feedback or contact information at the https://tendermint.com/rpc/ page).

**Comment by pasDamola** [comment]
I guess this a CORS error, because of the error message it returns in my console:

**Access to fetch at 'https://stargate.cosmos.network:26657/blockchain?minHeight=1&maxHeight=2' from origin 'https://tendermint.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.**
