### ISSUE TITLE
Evidence gets transmitted to ABCI application with wrong Time

### ISSUE THREAD

**Issue by AdityaSripal** [tendermint/tendermint#4150]
**Tendermint version**: `master`

Any Evidence that gets submitted will be transmitted over ABCI with the evidence.Time = block.Time of the block that the evidence is getting *submitted* in instead of the block time where the violation actually occured.

So if some double vote happens in block 100, but the evidence gets submitted in block 200; then the evidence.Time will be the block time in block 200. 

The correct behavior is for the evidence.Time to be equal to the blocktime of block 100 since that is the block where the violation actually occurred.

This affects any chain that uses `evidence.Time` in its state-machine. For example, the SDK slashing module ignores any evidence that is older than current block time by a parameter `MaxEvidenceAge`. This check is currently not effective since the evidence time is also equal to the current blocktime regardless of how old the evidence actually is.

Useful links to code:
https://github.com/tendermint/tendermint/blob/e71a2b161bf2964c5ed72d8f540bab4e7e85c47e/state/execution.go#L356

https://github.com/tendermint/tendermint/blob/e71a2b161bf2964c5ed72d8f540bab4e7e85c47e/types/protobuf.go#L142

Proposed Solution:

Load block at the height of infraction for each evidence and submit the blocktime of violated block.

Pros:

ABCI application receives Evidence with the correct time

Cons:

Efficiency: Must load block for every single evidence in Evidence list

**Comment by AdityaSripal** [comment]
Working on the fix here, but I don't know how to get access to the blocktime of a given block height inside `getBeginBlockValidatorInfo`

https://github.com/tendermint/tendermint/blob/3e1516b62427aba1199766fc98943dffe81d7f4b/state/execution.go#L348

I want to do something like:

```go
for i, ev := range block.Evidence.Evidence {
        // We need the validator set. We already did this in validateBlock.
	// TODO: Should we instead cache the valset in the evidence itself and add
	// `SetValidatorSet()` and `ToABCI` methods ?
        blockHeader, err := LoadBlockHeader(stateDB, ev.Height())
	valset, err := LoadValidators(stateDB, ev.Height())
	if err != nil {
		panic(err) // shouldn't happen
	}
	byzVals[i] = types.TM2PB.Evidence(ev, valset, blockHeader.Time)
}
```

However, blockheader information (or anything else that would contain time of each block) is not stored in stateDB. Only the LastBlockTime is stored.

If there is a way to get blocktime easier, let me know; but from my understanding there are 2 ways to get this information into `getBeginBlockValidatorInfo`

1. Persist the blockTime in stateDB on each saveState
2. Give access to blockStore in `BlockExecutor` so that we can pass it in to `getBeginBlockValidatorInfo`

would be useful to know which approach (or a completely different one) is best

**Comment by melekes** [comment]
I am leaning towards the first option mainly to avoid coupling these two packages.

Another option may be adding Time to Evidence (with minimal validation: `ev.Time < time.Now()`).

Also, found out there's an unused `BlockStore` service in `state/services.go`. Created https://github.com/tendermint/tendermint/issues/4159 to remove it.

**Comment by AdityaSripal** [comment]
> Another option may be adding Time to Evidence (with minimal validation: ev.Time < time.Now()).

Don't really understand this proposal. You mean not using blockTime and using vote.TimeStamp instead? I believe vote times can be arbitrarily chosen by voters as @ebuchman said, so it wouldn't work. And the minimal validation you suggest wouldn't prevent the attack I described because people can still make evidence look very very recent and avoid any outdated checks.

I think I'll start implementing proposal 1

**Comment by ebuchman** [comment]
I think he's suggesting adding a Time field to the evidence, where the Time is the timestamp in the block, not in the particular vote. That might be reasonable, but it doesn't solve the problem if we need to verify that time is actually correct, where we'd need to load the old block anyways.

So one way or another we need to get access to the old time.

I don't think we want to persist the time in save state though - that would require us to persist something for each height in the statedb, which was never really the intention of the state db. Its intention was only to persist the latest state, but of course it's expanded to also persist historical validator states, but to the extent those change slowly, we only persist when they actually change. For time, we'd be persisting something new every height. It might not be a big issue, but it also feels a bit wrong, especially since we already have the data in the BlockStore. 

I agree with the hesitation against coupling these components, but I can foresee other reasons to load historical blocks for validating other kinds of evidence. For instance, if we need to check evidence of signing an invalid block - ie. a validator may not have double signed, but they may have signed an incorrect validator set hash or app hash while they were bonded, which could be used to attack a light client. We have so far focused on invalid validator set hashes, which can technically be detected by loading old validators from the state, but if we need to punish for signing invalid app hashes too (unsure yet!) we'd need to load the historical blocks anyways ... so it's not clear that we'd actually be able to avoid this coupling in the end, and may need that BlockStore service back after all!

**Comment by melekes** [comment]
> I think he's suggesting adding a Time field to the evidence

Yes, but you're right that we'll still need to fetch the old time somehow.

> we only persist when they actually change

and every 100000 (valSetCheckpointInterval) blocks

> And the minimal validation you suggest wouldn't prevent the attack I described

I guess I don't really understand what the attack is?

**Comment by ebuchman** [comment]
It might be good before making a decision here to get further in the design of the rest of the evidence system so we have a better idea of the possible need for coupling between these components.

Also I'll point out, I believe the importance of evidence becoming invalid if it's too old is just to avoid DoS attacks on Tendermint with folks constantly sending us new evidence. Currently, this bug only affects apps and not Tendermint, which in the worst case means they try to slash someone that's no longer bonded (which app's are responsible for handling correctly).

**Comment by cmwaters** [comment]
Just coming into this now and trying to get up to speed with everything. So as far as I understand the reason why we need time is so that we can enforce expiration on evidence (and this is mainly to stop ddos attacks / make sure that the validator is still slashable). But with expiration checks we check both height and time i.e. both height and time must have exceeded the expiration limits. Does the fact that validator time can be arbitrarily chosen compromise expiration checks or can we rely on height? 

Second question, isn't block time also manipulatable (is it a reliable source of truth)?

Looking at the suggested solutions, I'm not really convinced of either for the aforementioned reasons. Adding all the block times to the stateDB seems to abuse the purpose of what we'd expect a stateDB to be and adding a reference to the blockDB in the blockExecutor will add more dependencies when ideally we want to be going in the other direction. 

This kind of brings me asking the first question again - do we really need time? or could evidence expiration be solely dependent on height (I guess to answer my own question, bonding period is defined in terms of time not height).

If we have to find a solution to this then I would say that technically the block executor (admittedly through an interface) already has access to the blockDB through the evidence pool. Perhaps the evidence pool can be in charge of timestamping evidence (both when it is spread through gossip and when we receive it in a proposed block)

**Comment by ebuchman** [comment]
> Does the fact that validator time can be arbitrarily chosen compromise expiration checks or can we rely on height?

Individual vote times can be arbitrary, but any vote is for a particular height, so we use the timestamp from the block at that height. 

> Second question, isn't block time also manipulatable (is it a reliable source of truth)?

It's a BFT time and assumed to be reliable, but +1/3 can fast forward it arbitrarily and unaccountably, though it's harder for them to fast forward the height, hence the hybrid height+time.

> do we really need time? or could evidence expiration be solely dependent on height (I guess to answer my own question, bonding period is defined in terms of time not height).

This is an age old question. We've gone for time by default because that's what makes sense to users, eg. "3 weeks" not "XXX blocks". But in reality we have this fallback to heights and in the SDK one of the modules (I think staking or distribution?) needs to track the expected blocks/second, and this needs to be updated by governance if the actual rate of block production diverges otherwise it can mess up economic calculations.

So there's something to be said for going back to a height based approach and having time be secondary - you could still compute the estsimate unbonding period in time but it would actually be based in blocks, and trusting_period is expected to be shorter than (eg. like 1/2 or 1/3 of) the unbonding_period anyways. But that would be a much bigger change.

> Perhaps the evidence pool can be in charge of timestamping evidence (both when it is spread through gossip and when we receive it in a proposed block)

This is a nice idea but proposers can put malicious stuff in a block so we still need full nodes to be able to verify time anyways. 

I think for now the most straight forward thing to do is give the BlockExecutor access to the BlockMeta's stored in the block store (it should only need `store.LoadBlockMeta` so we can use an interface with just that). Compared to storing something new in the state, this would be non-breaking on disk, so likely the least disturbance.

At some point we may want to think more comprehensively about the nature of stores in tendermint and potentially move some of the state store components into the `store` pkg so we can make it clearer what Tendermint stores on disk.

**Comment by alexanderbez** [comment]
> I think for now the most straight forward thing to do is give the BlockExecutor access to the BlockMeta's stored in the block store (it should only need `store.LoadBlockMeta` so we can use an interface with just that). Compared to storing something new in the state, this would be non-breaking on disk, so likely the least disturbance.

This gets my vote.

**Comment by cmwaters** [comment]
Thanks for answering my questions.

> This is a nice idea but proposers can put malicious stuff in a block so we still need full nodes to be able to verify time anyways.

I'm not sure what you mean by this. What I was suggesting is that since we will be using block time instead of the original evidence time which I think was the vote time in all cases, we will need to change the verification in more than in just the BlockExecutor. For example, when evidence is gossiped to the evidence pool, the evidence pool will need to be able to check that the evidence hasn't expired by also retrieving the block time and comparing it with the current time. The evidence pool already has access to the block store (for lunatic validator evidence in which in needs to retrieve the nodes own header) hence it wouldn't be too hard to write up a function within the evidence pool called `GetEvidenceTime(ev)` where it loads the block meta and returns the time. With this in mind I was suggesting that we expose this through the evidence pool interface such that the block executor can also use `GetEvidenceTime(ev)` with it's verification.

**Comment by cmwaters** [comment]
After doing some further digging around I realised that the functions that prepare the abci Evidence from the block evidence to be sent to the application (`getBeginBlockValidatorInfo` and `execBlockOnProxyApp`) are not methods belonging to the BlockExecutor, so adding the interface to the block executor to access the block meta won't help because then we will need to find all the headers for the evidence and pass them through the aforementioned functions which then also means changing `replayBlocks` and so forth. This is all to say that I don't think such an approach is too viable and that therefore in order to leave the block executor as is, I think it will be better if we change the actual evidence structs to contain the time information themselves and we validate the time through the evidence pool (what we would have had to have done anyway). The only downfall with this approach then is that the evidence structs will be a little larger (contain an extra timestamp)

**Comment by erikgrinaker** [comment]
That sounds reasonable to me: look up the block time when the evidence is received, and store it in the evidence before it's placed in the pool.
