### ISSUE TITLE
[blockchain] Routine queue configuration in v2

### ISSUE THREAD

**Issue by brapse** [tendermint/tendermint#4206]
The Routine abstraction used in the blockchain v2 package is initialized with a `bufferSize` parameter which is supposed to limit the number of in-flight messages being processed by the corresponding routine. However, the underlying queue data structure only uses that parameter as an initial size of the queue and not the limit. The Routine abstraction should be updated to apply the `bufferSize` parameter to an enforced limit on the in-flight messages such that when `bufferSize` messages are in-flight, `routine.send` calls will return false.

Additionally
- [ ] Queuing behaviour should be documented, when does it load shed?
- [ ] Metrics and logging when messages are dropped
- [ ] Understanding of termination condition if dropping messages
- [ ] Understanding and documenting blocking output channel from routines

**Comment by ebuchman** [comment]
Oh yes, I commented on the three distinct uses of the `bufferSize` in https://github.com/tendermint/tendermint/pull/4361#discussion_r376735278. While it does serve as a real bound for the reactor `events` channel and each routine's next channel, it's just a hint for the priority queues, which are unbounded.

But after [reviewing the PR](https://github.com/tendermint/tendermint/pull/4361#pullrequestreview-355560820) and thinking about this more, I'm not sure we want to bound those priority queues and just drop msgs, since then we'll have a more difficult problem of accounting for dropped msgs. So the unbounded queues may be ok, but we should do some analysis and testing to gain confidence that they will stay within a reasonable size (ie. they should be bounded by things like the max peers and send/recv rates, and by reactor specific mitigations like `targetPending`). The existing metrics should help to monitor this, and we can possibly instrument further by logging errors if the queues get too big ...

**Comment by brapse** [comment]
Agreed! I think we want to load shed at the edge so `blockchainReactor.events`, while internal events can be more liberal.  We need to take a look at the queues better after we wrap up the more minor issues in #4361

**Comment by marbar3778** [comment]
V2 has been removed
