### ISSUE TITLE
Events: RemoveListener and make code re-useable

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#421]
Frey: On client.Local, if I just call RemoveListener, it doesn't properly deregister. And in the end the listener fills up the channel and the node blocks and tests hang.
- https://github.com/tendermint/tendermint/blob/develop/rpc/client/helpers.go#L75

Frey: it is impossible to reuse code from go-event. All private (package local)
- https://github.com/tendermint/tendermint/blob/develop/rpc/client/httpclient.go#L183

**Comment by ethanfrey** [comment]
Okay, I investigated further and it turns out it was a typo on my part.

But the API is confusing.  There is
`AddListenerForEvent(listenerID, event string, cb EventCallback)` and
`RemoveListenerForEvent(event string, listenerID string)`

They are both strings and there is no compiler check to distinguish them.  I think it would be nice to update the API to `RemoveListenerForEvent(listenerID, event string)`.  Along with any other changes to make the code more reusable.

I fixed my calling code in tendermint in `2150181`.

**Comment by adrianbrink** [comment]
Is this still relevant? @ethanfrey

**Comment by ethanfrey** [comment]
Yeah, cleaning up the interface is good. And much easier now with the refactor. 

Ping me again here after the retreat if I don't do anything before then

**Comment by adrianbrink** [comment]
@ethanfrey ping

**Comment by melekes** [comment]
This is no longer actual once we merge https://github.com/tendermint/tendermint/pull/568
