### ISSUE TITLE
Question about consensus liveness failure

### ISSUE THREAD

**Issue by Luannet** [tendermint/tendermint#4308]
In the paper ["Byzantine Fault Tolerance in Partially Connected Asynchronous Networks" ](https://eprint.iacr.org/2019/1460.pdf) the author claims that tendermint doesn't achieve the liveness property in the partially synchronous model. According to the paper ["The latest gossip on BFT consensus"](https://arxiv.org/pdf/1807.04938.pdf,) this attack is feasible. 
Have you fixed the problem?

**Comment by melekes** [comment]
@milosevic you might be interested in this

**Comment by milosevic** [comment]
The paper  "Byzantine Fault Tolerance in Partially Connected Asynchronous Networks" makes false claims that Tendermint has liveness problems as the model in which Tendermint is analysed is not the same as the model we assume in  https://arxiv.org/pdf/1807.04938.pdf. Tendermint assumes stronger model than the traditional partially synchronous system model as it assumes gossip-based networking layer. This is precisely stated in https://arxiv.org/pdf/1807.04938.pdf. Tendermint is correct (does not have termination issues) in the model assumes and stated in https://arxiv.org/pdf/1807.04938.pdf.

**Comment by Luannet** [comment]
Hello, @milosevic! I am not so sure that the gossip-layer fixes this problem. If I understand correctly, malicious participants may separate honest participants into different groups and manage which group receives messages before GST. And they do not allow honest participants from different groups exchange messages (and in the gossip-exchange) before GST. In this case, the attack from the paper is feasible.
If I wrong, please, explain to me there is my mistake. (If it is possible, point the place in the Tendermint paper about it)

**Comment by milosevic** [comment]
We don't have any termination guarantees before GST (only safety). So in case of network split correct processes will not be able to receive enough messages (>2/3 voting power), so they will block. As soon as GST period starts, by assumption of Gossip communication property, all messages sent and received by correct processes (before GST) will be delivered the latest Delta after GST. This allows correct processes to continue and terminate (the proof is in the paper).

**Comment by Luannet** [comment]
@milosevic 
Well, let me explain the point that is confused me, please. 

Let consider attack 1 from the paper "Byzantine Fault Tolerance in Partially Connected Asynchronous Networks". Let round 0 and 1 have already done. On the round 2 GST period starts and all nodes receive all messages from previous rounds. The Proposer is from the group P2, who has to propose validValue=v and validRound =0. Honest participants from the group P3 receives messages from round 0 (notice that P3 receives the messages only in round 2).  Would participants P3 consider that they received the proposal with v and all prevote messages on validRound 0 and accept the proposal with validValue or not? This moment is unclear from the protocol.

**Comment by milosevic** [comment]
After GST starts, we will have all messages, that are sent and received by correct processes before GST, delivered within Delta period after GST. We however don't know in what order the messages will be delivered. So processes will either execute round 0,1 and then starts round 2, or maybe jump to round 1 or 2 (because of rule at line 55). Depending on the order in which messages are delivered to processes from P3 they would set validValue to v or not. In the worst case we cannot guarantee that the proposal of round 2 (started after GST) will propose v and that the proposed value will be accepted by all correct processes. In the worst case, we might need to go through the sequence of rounds (N rounds if voting power of every process is 1) until the process that have locked value is a proposer. More precise explanations of how this works are in the paper: Lemma 5, 6 and 7.
