### ISSUE TITLE
proposal: remove abci-cli

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#4336]
I have not heard or seen anyone use the abci-cli. I propose we put a deprecation warning and move to remove it in the next release.

**Comment by erikgrinaker** [comment]
The integration tests appear to use abci-cli, e.g.: https://github.com/tendermint/tendermint/blob/696e13e1ff4c0be2052d2a4f4e36ef3031b11598/test/app/test.sh#L18

**Comment by lazaridiscom** [comment]
seems to exist for mainly for testing: https://docs.tendermint.com/master/app-dev/abci-cli.html

As a sidenote, this this "cli" suffix is everywhere, should be "abci" (see https://github.com/cosmos/gaia/issues/260). The team should possibly decide to strip the "cli" suffixes everywhere, before the system becomes more mainstream.

**Comment by marbar3778** [comment]
this issue is to discuss the removal of `abci-cli` not the suffix. if there is a issue with gaia then it is best to keep the discussion in that issue.

**Comment by lazaridiscom** [comment]
> to strip the "cli" suffixes everywhere

Spawned Issue: #4339

**Comment by melekes** [comment]
abci-cli was written to test ABCI applications. But nobody's using it for that purpose. The only two places where we use it a) "Using abci-cli" documentation page b) https://github.com/tendermint/tendermint/issues/4336#issuecomment-578080473. I'd vote for replacing abci-cli with (vanilla tendermint + abci application + curl ...) in (a). As for (b), we can also use curl I believe.

**Comment by lazaridiscom** [comment]
https://github.com/tendermint/tendermint/search?q=abci-cli&unscoped_q=abci-cli

this looks like a nice tool actually.

Is it possible that `abci-cli` is used by adopters?

Then (@melekes), re usability and "cosmetics", how would

```sh
abci-cli kvstore > /dev/null &
```
look when using "vanilla tendermint + abci application + curl ..."?

**Comment by melekes** [comment]
Looks like there's no clear consensus on whenever we should remove it or not. Maybe leave it for the time being?

**Comment by marbar3778** [comment]
yea sounds good. will close this issue for now.

**Comment by ebuchman** [comment]
abci-cli currently serves two purposes:

- running the example apps (kvstore and counter)
- simple command line tool for testing new abci server implementations

If we remove it, we will still need some way to run the example apps as their own processes. They could be compiled into their own binaries, but then we have more binaries than we started with.

As for curl, you can't use curl (afaik) to send ABCI messages, since it's not an HTTP based protocol. Perhaps there's some better tool for sending generic protobuf messages from the command line, but abci-cli is simple enough it doesn't seem like a problem.

So I see no real reason to get rid of it. Did something motivate this issue?

**Comment by lazaridiscom** [comment]
> Did something motivate this issue?

Author labeled `code-hygiene`, so possibly just an attempt to remove redundant code.

(It seems to me that you need more senior devs / leads to monitor the projects. )

**Comment by lazaridiscom** [comment]
@ebuchman , possibly more important: https://github.com/cosmos/cosmos/issues/118
