### ISSUE TITLE
lite2: rename Alternatives to Witnesses

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4341]
The reason is alternative provider may be viewed as something not important. But in reality we are using alternative providers for cross-checking headers and they are super important.

Other solution may be requiring at least 5 (don't know what the good number is) alternative providers.

**Comment by cmwaters** [comment]
If alternatives provide the sole purpose of validating what is said by the full node then I think witnesses is better. If alternatives can potentially take over as the trusted full node then maybe stay as alternatives. 

Wouldn't it be recommended to have 1/3 of full nodes as witnesses. I'm not to sure what the lower bound of witnesses should be. If you allow the owner of the lite client to take the decision in their own hands then it should be at least 1. 

As a side note, if you were to choose a couple of witnesses that have the highest wealth in the blockchain then it is unlikely that they are all the same person and also that they would be dishonest (because that will devalue their own wealth) - so this would decrease the chance that the primary node and the witnesses would collude against the lite node

**Comment by melekes** [comment]
Proposal accepted.
