### ISSUE TITLE
[tx_search] goroutine for tx search does not stop even if the client timeout

### ISSUE THREAD

**Issue by YunSuk-Yeo** [tendermint/tendermint#4375]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): v0.32.9

**ABCI app** (name for built-in, URL for self-written if it's publicly available): https://github.com/terra-project/core

**Environment**:
- **OS** (e.g. from /etc/os-release): mac-os
- **Install tools**: 
- **Others**:

**What happened**:
It seems tendermint does not stop the search goroutine after the client timeout. In Terra columbus chain, there are lots of txs can't be hold on memory so it cause out-of-memory crash. For test purpose, I applied timeout enabled rpcclient(custom) to prevent this situation. But after the client timeout,  the memory keeps increasing until it finish the search task or meet crash.

**What you expected to happen**:
Stop search goroutine right after the client timeout.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):
sync columbus-3 chain & do try search with message.action='send' or message.action='multisend'

**Comment by gterzian** [comment]
@YunSuk-Yeo  do you have the code for the timeout enabled rpc client? It seems there is none in the current code, perhaps it would be helpful to try to merge it in addition to https://github.com/tendermint/tendermint/pull/4418

Otherwise https://github.com/tendermint/tendermint/pull/4418 might need to include one such timeout enabled client, or else appear useless? What do you think @melekes ?

**Comment by YunSuk-Yeo** [comment]
@gterzian here is timeout enabled rpc client 

https://github.com/terra-project/core/blob/d8160597537cbe5d936c5e15b1d3c1e9fb01ddb5/client/lcd/root.go#L42
