### ISSUE TITLE
[blockchain][v2] Should peer removal be permanent

### ISSUE THREAD

**Issue by brapse** [tendermint/tendermint#4415]
In the current  blockchain v2 scheduler can remove peer if they perform an error, timeout or are purged. Once a peer is removed, re-adding them will cause a fatal error. It isn't clear if this is the correct behaviour. Investigate wether removing a peer from the blockchain reactor scheduler should be permanent.

**Comment by cmwaters** [comment]
I think there should be a distinction between whether a peer performs an error or whether they just timeout. At least with timeouts, I believe it would be better if they weren't removed but just put to the back of a list. I'm sure it could be integrated with the list of peers that are ordered on the amount of pending requests (which is written in the function `selectPeer()`). I think it's best to keep a relatively large list of peers so that you can evenly spread the load. What do you think?

**Comment by brapse** [comment]
Yes the distinction you suggest makes sense. It isn't clear to me how to go about testing different strategies for `selectPeer()` which could substantial these kinds of arguments. What would you suggest here?

**Comment by cmwaters** [comment]
Here is a stab at a few proposals:

**First Suggestion:**

As a rather natural and simple approach, if we were to remove the pruning process of peers on timeout: `rTryPrunePeer` then the peer would still have at least one pending block and would therefore be outcompeted by peers that had zero pending blocks putting it further back on the list of peers to request blocks from. We could even multiply the pending blocks by a factor (i.e by 3) so that is is further pushed back on this list. The main implementation would be handling when the peer eventually came back online and submitted a block at a height lower than the state height in which case `scBlockRecieved` would instead of ignoring the block, remove the pending block and therefore free up the peer again. The disadvantage would be if instead of the network the message itself dropped such that the peer had no idea it had a block requested and therefore had become blocked from the fast sync process. 

**Second Suggestion:**

Have a separate timeout pool that peers are dropped into after timeout and where iteratively based on a timer every peer in the timeout pool is pinged, if they respond they are promoted back into the main pool. This covers the prior suggestions flaw but would most likely be more implementation heavy.

What do you think?

**Comment by brapse** [comment]
Both are perfectly valid suggestions! However my question was how would we compare different approaches. Even though we can do something here, both of your suggestions look good, it isn't clear what we would be improving and how we would measure such an improvement.

My intuition is that banning peers permanently results in some sending nodes being under utilized while some receiving nodes will somehow be starved of blocks. If that is the case then it should be observed first. A first step here might be to add some metrics around:
* Count of peers in which state
* Rate of blocks sent per peer_id
* Rate of blocks received per peer_id

This way we could observe the inefficiency before committing to particular strategy.  Worst case: It isn't a problem in most cases and our dumbest solution is fine. The metrics could then be used to help debug network partitions and inform a better strategy later.

**Comment by cmwaters** [comment]
Yes I agree with your intuition. That being said, as I am trying to become more familiar with the p2p module, I am wondering, since it seems that we don't actually keep a record of banned peers, is it possible that a removed peer be eventually picked up again by peer discovery and re-used in fastsync?

**Comment by cmwaters** [comment]
In regards to using metrics, I have seen it in other software that users can send there diagnostics back to the software team to analyse. Is there something similar to this with Tendermint, that real users can send their metrics so that we can see where the pain points are?

**Comment by tessr** [comment]
I'm doing some issue cleanup today, and I'm going to close this issue for now as I think it is covered by the upcoming P2P refactor. Feel free to re-open and ping me to triage if you disagree :)
