### ISSUE TITLE
lite2: document that we don't provide access to headers outside of trusting period

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4421]
"Note that after the header (time validity) expires, it can still be used to verify application data as part of backward header verification. In this case, although some header h1 is outside its trusted period (and is not considered valid on its own) can be trusted in case there is a consecutive sequence of verified headers between h1 and some trusted header h2 that is still valid, i.e., that is within its trusted period. This implies that there is a value of storing (verified) headers that are outside its trusted period, but what is the right strategy for efficiently doing this is outside the scope of this document."

It can be done, but trusting period is supposed to be sufficiently large (2 weeks of blocks which can be used to verify data).

This needs to be reflected both in ADR-46 and lite2 readme.

**Comment by melekes** [comment]
@cmwaters do you agree with rationale ^?

**Comment by cmwaters** [comment]
If we verify a header and it enters the trusted store, I believe the user should be able to access that header even after it has expired (is outside the trusting period) because it hasn't changed. But of course we shouldn't be taking in expired headers from the primary or other providers hence we shouldn't verify headers outside the trusting period but we should still grant access to the user of the lite client

**Comment by melekes** [comment]
now we do provide such access. pruning is now based on the number of headers https://github.com/tendermint/tendermint/issues/4469
