### ISSUE TITLE
Discoverable P2P seeds, RPC nodes, and trusted headers

### ISSUE THREAD

**Issue by erikgrinaker** [tendermint/tendermint#4583]
## Summary

When state sync lands (#828), setting up a new node will require obtaining the following pieces of information:

* A set of P2P seed nodes (to reach the network)
* A set of RPC servers (for light client verification)
* A trusted header height and hash (as a root of trust)

To make it easier for users to get started, we may want to consider publishing this information in a central place, or write a guide on how to easily obtain it. This must be weighed against concerns of having a central authority that can be abused or exploited, as well as the risk of overloading the published servers.

One option might be to collaborate with e.g. chain explorers to establish multiple independent sources of this information. It could also be gossiped over P2P and exposed via RPC such that chain explorers and others could automatically gather and publish it.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
Part of this issue may be better suited in the cosmos-sdk. This is more of an application-level concern then tendermint level concern. 

How I see this is we write the docs on it in Tendermint then its up to the applications/explorers on how they would like to handle it.

**Comment by erikgrinaker** [comment]
Allright, I'll move it to the SDK repo and we can create a new issue if we need any technical changes in Tendermint.

**Comment by marbar3778** [comment]
we should keep this issue but just label it as a docs issue since it already outlines what needs to be documented.

**Comment by tessr** [comment]
Although this is technically a Gaia/Cosmos Hub TODO, I'm happy to track it in Tendermint since we're the ones driving the state sync feature. 

In the short term, @marbar3778 suggested that we (or someone on the Gaia team) use a crawler similar to one that @alexanderbez made to crawl the network to find the seed nodes and RPC servers and then post that information to the Cosmos docs.

In the medium term, that crawler could be hooked up to a chron job (perhaps managed by Github actions?) to find these things on a regular basis and then automatically keep the Cosmos docs up to date.

Longer term, we could share that crawler (or another similar tool) with people running block explorers and ask them to host that information there. That way, the information isn't centralized through the Cosmos docs. But that will also take more time/collaboration to enable, so I think we should keep that as a longer-term plan for now.

**Comment by erikgrinaker** [comment]
We'll leave this to the network operators to handle.
