### ISSUE TITLE
consensus: do not account for misbehaved validator's power

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4593]
when calculating majority of prevotes/precommits for a block, which contains an evidence of some validator (V) committing double vote or other attack.

Therefore, reducing the chance of the cabal group (A being its member, presumably) filtering the evidence.

**Comment by cmwaters** [comment]
I completely agree with this. A few notes that I would like to add:

- A vanilla implementation of this would mean a reduction in total voting power, meaning each remaining individual has more power: 
    - Would we still want to commit transactions alongside this? 
    - Do we allow multiple evidence to be submitted at once. (this could further reduce the votable fraction of validators)? 
    - Would we put limits in place on power reduction i.e. No more than 50% of the voting power can be barred at any single block height. 
    - Is this even a problem -> if the malicious nodes are to be slashed than this will cause a similar transfer of power.

**Comment by alexanderbez** [comment]
Great questions @cmwaters, but I don't think we can necessarily assume the application's state-machine will slash accordingly.

**Comment by cmwaters** [comment]
Yeah your right, I guess this begins to delve into the grey area between what is the responsibility of the application and the responsibility of tendermint

**Comment by melekes** [comment]
> Is this even a problem -> if the malicious nodes are to be slashed than this will cause a similar transfer of power.

maybe I wasn't clear in the description. slashing occurs after the block with evidence is committed. I.e. if cabal group filters the evidence, nobody will be slashed.

> Would we put limits in place on power reduction i.e. No more than 50% of the voting power can be barred at any single block height.

Why do we need this?

> Do we allow multiple evidence to be submitted at once.

sure

> Would we still want to commit transactions alongside this?

why not

**Comment by ebuchman** [comment]
Not sure I understand what's being proposed here. It sounds like we're saying that if a block contains evidence for a validator that also voted on that block, we shouldn't consider them as part of the voting power for that block. I'm not sure that's safe in general. But I'm also not sure it actually helps us, since the block is committed before we process it, so the malicious validator can already try to censor the block before its committed if it contains evidence against them.

**Comment by melekes** [comment]
Proposal:

When calculating the amount of voting power needed to prevote/precommit (2/3+), we exclude misbehaved validators (evidence is not yet committed, but is scheduled to be included in this or the following block - i.e. it's in the evidence pool).

**Comment by cmwaters** [comment]
The evidence will need to be validated before we exclude their voting power from the consensus process hence I believe it has to just be in the current block sometime between receiving the proposal and prevoting. I don't think verification in the evidence pool counts because not all honest nodes will have the same evidence pool

**Comment by ebuchman** [comment]
>  I don't think verification in the evidence pool counts because not all honest nodes will have the same evidence pool

Right, we can't base it on something that isn't in consensus.

It's conceivable that if the evidence is included in the proposed block we could adjust the voting power for that block based on the evidence, but even that smells a bit fishy and is probably not ok. Would be interesting to reason through though.

**Comment by melekes** [comment]
> It's conceivable that if the evidence is included in the proposed block we could adjust the voting power for that block based on the evidence, but even that smells a bit fishy and is probably not ok.

why not? 😄

**Comment by ebuchman** [comment]
Thinking about it quickly, it could wreak havoc on the cross-round consensus rules - you need to agree on the validator set across rounds, otherwise you don't know what constitutes a polka. If there are different potential validator sets depending on what evidence a proposer knows about, I could see it getting hairy. You might have to include the evidence as part of the valid value somehow. All to say it might be possible, it's just very subtle and you'd have to be super careful with the design ...
