### ISSUE TITLE
Backport fast sync v2 to 0.32.x line so that it can be incl in a 2.0.x gaia release

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#4609]

**Comment by erikgrinaker** [comment]
Should this be fast sync v2?

**Comment by jackzampolin** [comment]
That would be ideal. Just syncing a node on the network now and it's going to take a few days at this rate. This would be great improvement for users.

**Comment by erikgrinaker** [comment]
Ah, I guess you did mean state sync after all, since I don't think fast sync v2 will be significantly faster than v0 - the `v2` threw me.

State sync is a breaking change, since it requires changes to the ABCI interface and P2P protocol, so I don't think we can backport it to Tendermint 0.32.x and Gaia 2.0.x. What do you think @marbar3778?

**Comment by marbar3778** [comment]
I agree with you @erikgrinaker. Not sure it's possible to do this in a nonbreaking way. 

For now I would recommend using a snapshot from a different node.
