### ISSUE TITLE
light: revert to sequential verification when bisection causes conflicting headers

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#4694]
## Problem Definition

When the light client uses bisectional verification it can verify headers much quicker but makes itself vulnerable to a few types of attacks (Phantom and Lunatic Validator => see https://github.com/tendermint/spec/blob/master/spec/consensus/light-client/accountability.md ) 

## Proposal

A potential solution could be after observing conflicting headers when comparing to other nodes, that the light client who'd previously been verifying with bisection goes back and tries to verify again using sequential. In this case, these attacks would be found out and the client providing the incorrect data dropped.

This requires extra work on the light client side in the event that something like this happens but saves the entire network from having to deal with evidence. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
As a thought experiment, I wonder if you'd get the same level of safety as sequential if you bumped the trust level from 1/3+ to 2/3+

**Comment by melekes** [comment]
> This requires extra work on the light client side in the event that something like this happens but saves the entire network from having to deal with evidence.

I thought we'd still want to punish the attackers, no?

**Comment by cmwaters** [comment]
Yeah I guess we still could. I guess in this case then this idea is beneficial in the fact that the lite client can recover and continue to operate.

**Comment by josef-widder** [comment]
First, I am not sure I get the difference to the detection mechanism. Second, I am not sure whether "not having to deal with evidence" is a good goal. Evidence leads to punishment, so that nodes have the incentive to follow the protocol. I don't think that just dropping the node will give any incentive. What do you think?

**Comment by cmwaters** [comment]
With regards to your first sentence are you referring to using sequential verification as a fall back or using a 2/3 trust level bisectional verification. In either case this is more a matter of light client robustness and not so much altering the detection mechanism. The light client will still send the evidence (either the first round or the second round) but in any case if it is just a light fork (F4 or F5)  it can drop the provider and recover instead of having to stop. 

Attack | FN | LCS | LCB
-- | -- | -- | --
F1 | direct | FN | FN
F2 | direct | FN | FN
F3 | direct | FN | FN
F4 |   |   | direct
F5 |   |   | direct

In regards to the second item, I believe prevention to be in most cases better than punishment. I.e. if we can stop malicious nodes from corrupting honest nodes then this should be more important than finding ways to punish malicious nodes for their behavior.

**Comment by josef-widder** [comment]
OK, I see. 
If I understand correctly, bisection can be "successfully" attacked by F4 and F5 only if in addition more than 1/3 of the voting power is faulty. Otherwise, bisection would not accept such a header. The question is whether in the scenario of +1/3 faults, sequential verification leads to a better guarantees, that is, whether a header that can be verified can be trusted "more".  Until now, my understanding was that we could just detect that something went wrong, and in general could not single out the culprit.

**Comment by melekes** [comment]
One more thought: I'd expect this to be a rare case. Most of the light clients will be keeping up with recent height, if not execute sequential verification due to always having a previous header: 

H100, H101, H102 ...

**Comment by ebuchman** [comment]
So there's two questions here:

1. If a light client encounters two valid bisection traces, should it do full sequential verification to determine which trace is valid?

So by verifying sequentially, a client can avoid the F4/F5 attacks, or if it already detected one, discover which fork is false. But this could require ~GBs of data which is not something we can in general expect or require from clients. We'd also still want to submit the evidence regardless so the offending validators can be punished, and its very cheap for full nodes to figure out from two bisection traces who is faulty. And while the light node might have to submit a large evidence message to a full node (eg. two potentially long bisection traces), the full nodes should be able to repackage it as much smaller evidence that can be easily verified by other full nodes. So I'm not sure it buys us much.

2.  If you set the increase the trust threshold from +1/3 to +2/3, do you effectively get the security of sequential verification and eliminate the F4/F5 attacks ? 

I think this might be right, but I'd still need to fully reason through it, and I'd ask @josef-widder to sanity check. I think this would mean +2/3 of the validators would have to be faulty to mount those attacks rather than +1/3, and if that were the case, they could already fool anyone ... If I'm not mistaken, the fork detection/accountability security model (ie. the model that kicks in when the tendermint failure model of +2/3 correct fails) still requires +1/3 correct nodes. If there are less than this many correct nodes, I think all bets are off.

If that's the case, does it mean we could simplify a lot of things by requiring a +2/3 trust threshold for now ? It means bisection traces will be much longer if there's a lot of validator turn over, but in practice, it probably still lets us go pretty far! Or does a +2/3 threshold somehow compromise light client's liveness? Need to think about this more ....

**Comment by josef-widder** [comment]
We briefly discussed this during some (verification-related) meeting recently. Increasing the trust threshold to 2/3 will definitely reduce the likelihood that skipping verification can be successful if validator sets changes even moderately. So that may boil down to do sequential verification in practice. At the same time, it is not so clear what theoretical gains can be achieved in the case of +1/3 faults. Right now, I am not convinced something can be gained. I will look into this in the next days (my work on forks was recently interrupted a bit).

**Comment by melekes** [comment]
> And while the light node might have to submit a large evidence message to a full node (eg. two potentially long bisection traces),

@cmwaters and me are leaning towards **finding a common root among two branches ON the light client** side and sending first two diverged headers (not the latest).

**Comment by ebuchman** [comment]
That sounds good. Though I'm not sure anymore we really even needed to send the full traces. Started writing about this in https://github.com/tendermint/tendermint/issues/5022

**Comment by cmwaters** [comment]
I think this issue can be closed now. For reference on the implementation of the light client detector / evidence handling refer to this [ADR](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-047-handling-evidence-from-light-client.md)
