### ISSUE TITLE
CommitSig validation doesn't adhere to ADR-025

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#4797]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
master

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
N/A

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:
All binaries are affected.

**What happened**:
In the source code, `CommitSig` validation checking on a `BlockIDFlagAbsent` type block (block_id == 1) deems the signature invalid, if the validator address is present. (Here:[CommitSig.ValidateBasic](https://github.com/tendermint/tendermint/blob/9f500067d387036e598c89195a793f10168401c6/types/block.go#L540))

I thought that the validator address is present in all cases and ADR-025 that describes CommitSig doesn't seem to contradict that. ([ADR-025](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-025-commit.md#decision)) (Also, what's the point of a CommitSig that doesn't have any valid information? Because the signature has to be missing already.)

Can I get a recommendation on how to implement this in Rust? Currently, I have the validator address as a mandatory field which will make it in line with expectations based on the ADR and incompatible with the Go implementation. Shall I go by the code or the ADR?

Additionally, at the same check (CommitSig validating a BlockIDFlagAbsent block), it is checked if the timestamp is zero. [here](https://github.com/tendermint/tendermint/blob/master/types/block.go#L543) I would have expected that field to be missing or set to `null` based on the ADR. But in Go, zero time means 0001-01-01T00:00:00Z which is a syntactically valid timestamp. I feel this should not be set to zero like that but to `null`.
I understand if this latter issue is not high priority enough. If it won't be changed, I'll work around it in Rust I just want to make sure I'm doing the right thing.

Cross-issue with the Rust implementation: https://github.com/informalsystems/tendermint-rs/issues/246

**What you expected to happen**:
I was expecting the BlockIDFlagAbsent type block to only have the validator address and missing the timestamp and signature fields. (or set to `null`).

**Have you tried the latest version**: yes/no
yes, this is on master.

**How to reproduce it** (as minimally and precisely as possible):
We've reproduced this in tendermint-rs, but this is proven by the links above.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
N/A (You can check the Rust source code and testing results here: https://github.com/informalsystems/tendermint-rs/runs/644552178?check_suite_focus=true)

**Config (you can paste only the changes you've made)**:
No changes made.

**node command runtime flags**:
N/A

**`/dump_consensus_state` output for consensus bugs**
N/A

**Anything else we need to know**:
I'm going to remove the questions next time that don't make sense in an architectural bug report. :)

**Comment by melekes** [comment]
Yeah, it looks like we have deviated from the ADR. The reason for it being https://github.com/tendermint/tendermint/blob/25890a66350f09b0d8fd54d8b9e73eb972265946/types/vote.go#L61 - it's tricky to get ValidatorAddress from a nil vote. So, if we decide to have ValidatorAddress in absent votes, we'll need to remove the concept of `nil` votes in Tendermint, which may be a good idea on its own.

**Comment by ebuchman** [comment]
Huh, nice find Greg. This speaks to the larger conversation around whether ValidatorAddress should be in CommitSig at all, ala #4835.

We could fix this to match the ADR a couple ways:
- .CommitSig() handles nil votes, but we only call CommitSig from places where we already have the validator set, so we could fill in the address after the fact, though this is error prone
- change VoteSet so absent votes are explicit absent instead of just being nil, but this might be a large change

Neither of the above seem great. It's also not clear how valuable it is to have the validator address in the absent commit sigs. Is there a real use case for that? 

I'm also increasingly convinced that we can remove ValidatorAddress all together, but maybe still we don't do that until we change the Commit again, ie. when we remove the timestamps - see CommitSig in https://github.com/tendermint/tendermint/issues/4835#issuecomment-634328417

To that end it might be worth to start modifying the code towards not depending on the CommitSig.ValidatorAddress so that when it comes time to remove it it will be trivial

**Comment by melekes** [comment]
Looks like the 2/3+ consensus is to remove ValidatorAddress https://github.com/tendermint/tendermint/issues/5023 and Timestamp https://github.com/tendermint/tendermint/issues/2840.
