### ISSUE TITLE
Vote & commitsig redundancy 

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#4835]
## Summary

First, in the commitsig we have:

```
type CommitSig struct {
	BlockIDFlag      BlockIDFlag `json:"block_id_flag"`
	ValidatorAddress Address     `json:"validator_address"`
	Timestamp        time.Time   `json:"timestamp"`
	Signature        []byte      `json:"signature"`
}
```

the validator address was left in the commit sig due to the reasons below:

```
ValidatorAddress: we include it in the CommitSig for now. While this does increase the block size unnecessarily (20-bytes per validator), it has some ergonomic and debugging advantages:

    - Commit contains everything necessary to reconstruct []Vote, and doesn't depend on additional access to a ValidatorSet
    - Lite clients can check if they know the validators in a commit without re-downloading the validator set
    - Easy to see directly in a commit which validators signed what without having to fetch the validator set
```
https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-025-commit.md

Currently, the lite client fetches the validator set, the debugging reasons while true there are other ways of debugging this as well. The first reason that a commit contains everything for a vote to be reconstructed is a convenience thing that if it were removed the overhead of fetching the data would not be large as we have not yet seen validator sets larger than 200-300 with Tendermint. 

Second, in the vote we also have the ValidatorAddress & ValidatorIndex:

```
type Vote struct {
	Type             SignedMsgType `json:"type"`
	Height           int64         `json:"height"`
	Round            int           `json:"round"`
	BlockID          BlockID       `json:"block_id"` // zero if vote is nil.
	Timestamp        time.Time     `json:"timestamp"`
	ValidatorAddress Address       `json:"validator_address"`
	ValidatorIndex   int           `json:"validator_index"`
	Signature        []byte        `json:"signature"`
}
```

This is a bit redundant, in the case we need to get the validator address we could get it by the validator index as the index will not change while a vote is happening.

## Proposal

I propose removing ValidatorAddress from these two types. 

For the commitsig if we were to remove the validatorAddress it would be a savings of 20 bytes. In a network of 100 validators over 1 million blocks that equates to roughly 2gb of disk space savings. While this becomes less prevalent with statesync and block pruning it is a savings. 

If this is accepted then we would need to amend https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-025-commit.md

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Liamsi** [comment]
cc @adlerjohn this sounds relevant to what you brought up yesterday 👍

**Comment by adlerjohn** [comment]
Removal of redundant or unnecessary fields from the block header (and specifically the much-repeated signatures) would be great for cross-chain light interaction (e.g. verifying Cosmos headers inside an Ethereum smart contract, or potentially even IBC communication). Previous discussion on the topic was optimized around lack of manpower and time, but going forward it would be nice to include cross-chain costs as an optimization target.

**Comment by cmwaters** [comment]
Just wanted to add that a lot of the evidence stuff uses votes and hence the validator address as a way of identifying the validator that voted. I imagine it's plausible to use the validator index instead but it will just mean a bit of refactoring in that area. I'm unsure of how it may affect other modules

**Comment by marbar3778** [comment]
I would also like to add the removal of address from the validator struct:

```
type Validator struct {
	Address     Address       `json:"address"`
	PubKey      crypto.PubKey `json:"pub_key"`
	VotingPower int64         `json:"voting_power"`

	ProposerPriority int64 `json:"proposer_priority"`
}
```

Reason being that you can get the address from the PubKey, making the address redundant as well. The computational overhead is quite small as well because of the address being `crypto.Address(tmhash.SumTruncated(pubKey))`

**Comment by marbar3778** [comment]
as per a conversation that happened in slack on why BlockID can be nil in a vote. 
```
commit sig is new. we used to just use the vote. and an empty blockid was a vote for nil which is part of the tendermint protocol (so we can skip to the next round). but to reduce the size of the commits we changed to using commitsig instead of votes, mostly because the blockid is redundant information in there, we can remove it from all the votes and just include it once in the commit, and use a flag to indicate which blockid the commit was for!
```

I would add another proposal of removing BlockID from vote after reading.

**Comment by melekes** [comment]
I'm in favor

**Comment by ebuchman** [comment]
Lots of subtleties here that should be addressed. I'm not convinced we should make any of the proposed changes in this issue any time soon.

# Vote

> I propose removing ValidatorAddress from these two types.

Votes are gossiped in real time consensus, but not stored in blocks anymore, since we now use CommitSig. It's true that removing the address from the vote could make consensus marginally faster, but it's not clear how much without benchmarking. The value of having ValidatorAddress in the vote is that it makes code cleaner and makes the system easier to debug since you don't need to pass around the validator set every time you want to figure out where a vote is from. It also plays a big role in evidence management as Callum mentioned.

It's also worth noting that the ValidatorAddress is *not* part of what is signed in the vote.

So to remove it from the vote would require:

1. Someone to prove with benchmarks that consensus is significantly faster without it
2. Someone to figure out all the implications on evidence handling
3. Someone to sketch how to keep the code clean despite having to pass around the validator set more.

In short, I don't think it's worth removing the ValidatorAddress from the Vote ...

> I would add another proposal of removing BlockID from vote.

This I don't understand at all. Without a BlockID, how do you know what the Vote is for? We can't remove BlockID from Vote. We already made the optimization to introduce CommitSig into the Commit instead of Vote, and removed the BlockID from CommitSig, so it's not included redundantly in the commit.

In short, doesn't seem worth it to change the Vote struct.

# CommitSig

> I propose removing ValidatorAddress from these two types.

So we discussed this at length as part of ADR-25 and decided against it. Specifically:

> If and when we change the CommitSig again, for instance to remove the timestamp, we can reconsider whether the ValidatorAddress should be removed.

In order to provide some consistency in our decisions making, I would stick with this. 

> Removal of redundant or unnecessary fields from the block header (and specifically the much-repeated signatures) would be great for cross-chain light interaction (e.g. verifying Cosmos headers inside an Ethereum smart contract, or potentially even IBC communication).

Re @adlerjohn points, it's important to note that alot of this redundant information isn't necessary for verification - eg. ValidatorAddress is not part of the information being signed. So it's not necessary to send it to an ethereum contract to verify a commit. It is hashed into the LastCommitHash, but afaik this isn't really important for a light client/cross chain protocol. 

> Timestamp: Proposer timestamp may be possible to use, now is the "later" in "we'll look at it later."

We recently discussed this, and while we'd all like to remove it from votes (and CommitSig), introducing proposer based time is a non-trivial change to the core tendermint consensus that makes liveness dependent on synchronized clocks. We'd like to do this, but we need time to specify and verify the protocol correctness before it's rolled out. Hope fully we can do that later this year, and of course when we do we can consider removing the ValidatorAddress from CommitSig as well, as per above.

> BlockIDFlag: Absent signatures look like an implementation artifact. If both Commit and Nil signatures need to be tracked (I'm not convinced the latter are required, though I'll admit I'm not the most familiar with the Tendermint consensus protocol) they can be tracked in two separate arrays in the Commit structure.

Nil is important because we want to track validators that are actively signing, even if they only signed for Nil and not the correct block. We discussed this in https://github.com/tendermint/tendermint/issues/3485. It could be reconsidered, but would be a larger convo. Again though, you don't need to worry about the nil votes for cross chain stuff, you can just focus on the votes for the BlockID.

We also considered two separate arrays but it seemed simpler to have a single list where the position in the list matched the validator index.

> ValidatorAddress: 1) The address (and in fact the pubkey) can be recovered from the signature so long as the original message is known, with ECDSA. This is not possible with EdDSA AFAIK. 2) This is redundant if the validator index is known, if all commit signatures are in an ordered list.

We shouldn't assume recoverability in general since mostly ED25519 is used and it doesn't work there or in general. See other points too.

# Commit

Re removing Height and BlockID. It's true this information is redundant with the header. But not having it in the Commit will complicate the code since Commit verification and vote reconstruction from commits will additionally require the header. Not sure it's worth it for the 80 byte savings per block.

# Validator

> I would also like to add the removal of address from the validator struct:

I'm not sure what this buys us, since validators aren't stored in the blockchain. It's already the case that when we hash the validator set, we only use the Pubkey, not the address. And since we do use the validator address more often then the Pubkey, we'll be constantly doing that hash operation, and would probably end up wanting to memoize the address in the struct anyways ...  So it doesn't really seem worth changing it.

# Other

The big one that no one has mentioned here that I would love to simplify more than anything is the BlockID, which contains the PartSetHeader, which is totally useless other than for real time consensus. If we could get rid of it, the BlockID would just be a 32-byte hash, instead of the ~80-byte thing it is now. Unfortunately doing this will require careful work on block propagation in the consensus, but hopefully that's something we can also get to in the next 12 months.

# Summary

All this said, I don't see a real need to change any of the structures right now, and in general would recommend against things that will force more parts of the code to be coupled. Of course this needs to be balanced against real world costs, especially for interchain use cases where data structures are processed on chain, but fortunately as I described a lot of the redundant information we're discussing doesn't need to be forwarded in this interchain contexts and so can already be left out there without changing the core Tendermint structs!

**Comment by adlerjohn** [comment]
@ebuchman that was an interesting read. To this point and this point only, a rebuttal.

> a lot of the redundant information we're discussing doesn't need to be forwarded in this interchain contexts and so can already be left out there without changing the core Tendermint structs!

Consider the following scenario: imagine that in Bitcoin, every field in the block header is duplicated when computing the block hash. In other words, headers are defined as `{version, prev_hash, txs_hash, time, bits, nonce, version, prev_hash, txs_hash, time, bits, nonce}`. The duplicate fields only affect the block hash computation, and how the duplication happens is an implementation detail: they don't need to be sent over the wire, or stored on-disk in history, or sent to a smart contract for verification. In such as scenario, you could say "well, they don't affect any performance metric in any way, therefore we don't need to change anything!" And you'd be wrong.

**Comment by ebuchman** [comment]
> you could say "well, they don't affect any performance metric in any way,

In this case it clearly affects performance since you're duplicating fields eg. in EVM memory and increasing the number of bytes being hashed. I appreciate the example, but it's clearly contrived, and I don't believe maps very directly to what we're dealing with.

Of course I agree with you about domain separation. I'm all for it. But the reality is we have an existing codebase and achieving the domain separation we desire without poisoning the code would take a lot of refactoring. It's something I hope we ultimately get to, but it will take time. Ideally we have completely separate types for structures that come over the wire, structures that are hashed, structures we manage in memory for convenience, structures returned on RPC, etc. But unfortunately the current codebase tends to use a single structure across all domains, and so we have developer concerns bleeding into consensus data structures.

> metadata needed for consensus should be outside the core data structures.

Totally agree. From what I can tell, the main consensus metadata that's in the core data structures is the BlockID.PartsHeader. I'd love to factor that out, as mentioned, but it will require some serious and potentially dangerous plumbing in the consensus reactor, so not likely to happen too soon. 

All that said, unless I'm missing something, I still think the current data structures are actually pretty good for interchain/light-client needs, since you don't need to worry about any of the redundant fields and there's no duplication on critical paths like in the contrived example. My understanding is that removing the redundancies wouldn't materially change anything, and you could have eg. EVM code with equivalent cost before and after such changes. Please let me know if I'm wrong!

**Comment by adlerjohn** [comment]
> But the reality is we have an existing codebase and achieving the domain separation we desire without poisoning the code would take a lot of refactoring. It's something I hope we ultimately get to, but it will take time.

Code debt and insufficient manpower and more pressing concerns are perfectly valid reasons for de-prioritizing non-critical work like deduplicating fields, or removing implementation details that leak into the spec. Ultimately though, all debts must be paid, so I'm hoping someone can get to this sooner rather than later.

> My understanding is that removing the redundancies wouldn't materially change anything, and you could have eg. EVM code with equivalent cost before and after such changes. Please let me know if I'm wrong!

You're correct if we ignore redundant address. Which as both of us mentioned, doesn't apply to generic Tendermint (but does for some choices of signature schemes and curves).
