### ISSUE TITLE
lite2: check header w/ witnesses only when doing bisection

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#4872]
bisection from nearest trusted header is not safe without checking with witnesses (latest: 200, first: 100, requested: 150; bisection from 100 to 150 is not safe)

we trust 100, but primary can still send us something invalid and, if we don't check it with witnesses, we can't fully trust it.

**Comment by cmwaters** [comment]
My confusion here is that at the end of the `verifyHeader` function we still compare with witnesses regardless of what method is used. So for the example above, if the latest header we have is at height 200 and the earliest is 150, regardless of whether we use backwards or bisection to verify that header, at the end we will still compare the header at height 150 with those of our witnesses

**Comment by melekes** [comment]
Oh, great! then it means we're safe :) yeah, we don't need to check witnesses if we're doing backwards hash chain verification. I also think we don't need to do it when sequential verification is being used.

**Comment by cmwaters** [comment]
Ah interesting, see at the moment we check headers regardless of whether we have used backwards, sequential or bisection. So perhaps an improvement is to not compare with witnesses when using sequential verification. This would speed up the verification using this methods because we wouldn't be waiting on the network speeds of all the other witnesses
