### ISSUE TITLE
Ask about liveness problem

### ISSUE THREAD

**Issue by FanGuoshun** [tendermint/tendermint#5009]
"Because in the pre-commit phase if a participant observes pre-commits on nil from ⅔ of the participants, they cannot move to the next view until the timeout expires, otherwise, an adversary with careful control of the network can make the algorithm switch between views indefinitely." Why does this happen?Why do we need a precommit-timeout?Can you give an example?Thank you very much!!!

**Comment by FanGuoshun** [comment]
The quoted sentence is from this article: https://near.org/blog/doomslug-comparison/

**Comment by ebuchman** [comment]
I believe the issue for this was here which somewhat describes the scenario: https://github.com/tendermint/tendermint/issues/1690

Essentially, without the timeoutPrecommit, validators could leave the round before hearing about the latest valid block, which means the next proposer might propose something that can't be committed because validators are locked on something else. And this could happen indefinitely. The timeoutPrecommit ensures that eventually the next proposer hears about the latest valid block and so proposes something that can be committed. To ensure liveness, we need ensure that eventually the proposer of a round knows the highest value locked by other validators and can propose that.

Consider a scenario with four validators (p1, p2, p3, p4), where two validators (say p1 and p3) are locked on different blocks (say v1 and v3) in different rounds (say rounds 1 and 3). Say p2 is not locked on anything and p4 is faulty. Suppose we're now in round 5 and p1 is the proposer. p1 will propose v1 (since its locked on it from round 1) and prevote for it. p2 will prevote for it. p3 will prevote nil because its locked on a different value from a higher round. now suppose p4 prevotes for v1, but it sends the prevote only to p1 just before the timeoutPrevote. Since the message wont get to p2 and p3 before they timeoutPrevote, they will both precommit nil (since they didnt see a polka), but p1 will precommit for v1 in round 5, since it saw a polka. In round 6, p2 will propose something else, but p1 and p3 won't vote for it because they're locked. Then in round 7, where p3 proposes v3 (that it's locked on from round 3), p4 can play the same trick. This can go on forever.

By introducing timeoutPrecommit, we ensure that eventually, the polka seen by one validator is seen by all of them, so the proposer at the next round knows to propose it. For instance in the above scenario in round 5, assuming we're after GST, by waiting timeoutPrecommit, p2 will see the polka that p1 saw, and will thus propose v1 in round 6 along with the polka, which p3 can use to unlock, and thus in round 6 they will commit v1. But without the timeoutPrecommit, we can't ensure that the proposer for the round sees the polka that caused other validators to lock in the previous round.

I'm not sure if this explanation exists somewhere nicely in the docs/spec but if not we should probably write it up!

**Comment by milosevic** [comment]
There is an explanation in the section III.A (https://arxiv.org/pdf/1807.04938.pdf) that explains the intuition behind termination mechanism and then the proof in the section IV provides more formal treatment. But we should probably extend the report with some of the scenarios you described here so it is even more clear.

**Comment by melekes** [comment]
Moved to https://github.com/tendermint/spec/issues/113. Thanks @ebuchman and @milosevic 👍 

@FanGuoshun let us know if you still have questions. feel free to join [our chat](https://discord.gg/AzefAFd)
