### ISSUE TITLE
Update RPC docs to indicate support for JSONRPC

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#5014]
The current RPC docs give the impression that we don't support JSONRPC, and that the only way to access the RPC is with all those GET requests.

But we actually do support JSONRPC, in addition to the GET requests (what I call URI style). For instance this works just fine:

```
curl --header "Content-Type: application/json" --request POST --data '{"method": "block", "params": ["5"], "id": 1}' localhost:26657
```

Of course you can make the same request in URI style:

```
curl localhost:26657/block?height=5
```

We should update the RPC docs to indicate that all those GET methods are also available via JSONRPC POST requests with the parameters encoded in JSON as expected.

If I'm not mistaken, we are JSONRPC compliant, except for a divergence in the websocket response #2949

**Comment by marbar3778** [comment]
> If I'm not mistaken, we are JSONRPC compliant, except for a divergence in the websocket response 

the json encoding is also not compliant to my knowledge since we dont use "normal" json but a subset of json proto spec.

We should add notes to the openapi docs and add an RPC page instead of having it point to the open API docs. The largest problem with JSON-RPC is that there is no cleanish way to document it. Open API doesn't support RPC connections that is why the examples/"Try it out" show gets (`curl -X GET "https://rpc.cosmos.network/status" -H  "accept: application/json"`)
