### ISSUE TITLE
light: sending conflicting headers

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#5026]
## Summary

This issue attempts to form an overview with a problem relating to submitting conflicting headers by a light client. The history of which was first mentioned here: #4934 and then was also mentioned again by @ebuchman here #5022. I believe that the folks at informal might be covering this also [here](https://github.com/informalsystems/tendermint-rs/pull/287)

## Problem Definition

When a light client performs bisection it checks the resultant header with witness nodes. If there is an instance where the two headers that are provided are different then currently it will check to see if there is at least a third of the votes (commits) from the primary header present in the secondary header (all forks will have at least a 1/3 overlap of malicious validators at their root). The problem with this approach is that (a) we are unsure whether either of the validator sets are correct at that height and (b) if this is a fork and not nodes fooling the light client we don't know how mature (old) this fork is, in which the validator sets could have long since diverged and there be no overlap. 

## Proposal

So far, there have been two approaches outlined

First approach:

When a light client detects conflicting headers it must then begin to query both the primary and witness for headers in descending height until it finds the "common parent header" i.e. where both nodes send headers with the same hash. The header directly thereafter is the "root of the fork" where both headers will still have the same validator set but the commits will have been different and at least 1/3 of these commits would have come from maliciously behaving validators. The light client then broadcasts these headers to primary and witness nodes. 

When a node receives the conflicting headers then it will pull the header and compare the validatorset hashes of the same height. If the node belongs to either of these forks it should match and then begin processing the evidence. If it does not match (maybe because it is following a third fork or because it is an invalid conflictingheaders), then it will ignore it.

The light clients only need search of the common parent header until the last trusted header height. If none is found before then, then it drops the witness and moves on to the next one. (the witness is just messing with the light client).

Note that in terms of implementation, the descension to find the common parent header does not need to be sequential and could also follow a quasi-bisectional process.

Second Approach:

When a conflicting header is discovered the light client must find and send 'traces' which prove the validator set transitions (the same as with bisection) to reach the two different validator sets that the conflicting headers have (no traces need to be sent if the validator sets are the same).  This proves that the validator sets all derive from the same trusted set.

I must admit that I am not too familiar with the second approach and perhaps @melekes can add more details.  

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ebuchman** [comment]
I think it might be enough for the light node to just send the two conflicting headers and for the full node to be able to figure it out from there.

For each header that's different from the one committed by the full node, we check if the validator sets are the same or not.

If the val sets are the same, then it's equivocation or amnesia.

If the val sets are different, then we check if the validators for the given header were active validators within the unbonding period. If so, then its a phantom or lunatic attack. If not there's no one to punish.

I think it might be that simple but we will be fleshing out a better spec for this.





1) if it's signed by a validator

**Comment by cmwaters** [comment]
The situation that I have been thinking of that prompted me to write the issue is when a light client tries to validate a header at a height in which a successful equivocation attack has happened at an earlier height and that two nodes are following different forks. As there might have been several heights inbetween it is possible that in that time the validator sets for both forks have drastically changed such that they are no longer the same. Hence we could be punishing innocent nodes who were split by the fork with phantom validator evidence or lunatic validator evidence hence I think it is important that you find the root of the fork

**Comment by ebuchman** [comment]
> Hence we could be punishing innocent nodes 

How would we be punishing innocent nodes?

In the scenario you describe, once the client confirms it has two conflicting headers, it sends them to a full node, who should be able to run the procedure I described above. 

I may be missing something but it's not clear we need the light client to find the common ancestor. We'll try to formalize this over the coming weeks though.

**Comment by cmwaters** [comment]
I'll try explain my line of thinking and you can point out if I've made a mistake somewhere.

Say we have three validators A, B, C where A is a byzantine validator with greater than 1/3 voting power

At height h = 5, A commits equivocation resulting in a fork
     fork i) { A, B, C}  // C has absent sigs because they didn't know about it
     fork ii) { A, B, C} // B has absent sigs because they didn't know about it

Let's say the partition continues and some validators replace others so that it now looks like this
height = 10
     fork i) { A, B, C}
     fork ii) { A, B, D} 

If a light client were to observe these two conflicting headers and submit to a node that was following fork (i) then the node would see that the validator sets were not the same. It would see that validator D voted when they weren't part of the chain and so create PhantomValidatorEvidence against D (the same would happen to C on the side of fork (ii). 

Also in this case, the validator sets aren't the same so if A voted twice, would we see it (?)

In any case, if byzantine validator A was able to stop voting in one of the sets and eventually remove itself from one of the validator sets then it might avoid being caught for equivocation unless a light client actually stumbles on the height where the fork occurred.

**Comment by ebuchman** [comment]
Right, so I was thinking about the case where there's only a fork for the light client, not amongst the full nodes. The latter is a lot more difficult to reason about because there is no true chain any more, and because if there's a real +1/3 adversary on the chain, they can already censor the evidence, so we'd have to go to out-of-band fork accountability anyways. And in the case of a fork amongst the full nodes, I think we'd expect the full nodes to detect it and try to submit the evidence (ie. is it reasonable to assume that if the full node network is fully partitioned so they can't see the existence of the fork that a light client is going to be better able to cross the partition and see the fork? hard to say ..).

So it seems we need to do a better job of decomposing this problem space to disentangle the various cases and what can/should be done in each. 

That said, you're right, just submitting the 2 conflicting headers is obviously not enough, because it might not include the validator who actually committed the punishable attack. Eg if your scenario was just a light client fork, and A dropped out of the validator set in the fork at height 10 so it was just D, then the conflicting headers would have {A, B, C} on one hand and {D} on the other, and {D} might not even be punishable! This is probably why we originally thought we needed the traces, which should include evidence of the actual fault. 

In the end, it might be nicer to just try to find the common ancestor. But actually this might not be possible, because full nodes serving the fork don't have to respond to all queries, only enough to create a valid bisection trace, so the best we can really do is find the first conflict in the bisection trace. 

Eg suppose the real chain is B1...B100 and B1 is trusted, and we have primary P and witness W. Suppose the primary is serving the real chain and the witness is serving a fake chain with only the blocks {B1, B50', B100'}. Client requests block 100 from P and verifies it without needing to bisect, so it now has {B1, B100} in it's store. It requests block 100 from W which returns B100' which requires bisection, so it requests block 50 from W and gets B50' which verifies without more bisection. So the trace from P is {B1, B100} and from W it's {B1, B50', B100'}. Now it wants to find where they diverged, so it requests block 50 from P which is B50 != B50'. So the divergence is between blocks 1 and 50.  But at this point W can stop answering queries, so the best the client can do is submit the two conflicting headers {B50, B50'}. This is still good enough, just pointing out we can't necessarily find the common header occurring one block before the first conflicting one. 

Note in the case where the client is talking to only forks, and no correct nodes, then we might not even be able to do this, since they could have non-overlapping traces (eg. {B1, B25', B75', B100'} and {B1, B50'', B100''}), but we assume away that case since we expect the client to always be connected to a true full node...

**Comment by ebuchman** [comment]
> In either case the light client should drop them. Hence when tracing back to the common ancestor header, if a node fails to respond any further, we should drop the provider and start again. If it is a witness we then move on to comparing with the next witness. If it is the primary we restart from the trusted header again. However, before doing that it should examine the closest conflicting headers to the source and if there is any overlap in votes then at least we can submit Duplicate and Amnesia evidence.

What I was trying to say is that if you just drop the bad nodes you may never find the common ancestor. And it's not necessarily safe to assume the nodes you dropped were from the bad fork. So rather than looking for common ancestor, I think we're just looking for first conflicting header in a bisection trace. 

> Lastly, you mentioned that in the case of a fork you'd expect the full nodes to detect it. Now I don't have the upmost familiarity with the code base but I believe only duplicate vote evidence is being detected and can be formed by full nodes during consensus, there is nothing detecting amnesia evidence. In addendum, there is no detection in the case of fast sync and state sync which may help if there was a network partition during consensus and therefore nodes weren't made aware of the malicious activity. I think maybe we should look into adding fork accountability in these areas.

Oh definitely.

**Comment by cmwaters** [comment]
| What I was trying to say is that if you just drop the bad nodes you may never find the common ancestor.

Yeah I think it should be a combination of trying to find the common ancestor and if that fails then submit the earliest conflicting header in the bisection trace

**Comment by ebuchman** [comment]
Close for #5083 ?

**Comment by melekes** [comment]
> The light clients only need search of the common parent header until the last trusted header height. If none is found before then, then it drops the witness and moves on to the next one.

I think there's an error in this logic. There might be the case where the witness is correct, but we're so deep into the fork (malicious primary), that we don't find the common parent before the last trusted header.

**Comment by cmwaters** [comment]
> I think there's an error in this logic. There might be the case where the witness is correct, but we're so deep into the fork (malicious primary), that we don't find the common parent before the last trusted header.

This would only happen if we just added the witness else if it is an old witness then it would have already cross verified the last trusted header
