### ISSUE TITLE
light/rpc: implement abci_query

### ISSUE THREAD

**Issue by melekes** [tendermint/tendermint#5106]
Currently, `ABCIQuery` and `ABCIQueryWithOptions` do not work (at least I don't think they do). Also, tests in `light/rpc/query_test.go` are all commented out. We should make the value proof format configurable so it can be checked and revamp the tests.

**Comment by cmwaters** [comment]
Did some burying around the code and realised that `light/proxy/routes.go` provides four arguments when the function only takes two hence the `ABCIQuery` instantly returns an overflow error. I reduced the arguments to just `path` and `data` and it seemed to continue with verification.

There were a couple of other issues: the first was that the kvstore always provides the last height as the height that it derived the query from (and that it returns in the response) but this makes it impossible to verify because the light client needs to verify the height after the last height which doesn't exist in order to compare the hashes.

The second issue, which is more of a problem with me is that I don't understand what the path would be in relation to a kvstore - something about `/store/<store_name>/key` - I'm not exactly sure and therefore I can't test whether the light client can prove the abci query. I do notice that with the full node, having the path isn't necessary so I'm not sure why the light client needs it.

My last observation is that it seems as though `height` and `prove` aren't used for both the light client and the full node. i.e. adding a height as a parameter with the rpc call doesn't mean that that is the height of the block to query (maybe this is also something inherit just with kvstore)

**Comment by marbar3778** [comment]
I do foresee this being a useful feature. Is there anything blocking the implementation?

**Comment by cmwaters** [comment]
Yeah I tried picking this up before but Anton was on holiday then and I didn't really have the full picture. Definitely think that this is something that should be fixed though and would like to get a better understanding of how it works
