### ISSUE TITLE
Inconsistency in the ABCI protobuf file

### ISSUE THREAD

**Issue by ratranqu** [tendermint/tendermint#5129]
While upgrading https://github.com/CosmosSwift/swift-abci to the latest ABCI (0.34. from master ), I came across a double definition of the ConsensusParam in the ABCI proto file: https://github.com/tendermint/tendermint/blob/7c8c356f717ddff0441264d572da5298191e7c74/proto/tendermint/abci/types.proto#L282

and in the 

https://github.com/tendermint/tendermint/blob/7c8c356f717ddff0441264d572da5298191e7c74/proto/tendermint/types/params.proto#L13

(the ABCI references that file here: https://github.com/tendermint/tendermint/blob/7c8c356f717ddff0441264d572da5298191e7c74/proto/tendermint/abci/types.proto#L11)

I believe there are more inconsistencies of the nature with params (as I suspect it might be work in progress) but I have not looked into them.

In the meantime, I am putting on hold the porting to 0.34.

**Comment by marbar3778** [comment]
The reason for having two consensusParams and not the other params is because the Consensus params exposed through the ABCI has one less field than the one used internally. We have looked at exposing this field to the application but were advised against it. We could rename the abci specific consensusParams to `ABCIConsensusParams` if you feel it would lead to better clarity.

**Comment by ratranqu** [comment]
ha ha! yes. indeed. I should have paid more attention. Having different names would definitely make things explicit. That said, I guess you already have the scoping. Thx for you quick response!
