### ISSUE TITLE
A counter example violating `VerifyNonAdjacent` of light client verification.

### ISSUE THREAD

**Issue by egonspace** [tendermint/tendermint#5139]
## Summary
I could think of a case where a block and validator set judged to be valid by `VerifyNonAdjacent` was actually fabricated.

## Problem Definition
Suppose the latest trust block and validators of a light client as following
block: B(h)
validators V(h): (v1, 10), (v2, 10), (v3, 10), (v4, 16) (The number on the right represents the voting power)

And it get a new block B(h1) that it is signed by only v4.(h < h1 < h + trust period)

1. This block B(h1) is valid by basic verification of the block itself.
2. B(h1) is valid by `VerifyCommitTrusting()` because it has been signed by 1/3+ of V(h)
3. B(h1) is valid by `VerifyCommit()` because it has been signed by all of V(h1)

But it is actually fabricated by a byzantine full node just using signature of v4. (v4 might be a byzantine or not in this case)

Theoretically, of course, this light client may later discover that the block is wrong and punish this full node, but it does not seem to be implemented in the light client at present, and it seems too dangerous to rely solely on post-policy.

I think the only time a light client can trust a block is when 1/3+ of the validators that signed the block remain(not slashed or not unbonded) **_after_** the trust period from that point, isn't it?

## Proposal

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by melekes** [comment]
v4 can indeed be malicious

that's why the light is using witnesses (the list of full nodes) to cross-check h1. If any of them report they have a different *h1, then the light client will

a) send evidence that will result in v4 stake slashed (probably 100% of it), then
b) return an error

> I think the only time a light client can trust a block is when 1/3+ of the validators that signed the block remain(not slashed or not unbonded) after the trust period from that point, isn't it?

but we can't wait that long! it's not practical. are u willing to wait for 21 day to confirm your transaction? probably not

**Comment by melekes** [comment]
Have you read [my article](https://medium.com/tendermint/everything-you-need-to-know-about-the-tendermint-light-client-f80d03856f98) of the subject?

**Comment by egonspace** [comment]
Whether more than 1/3 of the trust validators in the skipping verification have verified the new headers does not seem to be an important verification factor. This is because it may not be more than 1/3 of all validators in the new headers, although it was more than 1/3 in the trust block.

I think cross check by witness is just a means of assistance, but cannot be the theoretical basis of the verification of light client. 
So tendermint light client seems to need additional means to verify the validator set for the new headers. For example, a light client can get validator set hash from other full node. Or, I haven't thought deeply, we can think of a way to verify the validator set hash using merkle proof.

**Comment by melekes** [comment]
> For example, a light client can get validator set hash from other full node.

we're doing this currently (when cross-checking header with witnesses, we also request and verify validators)

> we can think of a way to verify the validator set hash using merkle proof.

could you please elaborate on this?

**Comment by cmwaters** [comment]
Just a few thoughts from me (in addition to what anton has said):

> I think cross check by witness is just a means of assistance, but cannot be the theoretical basis of the verification of light client.

In terms of a theoretical basis, tendermint, in a general sense is designed to be immune to a network where up to 1/3 are faulty validators (in terms of voting power of course). The light client is aligned in this respect, as it can not be fooled by less than or equal to 1/3 validators. There is the option, when running a light client, that you don't use 1/3 as the trust level but instead set it for example at 2/3. In this case more than 2/3 of a prior validator set will need to be faulty to fool the light client. 

Verification with witnesses is as you said just an assistance in a way that even a 1/3+ attack on a light client might be caught and result in the cabal being slashed and also as a means of robustness to the light client such that if one provider goes down the light client can query another. 

> I think the only time a light client can trust a block is when 1/3+ of the validators that signed the block remain(not slashed or not unbonded) after the trust period from that point, isn't it?

It could (although really unlikely) happen that a validator behaved incorrectly and wasn't caught for the entire trusting period - although it's designed to be long enough that the validator is. I think the general idea with having it within the trust period, as well as for speed is that validators are still incentivised to behave honestly else they could be slashed.

Hope this answers a few of your questions 😊

**Comment by cmwaters** [comment]
I think I understand what you are trying to say (correct me if I'm wrong). That for example if I was to verify an untrusted header h2 from a trusted header h1 that the validators that signed both these headers could have more than 1/3 voting power in signing the first header, but could have any voting power when it came to signing the h2 header (i.e. less than 1%) and we would still verify it because they exist in some capacity in the untrusted header.

This means whereas full nodes are only susceptible to an attack based on the current validator set power structure of that height, a light client is susceptible to all the validator set power structures from the most current to the last within the trusted period.

All this being said it would be possible to make sure that the validators that signed both headers had all together at least 1/3 voting power in both h1 and h2 and not just in h1 (albeit requiring a bit more computation) but this wasn't something that was part of the original spec. I'm not sure if it makes a difference to the security model because we trust the validator set (that there is at least one honest node in there) and if they voted for the header with the same blockID, regardless of their voting power we therefore trust the new header. Perhaps this might be something that @ebuchman might want to think about.

**Comment by josef-widder** [comment]
Tendermint consensus and the light client is based on the assumption that more than 1/3 of the voting power of V(h) is correct for a trusting period TP, that is in the interval [Time(h), Time(h) + TP]. In the example, this assumptions is broken by v4. This may lead to a fork on the chain, or as in your example, v4 does a fork attack on a light client.

In this scenario v4 may generate a fork on the chain. Therefore even doing sequential verification (with checking +2/3) might lead two clients to follow different branches. To the best of my understanding, the issue is not due to the +1/3 check, but is inherently the problem of fork scenarios.

Whatever fork scenario, the strategy is to detect a fork (within the trusting period), isolate who was misbehaving, and punish the faulty nodes (before they unbond). Therefore the trusting period needs to be smaller than the unbonding period.

**Comment by egonspace** [comment]
I don't think it's desirable to rely heavily on punishment. Wouldn't it be better to verify it as much as possible at that point?
Let's take a more realistic situation as an example.

The latest trust block and validators are same to my first example
block: B(h)
validators V(h): (v1, 10), (v2, 10), (v3, 10), (v4, 16) (The number on the right represents the voting power)

And in h1 (h < h1 < h + trust period), validators are 
(v4, 16), (v5,20), (v6, 25), (v7,30) and v4 is under 1/3 of V(h1) voting power.

V(h1) makes a consensus, but they failed to be consistency in round 0.
Only v4 votes on the block of round 0.
A malicious full node(cannot be punished) has a commit of v4 and block that has failed to reach an agreement at round 0 and responds to requests from light clients.
Of course our good validators will proceed to round 1 and normally agree on other blocks.

The more fundamental question is this. To verify blocks at a specific point in time, a method is needed to verify the entire set of validators at that point **_not depending on prior 1/3+ validators_**.

Maybe there's something I'm missing. I'm afraid I'm taking away your precious time, but I'm working on another project with Tendermint, and I hope there's no loophole in security.

**Comment by josef-widder** [comment]
In your example, when we check a commit, we are not only checking that v4 has signed, but also do basic block validation, which includes that we check whether the commit contains +2/3 voting power of the current validator set V(h1). So in your example, the malicious full node will not fool the light client. 

In Tendermint, fundamentally, to understand what actually is the current validator set, we always rely on prior validators, because the validators for block b decide on the next validators (that is, the validators of block b+1).

**Comment by egonspace** [comment]
> In your example, when we check a commit, we are not only checking that v4 has signed, but also do basic block validation, which includes that we check whether the commit contains +2/3 voting power of the current validator set V(h1). So in your example, the malicious full node will not fool the light client.

That's exactly what I'm pointing out. The light client has no choice but to trust V(h1) as the full node tells it (unless witness is set). I am saying that the light client needs a way to know what the current set of validators is without depending witness as possible.

**Comment by cmwaters** [comment]
As josef said, 2/3 will have needed to sign the block, but you could for example provide a different validator set that has v4 as well as v8 and v9. And this new validator set could all sign to a block and this would all pass the light client verification. You could even change the powers structure and in the next block thereafter (continuing with bisection), remove yourself from the validator set (v8, v9, v10) such that there is no chance that you can get punished. 

I guess the crux of this is that once a validator or cabal in a validator set is greater than a light clients trust level then all bets are off. The light client is at the whim of that validator (unless witnesses catch the malicious validator). In tendermint we offer guarantees that 1/3 faulty validators won't be able to damage the network. In alignment with this we set the lower bound of the light clients trust level to be 1/3. 

If you wanted a more secure light client you could set the trust level to be 2/3. Therefore a validator or cabal would need to have 2/3+ power in the validator set to be able to trick the light client. Any higher level than 2/3 (and one might say to a lesser degree 1/3) than the validator has full control of the network and can trick full nodes which will also end up tricking light clients

**Comment by cmwaters** [comment]
>  I am saying that the light client needs a way to know what the current set of validators is without depending witness as possible.

This is only possible with sequential verification where the hashes of the next validator set are in the previous block and we can use that to verify that the primary has sent us the right validator set. 

Non sequential verification can't do this and must rely on what the primary provider gives us and what our previous validator set was

**Comment by ebuchman** [comment]
Thanks @egonspace for opening this. What you're describing is what we call a "lunatic validator" attack and is a scenario we have been discussing a lot recently. For some more background info, you might want to see our [taxonomy of faults](https://github.com/tendermint/spec/blob/master/spec/consensus/light-client/accountability.md) which is a bit stale now but is the first place we introduced the Lunatic, and also our [formalization of the light client verification problem](https://github.com/informalsystems/tendermint-rs/blob/master/docs/spec/lightclient/verification/verification.md) and our ongoing work on [fork detection](https://github.com/informalsystems/tendermint-rs/tree/master/docs/spec/lightclient/detection) specs. We've also been discussing how to properly detect these attacks in https://github.com/tendermint/tendermint/issues/5083.

As Josef mentioned, the model explicitly assumes that +2/3 validators are correct not just at an instant, but for some duration (the trusting period), and depends on fork detection and punishment to counteract failure of that assumption. This is what lets us define a method for skipping verification, but it also opens up the lunatic attack.

As Josef also mentioned, we need this +2/3 correct-for-some-duration anyways since there are other non-lunatic attacks that can be mounted by +1/3 malicious validators and fool both full nodes and light clients, and we still want to punish them. The ability of +1/3 malicious validators to fork the network is a fundamental limit in tendermint, and the security model of Proof of Stake depends on being able to detect and punish them. 

And as Callum mentioned, the only way to avoid the Lunatic attack is to perform sequential verification, where every header & commit is verified.

This is because in the general Tendermint model, validator sets can change arbitrarily between blocks, so there's no default way to determine who will be in future validator sets without trusting past validators. If you verify headers & commits sequentially, you eliminate the Lunatic attack. However if you want to skip headers, lunatic attacks seem inherent to the model. You can change the model by restricting validator set changes at the app layer, or adding additional overlay protocols to introduce some kind of skip chain data structures where every so often, past validators sign off on future ones to help light clients skip. The former can be controlled by the abci app, the later would require some more complex protocol overlay (potentially could also be implemented by the abci app). Otherwise, as far as we know, you'd need some kind of Zk proof to prove that the current validator set is correct without sequentially verifying every header in between. 

Of course there's also the trust threshold which can be adjusted upwards if the +1/3 guarantee is not sufficient. You can increase it to +2/3 or even higher, but if I'm not mistaken anything less than 100% would still allow the lunatic attack.

I believe at some point we tried to construct an approach where we didn't assume +2/3 was correct for some duration, but only at each instant, and while this still allowed for some skipping, even minor changes to the validator set caused it to quickly collapse to sequential verification.

It's possible there are other parameters that could be added to the light client to restrict how much it will allow the validator set to change between two non-sequential headers being verified, but such parameters may just effectively collapse down to the existing "trust threshold", set by default at +1/3. 

Hope this helps clarify things and happy to hear any other ideas or concerns you have about this!

**Comment by egonspace** [comment]
> We call it "lunatic" because the validator is signing invalid state, ie. in the classic case you're describing, it's signing an invalid validator set
This is the part I missed. Thank you for pointing it out.

I'm glad to know that my questions have already been a part of your discussion. I've already read the documents that you've guided me a little bit, but I'll read them more carefully.

As I read the document, I actually doubt the basic assumptions of the Tendermint Failures Model. If this basic assumption(https://github.com/informalsystems/tendermint-rs/blob/master/docs/spec/lightclient/verification/verification.md#tmbc-fm-2thirds1) should be true, 2/3+ of Validators(h) must follow consensus protocol during the trusting period after time(h) and it means they must **be** validators. Doesn't this include the meaning that the 2/3+ validators should not unbond during the trusting period? But aren't the validators able to withdraw their staking and unbond at any time? If the 2/3+ validators were unbonded and new validators had come during this period, would the validity of this chain not be guaranteed? If only this question is solved, it will help us understand the document.

Thank you for your kind reply.

**Comment by josef-widder** [comment]
Thank you for reviewing the specifications! Any feedback is extremely valuable for us. Let me try to answer your question: The safety of the security model is ensured by the interplay of the following two points:

1. Following the notation of the specification, h.NextValidators fixes the validators for the next block. So you are right in that they are the validators for the next block h+1. However, they may leave the validator set and initiate unbonding as early as h+2. From the time of creation of block h+2 they still have to wait for the unbonding period (e.g., 3 weeks) to expire, before they actually get their stake back (without being validators in future blocks). 

2. [TMBC-FM-2THIRDS.1] states that they must follow the protocols during the trusting period, which is much smaller than the unbonding period. If a node that has been validator (and possibly left the validator set at some point) behaves badly during the trusting period (e.g., contributed to a lunatic attack), the time difference between the trusting period and the unbonding period allows us to detect the misbehavior and punish it before the unbonding period is over, that is, before they would have gotten back their stake. So it is in the interest of (former) validators to not misbehave during the trusting period.

Please let me know if this addresses your concerns!

**Comment by melekes** [comment]
> But aren't the validators able to withdraw their staking and unbond at any time?

If they unbond, their stake will be frozen for the whole duration of the unbonding period.

**Comment by ebuchman** [comment]
> 2/3+ of Validators(h) must follow consensus protocol during the trusting period after time(h) and it means they must be validators

Not quite. The idea is that we can still have assumptions on their behaviour even if they are no longer validators, because they still have something at stake.

**Comment by melekes** [comment]
I think this can be closed now. @egonspace let us know if you have any other questions or concerns. thanks!

**Comment by egonspace** [comment]
Thank you for your kind reply. I found out that the skipping verification was not perfect, and many questions were answered. I'll close this issue. If there is another question, I will post it as a separate issue.
