### ISSUE TITLE
modules define there own interfaces

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5220]
## Summary

Each reactor/modules should define there own expected interfaces

## Problem Definition

Tendermint is built in a modular manner, but throughout the years there was a greater focus on shipping, this has lead to a less modular design.

## Proposal

To aid in fixing the modularity of the system I propose every modules/reactor defining its own interfaces for what it expects. This will lead to a more modular repository and could lead to less direct imports. Some interfaces will be created multiple times, I don't see this as a negative because some modules don't need knowledge of what another reactor has outside of what it expects. 

A negative to this approach that was pointed out by @erikgrinaker  is that this leads to a greater overhead for engineering. Personally I feel the overhead is not large and helps define stable APIs for each module/reactor. 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
After the team call on Monday, I spent some time imagining what a repo would look like with each module defining what they expect, each module defining their own interfaces and a mix of both. 

I am leaning towards a mix of both. Some areas of the codebase it would be simpler to rely on the entire interface instead of a subset defined within the module. There are some areas that defining what it expects may come in handy, for example in consensus. To be able to mock everything it expects would be simpler than relying on an entire interface, adding to this example, consensus may be used on its own for various reasons related to research.

**Comment by cmwaters** [comment]
Another advantage of this that I thought of and just wanted to jot down here is that by defining the interfaces a module needs, it makes it easier to mock the inputs from the other modules and you don't need to construct potentially large data structures. When I think of the evidence module, we have to create an entire block store and state store in order to test whether evidence is verifiable and so on.

**Comment by erikgrinaker** [comment]
There's a fairly compelling reason against this in relation to backwards compatibility: we can't add new methods to public interfaces.

Let's say we have a block store with methods `LoadBlock()` and `Height()`, and that the evidence module only needs `LoadBlock()`, so it creates an interface containing only `LoadBlock()`. If the evidence module later requires `Height()`, it cannot add the `Height()` method to the interface, since this is a breaking change - even though the block store already provides this.

**Comment by marbar3778** [comment]
> There's a fairly compelling reason against this in relation to backwards compatibility: we can't add new methods to public interfaces.
> 
> Let's say we have a block store with methods `LoadBlock()` and `Height()`, and that the evidence module only needs `LoadBlock()`, so it creates an interface containing only `LoadBlock()`. If the evidence module later requires `Height()`, it cannot add the `Height()` method to the interface, since this is a breaking change - even though the block store already provides this.

Hmm, I see what you mean and I raise 1 counter. 😄 

In this case the block store could be a public interface, and the interface of the evidence reactor/module could be housed in the internal directory. In this scenario would we not be able to break the interface because it is an internal API. This is not saying this is the best approach, but food for thought. 

The way I imagine this internal vs external story is each reactor/module defines a public interface of what they provide. And each module has the **option** to explicitly state what they want from these external API in their internal API. Every module doing this is overkill I admit. Looking at the repo I would say this may apply for one if not two modules at most. In short, I don't agree with what Marko said in the original comment.

**Comment by erikgrinaker** [comment]
> the interface of the evidence reactor/module could be housed in the internal directory

But presumably the evidence module would take an input parameter having this interface as a type (e.g. `NewEvidencePool(bs BlockStore)`, so it would have to be public. Otherwise what's the point?

**Comment by marbar3778** [comment]
> NewEvidencePool(bs EvidenceBlockStore)

This could be internal and only used when calling `createEvidenceReactor`. 

> so it would have to be public. Otherwise what's the point?

I don't follow, what is the reason for it to be public? I think evidence is a poor example as I agree with you in that it does not need to define its own interfaces. 

Consensus may be better suited as an example. Consensus could be used on its own outside Tendermint, in this case it would make sense for it to define what it expects.

**Comment by erikgrinaker** [comment]
>I don't follow, what is the reason for it to be public?

Because if `NewEvidencePool()` just takes a regular block store, such that it would always have to be a block store, then why wouldn't we just use that block store internally?

> Consensus could be used on its own outside Tendermint, in this case it would make sense for it to define what it expects.

Yes, but in this case the interface has to be public, and thus can't be changed in any way, so we need to be very careful in designing these.

**Comment by marbar3778** [comment]
> Yes, but in this case the interface has to be public, and thus can't be changed in any way, so we need to be very careful in designing these.

It seems we are in agreement here and can close this issue as it overlaps with ongoing work around the public API of Tendermint
