### ISSUE TITLE
p2p: define switch interface

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5287]
## Summary

Currently, we pass around a concrete type for the switch. This has lead to "cheating", calling other reactors through the switch because it's available: https://github.com/tendermint/tendermint/blob/730e16566edad9792f3311eaa458d6407a54a526/blockchain/v2/io.go#L122-L128. 

To better define boundaries of what modules can do and depend on with peers a clear and concise interface for switch is needed. 

Starting out it could be something as simple as: 

```go
type SwitchI interface {
	Peers() IPeerSet
	StopPeerForError(Peer, interface{})
	MarkPeerAsGood(Peer)
	Broadcast(byte, []byte) chan bool
	StopPeerGracefully(Peer)
	IsPeerPersistent(*NetAddress) bool
	DialPeerWithAddress(*NetAddress) error
}
```

To make this happen changes need to be made to all blockchain reactors as they abuse the switch in the most direct way.

This can be considered a precursor to: 

https://github.com/tendermint/tendermint/issues/3719
https://github.com/tendermint/tendermint/issues/3679

____

#### For Admin Use

- [ ] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by erikgrinaker** [comment]
I'm not convinced we should make the switch an interface. We should have interfaces e.g. for the underlying transport (so we can mock it and test it), but I don't really see the need to use an interface for the switch itself. If the only purpose is information hiding, then this is already possible via private fields and methods. The example above is possible because `Reactor()` is a public method - if we made `Switch` an interface but kept `Reactor()` public then it wouldn't change anything, and we don't need to make `Switch` an interface to change the method to a private `reactor()` method.

Interfaces also have the drawback that any change is a breaking change, while with structs its at least possible to add methods without breaking anything. For this reason, structs are generally preferred over interfaces unless there's a clear need for multiple implementations.

**Comment by marbar3778** [comment]
Yes, the idea was to hide things to avoid abuse and mock the switch for easier testing. You are right that this could be done without an interface.
