### ISSUE TITLE
Websocket not delivering all transactions

### ISSUE THREAD

**Issue by jackzampolin** [tendermint/tendermint#5367]
On the [relayer](https://github.com/ovrclk/relayer) we subscribe to transaction and block events from tendermint and take action based on those events. Currently I'm not seeing transaction events come out of the websocket. I've tried different indexing settings, but that doesn't seem to be the issue. If you would like to test out the issue go to the relayer and run:

```
./scripts/two-chainz
./scripts/config-relayer
rly dev listen ibc0 --no-block
# in another terminal
rly tx link demo -d -o 3s
rly tx transfer ibc0 ibc1 100000samoleans $(rly ch addr ibc1)
```

This should output a number of events as the transactions run but for some reason only some txs are emited.

**Comment by marbar3778** [comment]
I tested this out with the kvstore application. I was not able to reproduce your issue. 

The process I followed was:

terminal 1:
```
tendermint init

tendermint node --proxy_app=kvstore
```

terminal 2: 
```
ws ws://localhost:26657/websocket

> { "jsonrpc": "2.0", "method": "subscribe", "params": ["tm.event='Tx'"], "id": 1 }
```

In terminal 3 I ran [tm-load-test](https://github.com/informalsystems/tm-load-test) and got the txs that were to be indexed.

**Comment by thanethomson** [comment]
Is it possible that this could be due to how events are currently not clearly delineated in the WebSocket RPC response [here](https://github.com/tendermint/tendermint/blob/ed046966bdcf275e6d2b8b8a406940cf07c67a35/rpc/jsonrpc/server/ws_handler.go#L441)?

i.e. the WebSocket RPC server is batching events together (separated by a single newline) in a single WebSocket text message response, as opposed to each event being contained within its own text message.

If this is not intended behaviour I'd be happy to submit a PR to fix it.

**Comment by jackzampolin** [comment]
Can someone try out the repro case I've posted?

**Comment by melekes** [comment]
This should be fixed by https://github.com/tendermint/tendermint/commit/309e29c245a01825fc9630103311fd04de99fa5e @jackzampolin

**Comment by jackzampolin** [comment]
It is. Thank you for the great work y'all!
