### ISSUE TITLE
p2p/conn: secret connection incompatibilities between protobuf and amino formats

### ISSUE THREAD

**Issue by tarcieri** [tendermint/tendermint#5545]
In testing TMKMS against the `stargate-4` branch of gaiad (Tendermint v0.34.0), it seems the secret connection framing is slightly different from how it used to be.

The key exchange messages used to be the following with Amino encoding:

```
[0x21, 0x20, <32 byte X25519 public key>]
```

They are now the following Protobuf encoding (this seems to correspond to double length prefixing a bytes value):

```
[0x22, 0x0a, 0x20, <32 byte X25519 public key>]
```
 
The framing of the subsequent encrypted messages seems changed as well, although I don't have specifics there. Modifying the Secret Connection implementation in TMKMS to use the leading `[0x22, 0x0a, 0x20...` prefix at least gets it farther through the handshake.

We can support a different framing in TMKMS, and it might make sense (it seems things are currently somewhat questionably double-prefixed and if that can be changed, it should probably be removed), but it'd definitely be good to nail down whether we need to add support for a new framing to TMKMS or not ASAP as we're trying to cut another release and would like for it to be Stargate-compatible.

**Comment by erikgrinaker** [comment]
The encoding happens like this:

https://github.com/tendermint/tendermint/blob/9e98c74e3c00962a02732da3486b6f4d84ae5aaf/p2p/conn/secret_connection.go#L308

I think Amino, which we used before, could write bare encoded values to a stream, while Protobuf requires values to be wrapped in a message. The additional byte is the Protobuf field tag for the `Value` field in the `gogoproto.BytesValue` message, i.e. for `[0x22, 0x0a, 0x20, <32 byte X25519 public key>]`:

* `0x22`: is `34` in decimal, the length-prefix for the `gogoproto.BytesValue` message
* `0x0a`: is the Protobuf tag for key `1` wire type `2`, i.e. length-prefixed bytes (as `0b00001010` where 5 bits are key and 3 bits are wire type)
* `0x20`: is `32` in decimal, the length-prefix for the `Value` field

Since we now use Protobuf for all secret connection messages, I suggest we keep using this encoding. To decode, use a message of this type:

```
message BytesValue {
  bytes value = 1;
}
```

Then simply use a Protobuf stream reader with length-prefixed framing to read the message and extract the key from the `value` field.

**Comment by tarcieri** [comment]
FYI: WIP PR to add support for the new Protobuf-based format here: https://github.com/iqlusioninc/tmkms/pull/192
