### ISSUE TITLE
Merge protobuf types.Validator with tendermint types.GenesisValidator

### ISSUE THREAD

**Issue by greg-szabo** [tendermint/tendermint#5549]
## Summary
Since Validators are so well defined using protobuf now, can we make the `GenesisValidator` struct (used to read genesis.json) and the `Validator` defined in protobuf the same?

## Problem Definition
I'm trying to use the protobuf definitions everywhere possible (even when I'm not encoding/decoding protobuf). Duplicating structs for slight differences seem counterintuitive, hence the request.

## Proposal
It would require the protobuf type to be expanded with an optional `name` field. (And the genesisvalidator struct to be removed.)

I'm not sure if it blows up any protobuf encoding anywhere, so I need someone to validate if this is a good idea or not.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by greg-szabo** [comment]
Additionally, if this is not a good idea: would it be possible to rename the json encoding of tendermint.types.GenesisValidator.power to `voting_power`? That's how it's defined in protobuf so I can still salvage some stuff and reuse the struct.

**Comment by erikgrinaker** [comment]
I agree that we should try to use common JSON representations. However, I don't think using Protobuf for all encoding really makes sense. For example, in this case we're decoding the genesis file, which has no Protobuf analog - it's only represented as JSON and as canonical domain types. Why would we involve Protobuf here?

Similarly, in the RPC layer there's lots of requests and responses that are only represented as JSON and Go types. I don't think there's any reason to involve Protobuf here just to do the JSON encoding, which would involve now having three representations of them (Go domain types, Go Protobuf types, JSON).

The reason I bring this up is that we had this discussion internally in the Go team this summer, and I'd be interested to get the Rust team's take on it.

**Comment by greg-szabo** [comment]
Adding @thanethomson  here, he's got some great ideas around this.

On the Rust side we are discussing having three set of structs:
1. domain structs that are Rust friendly and represent architectural logic. These have built-in, high-level validation when converting from any other types. The assumption is that domain data _is valid_.
1. protobuf structs that come from the ecosystem. These are automatically generated from the protobuf messages and they represent connection to outside of Rust. Domain types have conversion mechanisms with simple rules: domain -> protobuf is infallible, while protobuf -> domain uses strict checks to make a valid struct (and can fail).
1. we are experimenting with separating the JSON encoding from our domain types. Serde, the Rust JSON encoder/decoder has a versatile way of annotating structs but we can either choose annotating each field one-by-one OR use a conversion method that applies all the validation too. Currently, a lot of domain structs have field attributes for serde which completely breaks the rule that domain types are valid. (A syntactically valid JSON struct can still be logically invalid and it directly converts into a domain type, which is bad.) In some cases, we can get away from the field attributes and tell `serde` to convert through an interim type (which also helps with the differences in JSON-encoding and our domain types). We use (abuse) some of the protobuf structs for this interim type, which allows us to have the validation done by serde too. (Serde decodes into the interim type and then does a protobuf->domain conversion which has the inherent validation.)

For example: the `/blockchain` endpoint has a `block_metas` field that is already defined in protobuf as `types.BlockMeta`. All the dependent fields under it are already scrutinized by our code because of the implemented domain structs and protobuf conversion checks. All I have to do is tell `serde` to use our domain `block::Meta` type for serialization/deserialization, using protobuf's `types.BlockMeta` as the interim struct.
The same is true for the `priv_validator.json` file: it can be generated from our `priv_validator_key::PrivValidatorKey` struct which is essentially the domain knowledge of the protobuf `crypto::PublicKey` type (and the not defined `crypto::PrivateKey` type, but we have a domain type for that). The genesis file is not different: `types::Validator`, `abci::ConsensusParams` definitely show up in it.

So, right now I'm trying to separate JSON-encoding to touch as few domain types as possible and possibly only touch them through these interim types. Most probably this will not be feasible completely and we will need to look into the swagger definitions of the JSON types. Which gets us to a similar situation as with the protobuf types. Most probably we will end up auto-generating the JSON types from the swagger definitions (are those up-to-date?) and create a conversion to our domain types.

For me, the protobuf structs are not much more than regular structs. The additional option of protobuf-encoding is a nice-to-have, but the main reason I'm in love with them is that they are auto-generated and define cross-platform data presentation. Most probably the swagger definitions can do the same for me in JSON, but since we already have definitions for a bunch of these, I'm using them to their full extent. :)

**Comment by thanethomson** [comment]
Yes, to add to what @greg-szabo said, ultimately what we're looking at is a way of separating two sets of concerns:

1. Serialization/deserialization-related concerns (i.e. can we read/write the data structures from/to Protobuf/JSON/etc.?)
2. Correctness/validation-related concerns (i.e. can I trust the data structure I'm using in my code to be *correct*?)

Right now we're trying to disentangle these concerns in tendermint.rs, because we've been using our "domain types" (2) to facilitate JSON de/serialization. @greg-szabo's got a way of mostly auto-generating the JSON de/serialization types from the Protobuf definitions, which cuts down on the number of data structures we need to manage on the Rust side.

Protobuf doesn't seem like the perfect format for sharing *all* data structures between Tendermint and tendermint.rs, but we're not totally sure right now if there's a better way that's as simple.

What'd be **really** amazing is if there were some way to specify common data structures and validation-related constraints such that we could automatically generate the serialization-related mechanisms **and** the validation in Go and Rust (and possibly other languages where the Tendermint protocol's implemented). Perhaps there is something out there that can do that for us? I'm not personally aware of anything at the moment.

We can discuss further on one of the next calls?

**Comment by erikgrinaker** [comment]
Thanks guys, would love to discuss further on a call.

My initial thought is that it might make sense to use intermediate types for e.g. JSON serialization/deserialization too (as well as e.g. TOML and other data formats). Sometimes, these types might only be used in a single place. One typical example is in a `POST` REST request that creates a new resource - often it's not desirable to allow all fields to be set explicitly by the user (e.g. a timestamp that should be autogenerated), so one would use an intermediate struct that validates specifically what should be allowed for the POST request, and generates/derives the rest of the values for the final domain struct.

I feel like it makes sense to separate these intermediate structs for each format and/or use-case as necessary, rather than conflating them with each other which can have unintended side-effects and make them difficult to reason about.

Another side-effect of going via Protobuf for JSON is that it ties us to using Protobuf's JSON format (specifically, 64-bit numbers as strings), which I'm not really a huge fan of.

Just some thoughts, let's discuss further on a call.
