### ISSUE TITLE
separate config files and data by creating 2 subfolders (config, data)

### ISSUE THREAD

**Issue by antoineherzog** [tendermint/tendermint#556]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

FEATURE REQUEST
We want to run tendermint on Amazon EC2 and S3.
Could you create a subfolder .tendermint/config where we have all configs files.

We would like to specify the location for each subfolder.

So we can do something like that
.tendermint/data ==> located on the EC2 instance
.tendermint/config ==> located on a S3 Bucket

BENEFITS

We could shut-down our EC2 instance but still keep alive all the configuration files. This way we could turn-on again later the validator without loosing the pub_key, genesis file etc ..

**Comment by antoineherzog** [comment]
@adrianbrink tagged here

**Comment by melekes** [comment]
We discussed it with Bucky and Greg before. Prehistory: it was done mainly for convenience (easy to operate on one dir than two). But we agree that state and configs must be separated.

**Comment by antoineherzog** [comment]
@melekes any ETA on this? or at least could we pass the priv_key file path in the tendermint cli?

**Comment by ethanfrey** [comment]
You can kind of do something already.  Take a good look at our config parser (file structure): https://github.com/tendermint/tendermint/blob/master/config/config.go

`TMHOME=/path/mounted/to/s3 tendermint node`

config.toml:

```
db_dir=/some/local/path

[mempool]
wal_dir=/some/other/local/path
```

If these directories don't start with `/`, they are relative to `TMHOME` (`--home`).  If they are absolute paths, they will ignore TMHOME.

I don't know if there is other data you don't want to write?  And also if it is possible to mount an s3 directory to the filesystem (since we just use `fopen` to open the config and data files).

Please let me know if this helps and what is missing.

**Comment by zramsay** [comment]
closing as stale/resolved

**Comment by melekes** [comment]
I still think there are things to do here. We could create 2 dirs: `~/.tendermint/config` and `~/.tendermint/data`, where the former consists of `config.toml` and `genesis.json` and the latter - WAL, DB files and `priv_validator.json`.

**Comment by antoineherzog** [comment]
i agree. two folders make sense.

**Comment by zramsay** [comment]
cool. I'll pick this up

**Comment by antoineherzog** [comment]
cool!

**Comment by zramsay** [comment]
see #709. Feel free to try that branch

**Comment by antoineherzog** [comment]
sure

**Comment by zramsay** [comment]
consolidated in #628

**Comment by zramsay** [comment]
merged on develop
