### ISSUE TITLE
nginx for rpc configuration

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#5704]
## Summary

We recommend using nginx in front of the RPC, for some users this is simple but for others they have not heard of nginx.

## Proposal

Provide a nginx template that users can use for their RPC. This template should be a general one that covers some basics. 

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by liamsi** [comment]
While at it, wouldn't it make sense to have a similar config for general TCP/udp streams? This could be a simple alternative to the sentry infra. Although it is by far not as defensive, it would much simpler than the sentry infra if I'm not mistaken. Parity went down the route of deprecating sentries completely in favour of this approach AFAIK: https://github.com/paritytech/substrate/issues/6845

**Comment by alexanderbez** [comment]
@marbar3778 could you mention why one would want a proxy in front of their RPC nodes please? e.g. rate limiting, route allow/deny lists, etc...

> wouldn't it make sense to have a similar config for general TCP/udp streams?

What does this mean @liamsi? What are TCP configs?

**Comment by liamsi** [comment]
> What does this mean @liamsi? What are TCP configs?

https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/

My relatively basic understanding here is that instead of putting several sentries in front of the validator, you'd basically put a reverse proxy in front of the validator for load balancing. [This](https://github.com/w3f/polkadot-validator-setup#structure) has a tiny bit more info. But as mentioned, this is very different fromm the sentry infrastructure most validators run today and I do not have much experience with how (or if) this runs well in production. I'm sure Marko (and actual node operators) would know more here.

**Comment by alexanderbez** [comment]
Ah yes, the only problem with a LB is that if you have multiple nodes behind the LB, client's can get conflicting views of data (e.g. if one or more nodes is lagging behind). This is analogous to not reading your writes. I wonder if nginx can handle this somehow?

**Comment by daniel-farina** [comment]
Following up on this conversation. Could we get some examples of the correct Nginx configuration for WSS? I was able to configure the API endpoints via a reverse proxy with Nginx but WSS seems a bit more challenging. 


Thank you
