### ISSUE TITLE
unsafe_reset_all should reset genesis?

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/tendermint#571]
noticed that old genesis files remain under the reset all within basecoin - sometimes we might want to re `init` with a different rich genesis key - Does this make sense or should it only be changed within basecoin? It seems silly to have to `rm -rf ~/.basecoin` for the genesis file

**Comment by adrianbrink** [comment]
I don't think that `unsafe_reset_all` should remove the genesis file, since we rely on it in the devops scripts to start a new chain with the same config.

I think if you want to reset the genesis you have to manually delete it, since you will have to copy a new one into the folder manually anyway.

**Comment by Greg-Szabo** [comment]
Adrian is right, I'm relying on unsafe_reset_all not removing the genesis file. I had a hard time understanding the logic and the relations among genesis.json/config.toml/priv_validator.json. Here are the current pieces I'm aware of:
1. `tendermint init` generates the priv_validator.json and that's its primary role.
Secondly it's generating an _example_ genesis.json, that assumes that the node is a validator node. Since the genesis.json (with public keys of validator nodes) is probably coming from the owners of a network, this is more of an example than anything and it should not be taken too seriously. 
As an afterthought it also creates a default config.toml that hooks onto all IP addresses on the default ports and can be overwritten on the command-line. As an example this is fine but for a network, the seeds part will be definitely overwritten and usually the IP addresses will be corrected too on the command-line or in the file. It is only valuable as-is if it is used as an example.
2. `tendermint gen_validator` will only generate the priv_validator.json content and print it to the screen. Together with `tendermint show_validator` it can be used to imitate the `init` command.
3. `tendermint unsafe_reset_all` will not touch the genesis.json or the config.toml file. It will remove the data folder and reset all counters in the priv_validator.json. It is considered unsafe because it destroys the database but it does not destroy the configuration. `unsafe_reset_priv_validator` will not remove the data folder, only reset counters. (I'm not sure in what scenario this is useful.)

So based on these findings it seems that tendermint only manages the `priv_validator.json` and gives examples to everything else. It makes sense to not remove the private key with any tendermint commands. If the file is removed, it can be easily regenerated.
The management of genesis.json and config.toml shouldn't come directly from tendermint. The file will change because of outside circumstances and they're telling tendermint how to behave. If tendermint is trying to manage it (tell it how tendermint will behave), we're risking overwriting user changes which we expect to have. I think it's a better bet to make the user remove their own files and manage our own only.
BTW I would change the gen_validator to write into the `$homedir/priv_validator.json` file instead of the standard out, but it's just my opinion that this would make it look more standard.

**Comment by rigelrozanski** [comment]
Hmmm okay sounds like there is consensus against this, I think it makes sense to have an alternative tool specifically for development testing functionality doesn't need to built into the CLI - will add on externally to basecoin if Frey in agreement. thanks
