### ISSUE TITLE
handle corrupt wal file

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#573]
node should still be able to start if arbitrary bytes have been truncated from end of file.

 we should add a checksum and line length to each entry to help detect corruption

**Comment by aphyr** [comment]
To elaborate somewhat: we've discussed three theoretical issues in Tendermint's write-ahead-log. 

1. First, WAL entries are not checksummed, which potentially allows bit-flips or truncation to go undetected in WAL records.
2. The second issue is that we're not sure whether WAL writes are fsynced before being acknowledged to the client, which might, in theory, allow committed operations to be rolled back.
3. The third problem is that depending on the filesystem, a write of a log entry may not be appended atomically. If the node crashes prior to an fsync, some sequence of bytes might be left in the WAL which are not recoverable.

Exploratory testing with process crashes has failed to produce WAL safety issues, but I haven't yet tested WAL truncation, node power failure or filesystem-level snapshots. It might be worth testing with those failure modes to see what happens.

One simple approach to writing recoverable WALs is to write a fixed-size checksum, fixed-size length header, then variable-length record. Errors can be detected whenever a record fails its checksum, or not enough bytes are present in the file to complete a read. For more advanced WAL formats, you might consider taking a look at the [SQLite](https://www.sqlite.org/fileformat.html#wal_file_format) WAL format, which incorporates checkpoints.

**Comment by aphyr** [comment]
To follow up: the `truncate-tendermint` nemesis now lets us test the effects of arbitrary truncation of the tendermint WAL file; Tendermint silently ignores corrupt entries at the end of the file.

However, we *are* now relatively certain that Tendermint can lose acknowledged writes due to the lack of any fsync call on the write-ahead log. Saving an entry to the WAL calls writeLine to append data to the autofile group backing the WAL, then calls [group.Flush()](https://github.com/tendermint/tendermint/blob/01e008cedd7f6cdee31ae5f1463a9f6bbb233fd3/consensus/wal.go#L92) to flush that data to persistent storage. group.Flush() in turn [proxies](https://github.com/tendermint/tmlibs/blob/7ce4da1eee6004d627e780c8fe91e96d9b99e459/autofile/group.go#L156) to headBuf.flush(), flushing the active [bufio.BufferedWriter](https://golang.org/pkg/bufio/#Writer.Flush). However, BufferedWriter wraps a Writer, not another BufferedWriter, and the way it flushes is by calling io.Writer.Write() to clear the BufferedWriter's buffer.

The io.Writer we're wrapping here is [AutoFile](https://github.com/tendermint/tmlibs/blob/7ce4da1eee6004d627e780c8fe91e96d9b99e459/autofile/autofile.go#L88), whose Write method calls os.File.Write(), performing an unbuffered write to the operating system, where, I assume, it sits in the OS buffers awaiting sync. This means that Wal.Save does *not*, in fact, ensure the saved operation is synced to disk before returning.

There *is* a [Sync](https://github.com/tendermint/tmlibs/blob/7ce4da1eee6004d627e780c8fe91e96d9b99e459/autofile/autofile.go#L102-L107) function for AutoFile, but it's not invoked. I think all that has to be done here is call `head.Sync()` after headBuf.Flush call in Group.Flush.

Eventually, you'll want to have a thread that periodically syncs the file every n milliseconds or n writes, and have WAL writes be asynchronous, completing whenever the flushing thread has written them to disk. That way you can batch multiple WAL writes into a single fsync call.

**Comment by ebuchman** [comment]
Thanks Kyle.

Note we do periodically close the autofile and reopen it on the next write, ie.

https://github.com/tendermint/tmlibs/blob/master/autofile/autofile.go#L72

and 

https://github.com/tendermint/tmlibs/blob/master/autofile/autofile.go#L93

Currently happens every second.

**Comment by aphyr** [comment]
Note that close (2) does not call fsync; closed files may not be persisted to disk.

**Comment by melekes** [comment]
4B checksum (uint32) and 4B (uint32) length should be enough

|---------------------- | ----------------------- | ---- |
| crc checksum of data | length of data in bytes | data |
|---------------------- | ----------------------- | ---- |

**Comment by melekes** [comment]
From https://www.postgresql.org/docs/9.5/static/runtime-config-wal.html: 

```
Method used for forcing WAL updates out to disk. If fsync is off then this setting is irrelevant, since WAL file updates will not be forced out at all. Possible values are:

open_datasync (write WAL files with open() option O_DSYNC)

fdatasync (call fdatasync() at each commit)

fsync (call fsync() at each commit)

fsync_writethrough (call fsync() at each commit, forcing write-through of any disk write cache)

open_sync (write WAL files with open() option O_SYNC)

The open_* options also use O_DIRECT if available. Not all of these choices are available on all platforms. The default is the first method in the above list that is supported by the platform, except that fdatasync is the default on Linux. The default is not necessarily ideal; it might be necessary to change this setting or other aspects of your system configuration in order to create a crash-safe configuration or achieve optimal performance. These aspects are discussed in Section 29.1. This parameter can only be set in the postgresql.conf file or on the server command line
```

**Comment by melekes** [comment]
1. https://github.com/tendermint/tendermint/pull/672
2. https://github.com/tendermint/tmlibs/pull/52
3. should be fixed by (1)

**Comment by ebuchman** [comment]
If the WAL is corrupted, we now detect it, but just abort. There are a few cases:

- the corruption is in an older height. in this case, we don't care, because we only replay messages from the current height, so we can just note the error and move on.
- the corruption is in the latest message. in this case, we note the error, and just start the consensus state. hopefully we're fine.
- the corruption is not in the latest message, but is in a message in the latest height. in this case, we note the error, and continue trying to replay subsequent messages - we may have an issue since we will have missed a message, but it's probably better to play the additional messages than to just skip them and start the consensus.

@aphyr does that sound right to you ? how do we test this stuff?

**Comment by milosevic** [comment]
We shouldn't forget to spec this part also.

**Comment by aphyr** [comment]
It sounds like no matter what happens to the WAL, you plan to continue operating? That... doesn't sound particularly safe to me. I think that if you are ever in a situation where you may have lost information, you should abort with a prominent error, rather than start--users are *not* going to read the logs. Give them a special command to clean up the WAL as best you can, like `--recover-as-much-as-possible`.

**Comment by zramsay** [comment]
#965

**Comment by aphyr** [comment]
Just skimming the comments here, I think it might be worth carefully considering whether it is possible to recover a subsequent log entry when a prior length header has been corrupted. A separator sounds like a nice idea, but without careful forethought, other data in the WAL (user payloads, for example) might contain the same byte sequence as a separator and give rise to interesting results. :)

**Comment by ebuchman** [comment]
Yeh we've been thinking through this. I think for now our solution is to fail if corruption is detected as suggested, and point the user to corruption docs: https://github.com/tendermint/tendermint/blob/develop/docs/specification/corruption.rst#wal-corruption

They can then try to repair manually, or just delete all lines from the corrupted one on and try to resync.
