### ISSUE TITLE
Introduce entropy into Tendermint

### ISSUE THREAD

**Issue by KrzysiekJ** [tendermint/tendermint#574]
Entropy (i.e. random, unpredictable bits) may sometimes be desirable in blockchain applications. For example, in decentralized proof of stake currencies, one may want to allow every stakeholder to participate in securing the blockchain. However, due to efficiency reasons, not every stakeholder can be a validator. Therefore validators need to be drawn from a set of willing stakeholders. To perform the drawing, entropy bits need to be used.

Obtaining entropy on a local machine is easy; one can just use a random number generator provided by an operating system. This won’t work in a distributed environment, where it is not trivial to obtain entropy bits in a way that is not subject to manipulation. Usage of deterministic signatures has been proposed in [Algorand](https://arxiv.org/abs/1607.01341), however a signatory can always choose to not submit his signature at all; therefore he has at least two options.

[Publicly verifiable secret sharing](http://www.win.tue.nl/~berry/papers/crypto99.pdf) can be used to solve this problem (this is an approach taken in the [Ouroboros protocol](https://eprint.iacr.org/2016/889)), but performing the procedure for every block would create a bloat, especially in Tendermint, where block duration is only 1 second. Therefore blocks would need to be divided into epochs (probably with parameterized length) for the purpose of entropy generation, and new entropy bits would be submitted to ABCI applications only once in a while. Does this approach sound reasonable and have a chance of being implemented in Tendermint?

**Comment by KrzysiekJ** [comment]
A simpler (on the Tendermint side) and more flexible variant would be to let applications handle entropy generation by themselves, add entropy bits to `ResponseEndBlock` and just make Tendermint use them, if provided, for choosing slot leaders (instead of the round-robin algorithm).

**Comment by AFDudley** [comment]
I think threshold signatures are closer to production and integration into
Tindermint than the two solutions suggested.

**Comment by ValarDragon** [comment]
Closing this issue for now. This decision will require a much more thought out proposal / summary of the 3 main methods and the various benefits they would bring the protocol, and various drawbacks. The crypto community as a whole is putting a great deal of thought into this problem, so we can draw from that as well.

To briefly summarize, the 3 approaches are VRFs, VDFs, and a BLS DKG. (At the point where we consider a VSS scheme, we should probably just go with the BLS DKG, since that has other useful properties as well) 

VRF's for consensus will require significant analysis to how they affect our security assumptions, due to signature withholding as you mentioned. VDF's don't hide the next proposer, but are terrific for  randomness, and could safely be used to randomize proposer selection if we don't care about hiding the next `n` blocks. Chia has done a lot of work on this, and I really like their approach. The BLS style DKG is also extremely promising, though it comes at a scalability hit. Additionally a fault attributable DKG algorithm must be engineered (unless it already exists). We also need need to solve weightings for different validators efficiently.
