### ISSUE TITLE
RPC endpoint to report sync status

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/tendermint#577]
An ABCI app might want to display whether it is syncing or caught up. 

We should have an RPC endpoint that returns whether we are currently in fast-sync (syncing) or consensus (not-syncing).

**Comment by srmo** [comment]
Good idea. At the moment, we query the state each second and say that we are syncing when our height < network/neighbor height. A dedicated endpoint would be really great. Might also report enhanced info on the network. For example, a detached node can only be detected indirectly due to abci not producing blocks. A dedicated state-info would be much cleaner.

**Comment by ebuchman** [comment]
This has been merged https://github.com/tendermint/tendermint/pull/579/files
