### ISSUE TITLE
v0.33 linting

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#5775]
We will be supporting v0.33 till the next major release (0.35). We should bump golangci-lint version to the latest version to fix ci failures. In doing so many linting errors will arise, these should be cleaned up in the same PR. 

This is an easy first contribution to Tendermint, if you are looking to get your hands dirty :)

**Comment by tessr** [comment]
Somewhat more context: 

We're using an old version of golangci-lint (1.12, I think) that also relies on older features in Github Actions. Those Actions features have been deprecated, so the golangci-lint job on the `0.33.x` and `0.32.x` are currently failing. But if we update the golangci-lint version, we'll also need to make code changes to adhere to the new linting rules. This issue is a ticket for that work.

**Comment by tessr** [comment]
Actually, on second thought, why not just turn off the linters for the backport branches? We should only be applying changes that have already passed linting on master.

**Comment by marbar3778** [comment]
yea, that makes sense to me.

**Comment by erikgrinaker** [comment]
>Actually, on second thought, why not just turn off the linters for the backport branches? We should only be applying changes that have already passed linting on master.

Changes on maintenance branches may not be all backports. For example, after we refactor P2P, if someone discovers a bug in the 0.33 P2P stack there will have to be a fix committed directly on the 0.33 branch, because `master` has a completely different P2P stack that may not even have the bug. In these cases, linting is still helpful.

**Comment by tessr** [comment]
Ah, good point!

**Comment by salman-bhai** [comment]
Hi not sure if someone is working on this. Can I maybe pick this up. Looking to learn and contribute here.

**Comment by cmwaters** [comment]
Hey @salman-bhai. Yup you can pick this up. No one is working on it at the moment. Let me know if you need a hand with anything.

**Comment by cmwaters** [comment]
Hey @salman-bhai, we want to get this fixed now so we can backport some fixes to the 0.33 branch. I hope you don't mind me taking over this. Feel free to jump on another issue marked as `good first issue` if you're still interested in contributing.

**Comment by salman-bhai** [comment]
Hi @cmwaters totally understand. Please go ahead. Have been caught up in other commitments unfortunately couldn't help on this. Thanks again for letting me know.
