### ISSUE TITLE
Validator stopped proposing blocks after migrating to new node

### ISSUE THREAD

**Issue by anilCSE** [tendermint/tendermint#5804]
I am not 100% sure if this is a bug but wanted to check if its purely node/operator issue.

We have an observation from [bigbang testnet](https://bigbang.aneka.io). The network was on highload with number of spam txs yesterday.
- One of the validators we manage has 42% of the total votingpower. We were using all the sentries of this validator for spamming
- The validator went down due to heavy load (there were more than 10000txs in the mempool) and CPU usage was >90% (avg load on 4 cores)
- The network stopped producing blocks because our validator was down. When we restarted the node, it was showing following error logs (same, continuous logs):
```
E[2020-12-15|12:41:19.872] Error signing vote                           module=consensus height=259115 round=0 vote="Vote{0:E6C9F1852DD3 259115/00/SIGNED_MSG_TYPE_PREVOTE(Prevote) 947699A061D1 000000000000 @ 2020-12-15T12:41:19.872729634Z}" err="error signing vote: round regression at height 259115. Got 0, last round 3"
E[2020-12-15|12:41:19.877] Error signing vote  
```
- The network was just waiting for the vote from our validator, but our node was showing the same error and looked like there's some issue with gossiping this vote to the proposer.
- We queried our state to cross check the vote, we had this
```
{
  "height": "259115",
  "round": 3,
  "step": 3,
  "signature": "O9CYh2BuJa6nZyGO8aKoPllxspuf5OcpafXE8jTL8LgHk7zgemm1tbpEzyBYlbuYjjH9KQmV9sDJACPQkvmsBA==",
  "signbytes": "2C0802112BF40300000000001903000000000000002A0B08EFDBE2FE0510C3CDA963320962696762616E672D32"
}
```
- Node was active, cross checked the firewalls, all seemed to fine
- As a last option, we moved the validator keys and private validator state onto one of the sentries. Started the node risking double sign. Surprisingly, the validator sent the vote and network started producing blocks. (1)
- It's signing all the blocks from other proposers but It is not producing any blocks (even now). We asked a few other validators to increase their inbound limit, but still no luck.

1) I would like to understand if there's any potential issue or could it be just the node/operator issue?
2) One of the other issues we faced was with addressbook. If it is filled with dead peers, the node is not accepting new peers due to max inbond/outbound limit. It's just sitting there. May be there should be a way to manage addressbook as `active-peers`, `inactive-peers` and these limits should apply only for active-peers?

**Comment by cmwaters** [comment]
Thanks for submitting the issue. Looking at what you described here, I would say that what most likely happened is that the validator reached round 3 (because the validator was slowing down under the load and wasn't able to send out votes in time). The KMS, which tries to prevent double signing, saved this round when the validator asked it to sign the vote. You then restarted the node which somehow reset the round to 0. This meant the KMS store refused to sign any of the votes and thus caused the network to halt.

I am not too familiar with this but I would think that the write-ahead log should have saved this round information so perhaps something went wrong there (I am not too sure if the high load had anything to do with it). Do you have any logs of the consensus WAL? or of consensus?

In regards to (2), the address book already has a two bucket system: `bucketsNew` and `bucketsOld` (this latter one is for  "trusted" peers). I think when a peer gets in the old bucket it is only removed if it sends a erroneous message. If so then this could explain why dead peers are filling up the peer list and no new peers are being accepted. We are currently refactoring the p2p layer which will also extend into looking into and trying to improve the address book and overall peer life-cycle management.

**Comment by anilCSE** [comment]
> I am not too familiar with this but I would think that the write-ahead log should have saved this round information so perhaps something went wrong there (I am not too sure if the high load had anything to do with it). Do you have any logs of the consensus WAL? or of consensus?

Thank you @cmwaters for digging through this. Unfortunately we don't have enough logs around the consensus state. But we have a backup of the data dir if that helps.

> We are currently refactoring the p2p layer which will also extend into looking into and trying to improve the address book and overall peer life-cycle management.

Good to know this.

**Comment by cmwaters** [comment]
That's alright @anilCSE. I was able to reproduce it locally. It definitely seems like it's the WAL either when it writes state or when it tries to recover it. It only seems to occur when there is a heavy load and the node begins to slow down. I'll look into a little more and let you know if I find anything.
