### ISSUE TITLE
Events [Tracking Issue]

### ISSUE THREAD

**Issue by tessr** [tendermint/tendermint#5963]
We've historically de facto deprioritized work on the events system. But it's not just an auxiliary system: It's used by IBC. [todo: explain how IBC uses events] 

Important bugs to fix: 

- [x] Cannot query events in `BeginBlock` or `EndBlock` https://github.com/tendermint/tendermint/issues/3665 
- [x] Events "collapsing" into one event type https://github.com/tendermint/tendermint/issues/5133 (likely root cause of https://github.com/cosmos/cosmos-sdk/issues/8419) 

A relevant discussion on the event system can be found [here](https://github.com/tendermint/tendermint/discussions/6114)

**Comment by cwgoes** [comment]
Ref https://github.com/cosmos/cosmos-sdk/issues/8593 - if this work can be prioritised, it will save us kludgy downstream workarounds.

**Comment by cwgoes** [comment]
As a quick summary: IBC uses events to log data which needs to be processed by relayers (contents of packets and acknowledgements) but which isn't actually stored on the chain, since it doesn't need to be. I'm actually surprised these issues have only come up now - this is a pretty standard way to use any sort of events system in a blockchain context, I'd expect other Tendermint clients do similar sorts of things (though perhaps they haven't used BeginBlock/EndBlock or the like).

**Comment by cmwaters** [comment]
I'm just trying to parse this into something I understand. Is the outstanding issue essentially that we don't save begin block and end block events in the tx indexer?

**Comment by alexanderbez** [comment]
The gist of it is the following @cmwaters:

- Lack of BeginBlock and EndBlock events from being persisted, indexed and exposed via the query interface
- A crude query interface preventing the ability to create rich and complex queries
- Issues around events being "flattened" when queried for (I still need more clarification on this)

While this is the tracking issue, we have a [discussion](https://github.com/tendermint/tendermint/discussions/6114) started that would hopefully outline a solution for which we can tweak this issue to reflect.

**Comment by ethanfrey** [comment]
> Issues around events being "flattened" when queried for (I still need more clarification on this)

This affects you if you submit a tx with multiple messages (say a relayer submits one that contains 3 receive packet messages, rather than 3 sepearate tx to avoid sequence and ordering issues). In this case, all the events with `ibc_acknowledge_packet` type will be flattened into one event by Tendermint. So, I don't get 3 unique acknowledgements in the tx events, but one.

I think almost no one tries to use the multi-message functionality, which is why no one really reports this. CosmWasm does multi-message internally, and we have tested multi-message in CosmJS test cases, which is why I came across this.

This is not a blocker persay if you use it "carefully", but says it will break if you make use of all the functionality the Cosmos SDK offers.

**Comment by cmwaters** [comment]
@alexanderbez thanks for the explanation. I also looked over the discussion thread as well. I do think however that we may want to consider breaking these into their short and long term components. The discussion that Marko opened seems to focus on the broader questions of what are the needs of an event system in Tendermint (and indicating at moving to a well-supported query engine). This may be on the timespan of 6 months to a year. @cwgoes seems to suggest that we should look at making a more immediate fix to the current tx indexer to include the events that begin block and end block produce which we could prioritise and get done in a week

**Comment by ethanfrey** [comment]
>  @cwgoes seems to suggest that we should look at making a more immediate fix to the current tx indexer to include the events that begin block and end block produce which we could prioritise and get done in a week

It's not just the indexer, the data is not stored in the block anywhere. One should minimally be able to query eg. `/block_events?height=h` and get:

```go
{
  BeginBlock []Event
  EndBlock []Event
}
```

or add that to the `/block` return value. (I was tending to something like `/block_results`)

This data should also be available from the indexer, but exposing it directly is also very important, so any other indexing process (eg. block explorer, rosetta) can access it as well

**Comment by alexanderbez** [comment]
@cmwaters, where do you get that estimation from? If we just switch to a database with the correct semantics, it shouldn't take that much time. Maybe a month or two.

**Comment by cmwaters** [comment]
@ethanfrey we currently store all ABCI Responses in the state store (including begin block and end block). It wouldn't be too difficult (famous last words) to expose this through the RPC with `/block_events?height=h`
 
> where do you get that estimation from?
Sure the implementation may not be too difficult but I was more thinking the processes of design, consultation with the community etc that may take a while. This is also not to mention that most of us already have our work cut out for the next couple of months.

**Comment by cmwaters** [comment]
Hey @ethanfrey, just for further clarification on this: Do you want `BeginBlock` and `EndBlock` events to be queryable in the same `/block` query. I actually wasn't aware of this before but can't you just use the `/block_results?height=h`call to retrieve the events?
```
type ResultBlockResults struct {
	Height                int64                     `json:"height"`
	TxsResults            []*abci.ResponseDeliverTx `json:"txs_results"`
	BeginBlockEvents      []abci.Event              `json:"begin_block_events"`
	EndBlockEvents        []abci.Event              `json:"end_block_events"`
	ValidatorUpdates      []abci.ValidatorUpdate    `json:"validator_updates"`
	ConsensusParamUpdates *tmproto.ConsensusParams  `json:"consensus_param_updates"`
}
```

**Comment by ethanfrey** [comment]
Ah, I didn't know the block results returned that. That is nice and covers my feature request (that the data was available somewhere to be queried later)

**Comment by cmwaters** [comment]
Awesome to hear. Is it okay then if I close #3665?

**Comment by ethanfrey** [comment]
@cmwaters Please don't close that.

This was an additional request on #3665, so that *external indexers* like Block Explorers could get the data. As long as you support the in-process Tendermint indexer and have not fully replaced that with another canonical solution that all clients can code against, we still need to be able to query the Begin and EndBlock Events.

In particular, Band protocol sends IBC packets in EndBlock. These packets currently cannot be queried by any relayer due to this bug.

**Comment by alexanderbez** [comment]
It should be trivial I think to address #3665 while we revise the system all together. We could probably get it into 0.34.x since it should not be breaking.

I'll see if this is viable over the next few days.

**Comment by marbar3778** [comment]
closing this as the issues slated in the description have been resolved.
