### ISSUE TITLE
WebSocket: Add block ID to "newblock" event

### ISSUE THREAD

**Issue by clockworkgr** [tendermint/tendermint#6028]
According to the comments here: https://github.com/tendermint/tendermint/blob/master/types/events.go#L14-L18, a `newblock` event is triggered after a block has been committed. 

That being the case, I would expect the block data included with the event to have the same structure as the `/block?height=xxxx` RPC call.

However, the `newblock` event seems to be missing the `block_id` section.

e.g. 

WS event: https://gist.github.com/clockworkgr/46adb9ae51af24b928f83d443fae617f
RPC call: https://gist.github.com/clockworkgr/61ed9fa97d40950a8ce8bfd06f7a87c6

Is this by omission or by design?

As it stands, someone would have to do an RPC call to get that additional data as soon as a `newblock` event is received which kind of defeats the purpose for a lot of use cases.

**Comment by cmwaters** [comment]
Although they are meshed together at the surface level, the web socket and RPC data structures stem from two different sources. The WS is tied with the event system within consensus (hence it returns a bunch of other events ) whilst RPC calls come from the block store. 

As to whether `block_id` was left out of the `newblock` event by design, I don't think so but nor would I call it a bug. 

In any case, I would think this should be quite an easy change to make if we feel that it might help those using WS.

**Comment by clockworkgr** [comment]
That makes sense on why they ended up different.

In any case, I think it would be helpful for WS users so would appreciate it if it gets added to the pipeline somewhere if it's an easy change.

Thanks

**Comment by marbar3778** [comment]
@clockworkgr do you want the BlockId in order to get the header hash, or do you have a need for the parts as well?

**Comment by clockworkgr** [comment]
In the specific case I'm using it I make an extra request by height to get the hash yes. 

Don't think I have a need for the parts at this time, however I'd still consider it best practice for the RPC call and the WS event to contain the same information.
