### ISSUE TITLE
Test Failure: TestRouter_AcceptPeers

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#6119]
```
2021/02/16 16:07:41 Failed to accept conn: accept tcp 127.0.0.1:44541: use of closed network connection
2021/02/16 16:07:41 Failed to accept conn: accept tcp 127.0.0.1:35657: use of closed network connection
2021/02/16 16:07:41 Failed to accept conn: accept tcp 127.0.0.1:46571: use of closed network connection
2021/02/16 16:07:41 Failed to accept conn: accept tcp 127.0.0.1:39371: use of closed network connection
2021/02/16 16:07:41 Failed to accept conn: accept tcp 127.0.0.1:38471: use of closed network connection
2021/02/16 16:07:41 Failed to accept conn: accept tcp 127.0.0.1:38939: use of closed network connection
2021/02/16 16:07:42 Failed to accept conn: accept tcp 127.0.0.1:37109: use of closed network connection
2021/02/16 16:07:42 Failed to accept conn: accept tcp 127.0.0.1:46321: use of closed network connection
2021/02/16 16:07:42 Failed to accept conn: accept tcp 127.0.0.1:33245: use of closed network connection
2021/02/16 16:07:42 Failed to accept conn: accept tcp 127.0.0.1:33461: use of closed network connection
2021/02/16 16:07:45 Failed to accept conn: accept tcp 127.0.0.1:38011: use of closed network connection
2021/02/16 16:07:46 Failed to accept conn: accept tcp 127.0.0.1:34905: use of closed network connection
2021/02/16 16:07:46 Failed to accept conn: accept tcp 127.0.0.1:36265: use of closed network connection
2021/02/16 16:07:46 Failed to accept conn: accept tcp 127.0.0.1:42145: use of closed network connection
2021/02/16 16:07:46 Failed to accept conn: accept tcp 127.0.0.1:43493: use of closed network connection
2021/02/16 16:07:46 Failed to accept conn: accept tcp 127.0.0.1:38245: use of closed network connection
2021/02/16 16:07:46 Failed to accept conn: accept tcp 127.0.0.1:40393: use of closed network connection
2021/02/16 16:07:46 Failed to accept conn: accept tcp 127.0.0.1:45295: use of closed network connection
2021/02/16 16:07:46 Failed to accept conn: accept tcp 127.0.0.1:43939: use of closed network connection
2021/02/16 16:07:46 Failed to accept conn: accept tcp 127.0.0.1:44205: use of closed network connection
--- FAIL: TestRouter_AcceptPeers (0.32s)
    --- FAIL: TestRouter_AcceptPeers/valid_handshake (0.14s)
        router_test.go:366: PASS:	String()
        router_test.go:366: PASS:	Protocols()
        router_test.go:366: PASS:	Close()
        router_test.go:366: PASS:	Accept()
        router_test.go:366: PASS:	Accept()
        router_test.go:367: PASS:	String()
        router_test.go:367: PASS:	Handshake(string,p2p.NodeInfo,ed25519.PrivKey)
        router_test.go:367: PASS:	Close()
        router_test.go:367: FAIL:	ReceiveMessage()
            		at: [router_test.go:330]
        router_test.go:367: FAIL: 3 out of 4 expectation(s) were met.
            	The code you are testing needs to make 1 more call(s).
            	at: [router_test.go:367]
FAIL
coverage: 78.3% of statements
FAIL	github.com/tendermint/tendermint/p2p	20.282s
```

https://github.com/tendermint/tendermint/pull/6056/checks?check_run_id=1911990868

**Comment by alexanderbez** [comment]
This could be due to `use of closed network connection`, in which case this is benign. Although, I do very frequently see these `use of closed network connection` logs in CI and perhaps it's worth the investigation into why this happens.

**Comment by tychoish** [comment]
`TestRouter_AcceptPeers` uses mocked transports/connections , so I don't think that the tcp connection messages are related in anyway to the failure. 

I've seen this in CI a few times, and reproduced it locally, though I have to run this test 100s of times to get a single failure. It seems like the part that isn't working is that (sometimes, likely due to timing effects,) the `Connection.ReceiveMessage` method isn't being called after the peer has a successful handshake. 

The options are: 
- drop the requirement to call `ReceiveMessage` in this test. I don't think this reduces the coverage of the test, as the _core_ assertion is that the peer update receives the information about the new  post-handshake. I think the mocked `ReceiveMessage` call is just to prevent the test from panic'ing, but I'm not sure. 
- add a millisecond sleep after calling `p2ptest.RequireUpdate` to force the runtime to context switch, because I believe that the `ReceiveMessage` call happens in a different go routine, and the context switch increases the likelihood  that the method will be called. This isn't a "for sure" fix, but it probably helps, and I haven't been able to observe a local test failure with a sleep.

**Comment by alexanderbez** [comment]
Nice, thanks for digging into this @tychoish! It seems the first option is preferable as we don't have to rely on a hacky sleep, but the test will panic if we remove it.

**Comment by tychoish** [comment]
we can add a `.Maybe()` to the mock declaration to get it to always pass. Having said that, I don't know if that reduces the value of the test: as I thought through it, it seems like skipping this call might indicate that the connection isn't being used or acted upon, so maybe we want to keep it.

The "hacky sleep" is hacky, but seems to work pretty reliable in my testing.
