### ISSUE TITLE
The websocket RPC client doesn't have a way to configure the ping period

### ISSUE THREAD

**Issue by hydrogen18** [tendermint/tendermint#6162]
I'm a member of the akash team and I have observed that after long idle periods we sometimes stop getting events from tendermint nodes. Restarting the process solves the problem.

I looked over the code and found that a websocket client is used to stream the data back. It looks like there are defaults set in the websocket client that disable websocket pings by default

https://github.com/tendermint/tendermint/blob/master/rpc/jsonrpc/client/ws_client.go#L110

I couldn't find any exposed methods or configuration that would permit this to be configured. I used a fork to test out my idea, and it appears that enable websocket pings fixes the issue.

Is there a way to enable these pings? If not, what is the best way to come up with a PR to allow application level code to enable websocket pings?

**Comment by melekes** [comment]
I don't know why pings are disabled by default. Maybe we should just enable them + set reasonable values for `readWait` and `writeWait` instead of zeroes.

Additionally, we can expose `WSClient` options (https://github.com/tendermint/tendermint/blob/42f6c40751ba74eb448b7a1af7b9e206d736f905/rpc/jsonrpc/client/ws_client.go#L132) here https://github.com/tendermint/tendermint/blob/42f6c40751ba74eb448b7a1af7b9e206d736f905/rpc/client/http/http.go#L132 and therefore give the user ability to tweak WS client.

**Comment by cmwaters** [comment]
Do you know what the reason for having them disabled by default is?

**Comment by melekes** [comment]
> Do you know what the reason for having them disabled by default is?

who are you asking?

**Comment by melekes** [comment]
https://github.com/tendermint/tendermint/commit/2fd8496bc109d010c6c2e415604131b500550e37 I kinda remember now that I've disabled pings on the client because the server sends them (no need for a client to do the same?). As for read wait, if you set readWait less than 30s (server ping period), client will disconnect IF there are no other messages. For write wait, we can set something reasonable, like 10s.
