### ISSUE TITLE
Serialization of Tendermint RFC3339 Timestamps

### ISSUE THREAD

**Issue by shonfeder** [tendermint/tendermint#6233]
The purpose of this issue is to surface a complication in the implementation of `tendermint-rs` (which is also likely to affect interop with any future implementation) and to provide a point for coordinating and soliciting feedback.

## Context

In `tendermint-rs`, we have ended up hand rolling our RFC3339 timestamp serialization. This was due the following factors:

1. The protocol includes RFC3339 timestamps in messages between nodes.
2. The Go implementation uses a particular go formatter, `RFC3339Nano`, which trims trailing zeros from the nano seconds.
    - E.g., `1985-04-12T23:20:50.5200000Z` is only ever serialized as `1985-04-12T23:20:50.52Z`
4. The standard date/time lib for Rust, `chrono`, doesn't support this flavor of RFC3339 timestamps. Instead it defaults to including trailing zeros up to the precision of the internal time representation.
5. This presented problems in our testing, especially in cases where we are comparing generated data structures in testing (in Rust) to those received from the Go-based Tendermint RPC.

## Current situation

The handrolled serializer in our Rust code effectively reproduces this RFC3339Nano format from go, and that seems to have been sufficient to get consistent hashes for the current WIP.

## Questions

1. Is this a sustainable design decision? Or should we put back pressure into the spec and on the Go implementation to instead use a serialization and hashing strategy that avoids having to use finicky textual representations? 
    - E.g., looking at the "BFT Time" subsection of the tendermint core spec, it says  "In the context of Tendermint, time is of type int64 and denotes UNIX time in milliseconds, i.e., corresponds to the number of milliseconds since January 1, 1970.".
        - Should we only be hashing on the integer value of the deserialized timestamps (in milliseconds) rather than the textual timestamp?
        - Should Tendermint Go only be putting the integer value into its messages (contra https://github.com/tendermint/tendermint/pull/953#discussion_r156179067).
        - Since the internal representation is only accurate to milliseconds, shouldn't a milliseconds-level timestamp representation be accurate enough? What drives the need for nanoseconds-level timestamp representation?
2. If we don't change our implementations to use the UNIX time in milliseconds (at UTC) in our transaction messages, then where do we specify this behavior, so that future implementors will be aware of the need to adhere to this particular subset of RFC3339 in the messages they generate? (So far, I have not found a standard or specification for the formatting of these messages.)

Related to https://github.com/tendermint/tendermint/issues/2309#issuecomment-417815447

(@thanethomson provided much of the context for this issue, and helped draft the text. It was also discussed with @milosevic.)

This issue grew out of work on https://github.com/informalsystems/tendermint-rs/pull/815

**Comment by alexanderbez** [comment]
It's a shame that these standards, i.e. RFC3339, aren't handled uniformly across language boundaries. Do you happen to know if the RFC3339 spec states on what the behavior should be here? Or is it intentionally or unintentionally not specified?

I do agree having to maintain a modified implementation rust-side is not idea. It makes sense to support timestamps in unix nano seconds, i.e. `int64`. I don't know what the repercussions would be here. Certainly it'd be protocol breaking, right?

**Comment by shonfeder** [comment]
> Do you happen to know if the RFC3339 spec states on what the behavior should
> be here? Or is it intentionally or unintentionally not specified?

Here's everything I could find that bears on this question:

In [Appendix A](https://tools.ietf.org/html/rfc3339#appendix-A) of RFC3339 the
ABNF spec for fractions of a second is given as:

```abnf
   time-fraction     = ("," / ".") 1*DIGIT
```

This is consistent with any treatment of trailing zeros. 

Somewhat related: in [Section 5.1][], on ordering, they note that the expected
temporal ordering is consistent with lexigraphic ordering of the serialized
representations only if all stamps are in the same timezone, using the same zone
indicator, and "all times have the same number of fractional second digits".

And the [golang docs](https://golang.org/pkg/time/) note that

> The RFC3339Nano format removes trailing zeros from the seconds field and thus
> may not sort correctly once formatted.

[section 5.1]: https://tools.ietf.org/html/rfc3339#section-5.1 

The most relevant point from RFC3339 may be [the
following](https://tools.ietf.org/html/rfc3339#section-5.3):

>  5.3. Rarely Used Options

>  A format which includes rarely used options is likely to cause
>  interoperability problems.  This is because rarely used options are
>  less likely to be used in alpha or beta testing, so bugs in parsing
>  are less likely to be discovered.  Rarely used options should be made
>  mandatory or omitted for the sake of interoperability whenever
>  possible.

>  The format defined below includes only one rarely used option:
>  fractions of a second.  It is expected that this will be used only by
>  applications which require strict ordering of date/time stamps or
>  which have an unusual precision requirement.

Very prescient :) (Tho this option is probably less rarely used these days).

--- 

I imagine that the main reason *to* include trailing zeros is to communicate the
time  precision being used in the internal representation. E.g., if we're using
millisecond precision internally, we can signal this by always including 3
decimal places in the serialization. This is useful information to communicate
in the serialized data.

I agree that it would ideally be preferable to just use the integer value of the
timestamp in some determined fractions of a second. If, however, that is
infeasible for reasons of backwards compatibility, perhaps we might reconsider
use of Rfc3339Nano, and instead commit to a fixed precision in the timestamps?

**Comment by thanethomson** [comment]
> Certainly it'd be protocol breaking, right?

To my knowledge it would break the RPC, but not the Protobuf representations.

All Protobuf representations use Google's timestamp format, which is a struct containing `seconds` and `nanos` fields, and from what I remember all hashing of timestamps takes place on the Protobuf-serialized data structures. As such it shouldn't be protocol-breaking anywhere that makes use of the Protobuf data structures.

**Comment by tessr** [comment]
I think this would be good fodder for an upcoming dev call, maybe the one on May 13. @thanethomson, will you be available for that one?

**Comment by thanethomson** [comment]
> I think this would be good fodder for an upcoming dev call, maybe the one on May 13. @thanethomson, will you be available for that one?

Sure!

**Comment by tessr** [comment]
[Postponed to May 27.]

**Comment by tessr** [comment]
Posting the conclusions from today's dev call:

- Leave implementations as-is (continue to trim zeroes before sending them back over RPC)
- Update the spec: @marbar3778 will update the RPC spec to reflect the state of the implementation 
- Post-0.35, we'll make a decision about gRPC. After that, we can revisit whether we want to fix this at a block-level or at an RPC level (and decide if we want to keep nanoseconds around, for example)

**Comment by marbar3778** [comment]
In talking with thane after the call about this, I had more questions, the simplest approach would be to recreate the block and header type along with other types that contain timestamps to use a string, and we handle the timestamp ourselves. 

The next approach is what is being worked on now, where the light client hooks up into the p2p layer, which would provide the tm-rs team with the correct encoding because it's using protobuf. This is mainly an unfortunate circumstance that stems from using the rpc layer, an under specified package, for consensus critical data. 

Within the go codebase, we have not seen this issue because gogoproto handles this for us with as we see here https://github.com/tendermint/tendermint/blob/master/proto/tendermint/types/types.proto#L63, specifically `(gogoproto.stdtime) = true`

IMO, this doesn't have much to do with how we do hashing, and we should not change anything internal to tendermint as this would break protobuf specification and will 100% cause more issues down the road.

**Comment by tony-iqlusion** [comment]
In discussion on https://github.com/informalsystems/tendermint-rs/issues/865 the question of whether RFC3339 dates are required to be Z-normalized (i.e. always Zulu/GMT/UTC) came up, or whether parser implementations need to be able to potentially do time zone conversions.

I would suggest mandating Z-normalized RFC3339 dates and requiring parsers to reject dates with other time zones so as to eliminate the need for any time zone conversion logic.

**Comment by mzabaluev** [comment]
> I would suggest mandating Z-normalized RFC3339 dates and requiring parsers to reject dates with other time zones so as to eliminate the need for any time zone conversion logic.

I think any Internet-capable programming language ecosystem should have a library that is able to parse any RFC 3339 compliant date into the corresponding date-time or timestamp value referenced against either the Unix timestamp or UTC. On output, Tendermint libraries should normalize to UTC and use the `Z` suffix.

There is some weirdness around processing leap seconds. RFC 3339 permits a seconds value of 60 when the UTC (not local time) is 23:59:60 and _some vague unimplementable language about the leap second having been announced for this date by the international committee that controls this stuff_. Treatment of leap seconds in RFC 3339 input by libraries... varies. Rust's `time` rolls back any parsed time with the seconds part of 60 to 59.999999999 (will do, since https://github.com/time-rs/time/issues/404 got fixed today). `chrono` rolls back the second to 59, but extends the subsecond value to more than 1_000_000_000 nanoseconds. :scream:

I think the sensible thing to do here is to either do what `time` does on parsing, or reject second 60 outright, and tell everyone to use clock with [linear 24-hour smear](https://developers.google.com/time/smear) around leap seconds, like protobuf's [`Timestamp`](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Timestamp) is already specified to do by Google.
