### ISSUE TITLE
mempool: speed up broadcastTxRoutine

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#625]
`broadcastTxRoutine` does expensive interface handling every loop and only sends one tx per message.

We should allow it to batch txs per peer.Send.

**Comment by odeke-em** [comment]
I can work on this, thanks for the suggestion @ebuchman.

**Comment by melekes** [comment]
@odeke-em I think at least the last part was done in https://github.com/tendermint/tendermint/pull/632. not sure about the "expensive interface handling"

**Comment by odeke-em** [comment]
Nice catch @melekes! The interface handling I think can't go away since we do
https://github.com/tendermint/tendermint/pull/632/files#diff-faa5920fe04b5bb0d81cec8ad247ccdcR152
<img width="1252" alt="screen shot 2017-09-22 at 9 32 48 pm" src="https://user-images.githubusercontent.com/4898263/30769798-9bc63eb2-9fdd-11e7-9de1-aa6561a4f68a.png">

**Comment by ebuchman** [comment]
think this requires more analysis on whats causing the slowdown and if TxsMessage is really the right solution

**Comment by ValarDragon** [comment]
Batching wasn't done. (I'm not sure why, reading into the conversation in the previous PR) Currently we are only sending 1 tx per message, and then waiting for the response. The reason why batching is such a huge performance win is because we wait for the recipient to send an ACK that they've received it (TCP).

**Comment by ebuchman** [comment]
Yeh we should probably bring that back. I think it was closed under suggestion by @jaekwon that there might be some other slowness we're missing and we should find that first, but seems batching would be a clear benefit and based on my benchmarking and profiling seems it provides real value. Not a launch priority per-se though.

**Comment by ValarDragon** [comment]
> `broadcastTxRoutine` does expensive interface handling every loop

Local benchmarks show that a single type assertion took `0.63ns` (though its possible that there was some caching going on), but regardless I don't think that was a significant cause of the slowness. (It was probably purely network delay)
