### ISSUE TITLE
consensus: HasBlockPart message to avoid receiving duplicate parts

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#627]
Right now we may receive the same block part from many peers.

We should consider a HasBlockPart message to be broadcast after every part is received to help avoid this.

**Comment by odeke-em** [comment]
Thanks @ebuchman, this looks like an interesting issue.
Just for the purpose of clarification despite being verbose:
1) On receiving a part, broadcast this new message to every peer that we now have this message
2) How should this message look? Should we just broadcast the hash of the block as well as some sort of peerID?
3) Before any peer "gossips" a block part to other peers, it should check its "peersCache" for the hash and see if any of those peers already declared that they have this messages, as per 1)
4) What happens when a peer drops a block(data loss, or Byzantine behavior) but then it already sent the HasBlockMessage to its peers. Would this conflict with point 3)?

Please pardon the newbie questions :)

**Comment by ebuchman** [comment]
Good questions. The intention of this message is to alert other peers that we have a block part, so they don't need to send it to us. It should probably contain height/round/index, but it may be helpful to include the block hash. We need to consider what happens when two conflicting blocks are proposed and a peer sends HasVote for a part on the minority block.

**Comment by melekes** [comment]
Why are we receiving duplicate parts in the first place? Can't we request parts in a round-robin fashion? Or it is due to how libswift-inspired propagation works?

**Comment by ebuchman** [comment]
We don't request parts. Peers send to us based on what they think we don't have

**Comment by cloudhead** [comment]
I'm going to try to tackle this. A few questions so I understand better:

1. Does this apply to the blockchain reactor? Or only to the consensus reactor? In the consensus reactor, we send block parts during the proposal phase, is there another point at which we send block parts that I am missing?

2. If the idea here is to reduce bandwidth, then broadcasting a message every time we receive a block part might be counter-intuitive?

3. What is the current gossiping algorithm? Do we know its efficiency in terms of bandwidth? I think it should be possible to implement an algorithm that can be pretty efficient without broadcasting what a node knows, using a push&pull mechanism: each round, nodes contact a random neighbor and they exchange what they know and keep a map of each other's knowledge, until they know a given rumor is known by all nodes, or a certain number of rounds for that rumor has been reached.

**Comment by ebuchman** [comment]
1. Just consensus. We don't really "send during proposal phase", we send when we ascertain that the peer needs them - generally they need them during the proposal, but they might also have seen +2/3 precommits before receiving the block and now need to get the block parts so they can actually commit it. The peer sending could be in any phase.

2. Fair enough - but compare sending a small "HasBlockPart" msg vs potentially receiving a 64kb block part from many validators. We need to do some analysis, but we already take the HasVote strategy with votes

3. I would love it if you could help write this up and do some analysis. It would be a good way to read the code and understand it, and would be super helpful for everyone else. You could also work with @milosevic on it who is working on formally specifying the entire protocol. What you're describing sounds reasonable, but we have to be very careful with liveness. So let's study what we currently have and try to make a good argument for how it could be better.

**Comment by cloudhead** [comment]
Great, thanks.

The way I'd like to proceed now is to measure the total bandwidth used per block bytes synchronized. From some cursory research, it should be possible to be near optimal, ie: if 10 bytes need to be synced to each node, then each node should receive more or less 10 bytes. It might be difficult though due to byzantine behavior etc. but let's see. If this was never optimized, then it's possible that bandwidth spent is up to O(N^2) of actual bytes synced, so there would be room for improvement.

**Comment by milosevic** [comment]
I have just started to work on a gossiping part of the protocol. @cloudhead We should probably synchronise on this task as doing analysis without having protocol written down could be tricky.

**Comment by cloudhead** [comment]
Cool, let's sync.

**Comment by ebuchman** [comment]
Let's get back to this after launch
