### ISSUE TITLE
Contributing to the library.

### ISSUE THREAD

**Issue by androlo** [tendermint/tendermint#63]
I'm building a javascript lib for Thelonious-Tendermint and would like to contribute to the server side, particularly the RPC/RMI section. Seems like the logic is mostly there, so I'd be refining & standardizing.

This is my suggestions:

**Coding**

Separate into two different RPC protocols. The first would be used between Go libraries that can just import the serialization/binary stuff. The second would be generic (JSON) RPC, and that's what I'd be working with. I'd create proxies and conversion functions for all the needed data-structures and hook them up with the handlers. I guess regular HTTP requests could use them as well, though I wouldn't be concerned with that.

This would also involve going over method names, namespacing etc. Maybe add some more functions (a way to get the client version etc.), and divide a few of the current ones up etc. The model I use in the javascript library (as of now) has the following classes:

- Accounts
- Blockchain
- Consensus
- Core
- Networking
- Transactions
- Unsafe

These are based on the current rpc commands (and looking at the client), and I don't think more classes will be needed for some time.

**Tests**

I would make sure the tests are working before PRing to develop, and add any new ones that might be needed.

**Docs**

I could put the spec in the wiki.

**Time**

It would probably take about a week for the code, and another for doing good tests and docs + the time it takes to look into / research the library more. Around 3 weeks in total.

**Comment by jaekwon** [comment]
Hi androlo,  thanks for the writeup.

Maybe we can put off the binary RPC protocols until they're needed due to performance bottlenecks.  I don't need them any time soon.  What do you think?

If "create proxies and ... and hook them up with the handlers" means following the convention of the existing RPC methods, then that sounds good.

I'm in favor of making changes to the method names and adding namespacing if appropriate.  Those classes seem good.  What is "Core"?

I'm also developing (re-writing) a javascript library.  It's broken and incomplete, but you can see a work in progress here:  https://github.com/tendermint/tendermint-lib-js   Does this maybe overlap with what you're doing?

**Comment by androlo** [comment]
Hi, thank you for responding. 

About "Core" - It may be a bad name, and of course subject for change, but it is a placeholder for things like getting the client version, maybe some core config stuff - basically it would hold all the "core" tendermint+thelonious methods that is exposed.

I don't mean to push any ideas really. I just want to do the grunt work on top of what Ethan already did (which I believe already works fine). Things like going over the calls, maybe complement with some logging where needed, error reporting, extra tests, docs etc. I want to help you guys speed this up mainly because it would make the calling code more stable from the start.

If you green-light I'll start Monday, and the time-table will probably hold. Before making the pull-request I'd put up an "ideas for review" issue with the final RPC method and objects draft for you or Ethan to review. This process should not require much time/involvement from either of you I think.

About the js - Yes I looked at that lib and basically started from there. Writing a separate version though, because it's going to be the thelonious lib (so will diverge from tendermint-core). It'll be reviewed in 1-2 weeks or so btw., and there is also a web3 fork that'll be running on top of it (rather then ethereum) so that their awesome js solidity contract objects and solidity events + filters can be used. Hoping it'll all be ready this month.

**Comment by jaekwon** [comment]
+1 Sounds great.  Let me know if I can help in any way.  email: jae@tendermint.com

**Comment by androlo** [comment]
Gonna push a lot of stuff to a new branch. Probably tomorrow.

**Comment by androlo** [comment]
Hi. Going pretty well. Don't want to push until the tests are in place which is why I've waited. Maybe i'll do first push today, or maybe tomorrow. My work is in a sub-package of tendermint/rpc btw, so does not modify any of the rpc code that's already there. Will still push into a new branch though.

The structure now is basically this:

1. generic json-rpc package
2. tendermint rpc service(s)
3. tendermint pipe

Pretty standard. The generic json-rpc package has the server. It supports http and websocket, and depends on rpc service interfaces to do the actual calls (so is generic). The services are registered to the rpc server upon launch, and receive requests from the http handler and websocket sessions. Websocket services are bound to sessions and can register event callbacks that writes the results to the sessions. Methods on the rpc services always call methods on the running tendermint node via the pipe, which does some proxy'ing of objects etc.

The pipe is basically done. It implements most of the functions that was already there, just some tx stuff left that I'm gonna have to ask a few questions about. Also, I'm not sure to what extent the binary library can be used to make the processing simpler. I assume it is designed for the network, but looks like it uses json serialization. Does it ever use something other then standard json? Otherwise I guess might as well cut out the middlemen and just use that directly. As an example, this is the account objects I use now:

```
type (

	// An un-assuming Tendermint account.
	Account struct {
		Address     string `json:"address"`
		PubKey      *Key   `json:"pub_key"`
		Sequence    uint   `json:"sequence"`
		Balance     uint64 `json:"balance"`
		Code        string `json:"code"`         // VM code
		StorageRoot string `json:"storage_root"` // VM storage merkle root.
	}

	// Account storage.
	Storage struct {
		StorageRoot  string         `json:"storage_root"`
		StorageItems []*StorageItem `json:"storage_items"`
	}

	// A single storage-item.
	StorageItem struct {
		Key   string `json:"key"`
		Value string `json:"value"`
	}

	// JSON representation of a private or public key (see accounts package).
	// Types are defined in accounts/priv_key.go and accounts/pub_key.go
	Key struct {
		Value string `json:"value"`
		Type  byte   `json:"type"`
	}
)
```

Started on the rpc services today but ran into some difficulties. The code makes heavy use of reflection on global functions, which does not work when those functions are instead methods on a struct (pointer). It'll take some time to bone that out.

The http/websocket is moving along. Done a bunch of work there. Websockets had separate request and response objects and was used only to pass events (through a direct reference to `events.EventSwitch`). I changed it to use the standard json rpc request and response objects, and  added Event sub/unsub methods to the pipe.

I'll compile a list of all functions later with the param and response objects for each, and would be happy if you and Ethan could all look at the method names and objects and see that they are good. Guessing by the end of next week or so. After that I'll refactor everything, pr, and if successful I'll add the list to the wiki rpc section.

**Comment by androlo** [comment]
So, to be clear: The reason I started with proxies is because I assume the objects that are passed over the network may have some weird stuff in them that maybe is not suited for generic json-rpc "display" versions, like accounts etc. ... If that's not the case then why bother.

**Comment by androlo** [comment]
Actually, no. I'll reduce it to a websocket handler class that provides a simple http.HandlerFunc. It'll be able to do full-on json-rpc over the socket, that's the only difference really. No point in doing double work on top of Ethans stuff.

**Comment by jaekwon** [comment]
```golang
    // JSON representation of a private or public key (see accounts package).
    // Types are defined in accounts/priv_key.go and accounts/pub_key.go
    Key struct {
        Value string `json:"value"`
        Type  byte   `json:"type"`
    }
```
Tendermint uses the `tendermint/binary` module to encode most structs, including the (priv/pub)keys.  It supports both C-style byte encoding as well as JSON encoding for all objects.  It also supports golang interfaces, though it requires you to register the interface.  Documentation here (a bit out of date): https://github.com/tendermint/tendermint/tree/master/binary

So there's probably no need to declare a Key struct, because the type information (the "type byte") of the interface is automatically encoded when using binary.WriteJSON.  The format is `[type_byte, {field:value,...}]` when JSON encoded, so it's always an array of length 2 with the type_byte in front.

Note that the default `encoding/json` module can't deal with interfaces or pointers, so for this feature we must use `tendermint/binary`.

>  Started on the rpc services today but ran into some difficulties. The code makes heavy use of reflection on global functions, which does not work when those functions are instead methods on a struct (pointer). 

Ok.  The convention is that we declare all RPC functions as global functions.  Is there a good reason to change it?  There's a ton of logic in https://github.com/ebuchman/go-rpc-gen that is used when you run `go generate rpc/core/client/*.go`.  (See this make task: https://github.com/tendermint/tendermint/blob/develop/Makefile#L29)  It's experimental code that we're using to auto-generate the client files.  I suspect that go-rpc-gen currently depends on global functions.

If you want to change the structure/conventions of the rpc/core/*, it will likely break that make task above.  It would be great if go-rpc-gen could be adapted to suit the new rpc refactor.  If not, I our choices are either to stick with the RPC global funcs structure or to deprecate go-rpc-gen usage.  The latter requires rolling out the client code by hand (which shouldn't be too hard) or changing the RPC client unit tests.  Lets get Ethan's input.

**Comment by androlo** [comment]
No need to worry about breaking something. I won't break anything. I did a PR to add a BlockStore getter to Node earlier today. If that's done it's possible to do all tendermint stuff without problems (no matter if binary is used to create return objects or not). In fact I put my stuff in a separate repo (not the tendermint fork) i.e. the generic socket-based rpc code + the tendermint specific service and pipe. I think that's best. For you guys it'll be possible to pull in anything that's considered useful, and if it doesn't fit the mold then no problems.

What I'm mostly concerned with tbh is that the api is good and clean, so it is easy to call from javascript.

**Comment by jaekwon** [comment]
Hi androlo,  please take a look at this branch:
https://github.com/tendermint/tendermint/tree/newconfig

There were some RPC refactors.  It isn't necessary but does seem like an improvement to divide rpc/* into smaller modules.

**Comment by androlo** [comment]
Hi, thanks for the update. I noticed that but Ethan's tests was updated so i just duplicated.

**Comment by androlo** [comment]
We can continue this in the slack.
