### ISSUE TITLE
rpc: genesis endpoint

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#6354]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): Present on master.

**ABCI app** (name for built-in, URL for self-written if it's publicly available): Cosmos-sdk

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **Install tools**:
- **Others**:

**What happened**:

When querying the Tendermint RPC I was not able to receive the entire genesis due to the network request timing out.

**What you expected to happen**:

Receive the entire genesis file

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

Visit https://rpc.cosmos.network/genesis?

**Proposed solution**

Introduce a new endpoint `genesis_chunk` which can be used to receive a specific chunk. The total amount of chunks will be sent within the response as well. 

The response will be:

```
{
  "chunk": 1,
  "total": 15,
  "data: <base64-blob>
}
```

**Comment by alexanderbez** [comment]
Just to clear it up a bit more,

The old `/genesis` endpoint will still exist, however, it will error if the genesis file is too large, stating chunking should be used.

**Comment by tychoish** [comment]
I wanted to follow up to this and ask some detailed questions, which we should hash out in the spec, but I think getting a sense of the desired behavior should be for this endpoint. My questions are: 

- How big should each chunk be? 

- I think making chunk size configurable doesn't seem necessary?

- Is there prior art in RPC layer for pagination/cursors that we should copy/use? It looks like block search has some kind of pagination, but is this the current best practice? 

- Should we provide access separately to the other metadata in the gensis doc (e.g everything except the `app_state` field,) and then just paginate the chunks, e.g. `/gensis/meta` for the metadata and have `/gensis/state` be paginated?

- I suspect that the existing data is slow for two reasons: first that it takes a lot of time to copy a big gensis block to the client, but also it's the case that the current state data is stored as a raw byte sequence which means it would need to be entirely re-serialized for each page, which means we probably want to break it apart into an array. 

- At what threshold should the existing gensis endpoint begin returning an error? 

- For the state data, `/gensis/state` above, should we write the state data as line-separated JSON or as a JSON array? If the former, should we try for some kind of streaming approach rather than pagination?

Thanks!

**Comment by cmwaters** [comment]
Here are my very subjective answers

> How big should each chunk be?

The genesis size for the `cosmoshub-3` is 60mb. Apparently the `cosmoshub-4` is 120mb. It looks like AWS usually has a max payload size of 10mb. So I would estimate somewhere between 1 and 10mb

> I think making chunk size configurable doesn't seem necessary?

I tend to agree

> Is there prior art in RPC layer for pagination/cursors that we should copy/use? It looks like block search has some kind of pagination, but is this the current best practice?

If you want to instil a best practice then you will need to apply it to all the other places that we use pagination. My sense is to just copy how we do `/validators` or `/block_search` but it depends on how strongly you feel about this.

> Should we provide access separately to the other metadata in the gensis doc (e.g everything except the app_state field,) and then just paginate the chunks, e.g. /gensis/meta for the metadata and have /gensis/state be paginated?

It's a nice idea but I don't think it's necessary and I wouldn't worry about it for the first iteration

> I suspect that the existing data is slow for two reasons: first that it takes a lot of time to copy a big gensis block to the client, but also it's the case that the current state data is stored as a raw byte sequence which means it would need to be entirely re-serialized for each page, which means we probably want to break it apart into an array.

I don't quite understand what you're saying here. Are you suggesting that state should be `[][]byte`? 

> At what threshold should the existing gensis endpoint begin returning an error?

I was thinking for simplicities sake that the moment it is bigger than a single chunk it should return an error

> For the state data, /gensis/state above, should we write the state data as line-separated JSON or as a JSON array? If the former, should we try for some kind of streaming approach rather than pagination?

I'm not familiar with the streaming approach. Does it require any extra effort on the client side?

**Comment by tychoish** [comment]
> > Should we provide access separately to the other metadata in the gensis doc (e.g everything except the app_state field,) and then just paginate the chunks, e.g. /gensis/meta for the metadata and have /gensis/state be paginated?
> 
> It's a nice idea but I don't think it's necessary and I wouldn't worry about it for the first iteration

I actually think the separate approach is a bit easier/clearer to implement because it means we don't have to resend the metadata in each response. But I don't think it matters. 

> I don't quite understand what you're saying here. Are you suggesting that state should be [][]byte?

I think that's probably the best way to do it internally. Probably actually it'd be `[]json.RawMessage`, but this might be the main delicate response.

> I'm not familiar with the streaming approach. Does it require any extra effort on the client side?

Depends on the protocol/etc, but for things like gRPC or websockets we could just write documents to the socket and use the client to provide backpresseure, though I don't know as much about our RPC layer.

**Comment by cmwaters** [comment]
> I actually think the separate approach is a bit easier/clearer to implement because it means we don't have to resend the metadata in each response. But I don't think it matters.

I don't know if many users would want just the genesis meta data. Also it could be quite large if there are a lot of validators. If you feel like it doesn't add too much overhead in work then I don't mind. You could also have it so that the first chunk is always the meta data (complete) and the following chunks are all the state data

**Comment by randomshinichi** [comment]
The [cosmos registrar](https://github.com/cosmos/cosmos-registrar) using tendermint 0.34.9 is experiencing this issue too when trying to register `cosmoshub-4`. Hopefully this can be solved soon.

Apparently the problem is using `ioutil.ReadAll()` tendermint/tendermint@v0.34.9/rpc/jsonrpc/client/http_json_client.go:220, which is [known not to handle large buffers well](https://haisum.github.io/2017/09/11/golang-ioutil-readall/).
