### ISSUE TITLE
[pubsub] there is too highly memory usage when creating many events subscriptions

### ISSUE THREAD

**Issue by banishee** [tendermint/tendermint#6439]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
before https://github.com/tendermint/tendermint/commit/a91680efee3653e3de620f24eb8ddca1c95ce8f9

**What happened**:
When I use a bot to make lots of events subscriptions to a node, I noticed that there is a huge increasing memory usage.
Then I checked the code, and I found there is an unreasonable initial slice with the **math.MaxInt16** length.
https://github.com/tendermint/tendermint/blob/a91680efee3653e3de620f24eb8ddca1c95ce8f9/libs/pubsub/query/query.peg.go#L440

For almost over ten thousand subscription clients, the node will take over 25 GB memory
![image](https://user-images.githubusercontent.com/48553537/117615036-c2223100-b19b-11eb-8e33-e30df2f850f3.png)

**What you expected to happen**:
I think it is better to lower the initial length, such as 16 (the length of most subscription types I tested are only using less than 16 )

**Have you tried the latest version**: yes/no
no 

**How to reproduce it** (as minimally and precisely as possible):
* run a local node
* make many subscriptions

**Comment by marbar3778** [comment]
Thank you for opening this issue. We are currently working on a refactor of the event system. We will be adding event sinks (https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-065-custom-event-indexing.md) with on being postgres. This allows you to query a postgres database instead of the tendermint node. Does this solve the problem for you?

**Comment by banishee** [comment]
> Thank you for opening this issue. We are currently working on a refactor of the event system. We will be adding event sinks (https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-065-custom-event-indexing.md) with on being postgres. This allows you to query a postgres database instead of the tendermint node. Does this solve the problem for you?

I mean, if I change the value of **math.MaxInt16** into **16**, does it have an influence on node?

**Comment by marbar3778** [comment]
> I mean, if I change the value of **math.MaxInt16** into **16**, does it have an influence on node?

The file you mention query.peg.go is auto generated. Generally we prefer to leave generated code untouched. 

@cmwaters @alexanderbez @tychoish what do you think, should we make an exception here?

**Comment by alexanderbez** [comment]
Using other event sinks won't fix this problem. This problem resides with `QueryParser#Init` and `QueryParser` is used for parsing queries to be used again the current `KV` event store. Given that this store will continue to exist even with the new event system sink(s), the `QueryParser` will remain to support the legacy `KV` sink.

So unless the author wants to run their own postgres instance, they still have to rely on this `KV` sink which has this interesting bit of code.

As to why we pre-allocate a slice of size `math.MaxInt16` is beyond me. I'm not familiar with this code at all. Based on the commit history, @melekes would be our best bet. I would say we should consider not pre-allocating at all, but I don't know what repercussions that has.

**Comment by melekes** [comment]
The temporary solution is add a caching layer -> https://github.com/tendermint/tendermint/issues/1770. I don't know why a single `Query` object takes so much memory. I believe it's best to ask https://github.com/pointlander by opening an issue in https://github.com/pointlander/peg.

**Comment by creachadair** [comment]
> The temporary solution is add a caching layer -> #1770. I don't know why a single `Query` object takes so much memory. I believe it's best to ask https://github.com/pointlander by opening an issue in https://github.com/pointlander/peg.

I think there were two main issues:

1. The packrat algorithm uses a lot of memory for caching, and the implementation does not appear to do the analysis necessary to only cache backtrackable productions.
2. The PEG query evaluator (matcher) re-walked the entire parse tree for every match, and that traversal allocated a lot of boxed values that escape to the heap.

I didn't do an exhaustive evaluation, but the rough profiling I did suggests the culprit was mainly (2). Anyway, both problems are now fixed by #7319, which I will backport into the v0.35 series so anyone who upgrades can get the benefits.
