### ISSUE TITLE
`/status` endpoint returns empty `version` 

### ISSUE THREAD

**Issue by RiccardoM** [tendermint/tendermint#6488]
**Tendermint version**:
Tetsted with `v0.34.4`, `v0.34.5`, `v0.34.6`, `v0.34.7`, `v0.34.8`, `v0.34.9`, `v0.34.10`

**ABCI app**: 
Tendermint Docker file - No app

**Environment**:
Tendermint Docker

**What happened**:
When calling the `/status` endpoint the returned `node_info.version` is always empty if Tendermint version if `>= 0.34.4`

**What you expected to happen**:
The `node_info.version` should return either the Tendermint version or the checksum of the version

**Have you tried the latest version**: yes/no
Yes

**How to reproduce it** (as minimally and precisely as possible):
1. Start a Tendermint Docker container 
2. Query the `/status` endpoint

**Comment by marbar3778** [comment]
You need to set this in you app via ldflags. Docs: https://github.com/tendermint/tendermint/blob/master/UPGRADING.md#version

**Comment by RiccardoM** [comment]
@marbar3778 I know, but is there a way to set this while running a Tendermint node using the Docker files? I'm doing so because I'm testing CosmJS and it used the Tendermint Docker images to run a local node and get the version from the `/status` endpoint

**Comment by marbar3778** [comment]
Hmm, it should be easy to get it. Will play with it

**Comment by webmaster128** [comment]
On the CosmJS side we'll adapt tests to not rely on the value of this field. As the version became completely unreliable with 0.34 we gradually migrated aways from it anyways. No offense though – it's just a matter of expectation management. This is no blocker for us.

**Comment by marbar3778** [comment]
> On the CosmJS side we'll adapt tests to not rely on the value of this field. As the version became completely unreliable with 0.34 we gradually migrated aways from it anyways. No offense though – it's just a matter of expectation management. This is no blocker for us.

Sorry about that. It's odd this started happening. Please feel free to ping us in chat or open an issue when things become unreliable, this shouldn't happen.

**Comment by webmaster128** [comment]
> It's odd this started happening. Please feel free to ping us in chat or open an issue when things become unreliable, this shouldn't happen.

It all began when Tendermint decided to move the version from the codebase to some place that is meta to the code (as you linked above). I understand the pain that comes with encoding the version into the source, but leaving it up to the caller to set a library's version seems to be unmaintainable.

A quick overview into our jurney:
1. Initially Tendermint 0.34 [provided versions starting with "0.34"](https://github.com/cosmos/cosmjs/pull/430/files#diff-8f4dff4b8115bd18e1f153ca917e4d41ffa6d594160c48c2bd985f1cfc1384b7)
2. At some point pre 0.34 we started [getting commit hashes](https://github.com/cosmos/cosmjs/pull/519) as version that change in an unpredictable way [as they are not semantic](https://github.com/cosmos/cosmjs/blob/v0.25.3/packages/tendermint-rpc/src/testutil.spec.ts#L52).
4. But we can [hack around it](https://github.com/cosmos/cosmjs/blob/v0.25.3/packages/tendermint-rpc/src/legacy/adaptors/index.ts#L31-L36) 💪 
5. Until we connect to chains using Tendermint, such as simd: https://github.com/cosmos/cosmos-sdk/issues/7963
6. Since we cannot wait 3 months for a fix that prevents connecting to a chain, so we [dropped auto-detection for Stargate chains](https://github.com/cosmos/cosmjs/pull/538)
7. The legazy Tendermint client that can connect to 0.33 and 0.34 still used version detection [but we're given that up](https://github.com/cosmos/cosmjs/pull/813) because of the bug described here (empty version in newer Tendermint docker images).
8. We now concluded that auto-detection is dead and the app developer needs to know in advance what backend they connect to. We still pass the version value to the caller, but unchecked. It can be a version, a hash or empty. We don't rely on it anymore.

**Comment by marbar3778** [comment]
seems like reverting that change would make the life of users better. Will see what the team thinks.

**Comment by webmaster128** [comment]
> seems like reverting that change would make the life of users better.

I think so, yes. It seems to be too easy to forget to set this version for the blockchains and nobody notices until CosmJS client come along and try to interprete Tendermint version value.
