### ISSUE TITLE
cli for indexing the missing events with PSQL server

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#6519]
## Summary

To implement the feature for handling the missing events if the PSQL server is disconnecting.

## Problem Definition

In ADR065, we implemented an eventsink with PSQL backend support. But it didn't handle the situation the node is indexing events but the PSQL server isn't under the running status. So, the events will be missing in the PSQL DB.

## Proposal

Add a CLI that can replay blocks for the missing events to the PSQL DB.
Can also implement #4371 within the same subcmd but different flags

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
Getting this in the next release would be a jump in better ux for node operators. 

Currently, we store events in two places, one in the event store and another in the ABCIResult store. We should take advantage of the abci.Result store in order to get the needed events. Replaying blocks may require application changes, this way we avoid that.

**Comment by alexanderbez** [comment]
I don't think we need a CLI command for this. I believe in the ADR I stated that we could just have a `resync?start_height=_&end_height=_` RPC endpoint.

**Comment by JayT106** [comment]
Ah, I see. Thanks.

**Comment by alexanderbez** [comment]
@JayT106 would this be something you'd like to work on?

**Comment by JayT106** [comment]
@alexanderbez, For sure, correctly just looking at some `jank` issues. I can do this if we want to make it in the next release.
