### ISSUE TITLE
p2p: PeerManager TryEvictNext Tests [P2P Audit]

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#6572]
`p2p.PeerManager#TryEvictNext` doesn't test conditions of above capacity. For robustness we need to ensure that even when we are above capacity, that we know how to evict peers but also that code doesn't crash.

**Comment by cmwaters** [comment]
How do we get to a situation where the peer manager is above capacity. I thought `Dialed` and `Accepted` were supposed to prevent such conditions?

**Comment by alexanderbez** [comment]
Good question. This was taken from the audit. I know `PeerManager#TryDialNext` maintains and checks the manager's `upgrading` set, which `Dial` uses. So it doesn't seem to me we ever get above capacity.

@odeke-em did you guys have anything specific in mind here?

**Comment by odeke-em** [comment]
@alexanderbez we are essentially asking per https://www.notion.so/P2P-Audit-official-report-eeb35cb35c784fd09649baa8a1f24071#488e8cf0f2154f53936b1c22b2e05547 that we test the code that deals with above capacity eviction
![image](https://user-images.githubusercontent.com/4898263/124674442-9788e780-de6f-11eb-9a6e-3eaac999543c.png)

An assumption that it can't happen still needs a test otherwise that code should then be deleted. If kept, not knowing how it'll behave makes for potential bugs. The severity is also LOW.

**Comment by cmwaters** [comment]
Hmm you're right. I looked through the code and I can't see a way that this part of the code may be triggered. I think this part was added just as an extra layer of protection. Maybe we can delete it. Wdyt @alexanderbez ?
