### ISSUE TITLE
Validate unconditional_peer_ids prior to establishing connection to app 

### ISSUE THREAD

**Issue by ValarDragon** [tendermint/tendermint#6759]
Unconditional peer ids get validated after InitChain runs. So if theres an error in the unconditional peer ID config, you only find out after InitChain terminates, which can take a potentially very long time. (In what I'm testing right now, ~45 minutes)

It'd be ideal if these (and generally other config parameters) could get validated before InitChain runs, so you can find out rather quickly.

**Tendermint version** : v0.34.10

**ABCI app**: Osmosisd

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible): Use an incorrect `unconditional_peer_id`, e.g. `{hash}@ip:port`, and then start any node from genesis.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:
```
4:07PM INF asserted all invariants duration=53015.563105 height=
275737 module=x/crisis
4:45PM INF Completed ABCI Handshake - Tendermint and App are syn
ced appHash= appHeight=0 module=consensus                       4:45PM INF Version info block=11 p2p=8 software=
4:45PM INF This node is a validator addr=9A0254C8584F4AA94D9FCAC
F39A187B388B61B6A module=consensus pubKey=IYmPnF6THLyXy1t6NECmfAQ7Fu0Q9oPgLbYeuiZUp4U=
4:45PM INF P2P Node ID ID=6c0b311e688c5c91192f64ec2892ba48d39e2a
7e file=/root/.osmosisd/config/node_key.json module=p2p
4:45PM INF Adding persistent peers addrs=[] module=p2p
4:45PM INF Adding unconditional peer ids ids=["e46a808d27f4bd837
b4c05de57c5c40cb6408289@157.0.0.0:26656"] module=p2p
Error: could not add peer ids from unconditional_peer_ids field:
 wrong ID #0: encoding/hex: invalid byte: U+0040 '@'
```

**Comment by cmwaters** [comment]
Make sense. AFAICS, in `master`, we do check all peers in the config file upon initialisation (i.e. before `InitChain` is run): 
https://github.com/tendermint/tendermint/blob/c3ae6f5b58e07b29c62bfdc5715b6bf8ae5ee951/node/setup.go#L504-L512

**Comment by cmwaters** [comment]
As a side question, what happened to `UnconditionalPeerIDs` @alexanderbez? Is this being deprecated in the new P2Pstack:
https://github.com/tendermint/tendermint/blob/c3ae6f5b58e07b29c62bfdc5715b6bf8ae5ee951/config/config.go#L661

**Comment by alexanderbez** [comment]
Great question @cmwaters. We currently don't have support for this in the new stack. We support persistent peers. I don't know if we want to support unconditional, but if we do, it'll be in the `peermanager.go`.

What do folks think?

**Comment by marbar3778** [comment]
are persistent peers in the new stack considered connections outside of max allowed connections? If so, we dont need it, if not then we would need it cause the previous issue, for why this was introduced will come back.

**Comment by cmwaters** [comment]
> are persistent peers in the new stack considered connections outside of max allowed connections?

In terms of the amount of connections they are considered the same as any other peer

**Comment by alexanderbez** [comment]
This is currently where we have the logic for dialing a next peer: https://github.com/tendermint/tendermint/blob/master/internal/p2p/peermanager.go#L468

**Comment by marbar3778** [comment]
> Do you have a link to the original issue?

not sure the issue, but I can describe it. 

When a validator lost connection to a sentry, the sentry may fill its spot in its addrbook. When the validator try to reconnect it can not because the sentry has a full addrbook. unconditional peers allows users to set a peer to connect, even if the sentry's addrbook is full.

**Comment by cmwaters** [comment]
In the new implementation, if the user sets up `MaxConnectedUpgrade` as non zero, then if the validator loses connection to it's sentry and then tries to dial again, it will get accepted and a currently connected peer that is lower scored will get kicked out.

**Comment by marbar3778** [comment]
> In the new implementation, if the user sets up `MaxConnectedUpgrade` as non zero,

is this documented? want to update the how to run a validator page?

**Comment by cmwaters** [comment]
I don't think so. I'll check and if not I will update it

**Comment by cmwaters** [comment]
It seems `MaxConnectedUpgrade` is hardcoded to 4. I don't know if we want to make that configurable or not

**Comment by cmwaters** [comment]
Going back to the issue at hand. It seems like we run the `Handshake()` with the application before initialising the peer manager which is the reason why we don't get these errors till afterwards. We do all this potential computation with replaying blocks in the constructor. I'm not sure if we want to move that logic to `OnStart()` because application state might diverge in between starting and stopping the Tendermint node and it just seems more intuitive to me that this happens when we start a node not when we are constructing it. If not, we should move the handshake to being one of the last things we do before returning the node struct

**Comment by alexanderbez** [comment]
Doing this in the constructor makes zero sense. Constructors should be as lightweight as possible, so I agree we should move this to `OnStart()`.

**Comment by tychoish** [comment]
I've been chipping away at this issue for a few weeks now, and after #8264 the handshake with the application is moved to the Start operation of the node rather than the constructor of the node. 

I think that means we can close this issue after that lands (in time for 0.36). I've read through this issue a few times, and I don't think that there's any more work that needs to be done here, but just holler if I've missed something.
