### ISSUE TITLE
rpc: `/tx` endpoint `hash` parameter encoding inconsistency

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#6802]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):

0.34.10

**ABCI app** (name for built-in, URL for self-written if it's publicly available):

kvstore

**What happened**:

It appears as though the expected encoding of the `hash` parameter for the [`/tx` RPC endpoint](https://docs.tendermint.com/master/rpc/#/Info/tx) differs between the URL-based and JSON-RPC-based interfaces:

- URL-based `hash` values are hexadecimal-encoded
- JSON-RPC-based `hash` arguments are base64-encoded

I think I've captured why and where the cause of this is here: https://github.com/informalsystems/tendermint-rs/issues/942

**What you expected to happen**:

These two interfaces to be consistently encoded, or for the RPC docs to include some kind of note about the difference in encoding between the two interfaces.

**Have you tried the latest version**: no

**How to reproduce it** (as minimally and precisely as possible):

```bash
# In one terminal
tendermint init
tendermint node --proxy_app kvstore

# ---
# In another terminal
curl 'http://localhost:26657/broadcast_tx_commit?tx="some-key=some-value"'
# tx hash is recorded as C659471A231AE0101E4F6574014446F0741DE9222ADDDF0E17087E908CF92432 in hex

# Get the tx using the URL-based interface
curl 'http://localhost:26657/tx?hash=0xC659471A231AE0101E4F6574014446F0741DE9222ADDDF0E17087E908CF92432'
# Returns successfully

# Get the tx using the JSON-RPC interface using the hex-encoded hash
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"method": "tx", "params": {"hash": "0xC659471A231AE0101E4F6574014446F0741DE9222ADDDF0E17087E908CF92432", "prove": false}, "id": 1}' \
  http://localhost:26657
# Returns error:
# {
#   "jsonrpc": "2.0",
#   "id": 1,
#   "error": {
#     "code": -32602,
#     "message": "Invalid params",
#     "data": "error converting json params to arguments: illegal base64 data at input byte 64"
#   }
# }

# Get the tx using the JSON-RPC interface using the base64-encoded equivalent of the original hex hash
curl -X POST \
  -H "Content-Type: application/json" \
  -d '{"method": "tx", "params": {"hash": "xllHGiMa4BAeT2V0AURG8HQd6SIq3d8OFwh+kIz5JDI=", "prove": false}, "id": 1}' \
  http://localhost:26657
# Returns successfully
```

**Comment by creachadair** [comment]
Thank you for your report! I agree, this is confusingly underspecified right now, and we will do our best to make it better.

The root of the issue is that binary data (including hashes and transaction blobs) are conventionally encoded in JSON as string values in base64. However, the URL processing code doesn't know about base64: It accepts either `"quoted literal strings"` (not base64-encoded) or hexadecimal-encoded bytes with a `0x` prefix (as described in the [schema doc](https://docs.tendermint.com/master/rpc)).

However, it appears at least some of the API paths encode hash outputs back to hexadecimal. This accurately reflects what the OpenAPI schema says, but I don't know if it's actually intended: The internal plumbing treats hashes as byte arrays. Currently those byte arrays carry ASCII-encoded hex digits, but I am guessing that wasn't the intention.

So I think we pretty clearly have at minimum a documentation bug here. We may in addition have an extra encoding/decoding step that wasn't intended. Fortunately the hash is not being mangled or changed by this transformation—but we clearly need to get all the code paths and the documentation to show a consistent state of affairs.

**Comment by creachadair** [comment]
After some further investigation, I think I now understand why the JSON endpoint is (IMO incorrectly) insisting on the hash being base64 encoded in some contexts but not others.

- Most of the service plumbing expects hashes to be hex-encoded (using the [`HexBytes`](https://pkg.go.dev/github.com/tendermint/tendermint/libs/bytes#HexBytes) type in the Go code).
- However, when the service parses JSON-RPC requests, it does so by [reflection over the arguments of the method handler](https://github.com/tendermint/tendermint/blob/31994cadc0f89d8cd57c23cd5400a6ed039b8acc/rpc/jsonrpc/server/http_json_handler.go#L163). 
- For the `"tx"` request in particular, the reflective type of the hash argument is `[]byte`, which the [encoding/json](https://godoc.org/encoding/json) package expects to be base64-encoded.

As a result, the current code requires double-encoding of hash arguments when transmitted as a JSON request via HTTP. I suspect (though I have not completely traced it out) that using the "real" JSON-RPC endpoint will not suffer from this problem.

**Comment by thanethomson** [comment]
Thanks @creachadair! Do you think this warrants implementing a change here then? If so, what version of Tendermint would that change target? (it's effectively a minor breaking change to the RPC)

I'm implementing a [fix](https://github.com/informalsystems/tendermint-rs/pull/948) on the `tendermint-rs` side that will use base64 encoding for now, but is easy to change back to hexadecimal encoding (just involves removing 1 line of code).

**Comment by creachadair** [comment]
In my view this definitely needs to be fixed. It is a breaking change, but one that I think we should make as a bug fix, on the principle that anyone who was relying on this behaviour previously was already working around an obviously-incorrect behaviour. I believe this can only happen with requests sent as JSON to the HTTP endpoint, so it shouldn't (at least in principle) affect folks using the library interfaces to the service.
