### ISSUE TITLE
backport event fixes

### ISSUE THREAD

**Issue by marbar3778** [tendermint/tendermint#6828]
## Summary

The ibc relayers have asked to back port the postgres event sink work along side the refactor of event subscription to 0.34. The event subscription should be put behind a feature flag to prevent causing a larger event system break. 

The reason for the back port is to use these features with current chains instead of waiting for them to come at a later date and then refactor parts of the relayers another time.

- [x] Backport postgres event sink (#6906).
- ~Backport event subscription (#6955).~

cc @jackzampolin @andynog

**Comment by tessr** [comment]
on the SDK call, Jack just mentioned it would be great to get this released in the next month or two. I think that's probably doable :)

**Comment by creachadair** [comment]
I will look into this soon. Since I'm not completely familiar with the history here, can you point me to the PRs for the specific features you'd like to have backported?

**Comment by tessr** [comment]
^ @marbar3778 @jackzampolin

**Comment by marbar3778** [comment]
yea!!

This would need to be behind a feature flag https://github.com/tendermint/tendermint/pull/6634
This would not need to be behind a feature flag https://github.com/tendermint/tendermint/pull/6411/files, but will be a bit harder.

**Comment by alexanderbez** [comment]
Correct, both #6634 and #6411 would need to be back-ported, but I believe they're both breaking go APIs so they both need to be behind a single feature flag I think?

**Comment by tessr** [comment]
Just talked with @aaronc and @alexanderbez about this, and we'd like to make these fixes (https://github.com/tendermint/tendermint/issues/6843) before backporting. @creachadair, do you think you can take those on as well? Bez has offered to be a resource.

**Comment by creachadair** [comment]
> Just talked with @aaronc and @alexanderbez about this, and we'd like to make these fixes (#6843) before backporting. @creachadair, do you think you can take those on as well? Bez has offered to be a resource.

I'm glad to try, though at the moment I don't fully understand the implications of what #6843 proposes. You describe these as "fixes" but that issue looks like it's proposing a new indexing schema, I think? I am interested, because I could learn a lot from doing it, but if you need this quickly I may not be your best bet. 🙂

**Comment by tessr** [comment]
Not a big rush. @alexanderbez has the full context and can share. (It is a new indexing schema, but it fixes problems with the old one--namely flattening data in such a way that it can't be properly reconstructed.)

**Comment by aaronc** [comment]
#6843 also identifies issues which will cause constraint violations at runtime which is another reason it's framed as a fix

**Comment by creachadair** [comment]
A question for anyone concerned with this issue. Probably @marbar3778 and @jackzampolin based on the comments above, but please feel free to tag in anyone else who may care.

I am currently working on backporting the changes from #6634 into the v0.34.x series.  The change is functionally not that complex—the main substance is to change the type used to plumb event attributes into and out of the query from a map to a slice of structs.

However, in doing so it breaks Go API compatibility in a couple ways that are tricky to flag around: 

- The types of some existing names are changed (event keys were renamed like `BlahEvent` → `BlahEventValue`, and `BlahEvent` was re-typed to be a query); and
- The `Matches` method of the `Query` interface had its type signature changed. 
 
The type change is tricky to flag away because the type of the declaration is fixed at build time. I might be able to finesse it with empty interfaces—depending on how the client code uses the values—but it's hard to check. The interface change may be a showstopper, though, for any implementations outside the `pubsub` package: Interface satisfaction is not contravariant on argument types (cf. https://play.golang.org/p/0WfXr_44duK).

So, my question is: How important is it to backport this change cleanly? Specifically, I'd like to know:

1. Was getting this backported meant to unblock porting the PostgreSQL indexer?
2. If so: Now that the `psql` event sink has been backported, could we do without it?
3. If not: Can you share or point to some existing usage that wants to benefit from this change?

Note that Question (3) is not about proving that a need exists, but for me to get some concrete examples I can use to guide which disgusting hacks I can afford to use in the backport, while still giving callers what they want. 🙂

**Comment by creachadair** [comment]
Following on from https://github.com/tendermint/tendermint/issues/6828#issuecomment-918542731, I have prepared #6955 to backport the changes from #6634 into the v0.34.x series. Anyone following this issue and who wants to make use of this change, can I please get your eyes on that PR?

**Comment by creachadair** [comment]
Based on some feedback in [discord](https://discord.com/channels/808343014225084416/814903186266521641/890877725454245928), we decided not to merge #6955 at this time.

With that in mind I'm closing this issue as resolved, but if anyone has further questions or concerns, please feel free to reopen it to discuss them (or to start new issues).
