### ISSUE TITLE
Further candidates for internalization

### ISSUE THREAD

**Issue by cmwaters** [tendermint/tendermint#6937]
## Summary

Most reactors have been moved into an `internal` folder (https://github.com/tendermint/tendermint/pull/6547) to reduce the surface of the public API's. I would like to propose a few more packages to be internalized (some of which might require further discussion):
- state
- store
- proxy (if we move the `ClientCreator` interface into the `abci` package.

I'm also thinking that it might be too late to put them in 0.35 since we've already released the first candidate but maybe it doesn't matter.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
I'm generally in favour of this, though I'd be mildly inclined to push it out past the 0.35 release so that we don't complicate the ABCI++ reviews any further. Or if we think these changes wouldn't affect that integration too much—but moving stuff into the `abci` package seems likely to leave a mark.

Apart from the SDK, do we have a list of other "known important users" of the TM libraries? If not, I can do a bit of digging to see how messy this might be for downstream.

**Comment by cmwaters** [comment]
> Apart from the SDK, do we have a list of other "known important users" of the TM libraries? If not, I can do a bit of digging to see how messy this might be for downstream.

Not that I know of (perhaps @marbar3778 has a better idea). I have instead a rough map in my mind of Tendermint users. It may be better to have some form of an explicit list.

In any case, I think `state` is basically unreachable given that most of the `Node` API's have been internalized.

**Comment by tychoish** [comment]
I actually think these are much less disruptive than it might appear because these are all used internally by the node package and there isn't really a use case for using them outside of the node construction.
