### ISSUE TITLE
error during handshake

### ISSUE THREAD

**Issue by p4u** [tendermint/tendermint#7039]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.34.12

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
vocdoni

**Environment**:
- **OS**: Debian 10

**What happened**:
After some benchmarking (launch test with thousands of transactions) one of the miners crashed (because of memory, probably a leak on our side) and then it is not possible to start it again. The `node.NewNode()` method fails when trying to handshake for replying blocks.

The error is originated on this line https://github.com/tendermint/tendermint/blob/v0.34.12/node/node.go#L309 with message `could not find results for height #30354`

```
2021-10-01T08:16:34Z	INFO	vochain/app.go:221	tendermint Core version: 0.34.12
2021-10-01T08:16:34Z	INFO	vochain/app.go:222	tendermint P2P protocol version: 8
2021-10-01T08:16:34Z	INFO	vochain/app.go:223	tendermint Block protocol version: 11
2021-10-01T08:16:34Z	INFO	vochain/app.go:232	replaying blocks. Current height 30354, current APP hash dad622aa0e2e364f87dd119eab5ead8e72cd6f07f731ce8aa43ef892f81ef015
2021-10-01T08:16:34Z	FATAL	vochain/start.go:36	could not set application Node: failed to create new Tendermint node: error during handshake: error on replay: could not find results for height #30354
go.vocdoni.io/dvote/vochain.NewVochain
	go.vocdoni.io/dvote/vochain/start.go:36
go.vocdoni.io/dvote/service.Vochain
	go.vocdoni.io/dvote/service/vochain.go:113
main.main
	go.vocdoni.io/dvote/cmd/dvotenode/dvotenode.go:508
runtime.main
	runtime/proc.go:255
```

**What you expected to happen**:
Some kind of automatic recovery method to allow the node start.

**Comment by p4u** [comment]
Could it be related to https://github.com/tendermint/tendermint/issues/6738 which is fixed on release .13 ?

**Comment by p4u** [comment]
Oh, so we are actually using 0.34.13, however the version number was not updated, so the tendermint version reported is wrong @tessr https://github.com/tendermint/tendermint/blob/v0.34.13/version/version.go#L10

**Comment by cmwaters** [comment]
> Could it be related to #6738 which is fixed on release .13 ?

I don't think so. This would show an error with the `PrivValidator`. It looks like your miner was in a state whereby the blockstore and the application stopped at 30354 but the state store was one behind (30353). Tendermint then tried to load the ABCI responses at height 30354 in order to replay the last block and update state to 30354 but as you can see the ABCI responses weren't there. This could have something to do with the atomicity of our operations. I will dig into it a little further. Thanks for submitting the issue.

**Comment by cmwaters** [comment]
> Oh, so we are actually using 0.34.13, however the version number was not updated, so the tendermint version reported is wrong @tessr https://github.com/tendermint/tendermint/blob/v0.34.13/version/version.go#L10

Good spot. I think we'll release an 0.34.14 soon and we'll make sure we remember to update the version number

**Comment by ed255** [comment]
Hi.  I'm from the vocdoni team and I think our code was causing this issue, because in `Info` we were returning a height corresponding to a block that in certain situations was started but didn't end in the previous run (didn't reach `EndBlock` + `Commit`).  I think that by returning a height in `Info` of the last ended block, this issue shouldn't occur.
