### ISSUE TITLE
v0.35: unclear how to use the mempool now that it's internal

### ISSUE THREAD

**Issue by mvdan** [tendermint/tendermint#7041]
Take a look at this code:

https://github.com/vocdoni/vocdoni-node/blob/c7cb23773a8709cdb006cc4230f1ca483c81cc57/vochain/app.go#L89-L91

Unfortunately this breaks with the upgrade to v0.35. I fully understand that making the mempool package internal, and making `node.New` return a smaller interface, have been intentional changes.

That said - how should we update the code to keep it working? With `Node.Mempool` now being a hidden method, and `mempool.TxInfo` now being an internal type, it seems like that piece of code just can't work with v0.35.

cc @p4u

**Comment by cmwaters** [comment]
Hey, the expected path for interacting with the mempool would be via RPC. There is [`/check_tx`](https://docs.tendermint.com/master/rpc/#/Tx/check_tx) call that you can make to verify a transaction against the application.

I'm not sure how vocdoni currently interfaces with tendermint's RPC server but you could do something like this:

```go

import rpc "github.com/tendermint/tendermint/rpc/client/http"

func CheckTx(tx []byte) error {
    client, err := rpc.NewClient("http://127.0.0.1:26657)
    if err != nil {
         return err
    }
    return client.CheckTx(tx)
}

```

**Comment by mvdan** [comment]
That makes sense, thank you - we'll give it a try.

I assume only the generic mempool operations would be available? A while back we added a custom CListMempool method (https://github.com/tendermint/tendermint/pull/5066) which we still use, and I don't see it in the HTTP RPC docs.

**Comment by cmwaters** [comment]
Yeah, only the calls listed by the RPC would be available.

Actually the ability to remove specific transactions was something that was brought up by another team the other day. They were having problems with transactions being stuck in the mempool. We might discuss this at our next meeting. Would you want this method for the same aforementioned reason?

I would like to add that the new v1 mempool comes with TTL semantics on all transactions which might be a feature that may help your use case

**Comment by tychoish** [comment]
Just to be clear, as well there's a local RPC client that allows you to access the RPC interface but skips the serialization and should be essentially the same from a performance perspective as your code. It's in the `"github.com/tendermint/tendermint/rpc/client/local"` package, and you'd do something like: 

```go
client, err := local.New(node.(local.NodeService))
```

The method you're looking for is probably `client.BroadcastTxSync()`.

**Comment by p4u** [comment]
Hello @cmwaters and @tychoish.
We decided not to use the tendermint RPC long ago since it is a non-necessary layer and a bottle neck. Instead we use Tendermint as a GoLang library so we have a much better comunucation layer (without inecessary HTTP headers), better error handling and complete control over the implementation. Here you can read some more details regarding this approach https://blog.aragon.org/vochain-a-blockchain-optimized-for-voting/

Regarding the mempool we disabled the transaction recheck (https://github.com/vocdoni/vocdoni-node/blob/master/vochain/start.go#L208) that enables tendermint by default (making all mempool transactions to be re-executed after every block commited), so we need a way to sanitize the mempool (else some transactions might live forever in the node's mempool). Here you can read about our transaction lifecycle: https://docs.vocdoni.io/architecture/services/vochain.html#transaction-lifecycle

As an example, here you can see how we use a call to `CListMempool` in order to remove a transaction https://github.com/vocdoni/vocdoni-node/blob/master/vochain/app.go#L147
Actually it was me who added this method in order to be able to have more control over the tendermint mempool (https://github.com/tendermint/tendermint/commit/137025ca73623eb00ee4ca4458001b04d028ba8e)

I have been pushing for some time in order to make Tendermint a more powerful golang friendly library and not just an RPC service. In my opinion that's the best way to achieve the great potential Tendermint provides, specially if someone wants to build a high performance blockchain.

So I'd like to ask tendermint core devs (@cmwaters, @marbar3778, @erikgrinaker, @tessr) to take into account this approach. I understand Cosmos SDK approach is to provide a one-click blockchain framework for developers, but please, do not forget those who want (and need) less abstraction layers and to have full control over Tendermint :smiley:

**Comment by mvdan** [comment]
To add to what @p4u said - I fully understand wanting to reduce Go API surface, especially when it comes to packages that under no circumstances should be used directly by downstreams. We ran into eight "missing package" errors when trying to upgrade, and I was able to fix or work around nearly all of them - except the mempool. I'd hope that interacting with the running node and its mempool does not fall under the "should never be used" category :)

**Comment by tychoish** [comment]
> We decided not to use the tendermint RPC long ago since it is a non-necessary layer and a bottle neck. Instead we use Tendermint as a GoLang library so we have a much better comunucation layer (without inecessary HTTP headers), better error handling and complete control over the implementation. 

I think we're getting caught up a bit on some of the terminology. The "local" RPC interface/implementation simply mirrors all of the
RPC methods, but without the HTTP headers/infrastructure: using this interface is really just like calling the method directly within the go library. Indeed [this implementation](
https://github.com/vocdoni/vocdoni-node/blob/c7cb23773a8709cdb006cc4230f1ca483c81cc57/vochain/app.go#L89-L91) is nearly the same implementation as what our "RPC" implementation is doing. Again, "RPC" is probably a poor term in this case, because it's not "remote", it's really just a function call from the perspective of your application, and the Client interface, makes it possible to describe a smaller, more consistent, and hopefully stable interface that also permits development and improvement without always breaking downstream users. 

One of the challenges of the mempool extensibility, is that in 0.35, tendermint introduces a second mempool implementation that allows applications (via a new field the response of `CheckTx`) to specify a priority for the mempool, which the new `v1` mempool uses to prioritize transactions. If this field is not specified by `CheckTx` then the behavior of the new mempool should be identical to the legacy `v0` mempool (which is also available as an option in 0.35.) The new mempool gossips transactions in the same fifo order that the legacy mempool used. Additionally the new mempool has a TTL capability for removing stale transactions after a time. It's our hope that these improvements and features will actually answer a lot of the core use cases that you bring up, and hopefully in a way that just works. 

If there's a specific operation (like `removeTxByID` or similar) that is a blocker to your workflow, we can definitely talk about adding that functionality in directly (and in a way that would work with both versions of the mempool, and would be easier to maintain for everyone,) that seems like a very productive conversation to have.

**Comment by p4u** [comment]
Oh I see @tychoish, the `rpc/client/local` package looks good (I agree that RPC is not a good name :+1:)

We need the RemoveTxByID method exposed cause we have our own transaction cache with its own purging mechanism. Once the transaction is removed from the cache, it must be also removed from the mempool (else we would have a loop and de tx would be again processed by CheckTx and added to the cache). I agree we could try to use the same TTL strategy on both mempool and cache and hope they both are removed in the same instant, but that looks risky. I'd prefer to be able to control the removal of mempool transactions from our application.

I also have another petition (now that you are breaking the whole API) regarding the mempool. Could you expose some method to get the P2P information for a transaction ID? This way in CheckTx() we can identify who is the node sending the transaction and build a kind of "trusted ring of nodes" in the network. If the transaction comes from a trusted node, perform a soft-check (much cheaper) instead of a full transaction check. 

Finally it would be great if we can set Tendermint to run the Mempool CheckTx async in order to parelallize the mempool transaction execution. Obiously that's an advanced feature that requires the application CheckTx method to be safe for asynchronous execution, but if done correctly the performance (transactions per second) could be much better.

**Comment by tychoish** [comment]
We should sync up with @marbar3778 about some of these use cases, because I have the suspicion that some of the current work with ABCI++ might go a long way to addressing your usecases about fast-path recheck tx workload and adding additional information to the transaction about the submitting peer. I suspect that, in the short term, adding this additional information about the gossiping patterns to transactions would be a pretty invasive change, though it might be possible to do some of that work in the application itself. Having said that, I'm not the best person to answer questions about the finer points. ,(ABCI++ covers the revision to the ABCI interface that's set to ship in 0.36, but work is already well underway.)

See [the ABCI++ spec](https://github.com/tendermint/spec/blob/master/rfc/004-abci%2B%2B.md} for more context. 

Perhaps it'd also be useful to understand more details about the transaction cache that you're maintaining in the application: it seems like maintaining parallel copies of pending transactions seems potentially frustrating, but without more context I feel likely to get mired in implementation details. I'm excited to find a path forward for your use case.

**Comment by p4u** [comment]
>  I suspect that, in the short term, adding this additional information about the gossiping patterns to transactions would be a pretty invasive change

AFAIK this information is available on the tendermint side, its just not exported to the application layer. My proposal would be to write a method on `rpc/client/local` in order to retrive the p2p information from a transaction identifier. So it should not break the CheckTx() backwards compatibility. 

 > Perhaps it'd also be useful to understand more details about the transaction cache that you're maintaining in the application: it seems like maintaining parallel copies of pending transactions seems potentially frustrating, but without more context I feel likely to get mired in implementation details. I'm excited to find a path forward for your use case.

We are not maintaining a parallel copy of a transaction. What we save in the cache is the digested transaction information, such as: signature is validated, hashes are computed, proofs are correct, etc. Thus we don't need to process again the expensive operations on DeliverTx if they have been already processed on CheckTx() and are available in the cache.

**Comment by marbar3778** [comment]
> We should sync up with @marbar3778 about some of these use cases, because I have the suspicion that some of the current work with ABCI++ might go a long way to addressing your usecases about fast-path recheck tx workload and adding additional information to the transaction about the submitting peer. I suspect that, in the short term, adding this additional information about the gossiping patterns to transactions would be a pretty invasive change, though it might be possible to do some of that work in the application itself. Having said that, I'm not the best person to answer questions about the finer points. ,(ABCI++ covers the revision to the ABCI interface that's set to ship in 0.36, but work is already well underway.)
> 
> See [the ABCI++ spec](https://github.com/tendermint/spec/blob/master/rfc/004-abci%2B%2B.md) for more context.

Hey, catching up here. ABCI++ wont change any of the behaviour around rechecktx or checktx. This would be a separate change from what is being worked on.

**Comment by cmwaters** [comment]
@p4u, I'm going to close this initial issue as being resolved now. Looking over the conversations it seems that a few other ideas were brought up. RemoveTx by id was introduced in #7047. I will open a new issue in regards to passing p2p related information to the application on `CheckTx`. Finally, in regards to the thread:

> It would be great if we can set Tendermint to run the Mempool CheckTx async in order to parelallize the mempool transaction execution. Obiously that's an advanced feature that requires the application CheckTx method to be safe for asynchronous execution, but if done correctly the performance (transactions per second) could be much better.

We are looking at removing the global mutex we have around the local client which would allow for concurrent execution abs may help in your use case. See https://github.com/tendermint/tendermint/issues/7073
