### ISSUE TITLE
Double registration of prometheus metrics

### ISSUE THREAD

**Issue by firelizzard18** [tendermint/tendermint#7076]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.35.0-rc3

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
Built in, https://github.com/AccumulateNetwork/accumulated

**Environment**:
- **OS** (e.g. from /etc/os-release): Gentoo Linux
- **Install tools**: VSCode, Go 1.17

**What happened**:

`node.New` [calls](https://github.com/tendermint/tendermint/blob/98bc4f0e2b600964bf07e9d85b2a0497c0d7d34c/node/node.go#L1055-L1074) `consensus.PrometheusMetrics` and friends which call `prometheus.NewGaugeFrom` and friends which register Prometheus collectors. This should be refactored so that the Prometheus gauges are only created once, even if `node.New` is called more than once. Otherwise:

```
panic: duplicate metrics collector registration attempted [recovered]
	panic: duplicate metrics collector registration attempted

goroutine 62 [running]:
testing.tRunner.func1.2({0x10179c0, 0xc0000a8fe0})
	/usr/lib/go/src/testing/testing.go:1209 +0x24e
testing.tRunner.func1()
	/usr/lib/go/src/testing/testing.go:1212 +0x218
panic({0x10179c0, 0xc0000a8fe0})
	/usr/lib/go/src/runtime/panic.go:1038 +0x215
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc0001354a0, {0xc0001354e0, 0x1, 0x0})
	GOPATH/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:403 +0x7f
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	GOPATH/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:178
github.com/go-kit/kit/metrics/prometheus.NewGaugeFrom({{0x0, 0x0}, {0x1102bf9, 0x9}, {0x10ff058, 0x6}, {0x110e4ca, 0x14}, 0x0}, {0xc0001354a0, ...})
	GOPATH/pkg/mod/github.com/go-kit/kit@v0.12.0/metrics/prometheus/prometheus.go:58 +0x127
github.com/tendermint/tendermint/internal/consensus.PrometheusMetrics({0x0, 0x0}, {0xc000746cc0, 0x2, 0x2})
	GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.35.0-rc3/internal/consensus/metrics.go:75 +0x265
github.com/tendermint/tendermint/node.defaultMetricsProvider.func1({0xc00660c4b0, 0xc})
	GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.35.0-rc3/node/node.go:1059 +0xb1
github.com/tendermint/tendermint/node.makeNode(0xc0011b0f20, {0x13b38d0, 0xc0010fa000}, {{0xc00056e300, 0xc00d0ec400}, {0x13caf80, 0xc0010e81f8}}, 0x0, 0xc001168040, 0x1289410, ...)
	GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.35.0-rc3/node/node.go:246 +0xbee
github.com/tendermint/tendermint/node.New(0xc0011b0f20, {0x13c45d0, 0xc000178230}, 0xc00d0dc380, 0x0)
	GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.35.0-rc3/node/public.go:54 +0x2c5
github.com/AccumulateNetwork/accumulated/internal/node.New(0xc0011b0f20, {0x13df758, 0xc00d0d8a80})
	SRCDIR/accumulated/internal/node/node.go:45 +0xf5
github.com/AccumulateNetwork/accumulated/internal/testing.NewBVCNode({0xc0010ecbd0, 0xc000600680})
	SRCDIR/accumulated/internal/testing/node.go:93 +0x61b
github.com/AccumulateNetwork/accumulated/internal/node_test.TestNodeSetupX(0xc000600680)
	SRCDIR/accumulated/internal/node/node_test.go:36 +0x105
testing.tRunner(0xc000600680, 0x1288508)
	/usr/lib/go/src/testing/testing.go:1259 +0x102
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:1306 +0x35a
FAIL	github.com/AccumulateNetwork/accumulated/internal/node	0.034s
```

**What you expected to happen**:

`node.New` should not panic the second time.

**Have you tried the latest version**: yes

**How to reproduce it** (as minimally and precisely as possible):

- Write two tests in the same package that call `github.com/tendermint/tendermint/node.New`
- Run `go test` in that package

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

Everything is normal until it panics.

**Config (you can paste only the changes you've made)**:

```go
config.P2P.ListenAddress = fmt.Sprintf("%s:%d", ip, port+tmP2pPortOffset)
config.RPC.ListenAddress = fmt.Sprintf("%s:%d", ip, port+TmRpcPortOffset)
config.RPC.GRPCListenAddress = fmt.Sprintf("%s:%d", ip, port+tmRpcGrpcPortOffset)
config.Instrumentation.PrometheusListenAddr = fmt.Sprintf(":%d", port+tmPrometheusPortOffset)
config.Instrumentation.Prometheus = true
config.P2P.AddrBookStrict = true
config.P2P.AllowDuplicateIP = false
config.Moniker = "Node0"
config.Accumulate.API.JSONListenAddress = fmt.Sprintf("%s:%d", ip, port+accRouterJsonPortOffset)
config.Accumulate.API.RESTListenAddress = fmt.Sprintf("%s:%d", ip, port+accRouterRestPortOffset)
```

**Comment by williambanfield** [comment]
Thanks for filing and thanks for using the RCs. The issue here is that `gokit` uses the prometheus global register and we use `gokit` for metrics within the node package. It'll be a little hairy to untangle this since `gokit` [doesn't appear to offer way to pass a registry through in its prometheus functions](https://github.com/go-kit/kit/blob/master/metrics/prometheus/prometheus.go).

We have a few options: 
1. Override the default prometheus registry each time we start a node so `gokit` doesn't re-register. I don't really like this option very much since it really gets the worst of both worlds: having global state while also using it like a parameter. It allows us to keep using GoKit but is ultimately a little hacky.
2. Specify different namespaces for each node started within Tendermint. This would allow us to register the metrics multiple times, but with different names. Means operators running multiple nodes in a process would need to construct different dashes for each node in a process instead of relying on labels which isn't ideal.
3.  Remove GoKit and use prom directly. 
4. Pass the metrics through as part of the constructor. This would allow the code constructing the node to handle the metrics how it wanted. 


@firelizzard18 Is using multiple nodes within a single binary something you're currently targeting? I'm interested to understand the use case a bit more if possible. Thanks!
