### ISSUE TITLE
Request for simplified implementation of Encoding's in Header.Hash

### ISSUE THREAD

**Issue by garvitgoel** [tendermint/tendermint#7193]
We are trying to implement the tendermint light client in `circom`(A DSL for ZK-SNARKS). In order to do this, we are facing issues wrt to some of the encoding protocols used in tm.

In the `header.hash` given at, https://github.com/tendermint/tendermint/blob/5cc980698a3402afce76b26693ab54b8f67f038b/types/block.go#L448, we are in need of simplified implementation of the `Version.Marshal()` function. (Protobuf's are not available in circom), that would make it easier to implement the encoding in circom.
We are facing similar issues with `gogotypes.StdTimeMarshal()` and `cdcEncoding()`
Solving this issue ourselves would require going deep into these protocols, which we would wanna avoid as much as possible.
We are willing to open-source our circom implementation, if it helps!

**Comment by creachadair** [comment]
It's not clear to me how to get a good solution to this problem without either using protobuf or re-implementing its encoding rules.

As you observed, the `Hash` function you pointed to here is defined in terms of the protobuf wire encoding for a `Version`. While the [protobuf wire format](https://developers.google.com/protocol-buffers/docs/encoding) is not all that complicated, there isn't a simple way of getting the wire encoding of a _particular_ message without either (a) understanding the structure of that message and re-implementing the encoding, or (b) depending on the protobuf machinery.

If (b) is ruled out, the only way forward seems to be for someone to implement a workaround for (a). Tendermint doesn't have that implementation, since it relies on the protobuf machinery to do it. I'm not sure it makes sense for us to build a workalike here, since that would only duplicate the functionality we already get from protobuf, and we'd have to manually keep them in sync (which would kind of defeat the point of using protobuf).

For that reason, my intuition is that your best bet is to implement the encoding directly. But if I have missed some aspect of your request, please let me know.
