### ISSUE TITLE
indexer: unbuffered event subscription slow down the consensus.

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#7247]
## Summary

The indexer is listening to the tx/block event using  `SubscribeUnbuffered`, it guarantees the tx/block data will be indexed after a new block is committed into the DB. However, if the indexer is performing badly,  the node will be out of sync with the network.

## Problem Definition

When a node is running with an indexer service using the default `kv` indexer with v0.34.x, we observed the node sometimes will out-of-sync. The node spent a lot of time indexing new events (and the I/O loading was almost occupied). 
Once the tx/block is indexed, and then the node can go sync with the next block.

Therefore, there are two issues in this case:
1. The kv indexer with goleveldb might be not performing well. it causes heavy load disk I/O. So it took a few seconds to finish event indexing.
2. The indexer uses `SubscribeUnbuffered` to listen to the events. it will block `state.ApplyBlock`. So the consensus cannot be continued.

## Proposal

the indexer service should not block the consensus, maybe do async and handle the event properly (like when the event is missing, there is a way to recover/reindex it) 

similar issue https://github.com/tendermint/tendermint/issues/3210

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
Thanks for the issue. This is a topic we're actively thinking about, and your feedback is helpful.

There are definitely some improvements we can make in this area (see #7156 for some examples of ongoing work).  More generally, the way to really solve this problem is to make indexing faster. For example: Switching from the KV indexer to Postgres is likely to help quite a bit even without other changes, since the KV indexer thrashes with large volumes of data and contention.

One point that's worth highlighting here is that making the current indexer asynchronous is almost certainly not the right solution. To understand why, consider the two general cases:

- If indexing _does_ have to be synchronized with transactions in the network, making the indexer asynchronous only converts lock/write contention into a memory leak (it's just a queue hidden by unresolved promises, since you have to wait for the backlog eventually).

- By contrast, if indexing _doesn't_ have to reliably synchronize with the rest of the network, then an optimal solution is to disable indexing in the consensus engine entirely. If coordinating isn't necessary, indexing could/should be done by a separate process (e.g.,  a dedicated subscriber). But in that case we would have to be OK with the possibility of lost events, though, since "indexing" _is_ the persistence step for events.

The important take-away point is that index reliability is the axis of the question: If the system requires the index to be up-to-date and complete, the index is going to be gated by the slower of consensus and indexing. If not, there's no reason for the consensus node to even _perform_ indexing (much less block for it).

My intuition is that the right solution in the long run is for applications to decide what items to index, rather than the consensus node. The node does it for historical reasons, and has a conservative implementation because it has to work (in principle) for any app. It seems likely that some apps don't actually need that, and could do something faster.

I don't know how important it is for the index to be synchronized generally. We could change it, but before we do we should have a clear understanding of why that decision was made.

That aside, though, I complete agree this is something worth working on. To the extent you can provide any metrics or other data to help us better-understand where the latency issues are coming from in production, it would really help us focus our efforts.

**Comment by JayT106** [comment]
@creachadair thanks for the feedback, and I totally agree with you. If the indexer performs well (say within a sec), the synchronize call in consensus is not an issue. We will try to use the other backend DB as a failover node to mitigate the issue. If the SDK starts to use v0.35.x, we can run Postgres DB for sure.

there is a filtered log from an indexer node. you can see the obvious gap between `executed block/committed state` and `indexed block` after 05:15
https://drive.google.com/file/d/1FjTytxP5vgIKI_kuW-ZcPcOcelKXumPL/view?usp=sharing

maybe we can add metrics for measuring the event indexing spent?

**Comment by JayT106** [comment]
Cool, I can help with #7249
