### ISSUE TITLE
Include consensus settings in block hash

### ISSUE THREAD

**Issue by mdyring** [tendermint/tendermint#739]
Potential bug.

Short version: It seems unclear what happens if nodes in the same network with different (incompatible?) configurations. See @melekes example below.

Maybe these settings should - somehow - be included in the genesis block and be part of the block hash?

Chat log:

mdyring 3:54 PM 
odd question of the day: is there any mechanism that forces nodes to run with the same settings (block_interval, create_empty_blocks etc)? i imagine it would be included in one of the hashes somehow, but is that in fact the case?
i guess in the create_empty_blocks case, the block hash will differ and the misconfigured node will get stuck/halt.. and perhaps block_interval is not really a problem to have configured differently?

melekes 12:01 PM
@mdyring interesting question!
I don't think it's reflected in a block hash
I do see one problem however
If one node is configured to produce 1s blocks and 2nd is not (configured with no empty blocks). the fist one will try to propose too often
but will fail because it won't be its turn in 50% of the cases

**Comment by ebuchman** [comment]
Note that settings related to time are subjective and we don't enforce them to be the same because we don't enforce synced clocks. So if one node has `create_empty_blocks=false` and another doesn't, that's fine, it just means there will be lots of empty blocks. We don't reject blocks just because they're empty, so `create_empty_blocks` is not a consensus setting, its a subjective setting.

That said, putting the hash of the ConsensusParams struct in the header seems like a solid idea. 

See summary of impending changes here: https://github.com/tendermint/tendermint/issues/952

Will close this in favor of that :)
