### ISSUE TITLE
LoadValidators return wrong ValidatorSet when round skip occurred

### ISSUE THREAD

**Issue by ilovers** [tendermint/tendermint#7394]
# Summary
state.SaveState() and state.LoadValidators() do not actually save the validator set for every height. They only save the validator set when it is modified (as given by State.LastHeightValidatorsChanged) or per 100000 block, and then calculate what the proposer priorities should be for a given height. 

But when round skip occurred,  proposer for a given height calculated by IncrementProposerPriority in https://github.com/tendermint/tendermint/blob/master/internal/state/store.go#L508 is not the actual proposer of that height.

# Problem
We want to rollback to a given height, but we can not get the state of that height,  as mentioned in this issue: https://github.com/tendermint/tendermint/issues/3072

**Comment by cmwaters** [comment]
Hi @ilovers, just so I understand it correctly, any height with multiple rounds will have shifted the priority such that `state.LoadValidators` will return an incorrect value. Is that right?

**Comment by ilovers** [comment]
> Hi @ilovers, just so I understand it correctly, any height with multiple rounds will have shifted the priority such that `state.LoadValidators` will return an incorrect value. Is that right?

Hi @cmwaters, yes, that’s right.

**Comment by cmwaters** [comment]
Just to add a little context to this issue for anyone that eventually decides to pick it up. What's needed is some way for the state store to know how many rounds, not heights, have taken place since the last validator set was persisted. Most likely, this number will need to be stored within the `validatorInfo` struct and potentially within `State` itself. When the state store goes to retrieve a validator set, if it turns out to be a pointer, the state store must then go to the height that the pointer is pointing to, retrieve the validator set from their and use the number of rounds to work out how many times the proposer priority needs to be increased. This will ensure that the correct proposer priority for each validator is given.

There may be more efficient solutions, but this is the best one I can think of for now

**Comment by creachadair** [comment]
That approach (https://github.com/tendermint/tendermint/issues/7394#issuecomment-1018536581) seems like it should work. Another thing we might consider is adding a "round count" to the data for each completed block:

- If the validator set changed, store round-count 0.
- Otherwise, increment round-count by 1 for each round and persist the final value with the committed block.

This would simplify the problem for the node: It then never needs to look back beyond the most-recent committed block to get the baseline for the height being computed.

**Comment by ancazamfir** [comment]
I am not sure that keeping a round count is the immediate solution here. Assume we have three validators with same voting power: `[v1, v2, v3]` (in their current priority order). With the current code it is expected that `v1` shows as being the proposer at `H` and `v2` at `H+1`, regardless of how many rounds `H+1` takes and what the actual proposer for `H+1` is (*). The problem is, as @williambanfield and I discovered, if `H+1` takes more than one round then the proposer is same as for `H`, i.e. `v1` in this case. This can be seen in the explorers for multiple chains, here is one example: [9193525](https://www.mintscan.io/cosmos/blocks/9193525 )vs [9193526](https://www.mintscan.io/cosmos/blocks/9193526). I see this every time `H+1` takes more than one round (or at least in tens of heights that I looked at).

imo, we should start by fixing this first. I believe this will also make this work:

> But when round skip occurred, proposer for a given height calculated by IncrementProposerPriority in https://github.com/tendermint/tendermint/blob/master/internal/state/store.go#L508 is not the actual proposer of that height.

**Comment by ancazamfir** [comment]
After debugging this it looks like `H` and `H+1` have the same proposer only in the 2 round case for `H`:
`(H:0,R:0): p1, (H:0,R:1): p2, (H:1,R:0): p2`

Assume `validators = [p1, p2, p3,..]`, `nextvalidators = [p2, p3,.., p1]`
It turns out that consensus works with a copy of `validators` (let it be `valsCopy`). Since proposer for `(H:0,R:1)` is `p2` (`valsCopy.increment()` is called for second round), it will be `p2` that timestamps the block with its address. When we get to the next height, the proposer will again be `p2` (`nextvalidators.getProposer()`) 
With `N` rounds we will see the proposer repeating at height `H + N-1`.
(this is all for the simple case of validators with equal voting power and no changes in the validator set)

In light of the above I believe we only have to store the round number `r` (or the actual proposer address, see Note) for the heights with more than one round (i.e. `r > 0`) 

Since this is not a validator set change we will not need to (re)set `LastHeightValidatorsChanged`. 
If set changes happened at `H` and `H + X` and there were `r` rounds at `H + x, with x < X` then for any height other than `H+x` validator set and proposer can be still computed with:

```
vs.IncrementProposerPriority(h - H)
```
For `H+x` only it will be:
```
vs.IncrementProposerPriority(h - H + r)
```

Note: I have to get through the code and check on all cases but it seems that the full mutation caused by `vs.IncrementProposerPriority(h - H + r)` is not what is needed here, rather just the proposer change caused by that `+ r`. That's why maybe just storing the actual proposer address (when different than the val set proposer) might be enough.

**Comment by ancazamfir** [comment]
@ilovers have you found this issue by looking at the code or are there some tests or feature branch where you see this?

**Comment by ancazamfir** [comment]
> In light of the above I believe we only have to store the round number `r` (or the actual proposer address, see Note) for the heights with more than one round (i.e. `r > 0`)

We could store `r` as a new field, `LastCommitRound`, in `BlockMeta` of next height.

**Comment by lisuxiaoqi** [comment]
Hi there, is this issue fixed?

**Comment by arnabmitra** [comment]
@cmwaters can this be fixed, we seem to have hit the same problem ie your comment here https://github.com/tendermint/tendermint/issues/7394#issuecomment-988249149
