### ISSUE TITLE
Update roundskip criteria to match arXiv paper

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#7452]
The arXiv paper lays out the following condition for a validator to skip from its current round `r` to a future round, `r'` where `r' > r`:

```
55: upon f + 1 <∗, hp, round, ∗, ∗> with round > roundp do
56: StartRound(round)
```
This rule states that if a validator receives votes representing `+1/3` of the voting power on the network that are either precommits or prevotes, it should move to this higher round. At the moment however, we only move to a higher round if a validator receives `+2/3` voting power as prevotes. 
This logic can be seen in `state.go`: 
https://github.com/tendermint/tendermint/blob/ab7da86b06233b325406d8b0fb5ff0902adec001/internal/consensus/state.go#L2197

We should update the logic in `state.go` to match the arXiv paper to allow roundskipping to occur when only `+1/3` of the voting power on the network is seen in the form of _either_ prevotes or precommits.

**Comment by cason** [comment]
I think the reason for not having this implemented is the possibility, in practice, of having more than `f` Byzantine processes for "a while". This would make Byzantine processes able to arbitrarily skip rounds orchestrated by correct processes.

**Comment by milosevic** [comment]
`f+1` is the lower bound, i.e., minimum number of processes you need to see in higher round to move there. I am not sure if termination proof still holds if we put instead `2f+1`. Someone would need to check that (@cason). If I am not wrong, although we do have that condition in the code, we are not really jumping directly to higher round, i.e., I think we move sequentially to a target round, paying at least timeoutCommit along the way. This is not ideal, but there was not bandwidth to implement this properly at that point in time.

**Comment by cezarad** [comment]
Hey guys, there seems to be a liveness issue cause by the gossip later within a height. 

Between heights there is a catch-up mechanism that allows late replicas to JUMP to an earlier round either a check point or the current height. 

Within a height there is no such mechanism, because to a late replica let's call it R4, the other replicas R1, R2, R3, send only messages from the round R4 is in. 
So the late replica R4 must go thought all rounds, no jumps are possible. 
For example, imagine R4 is in round 0 and R1,R2, and R3 are in round 10. There exists one network that delivers all messages required for R1,R2, R3 to reach round 11 and only the messages that will take R4 to round 1, and so on. Eventually all messages are delivered but there is a sliding window of constant size between R4 and the front running quorum. Now if one of R1, R2, R3 is byzantine it will prevent the front running quorum to decide, and since R4 can never catch up they never converge on a decision.  

Therefore,  within a height one late replica R4 might never catch up with the leading quorum R1, R2, R3, violating liveness when the byzantine is in the leading quorum, is a different process from the correct slow replica. The test: https://github.com/ImperiumProject/tendermint-test/blob/master/testcases/byzantine/foreverLaggingReplica.go and the tendermint logs showing no convergence up to round 34  https://github.com/ImperiumProject/tendermint-test/tree/master/logs/foreverlaggingreplica. 


Moveover, we observed that by creating a gap of 10 rounds between R4 and the leading quorum,  when we deliver all messages in sync it converged at round 15 (similarly for a gap of 20 convergences at 28 and 30/41). The test https://github.com/ImperiumProject/tendermint-test/blob/master/testcases/byzantine/laggingReplica.go and the terndermint logs https://github.com/ImperiumProject/tendermint-test/tree/master/logs/laggingreplica

Note:  this is not an f+1 vs 2f+1 round switch, but rather no jump over rounds, independently of how many messages of a round are required for the jump.

**Comment by josef-widder** [comment]
Shouldn't that behavior be prevented by increasing timeouts (cf. https://github.com/tendermint/tendermint/issues/2920#issuecomment-445874592)?

**Comment by cezarad** [comment]
Well the duration of the good period depends on the duration of the bad period, in the case of 10 bad rounds it need 7 good ones to reach a decision. Sure there is a covering assumption that there exists a long enough good period, but I still think the round synchronization is too slow and that the current design of the gossip layer prevents round synchronization to be efficient.

**Comment by williambanfield** [comment]
> Within a height there is no such mechanism, because to a late replica let's call it R4, the other replicas R1, R2, R3, send only messages from the round R4 is in.

To confirm this, I'm seeing here in the reactor code that we only gossip votes for the round that the peer is believed to be in: https://github.com/tendermint/tendermint/blob/1d3ecf37ee879a0958e76747e729da2811895855/internal/consensus/reactor.go#L704

**Comment by kayabaNerve** [comment]
I was working on an implementation according to the paper and noticed it had an error here. The literal writing, which is upon f+1 messages, isn't bound to a specific type of message. While the code is bound to prevotes, and original comment said it should be bound to prevotes || precommits, the distinction I want to raise is it should be bound to *processes*, from my understanding.

If this is solely bound to messages, as the paper describes, then without invalid messages `f+1` becomes `f/2` to force a skip, which allows the malicious minority to select the proposer. This would be via creating f+1 messages of PROPOSE, PREVOTE NIL, PRECOMMIT NIL (assuming one of the minority is the natural proposer, else it's `(f/2)+1`).

Would it be possible to have confirmation that this is intended to be bound to processes, not messages, and that any message (propose, prevote, or precommit) from any process signaling a future round is enough to contribute towards this f+1 threshold (yet multiple messages from the same process do not further contribute, of course)?

**Comment by milosevic** [comment]
You are right that it is necessarily to receive f+1 messages from different processes. Note the semantics of f+1 as described in the paper: The condition that assumes reception of X messages of a particular type and content denotes reception of messages whose senders have aggregate voting power at least equal to X. For example, the condition 2f + 1
<PRECOMMIT, hp, r, id(v)>, evaluates to true upon reception of PRECOMMIT messages for height hp, a round
r and with value equal to id(v) whose senders have aggregate voting power at least equal to 2f + 1.
