### ISSUE TITLE
Deterministic Events

### ISSUE THREAD

**Issue by robert-zaremba** [tendermint/tendermint#7471]
## Summary

We use events to query transactions https://github.com/cosmos/cosmos-sdk/issues/9723. However, today, the events are not deterministic  and are not provable (they are not part of the consensus).

References:
+ https://github.com/tendermint/tendermint/issues/5963
+ https://github.com/tendermint/tendermint/discussions/5977

## Problem Definition

Events are used to query transactions and will be used to hooks system in Cosmos SDK. (https://github.com/cosmos/cosmos-sdk/discussions/9150, https://github.com/cosmos/cosmos-sdk/discussions/9656)
Events are used for indexers and are very important for the off-chain ecosystem. We need to be able 

Events are managed by Tendermint, and there is a growing ecosystem build on top of that. 

## Proposal

Add Merkle hash of events to the block header. This will allow to:
1. Verify existence and not existence of an event
2. make events deterministic

### Alternative

We could technically move events to Cosmos SDK, but there are other, non-Cosmos SDK clients which require Tendermint events. So we either make it configurable on Tendermint and implement event management feature on Cosmos SDK or update Tendermint to make events part of the consensus. The latter sounds easier and doesn't require to duplicate the work and maintenance. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by marbar3778** [comment]
Hey, we did do this a couple months ago, but ended up reverting because it was said the sdk and ibc were not ready for this. This sort of change makes event changes consensus breaking. 

We should check with IBC if events have stabilised or been included in the spec, then if the sdk is ready then unreverting the pr should be easy enough. 

cc @AdityaSripal @colin-axner @ebuchman

**Comment by colin-axner** [comment]
I would prefer to keep events out of consensus. I don't think our event emission has stablized and being able to make event changes without breaking consensus has proven useful. Is there a use case for provable events? 

I'd also be concerned with changing the header since this might break IBC clients

**Comment by ValarDragon** [comment]
I strongly prefer keeping events out of consensus for now. IMO we absolutely need to be able to do rapid iteration with events for 2022.

I think this makes sense to reconsider once we have an actual user-facing light client ecosystem, and until then is premature and a strong restriction. Some ideas for when we should re-open:
- Cosmos wallets start self-relaying
- Cosmos wallets use light client proofs for balances

**Comment by cmwaters** [comment]
I think if we did want provable and deterministic emission of events, it would be better if this were implemented in the SDK or application side and were simply incorporated as part of the `apphash`. It seems that this could align quite well with the "State Listening" work but as @ValarDragon said, it's more important to build a stronger light client narrative in the cosmos ecosystem before doing such work.

**Comment by peterbourgon** [comment]
I don't think this makes sense conceptually. What would "events" look like, concretely? Would they not just be a copy of every existing entry in the consensus log, with the value/data dropped and an "event" prefix applied to the key?

**Comment by creachadair** [comment]
I am not sure I understand what it would mean for events to be “deterministic”, but I broadly agree with @peterbourgon that events should almost certainly not be used where trust is required.

I’m working on some changes now that should improve the reliability of event subscription from active nodes, and that will make it easier for applications and clients to use them, but I don’t really see a viable way to guarantee a consistent view of events across nodes. If an application wants to include additional content in the consensus block, it seems to me it already has full control over the structure of its transactions, and could add such data there.

**Comment by ebuchman** [comment]
Just to add some context, there's old issues for this like https://github.com/tendermint/tendermint/issues/1007 and even an [adr-058](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-058-event-hashing.md).

The "events" emitted by ABCI applications are in principle deterministic, they should be the same on every machine, they are deterministic results of executing the tx log. They are not part of the tx log itself and not just a copy of it. They are very similar to the LOG opcode in Ethereum land. They contain pretty essential informaiton (eg. for IBC relayers) and it was always anticipated that at some point folks would want verifiable proofs about them, which means ensuring they are deterministic and merklizing them into the header (see those previous issues/adrs).

The challenge has been there's never been a proper spec/standard for events and they've been developed a bit loosely and we've been afraid to merklize them because then any change to an event would be breaking. It would be very worthwhile to work towards their standardization for these purposes but seems we're not quite there yet, and we should collect a better understanding of key user stories for it.

**Comment by creachadair** [comment]
> Just to add some context, there's old issues for this like #1007 and even an [adr-058](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-058-event-hashing.md).
> …

Thanks for the context, that's very helpful. I could believe that the events emitted for (say) BeginBlock and EndBlock and for their corresponding transaction results might be deterministic, but the event bus injects additional key/value pairs (e.g., `tm.event`) and the order of those key-value pairs is unspecified. And for other event types, e.g., BlockSyncStatus, I'm not sure it really _is_ consistent across nodes.

Part of the problem is terminological: What ABCI calls an "Event" is a subset of what counts as an "event" in Tendermint, and particularly for subscribers to the node's RPC service.

**Comment by robert-zaremba** [comment]
There are other ways to make a commitment for a set, than a merkle root. For example RSA accumulators, for which the proof is just a single number, rather than a list of hashes.

**Comment by robert-zaremba** [comment]
Verifiable events are useful for:
* indexers
* relayers
* all sort of hooks.

**Comment by ebuchman** [comment]
> Part of the problem is terminological: What ABCI calls an "Event" is a subset of what counts as an "event" in Tendermint, and particularly for subscribers to the node's RPC service.

Yup meant to say this. I think we're really just talking about the ABCI events here. Wouldn't be a bad idea to use another name.

> There are other ways to make a commitment for a set, than a merkle root. For example RSA accumulators, for which the proof is just a single number, rather than a list of hashes.

Of course but that's presumably out of scope / independent of this issue?

**Comment by creachadair** [comment]
> > Part of the problem is terminological: What ABCI calls an "Event" is a subset of what counts as an "event" in Tendermint, and particularly for subscribers to the node's RPC service.
> 
> Yup meant to say this. I think we're really just talking about the ABCI events here. Wouldn't be a bad idea to use another name.

Agreed. I tried to address this in [ADR 075](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-075-rpc-subscription.md) by giving more explicit terms ("event items" and "event data") to distinguish from the existing use of "event" for ABCI key/value pairs. Those probably aren't ideal anyway, but if we can push those apart, it might help.

The mixing is more than _merely_ terminological, though—in the implementation the ABCI `Event` messages are attached to other consensus data too. 🤦🏼‍♀️  Still, we can make it better.

**Comment by marbar3778** [comment]
We have talked about the sdk not using tendermint events to provide typed events. If this is the case this becomes a bit irrelevant and could possibly be handled app side right?

**Comment by creachadair** [comment]
> We have talked about the sdk not using tendermint events to provide typed events. If this is the case this becomes a bit irrelevant and could possibly be handled app side right?

Yes, I think having the app be responsible for transaction metadata ("ABCI events") makes a lot of sense. If we were starting from scratch, that's probably what I'd propose, and we could certainly move in that direction. 

That said: Whatever we decide, we'll need to have some story for how to migrate all the existing use. Some of that use includes consensus "event items" that aren't (and probably shouldn't) be under the application's control, so it's not quite as simple as moving everything over.

**Comment by robert-zaremba** [comment]
What's the down side of deprecating ABCI events? Ie : handling it by SDK, without  involving ABCI / Tendermint?

**Comment by creachadair** [comment]
> What's the down side of deprecating ABCI events? Ie : handling it by SDK, without involving ABCI / Tendermint?

I don't think there's any real downside for future use. I think the main question is how to migrate the ecosystem of existing tools, that expect to talk to the consensus node for this purpose. 

Presumably the Cosmos SDK could grow support for indexing and querying by event metadata. Applications that are not built using the Cosmos SDK would need to reimplement some of these things from scratch. (I think some of the larger users of Tendermint are _not_ SDK apps, so I think we'd need to check with both communities)

**Comment by robert-zaremba** [comment]
Tendermint could continue to support the Events API.
So the downside is that tools will need to support both APIs.
