### ISSUE TITLE
Faster (est) way of sending/broadcasting a transaction

### ISSUE THREAD

**Issue by dunidaho75** [tendermint/tendermint#7476]
Hello,

Currently, when a user send a transaction to a tendermint node (let's pick `/broadcast_tx_sync` endpoint), the following steps happen:
 - mempool's `CheckTx` method is called which
    - adds the txn to mempool's cache
    - checks against the baseapp that the txn is correct/well formatted
    - adds to internal txn list of mempool
    - notifies to others that a new txn has been added
 - a separate goroutine picks up the new change, and gossips the new txn to all the peers of the node.

For a particular application, I need to broadcast my transaction as soon as possible to other nodes. (latency is the highest priority). Note that I am running my own local tendermint node, and I was wondering if there is a way in which I can avoid most of the above things in my node and directly have it broadcast my txn to its peers. 

My node is not a validator. 

![tendermint](https://user-images.githubusercontent.com/93879746/146656025-6a0f2640-2094-4ce8-8944-54dc24362837.png)

**Comment by creachadair** [comment]
Hi, @dunidaho75. At present, what you're describing is the fastest available path to broadcast transactions, and the consensus node does not provide a way to bypass the consensus machinery when broadcasting transactions.

It's possible you could look for workarounds, but it's not clear where there are obvious latency savings to be found.  Once a transaction reaches a proposer, the rest of consensus is "baked in". If you're exploring options, a good place to start might be to gather profiles of the network under load, to see where transactions spend their time between insertion and proposal.

Beyond gossiping the transaction, there should not be much overhead from the node itself: A `CheckTx` is usually fairly lightweight, and otherwise the latency is primarily driven by the mechanics of forwarding it to peers. To do better than that, one would have to know something about the structure of the network—e.g., where the validators are, and possibly who the proposer is. You could imagine possibly contacting validators directly to broadcast a transaction, but if that information is already available, it could also be used to speed up the gossip network. I'm speculating a bit here, but that's where I'd recommend starting if you're investigating further.

**Comment by dunidaho75** [comment]
Thanks @creachadair for the reply.

Mainly, I was interested to see if there is a way in which a transaction can be directly broadcasted to all connected peers without spending any time in the hosted node.

**Comment by dunidaho75** [comment]
@creachadair I am wondering if you can explain the parameter `flush_throttle_timeout` to me. 

The config docstring says:

```
# Time to wait before flushing messages out on the connection
flush_throttle_timeout = "100ms"
```

Does this mean that when a node tries to send a message to its peer, it can wait upto potentially 100ms before actually sending the message?

**Comment by creachadair** [comment]
> @creachadair I am wondering if you can explain the parameter `flush_throttle_timeout` to me.
> 
> The config docstring says:
> 
> ```
> # Time to wait before flushing messages out on the connection
> flush_throttle_timeout = "100ms"
> ```
> 
> Does this mean that when a node tries to send a message to its peer, it can wait upto potentially 100ms before actually sending the message?

I'm not expert with the P2P internals, but as I understand it the `flush-throttle-timeout` is a per-connection rate limit. If a node has just sent a message to a peer, it will not send another on that connection until at least that timeout has elapsed.

So to your question, the simple answer is "yes": It is possible a node could wait up to (say) 100ms. However, that case can only happen immediately after the node has sent a message to that same peer. Moreover, the throttle is per-connection, not global, so the node may continue sending messages to other peers during the timeout for that one connection.

Note also that if it has been more than `flush-throttle-timeout` since the last send on a connection, there is _no_ delay on the next message—the timeout only resets when a message is sent. It smooths out bursts, but does not slow down steady-state traffic below the rate implied by the timeout.

**Comment by dunidaho75** [comment]
@creachadair Thanks a lot!

I am closing this issue for now.

**Comment by feizerl** [comment]
@creachadair 

In one of your replies you had mentioned this:

>  To do better than that, one would have to know something about the structure of the network—e.g., where the validators are, and possibly who the proposer is.

Is there a way to figure out both these questions? e.g. what are the ip addresses of validators and who is going to be the next proposer? (is the last part even deterministic? If yes, isn't it an attack vulnerability because that proposer can potentially be DDOS'ed?)

Once again, thanks for your very informative replies!

**Comment by creachadair** [comment]
> In one of your replies you had mentioned this:
> 
> > To do better than that, one would have to know something about the structure of the network—e.g., where the validators are, and possibly who the proposer is.
> 
> Is there a way to figure out both these questions? e.g. what are the ip addresses of validators and who is going to be the next proposer? (is the last part even deterministic? If yes, isn't it an attack vulnerability because that proposer can potentially be DDOS'ed?)
> 
> Once again, thanks for your very informative replies!

I don't know of an obvious way to answer those questions, unless you control the network. Intuitively, this makes sense: If you know where all the validators are, and who will be the next proposer, you could use that to attack the network. So at least in principle, the loose coupling is more a feature than a bug.

Even absent malicious action, the more connected nodes are to "locations" (e.g., fixed hosting or IP addresses) rather than "identities" (public keys), the more brittle the network is to outside interference. In that sense, the "inefficiencies" of gossip help make the consensus network more resilient.

Or to look at it another way: The more control one person or organization has over the network, the less decentralized it is, and at some point along that spectrum, the benefit of distributed consensus as compared to a federated service is questionable. That's not to say it couldn't be done, but only to point out some of the tradeoffs that could be involved.

**Comment by feizerl** [comment]
That makes sense. Thanks @creachadair !

**Comment by dunidaho75** [comment]
@creachadair I had one final question related to P2P :)


There are two parameters in 0.34.14 config (Both of them are deprecated in 0.35.0):
 - max_num_inbound_peers
 - max_num_outbound_peers

(They are replaced with max-connections in 0.35.0)

From what I understand from the docs, inbound peers are those that connect to my node and outbound peers are those that we connect/dial to to make sure that we have sufficient number of connected peers. 

 - When mempool reactor broadcasts a transaction, does it broadcast to both inbound as well as outbound peers? (I think the answer is yes, but wanted a confirmation). 
 
 - Is there any harm in increasing `max_num_outbound_peers`? My thinking here is that if I am connected to more number of peers, I can broadcast my transaction faster in the network. Do you see any flaw in this reasoning?

thanks!

**Comment by creachadair** [comment]
> * When mempool reactor broadcasts a transaction, does it broadcast to both inbound as well as outbound peers? (I think the answer is yes, but wanted a confirmation).

I'm not sure either. I think that's right based on a skim of the code, but here I'm beyond my familiarity with the p2p implementation. Once the team is back after the new year, someone else may have a better answer (perhaps @tychoish).

> * Is there any harm in increasing `max_num_outbound_peers`? My thinking here is that if I am connected to more number of peers, I can broadcast my transaction faster in the network. Do you see any flaw in this reasoning?

Increasing that number is generally fine. The main issues to watch out for are file descriptor exhaustion (each connection consumes a socket) and network bandwidth contention.  If you increase that number, you may also need to increase your process's ulimit/rlimit settings. Note that the process descriptor limit includes not just p2p connections, but also websocket connections (for event subscription) and open files (for logs, WAL, database, etc.). It's also possible you may need to bump up RAM limits also, since connections serve buffers and queues.

Whether or not increasing max connections would help is an open question. Your theory seems reasonable, but it's hard to reason about system performance from a change to a single node. Gossiping to more peers might increase throughput for one node at the expense of others. You'd have to measure it to know for sure.

**Comment by feizerl** [comment]
thanks @creachadair

I have already increased the number of file descriptors on my system. Let me give this configuration a go, and see how it goes.

**Comment by dunidaho75** [comment]
thanks @creachadair

I have already increased the number of file descriptors on my system. Let me give this configuration a go, and see how it goes.
