### ISSUE TITLE
Problem: Txs with too high nonce should be pending instead of being rejected and dropped.

### ISSUE THREAD

**Issue by Muggle-Du** [tendermint/tendermint#7510]
## Summary
We need a third status for tx: pending besides mined and rejected in tx pool level.
So that a tx with too high nonce will not be directly rejected but stay pending util the tx with the correct nonce got mined.

## Problem Definition
Currently if the tx went through the `checkTx`, it could be only `rejected` or `mined`.
For complexed smart contract operations, usually the user would send a sequence of txs with increasing nonce.
However if the tx series simultaneously passed the `checkTx`, the nonce verification will directly reject the txs with higher nonce and those rejected txs will not be mined unless the user resends them.
This behavior is quite unfriendly for users interacting with the smart contracts.
The `ethermint` implementation of nonce verification is [here](https://github.com/tharsis/ethermint/blob/main/app/ante/eth.go#L180)
While we can refer to the implementation of `go-ethereum` [here](https://github.com/ethereum/go-ethereum/blob/master/core/tx_pool.go#L1339)

## Proposal

There should be a pending status for tx in tx pool and tx could remain pending even if the tx went through the `checkTx`.
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
Hey @Muggle-Du, this functionality where we don't want to remove a tx but we don't want it in a block yet (because the nonce is too high) is something that ABCI++ enables with the `PrepareProposal` method. I'd take a look at this [PR](https://github.com/tendermint/spec/pull/366) for more details. The tl;dr is that Tendermint will send the batch of txs it plans to propose to the network first to the application which can change these transactions in various ways, one such way is to tell Tendermint to not have a tx in the block but also to not remove it from the mempool. Does this solve the problem you describe?

**Comment by Muggle-Du** [comment]
> Hey @Muggle-Du, this functionality where we don't want to remove a tx but we don't want it in a block yet (because the nonce is too high) is something that ABCI++ enables with the `PrepareProposal` method. I'd take a look at this [PR](https://github.com/tendermint/spec/pull/366) for more details. The tl;dr is that Tendermint will send the batch of txs it plans to propose to the network first to the application which can change these transactions in various ways, one such way is to tell Tendermint to not have a tx in the block but also to not remove it from the mempool. Does this solve the problem you describe?

yes, this is exactly what I want.
thank you and I'm looking forward to this PR being merged into the coming ABCI++.
