### ISSUE TITLE
ABCI++: Decide whether `Commit` should stay out of `FinalizeBlock`

### ISSUE THREAD

**Issue by sergio-mena** [tendermint/tendermint#7659]
## Summary

The current code in abci++ branch has `Commit` outside `FinalizeBlock`, but the spec assumes `Commit` is part of `Finalizeblock`.

## Problem Definition

Preliminary inspection of the code seems to suggest `Commit` should indeed be outside `FinalizeBlock`, as it is needed to implement Tendermint's crash-recovey mechanism.
Investigate if that is the case and, if so, adapt the spec repo to reflect that.

## Dependencies

None

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by cmwaters** [comment]
So my understanding of the sequence of events for the crash-recovery mechanism is:
1. Consensus reaches 2/3+, persist the block. In failure the WAL should recover the block and all the votes.
2. Send the block to the application via `FinalizeBlock`. If the app crashes we have the block and upon startup will feed it back to the application.
3. Get the returned values from `FinalizeBlock` calculate the new state and persist that. In the event that Tendermint crashes it should feed the application the block and if it has the state it should assert that the correct appHash was returned. Note that this is what `rollback` does. It removes that last state we saved so that if the binary changed in between, it won't panic when it receives a different app hash.
4. Execute the `Commit` method which tells the application to persist the state it executed.
5. Flush the WAL and move on to the next height. 

If we were to remove the `Commit` method this would mean that the application would need to persist itself as it executed the new transactions and before we committed state. This would be okay so long as that on start up after a crash, when we query `Info` to understand the state of the application we were able to retrieve not just the apphash but the validator set and consensus params as we do with `InitChain` so that we could persist the new state and march onwards. 

This is also easier in the case of "Immediate Agreement" because we know the outcome of executing the block before we commit it thus it's possible to atomically persist both the new block and new state and thus `Commit` is redundant. 

For now, I would recommend leaving `Commit` as separate to `FinalizeBlock`.

**Comment by sergio-mena** [comment]
I went through @cmwaters's comment above, the section in the spec, and the code.
With all that I read and understood, I agree that it would be best to leave `Commit` as a separate API call. This would allow us to reuse the current logic, which has been battle-tested. So, following the *don't fix what isn't broken* principle here.
Nevertheless, I realize now that it would be good to clarify the paragraph in the spec, as I find it hard to understand in its current state.
So, the PR I'll open for this issue will
* Adapt ABCI++ spec to reintroduce `Commit`, including the ABNF grammar
* Refactor the *Crash-recovery* section as we move it into ABCI++ directory
