### ISSUE TITLE
RPC: Why is there a nested .evidence.evidence field?

### ISSUE THREAD

**Issue by webmaster128** [tendermint/tendermint#7697]
In Tendermit up to at least 0.34, there is a field `.result.block.evidence.evidence`. Is this double nesting required? All the client code I saw so far does not read anything else than `.evidence` in `.result.block.evidence`.

This can be reproduced currently using

```
$ curl -sS "http://198.50.215.1:36657/block?height=7900625" | jq .result.block.evidence.evidence
$ curl -sS "http://198.50.215.1:36657/block?height=7900625" | jq .result.block.evidence
```

The API response can be found in https://github.com/cosmos/cosmjs/issues/980#issuecomment-1017632187 in case the node becomes unavailable.

In CosmJS we currently lift up the evidence one level:

```ts
function decodeBlock(data: RpcBlock): responses.Block {
  return {
    header: decodeHeader(assertObject(data.header)),
    // For the block at height 1, last commit is not set. This is represented in an empty object like this:
    // { height: '0', round: 0, block_id: { hash: '', parts: [Object] }, signatures: [] }
    lastCommit: data.last_commit.block_id.hash ? decodeCommit(assertObject(data.last_commit)) : null,
    txs: data.data.txs ? assertArray(data.data.txs).map(fromBase64) : [],
    evidence: data.evidence && may(decodeEvidences, data.evidence.evidence),
  };
}
```

But I'm not sure of this is the right thing to do.

**Comment by cmwaters** [comment]
Hey thanks for bringing this up. I think the only reason why we have this nested format is because we have a few non exported fields for caching things like the hash. I'm not sure if having these cached fields are actually that necessary. I've found the nested format to also be ergonomically annoying but before cleaning up I'd want to make sure that we're not accidentally breaking the hashes in the block in any way. 

There was a similar issue about moving `Evidence` into `Data` since the evidencehash isn't needed for any proofs
