### ISSUE TITLE
ABCI++: Do `PrepareProposal`, `ProcessProposal`, and `FinalizeBlock` need to see the whole block header as a parameter?

### ISSUE THREAD

**Issue by sergio-mena** [tendermint/tendermint#7950]
Current ABCI++ specification, as of tendermint/spec#366, includes the whole block header in `Request*` calls to `PrepareProposal`, `ProcessProposal`, and `FinalizeBlock`; in the same way as ABCI included the header in `RequestBeginBlock`.

It is unclear whether the whole block needs to be exposed in these calls. We have agreed on making the implementation progress and, when implementation of `Request*` calls to `PrepareProposal`, `ProcessProposal`, and `FinalizeBlock` are clear, we will make a decision on the `header` parameter. This will be how we handle this issue.

**Comment by williambanfield** [comment]
For clarity on this issue, here are the set of fields currently present in the Block from the `types.proto` file:

```
message Header {
  tendermint.version.Consensus version  = 1 [(gogoproto.nullable) = false];
  string                       chain_id = 2 [(gogoproto.customname) = "ChainID"];
  int64                        height   = 3;
  google.protobuf.Timestamp    time     = 4
      [(gogoproto.nullable) = false, (gogoproto.stdtime) = true];

  // prev block info
  BlockID last_block_id = 5 [(gogoproto.nullable) = false];

  bytes last_commit_hash = 6;  
  bytes data_hash        = 7;  

  bytes validators_hash      = 8;  
  bytes next_validators_hash = 9; 
  bytes consensus_hash       = 10; 
  bytes app_hash             = 11; 
  bytes last_results_hash =
      12; 

  bytes evidence_hash    = 13;
  bytes proposer_address = 14;
} 
```

Of these, the hashes are largely irrelevant to the application. The hashes capture the state of previous versions of the chain. These are merkle root hashes without any hashes of the intermediate nodes in the tree. They allow the node to validate that some block succeeds another in the chain. The node is able to use them for this verification because it has all of the data locally to compute the hash and it verifies that the hash matches what it expects. The application does not seem likely to have this information locally. Even if it does, it seems like all it would allow the application to do is perform the same check that Tendermint can do, check that it equals to the hash of its local data. That appears to be of limited use. 

Handing these values to the application also forces us to consider maintaining these for any applications that may rely on them for whatever reason. If we change the structure of the header or the values it contains, we may break applications that, say, stored values keyed by blockID. I think that we should not do that and should instead treat these values as internal to Tendermint, only passing through what's likely to be valuable to an application, namely the Timestamp and Height.

**Comment by sergio-mena** [comment]
Thanks @williambanfield for the description. I agree with the overall message (thinks like the hashes are of little use for the apps and may get us into problems if we changed the format in the future).
Only thing I'd say is that I'm not sure about:

* version (Apps might need it for managing upgrades?), and
* chain_id (maybe for sanity) 

But, as @creachadair mention in Slack, these can always be added as extra fields in the protobufs without fear of breaking compatibility.

**Comment by sergio-mena** [comment]
As a due-diligence exercise, we have modified the source code of Tendermint (a pre-ABCI++ version), Cosmos SDK, ibc-go, and gaia.
The modification was carried out the in the following way: (1) remove field `Header` from `RequestBeginBlock` protobufs, (2) have "make build" pass in Tendermint, (3) have "make build" pass in the SDK, (4) likewise for ibc-go, (5) likewise for gaia... finally having `gaiad` built.
The build of (5) uses (4), (3), and (2) as dependencies; (4) uses (3) and (2) as dependency; (3) uses (2) as dependency.

*The end result* is that `RequestBeginBlock` was modified to not contain the header but only the fields used by any of (3), (4), or (5).

For further details, please check the branch for [(1) and (2)](https://github.com/tendermint/tendermint/tree/sergio/hide_header_beginblock), for [(3)](https://github.com/informalsystems/cosmos-sdk/tree/sergio-mena/hide_header_beginblock), for [(4)](https://github.com/informalsystems/ibc-go/tree/sergio-mena/hide_header_beginblock), and for [(5)](https://github.com/sergio-mena/gaia/tree/sergio-mena/hide_header_beginblock)

N.B.: These modifications are just a proof-of-concept, they are not meant to be merged to any release branch.

**Comment by marbar3778** [comment]
Showing up a bit late, but my recommendation would be to not use cosmos-sdk as the basis of these types of decisions. The cosmos-sdk has a very simple use case and does not use the full potential of some of these features.
