### ISSUE TITLE
sync: Sync current state without full replay for Applications

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#828]
We want to be able to sync the current state without having to replay all transactions in the blockchain. 

This can be done securely by first syncing a light client to a recent state root, and then polling peers for the pieces of the state tree.

Let's add a new `state-sync` reactor to Tendermint to handle this. It should use a new ABCI connection and message to ask the app what to ask other peers for - alternatively, there may be a case for it to just use the existing Query connection and message. The base of this could be thought of as a general purpose mechanism for letting apps control the fetching of data from Tendermint peers

**Comment by cloudhead** [comment]
Specification here: 
https://docs.google.com/document/d/15MFsQtNA0MGBv7F096FFWRDzQ1vR6_dics5Y49vF8JU/edit?ts=5a0f3629

**Comment by ebuchman** [comment]
@jlandrews

**Comment by jlandrews** [comment]
Future reminder from https://github.com/cosmos/cosmos-sdk/issues/1516#issuecomment-402202485. When building state syncing make sure to check if node is configured for a full prune, and if so disable the sync provider reactor and don't advertise that channel to peers.

**Comment by hrharder** [comment]
If @cloudhead's spec from last November is implemented (or something similar) will this support pruning the leveldb blockstore while consensus is running?

**Comment by ebuchman** [comment]
That's the ultimate goal, to institute a checkpointing mechanism that will allow nodes to prune history.

**Comment by ackratos** [comment]
@ebuchman is this issue & proposal still valid? I'd like to contribute (because of our organization requirement).

**Comment by ValarDragon** [comment]
I'm mostly in agreement with the current proposal. As a quick summary as I understand, the proposal is essentially suggesting to do BFS between syncer and syncee. (so you go layer by layer) The data is separated into chunks, and you do merkle proofs along the way. We can't initially send anything about leaves directly, since IAVL is insertion-order dependent, and encoding the tree structure is a pain. Similarly, you can't use knowledge of prior states to help here, unlike in patricia trees, and similar. We don't skip any interior nodes, even though they are in principle functions of later data. This is because the amount of data that they occupy relative to the data at the leaves should be negligible. (This isn't currently true in the cosmos hub, but will be eventually, one example: https://github.com/cosmos/cosmos-sdk/issues/2562#issuecomment-447512158)

The point I disagree about is the choice of BFS vs DFS. I actually think DFS is better. You can be learning half of the tree from one peer, and another half from another peer independently. This is actually extremely important, as a person doing a service for the ecosystem, I am probably not willing to have 100's of GB bandwidth requirement. Instead we should have the software support querying many different state syncers at once. (With locality in where you query them, for cache effects) Also in the case where everyone goes offline for some reason after you've begun syncing, its more useful to have some leaves rather than no leaves.

This proposal also skips one important part (though it was in some sense out of scope of the proposal). We need a standard put in place about which blocks should be state sync'd blocks, otherwise you may only be able to state sync with one peer, and thats too large of a overhead. Perhaps every `n` blocks suffices. (It mentions that you may want to store the last `k` states, but I actually think storing every `n`th state, and perhaps only keeping the last one or two suffices, and you can replay blocks from there)

**Comment by ackratos** [comment]
> The point I disagree about is the choice of BFS vs DFS. I actually think DFS is better. You can be learning half of the tree from one peer, and another half from another peer independently. This is actually extremely important, as a person doing a service for the ecosystem, I am probably not willing to have 100's of GB bandwidth requirement. Instead we should have the software support querying many different state syncers at once. (With locality in where you query them, for cache effects) Also in the case where everyone goes offline for some reason after you've begun syncing, its more useful to have some leaves rather than no leaves.

I am also vote for DFS (in implementation, seems I can rely on existing traverse method of ival tree), does maintainer has any objective?

> This proposal also skips one important part (though it was in some sense out of scope of the proposal). We need a standard put in place about which blocks should be state sync'd blocks, otherwise you may only be able to state sync with one peer, and thats too large of a overhead. Perhaps every n blocks suffices. (It mentions that you may want to store the last k states, but I actually think storing every nth state, and perhaps only keeping the last one or two suffices, and you can replay blocks from there)

I was presuming that we will discard all historical blocks (only negative impact is we cannot query blocks and txs information on this node's api-server or rpc call). What's the benefit of sync every n-th block?

**Comment by ackratos** [comment]
I raised a PR: https://github.com/tendermint/tendermint/pull/3243
The main functionality is workable in our app, I will port some logic into cosmos baseapp.go to indicate how we use it. It's slightly different with proposal in terms of how we serialize key/value from response side, I actually tried two ways:
1. transfer serialized node and persist node to nodedb (prefix db) on request side, together with essential meta keys like `latest` and `root` 
2. transfer key/value pair per store and construct an iavl tree on request side, then save the tree

The API is mostly same, except I make LatestSnapshot return []int64 rather than int64, because app might has multiple stores, I have to figure out each node  (in solution 1) OR each key/value pair (in solution 2) belongs to with store. 

This is least effort to make tendermint free from upper level implementation I thought. i.e. If upper application doesn't use multiple store, it can just make `LatestSnapshot` return []int64 with one element 

I will port our changes into cosmos Baseapp within 2 days to demo how this works on app level

**Comment by ackratos** [comment]
@melekes @ebuchman @cwgoes according to our practice on current proposal and review comments in https://github.com/tendermint/tendermint/pull/3243 and new issue https://github.com/tendermint/iavl/issues/135

we want raise this new proposal and can contribute on implement it:
https://docs.google.com/document/d/1npGTAa1qxe8EQZ1wG0a0Sip9t5oX2vYZNUDwr_LVRR4/edit?usp=sharing

Would you like review and comment?

**Comment by ebuchman** [comment]
@ackratos looked briefly at your writeup. My understanding of the original proposal was that we would be serializing the tree into chunks and then syncing those chunks, which sounds similar to what you've written up. However it's not entirely clear how the proofs work. In the past, we had discussed chunking in a way that still preserves possibility of proofs within the same tree, but it seems your proposal is to basically build a new simple Merkle tree out of the chunks and then they can be verified Tendermint side. But where would the Merkle root go?

Also, you're right that we probably need some way to sync the Tendermint State, but I'm not sure if this should happen in band or if the new node should be expected to have access to the validator set and consensus params from the height it's syncing. At the very least it needs to subjectively fetch the validator set hash, but I suppose once it has that, it could get the rest of the Tendermint state as a single chunk through the state sync mechanism. Needs to be better specified.

In our discussion last week, we talked about two over all design strategies:

1) Chunking (ie. split tree into numbered chunks)
 - Pros
  - very similar to blockchain reactor
  - simple
 - Cons
  - requires serializing and chunking the tree and still supporting proofs for the chunks

2) Allow peers to request specific ranges of keys from the tree
 - Pros
  - More intelligent, potentially more efficient
 - Cons
  - more complex interactions between peers and the tree
  - may actually be slower due to all the tree lookups

After our discussion, we felt we should do a bit more research into these two options. For (1), to look at what chunking the tree would be like, how long it would take, and whether we could preserve proofs, or if we'd need new proofs (eg. put the chunks in a new simple Merkle tree). For (2), to look at how long it takes to query from the tree and what kind of algorithm we'd have at the reactor level to request ranges.

From your work, it sounds like you lean heavily in favour of (1). I think that's also my preference, since it appears much simpler, can re-use blockchain-reactor code (hopefully, at least it should be similar logic), and might actually end up being faster since we may not need to traverse the tree. 

Want to weigh in on this context? And have you looked at serializing/chunking a large AVL tree and how long it takes?

**Comment by ackratos** [comment]
@ebuchman thank you!
I missed your comment until raised this new chunking implementation: https://github.com/tendermint/tendermint/pull/3594...

Regarding the proof of Merkle tree, I didn't understand from beginning. My understanding is the proof is used to make sure chunks this peer synced should same with majority peers' snapshot (call it collection of chunk or iavl tree after synced whatever:)). Do you mean the merkle proof be consistency regarding to tree itself (i.e. a malicious node send us a "valid" (in term of merkle proof, but different with all other nodes in network) application state)? Do you have a concrete example to explain how proof would work for account store iavl tree in your design?

TBH, I didn't aware of validator set validation until recently, we worked around that by save complete tendermint state (which contains validator set information) recently (i.e. 1M blocks) and directly return if the query is within 1M blocks and don't replay validator set change as current implementation. I am afraid there is defect in this way and also not take validator set validation/query into consideration for new state sync mechanism... Will have a deeper investigation.

I just finished the draft implementation in tendermint and our application level (this time I will port it to cosmos so that you will see how application use the chunks), will have some performance test from tomorrow.

**Comment by ebuchman** [comment]
>  make sure chunks this peer synced should same with majority peers' snapshot

I don't think we can just rely on a majority peers assumption, especially since we can have lots of peer turnover while syncing and we need some guarantees that peers have the same snapshot to offer. Is this really what Ethereum does? How does it ensure the peers offer snapshots from the same height ? Does it provide no guarantee in the blockchain itself that the state you're syncing is correct? So with Ethereum it's possible to just sync an incorrect state if you have bad peers?

I would think we need some way to get the merkle root of the chunks in to the blockchain or the application state directly to avoid relying on just peers. Not sure what the best approach would be.

For a concrete example, we could imagine a new consensus parameter called SnapshotFrequency, and a new field in the header called LastSnapshotRoot. So if SnapshotFrequency=10000, it means every node *must* snapshot their state every 10000 blocks. They compute the chunks, and they make a merkle root of the chunks, and then set LastSnapshotRoot equal to that merkle root for the next 10000 blocks. This way, when a client goes to sync the state, they know LastSnapshotRoot, and so they can verify that every chunk they download is correct according to the blockchain. Note this is fully independent of the IAVL design and would work for any tree. All that matters is that you chunk up the tree (however the application wants) and then compute a Merkle root from those chunks.

That said, this is just an example, and I'm not sure a new field in the header is the right way to do this, especially if it only changes every 10000 blocks. An alternative is to store this Merkle root in the application state itself. While this avoids adding extra data to the header, it means the chunk has to be forwarded to the application before it can be verified as correct. Probably a worthy trade off, especially since we want to make headers smaller (#2530, #2521).

In both cases (ie. storing the merkle root in the header or in the state), we have to deal with the fact that serializing the state will actually take on the order of minutes, and we don't really want making the next block to wait for serializing the state. So we might need some kind of delay functionality - for instance you start serializing the state at block 9900, but then only include the resulting merkle root into the header or into the state at block 10000. So even though you start serializing at block 9900, it only becomes available starting at block 10000.

As for the Tendermint State, I think we have to use the light client protocol here to sync the changes to the validator set. Otherwise there's no way to ensure the Tendermint State you download from peers is correct. If you use the light client protocol, then you don't even need to download the Tendermint State, since you can figure it out yourself from the light client sync.

I will try to synthesize everything here into a more coherent document outlining the requirements and potential design over the weekend or early next week. Thanks for your help so far with these prototypes and in fleshing out possible issues. Certainly it would be very valuable if you could help with the chunking of the IAVL tree - I'm not sure that's been implemented yet.

Also note, as mentioned before, ideally the state sync reactor will be able to reuse quite a lot of code from the blockchain reactor re-write, which is moving forward quite well. See the ongoing work in https://github.com/tendermint/tendermint/pull/3561 and the ADR (ie. the spec) in #3506.

**Comment by zmanian** [comment]
So at the application level we have a notion of pruning.

I think it's probably sufficient for the application to have conventions about what blocks for which manifests are commonly available based on standard pruning policies.

I think we want to make sure that weak subjectivity initialization plays well with this feature. 

I sort of imagine in an ideal world that a user passes in a weak subjectivity initialization of `(trust_height, blockhash, pruning convention)`. The node light client syncs from the trust_height to head and then gets a block header for most recent unpruned block and then state syncs and starts.

**Comment by ebuchman** [comment]
> I think it's probably sufficient for the application to have conventions about what blocks for which manifests are commonly available based on standard pruning policies.

But this doesn't help us if we're serializing and chunking the tree independent of its structure since we need to put the new merkle root somewhere, unless we forego the need for a merkle root by making a "majority honest peers" assumption. 

The other alternative is to serialize in such a way that preserves the merkle root of the existing tree so we don't need to track a new root of the chunks, but I'm not exactly sure how this would work (though we should probably explore it!).

Of course if we abandon the chunking approach and just let peers query for ranges of the tree directly, this problem goes away, but then we're assuming trees are iteratable (which isn't true for the patricia trie), we'd need to preserve merkle tree structure in the state sync reactor peer msgs, and we'd have to deal with insertion-order-dependence of the tree root ... all of which suggests we do want to go the chunking route.

**Comment by ebuchman** [comment]
Ok I think we should definitely try to avoid this additional merkle root from arbitrary chunking and just expect that apps will chunk in a way that preserves proofs in the original tree. In any case, we can leave this proof checking to happen app side so that app can decide. Those that want to make honest peer assumptions can do so, and those that don't should chunk accordingly.

**Comment by zmanian** [comment]
If an application wants to offer state sync, it needs to know how to chunk the application state such that it's incrementally verifiable.

**Comment by ackratos** [comment]
> I don't think we can just rely on a majority peers assumption, especially since we can have lots of peer turnover while syncing and we need some guarantees that peers have the same snapshot to offer. Is this really what Ethereum does? How does it ensure the peers offer snapshots from the same height ? Does it provide no guarantee in the blockchain itself that the state you're syncing is correct? So with Ethereum it's possible to just sync an incorrect state if you have bad peers, and then you just have to start over?

AFAIK, parity-ethereum trust the first manifest it received from `peers`:
https://github.com/paritytech/parity-ethereum/blob/b30b54e446981dc57835b74d550b40b36385742a/ethcore/sync/src/chain/handler.rs#L476-L499

A parity-ethereum node verify `peers` on genesis, network parameters:
https://github.com/paritytech/parity-ethereum/blob/master/ethcore/sync/src/chain/handler.rs#L567-L643

**Comment by ackratos** [comment]
> I would think we need some way to get the merkle root of the chunks in to the blockchain or the application state directly to avoid relying on just peers, and to avoid a situation where we synced an incorrect state and have to start again. Not sure what the best approach would be.
> 
> For a concrete example, we could imagine a new consensus parameter called `SnapshotFrequency`, and a new field in the block header called `LastSnapshotRoot`. So if `SnapshotFrequency=10000`, it means every node _must_ snapshot their state every 10000 blocks. They compute the chunks, and they make a merkle root of the chunks, and then set `LastSnapshotRoot` equal to that merkle root for the next 10000 blocks. This way, when a client goes to sync the state, they know `LastSnapshotRoot`, and so they can verify that every chunk they download is correct according to the blockchain. Note this is fully independent of the IAVL design and would work for any tree. All that matters is that you chunk up the tree (however the application wants) and then compute a Merkle root from those chunks.
> 
> That said, this is just an example, and I'm not sure a new field in the block header is the right way to do this, especially if it only changes every 10000 blocks. An alternative is to store this Merkle root in the application state itself. While this avoids adding extra data to the block header, it means the chunk has to be forwarded to the application before it can be verified as correct. Probably a worthy trade off, especially since we want to make headers smaller (ie. #2530, #2521).
> 
> In both cases (ie. storing the merkle root in the header or in the state), we have to deal with the fact that serializing the state will actually take on the order of minutes, and we don't really want making the next block to wait for serializing the state. So we might need some kind of delay functionality - for instance you start serializing the state at block 9900, but then only include the resulting merkle root into the header or into the state at block 10000. So even though you start serializing at block 9900, it only becomes available starting at block 10000.

I see your point. The major problem is we understand state sync different with you from beginning. It looks like you want make it a necessary functionality just like fastsync and consensus reactor. But to our understanding we regard it as an add-on implementation for original gaiad (or our app) just like parity-ethereum's warp sync and original geth. 
Which means, it keep most independent from existing modules:
1. doesn't effect underlying data structure in state/app state which effect consensus and means hard fork.
2. nodes can choose whether to enable this feature, and no matter whether it is enabled doesn't effect consensus - They still have same block store and app state.
3. chunking trees doesn't block block execution. (awkward part is it has to interfere with iavl prune strategy as we need keep the snapshoting version in db before snapshot is done)

If you thinking from this design philosophy, there is no difference between merkle root solution and manifest one. 
If new joiner connected to 3 wrong nodes sending fake merkle root of snapshot in app state (or block header) initially. After it state synced, it connected to 6 more right nodes, it still have to delete all things and start again right?

**Comment by ackratos** [comment]
> Ok I think we should definitely try to avoid this additional merkle root from arbitrary chunking and just expect that apps will chunk in a way that preserves proofs in the original tree. In any case, we can leave this proof checking to happen app side so that app can decide. Those that want to make honest peer assumptions can do so, and those that don't should chunk accordingly.



> If an application wants to offer state sync, it needs to know how to chunk the application state such that it's incrementally verifiable.

Thank for your suggestions. But I still cannot see what is the proof or incrementally verifiable used for.
1. if you want use it verify providers are honest, that's impossible IMHO. I think (might be wrong) the only way to distinguish dishonest nodes in network is connect to honest node and make app hash validation fail. 
2. if you want use it verify snapshot we synced itself is valid, I can add check state.apphash (because current tendermint state is also a chunk) against the hash of iavl tree roots (CommitId of rootMultiStore). That's a bit earlier than waiting next block's app hash check fail.
3. if you want fail earlier than 2nd point, saying fail immediately on receiving a piece of unexpected chunk. Self-containing proof like a manifest file can serve that well as I already made in https://github.com/tendermint/tendermint/pull/3594

**Comment by ackratos** [comment]
> I will try to synthesize everything here into a more coherent document outlining the requirements and potential design over the weekend or early next week. Thanks for your help so far with these prototypes and in fleshing out possible issues. Certainly it would be very valuable if you could help with the chunking of the IAVL tree - I'm not sure that's been implemented yet.

The chunking of the IAVL tree is implemented. please refer: https://github.com/cosmos/cosmos-sdk/blob/070ab7f2818b01f6545c85ccb0ab72b5cf0e9c23/store/statesync_helper.go#L383-L456, in PR https://github.com/cosmos/cosmos-sdk/pull/4275

**Comment by ebuchman** [comment]
> AFAIK, parity-ethereum trust the first manifest it received from peers

Wow, that's crazy.

> Which means, it keep most independent from existing modules:
> 1. doesn't effect underlying data structure in state/app state which effect consensus and means hard fork.
> 2. nodes can choose whether to enable this feature, and no matter whether it is enabled doesn't effect consensus - They still have same block store and app state.
> 3. chunking trees doesn't block block execution. (awkward part is it has to interfere with iavl prune strategy as we need keep the snapshoting version in db before snapshot is done)

Agree with all of this. State sync should be optional and should not impact the consensus state. I revoke my proposal around LastSnapshotRoot. Ie:

> Ok I think we should definitely try to avoid this additional merkle root from arbitrary chunking and just expect that apps will chunk in a way that preserves proofs in the original tree.

As for:

> But I still cannot see what is the proof or incrementally verifiable used for.

The point is to avoid every downloading an incorrect chunk. We use the light client to sync up to the header of the height we're downloading the state from, so we know the state root. Then every time we download a chunk from a peer, we can verify the proof according to that state root. So up to the security of the light client, we can verify that the peer is sending us correct chunk. Does that make sense? 

> Self-containing proof like a manifest file can serve that well as I already made

But in my understanding the manifest file isn't part of the consensus, so you don't know that the manifest you're getting is correct. Whereas by using the light client to determine the correct Merkle root, you get the security of the light client, and can verify each chunk according to that.

**Comment by ebuchman** [comment]
Also, Jae just made an alternative proposal in #3639 - what do you think of that?

**Comment by ebuchman** [comment]
We actually don't trust peers for the SignedHeader since we're verifying those signatures. The only point we want trust to enter the system is on the subjective initialization, which is currently not even implemented, but is in progress.

**Comment by melekes** [comment]
https://research.codechain.io/t/snapshot-sync-proposal/21

**Comment by dlguddus** [comment]
I went to codechain's tech seminar and get interested by this topic. I think when chains get bigger, the assumption to make all nodes provide snapshots is not very realistic. 

What I imagine is a branding of snapshot chunks by signatures from the validators. every chunk will have the certification of origin from trusted validators so that nodes can trust the brand. The trustness can be multiplied if two chunks having same hash but different originator(validator). Then the header of a chunk can possess multiple certifications(signature from validators)

The ecosystem can enforce validators to create and spread such snapshots every period and broadcast proof by signature. Those evidence of creating snapshots(signatures) can be stored in blockchain so that slash module can slash the validator when certain snapshot proof from given period is not submitted.

Because smaller validators have less incentives to keep this responsibility, maybe this kind of responsibility can be given to number of top validators.

**Comment by dlguddus** [comment]
Below is our spec definition on the snapshot sync feature.
Please feel free to share comments!

## 1. ultimate goal

- chunk size optimization and parallel processing
- ability to download and validate historical blocks from arbitrary height to arbitrary height(partial snapshot sync)
- only chunks signed by multiple top validators are allowed to be downloaded and used as a source of validation
- economic incentives design for chunk signing and download centers in each continent
- else?

## 2. step by step implementation

### 1) single snapshot download and validation

- single snapshot containing whole historical blocks as a compressed file
- request download by gaiad command from given provider(node)
- receive download request and send the snapshot file to the requester
- decompress received snapshot and start validation of downloaded snapshot
- when validation is finished, delete existing data and copy validated data to gaia folder

### 2) splitting snapshot into multiple height range(buckets)

- snapshot data splitted into buckets based on height ranges
- each bucket compressed and delivered separately

### 3) splitting each bucket into multiple chunks

- problem : chunks are decided by merkle tree but we also need to split based on height to allow gaiad to validate group of chunks based on height
- we need to first split data based on height, and then split again based on merkel tree

### 4) parallel processing for download and validation

- download and validation of each bucket/chunk is processed parallely to optimize performance

### 5) add signature when a node create each bucket or chunk

- signature allows downloaders validate the original creator of the bucket/chunk
- multiple signature on one bucket/chunk can strengthen the trust on the data
- it is natural to have signatures of multiple top validators on each bucket/chunk so that users can have similar level of trust with the blockchain itself

### 6) a consensus procedure for each bucket/chunk hash

- in the existing consensus process, we can add another consensus layer which create agreement on the hash of each bucket/chunk
- when consensus met for given bucket/chunk, the hash and each signature will be stored in blockchain for users to query

**Comment by marbar3778** [comment]
Here is the current adr for the design, https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-042-state-sync.md also there is a wip pull request for the tree chunking design I'd recommend taking a look at. This is the next thing after the lite client work we aim to solve. We will be starting it in the coming weeks

**Comment by dlguddus** [comment]
> Here is the current adr for the design, https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-042-state-sync.md also there is a wip pull request for the tree chunking design I'd recommend taking a look at. This is the next thing after the lite client work we aim to solve. We will be starting it in the coming weeks

Thanks for the link. If dev team plans to work on it in the "coming weeks", we want to backoff from this topic. 

One question about broad direction of this feature. Why it does not have any property about trustness of the data itself rather than peers? If each peer does not validate each chunk, wrong chunk can floating around the network without any punishment on original creator. Because it is not validated from each peer, it is not each peer's responsibility.

If each peer should validate each chunk, I think it is too overlapped responsibility. It is easier if we can attach signature evidence from already trusted entities, validators. Then we can just directly trust the data itself and does not need to trust peers.

**Comment by erikgrinaker** [comment]
The implementation plan for the initial version of state sync is outlined in [ADR-053](https://github.com/tendermint/tendermint/blob/master/docs/architecture/adr-053-state-sync-prototype.md).
