### ISSUE TITLE
build docker image twice

### ISSUE THREAD

**Issue by kimroniny** [tendermint/tendermint#8362]
https://github.com/tendermint/tendermint/blob/2e432d12f77b1730cb838807bbb6123656838751/Makefile#L233

first: build-linux

second:  inside the build-docker

so why build twice with build-docker command?

**Comment by creachadair** [comment]
It's probably just a historical artifact, you're right that it's not necessary. The rest of the rule copies the built binary into the image, but I'm guessing that's left over from a time before #5087 when the build context was just the `DOCKER` directory instead of the root. We've already cleaned that up on master.

**Comment by creachadair** [comment]
Closed by #8363, will go out in the next point release for v0.35.
