### ISSUE TITLE
priv_validator_state.json does not get regenerated

### ISSUE THREAD

**Issue by czarcas7ic** [tendermint/tendermint#8389]
**Tendermint version** : v0.34.19

**ABCI app**: Osmosis v7.2.0

**Environment**:
- **OS**: linux/amd-64

**What happened**: On `unsafe-reset-all`, a new `priv_validator_state.json` does not get generated.

**What you expected to happen**: If the data folder has been wiped, I expect a new `priv_validator_state.json` to be created.

**Have you tried the latest version**: No

**How to reproduce it** (as minimally and precisely as possible):
```
git clone https://github.com/osmosis-labs/osmosis.git
git checkout v7.2.0
make install
rm ~/.osmosisd/data/priv_validator_state.json
osmosisd unsafe-reset-all
```

**Comment by williambanfield** [comment]
Thanks for the report, I believe that this is caused by recent changes to the code that integrates Tendermint and the SDK. The changes that are likely related are https://github.com/tendermint/tendermint/pull/8134, https://github.com/tendermint/tendermint/pull/8081 and https://github.com/tendermint/tendermint/pull/8270 that altered the surface area of the Tendermint commands. As a workaround, you should be able to specify the home directory on the command line using `--home=path/to/osmosis/folder'.
