### ISSUE TITLE
Complete `panic` review

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#84]
The problem is if, say, a proposer maliciously proposes a block where the first transaction deletes a nameTx, then a second transaction updates that name.  Not sure if this is actually a problem or not, but state/execution seems to panic in this case, and I'm not sure what catches it.

We should catch panics during block execution and return an error.

**Comment by ebuchman** [comment]
ok so is this also a problem for CallTx? no right, since if its removed theres no way even for a malicious block to cause an update to it. But for a name tx, maybe it doesn't even make sense, since the name could be removed and then created again within the same block, so it should be totally legit to update a removed account and we can just remove that panic? tho id still say we should catch panics around the ExecTx loop.

**Comment by ebuchman** [comment]
panic function wrappers instead of big bold comments

**Comment by jaekwon** [comment]
Sounds like a great idea.  In common/errors.go perhaps?

**Comment by ebuchman** [comment]
i think at this point we just need to stick a couple `defer/recover` statements in to protect ourselves
