### ISSUE TITLE
p2p: sentry node peer connecting could create 10K sockets in a very short period

### ISSUE THREAD

**Issue by JayT106** [tendermint/tendermint#8435]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
v0.34.14

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
https://github.com/crypto-org-chain/cronos

**Environment**:
OS (e.g. from /etc/os-release): Linux
Install tools: https://github.com/rockset/rocksdb-cloud/blob/master/INSTALL.md
Others: RockDB backend

**What happened**:
Looking at an issue related to our network will miss a lot of votes in certain blocks. Checking the log of our sentry node, and observing the similar message repeatedly in a few seconds period(usually with the same peer id), and at the same time, the waiting close socket number might increase to around 10K scale. The frequency is around 5~15 mins.

```
Apr 28 21:42:55 ip-10-202-128-106 cronosd[707073]: 9:42PM INF Ignoring inbound connection: already have enough inbound peers address={"id":"325978f555b83614ac655c0f07bacc5a3a3b5f6a","ip":"10.202.128.111","port":41886} have=30 max=30 module=p2p server=node
```

**What you expected to happen**:
Not sure if it relates to the block missing votes issue, but almost we can see the block missing votes after seeing this p2p behavior. Expected the inbound connecting should not happen that frequently. (Assuming this issue is not a p2p DDoS)

**Have you tried the latest version**: yes/no
No

**How to reproduce it** (as minimally and precisely as possible):
might need to create a 50~100 nodes network with validators setting behind some sentry nodes.

**Logs (paste a small part showing an error (< 10 lines) or link a pastebin, gist, etc. containing more of the log file)**:

```
Apr 28 21:42:37 ip-10-202-128-106 cronosd[707073]: 9:42PM INF Ignoring inbound connection: already have enough inbound peers address={"id":"fac27d93e238f22b0131b98dbca7c4c236582a5a","ip":"142.132.213.20","port":33400} have=30 max=30 module=p2p server=node
Apr 28 21:42:39 ip-10-202-128-106 cronosd[707073]: 9:42PM INF Ignoring inbound connection: already have enough inbound peers address={"id":"965cc3cfb22a40237fd45b5d3ddffad87114fc82","ip":"149.28.87.154","port":53272} have=30 max=30 module=p2p server=node
Apr 28 21:42:49 ip-10-202-128-106 cronosd[707073]: 9:42PM INF Ignoring inbound connection: already have enough inbound peers address={"id":"b29e550dda70b952bdd3ec540fb82b116e2925d9","ip":"3.120.152.165","port":56342} have=30 max=30 module=p2p server=node
Apr 28 21:42:52 ip-10-202-128-106 cronosd[707073]: 9:42PM INF Ignoring inbound connection: already have enough inbound peers address={"id":"325978f555b83614ac655c0f07bacc5a3a3b5f6a","ip":"10.202.128.111","port":39092} have=30 max=30 module=p2p server=node
Apr 28 21:42:52 ip-10-202-128-106 cronosd[707073]: 9:42PM INF Ignoring inbound connection: already have enough inbound peers address={"id":"325978f555b83614ac655c0f07bacc5a3a3b5f6a","ip":"10.202.128.111","port":39094} have=30 max=30 module=p2p server=node
Apr 28 21:42:52 ip-10-202-128-106 cronosd[707073]: 9:42PM INF Ignoring inbound connection: already have enough inbound peers address={"id":"325978f555b83614ac655c0f07bacc5a3a3b5f6a","ip":"10.202.128.111","port":39096} have=30 max=30 module=p2p server=node
Apr 28 21:42:52 ip-10-202-128-106 cronosd[707073]: 9:42PM INF Ignoring inbound connection: already have enough inbound peers address={"id":"325978f555b83614ac655c0f07bacc5a3a3b5f6a","ip":"10.202.128.111","port":39098} have=30 max=30 module=p2p server=node
Apr 28 21:42:52 ip-10-202-128-106 cronosd[707073]: 9:42PM INF Ignoring inbound connection: already have enough inbound peers address={"id":"325978f555b83614ac655c0f07bacc5a3a3b5f6a","ip":"10.202.128.111","port":39100} have=30 max=30 module=p2p server=node
Apr 28 21:42:52 ip-10-202-128-106 cronosd[707073]: 9:42PM INF Ignoring inbound connection: already have enough inbound peers address={"id":"325978f555b83614ac655c0f07bacc5a3a3b5f6a","ip":"10.202.128.111","port":39104} have=30 max=30 module=p2p server=node
```
the latest log will repeat few thousand times within 2~3 seconds

**Config (you can paste only the changes you've made)**:
N/A
**node command runtime flags**:
N/A
**Please provide the output from the `http://<ip>:<port>/dump_consensus_state` RPC endpoint for consensus bugs**
N/A
**Anything else we need to know**:

**Comment by creachadair** [comment]
The code has changed quite a bit since v0.34, but your analysis seems consistent with what the p2p switch does in v0.34 (and I think also in v0.35). 

The [`acceptRoutine`](https://github.com/tendermint/tendermint/blob/v0.34.x/p2p/switch.go#L618) accepts connections from the listener before checking whether they're wanted, so that even if it then closes the connection later (cf. [here](https://github.com/tendermint/tendermint/blob/v0.34.x/p2p/switch.go#L685)) it is believable that the kernel winds up with a lot of connections pending.

That said, I would not expect a lot of `CLOSE_WAIT` in that case, since that usually requires a connection that has _not_ been closed yet. It looks like the `Cleanup` method does devolve to the `net.Conn.Close` method under the covers, which should release the socket more or less immediately. In v0.35, that code does more or less the same thing with one fewer layers of interface indirection.  Do you actually see these sockets lingering in `CLOSE_WAIT` when this occurs (e.g., in `lsof`)?

There might be a good argument that we shouldn't call `Accept` on connections we know we don't want. It would be better to let the kernel reject the connection entirely at the IP layer because the listener fills up, than to complete the handshake and accept them only to immediately shut them back down (thus triggering a FIN/ACK round per rejected socket).

**Comment by JayT106** [comment]
> Do you actually see these sockets lingering in CLOSE_WAIT when this occurs (e.g., in lsof)?

No, the `lsof` of TCP is pretty stable, around 70+.
