### ISSUE TITLE
RPC: Support R/W Timeout Configurations

### ISSUE THREAD

**Issue by alexanderbez** [tendermint/tendermint#8465]
## Summary

Add read and write timeout configurations to the RPC configuration block.

## Problem Definition

The RPC server does not have the ability for operators to set read and write timeouts. This means the default HTTP timeouts are used. This means that requests that return large blobs of data sometimes timeout. See https://github.com/osmosis-labs/osmosis/issues/1391.

```go
// ListenAndServe listens on the address specified in srv.Addr and handles any
// incoming requests over HTTP using the Inspector rpc handler specified on the server.
func (srv *Server) ListenAndServe(ctx context.Context) error {
	listener, err := server.Listen(srv.Addr, srv.Config.MaxOpenConnections)
	if err != nil {
		return err
	}
	go func() {
		<-ctx.Done()
		listener.Close()
	}()

	return server.Serve(ctx, listener, srv.Handler, srv.Logger, serverRPCConfig(srv.Config))
}
```

I propose we add R/W timeouts to the RPC configuration blob in Tendermint and pass them to the `server.Serve` call where we create the `*http.Server`. However, this currently conflates with `serverRPCConfig`. We shouldn't use `r.TimeoutBroadcastTxCommit` for that, but rather dedicated configurations.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by creachadair** [comment]
Do the settings on the [`server.Config`](https://github.com/tendermint/tendermint/blob/master/rpc/jsonrpc/server/http_server.go#L22) type not address this concern? The server plumbs those timeouts in to the underlying HTTP server [here](https://github.com/tendermint/tendermint/blob/master/rpc/jsonrpc/server/http_server.go#L52).

**Comment by tyrion70** [comment]
@creachadair thats interesting actually, I just tried but it seems you can actually set the WriteTimeout throught the `timeout_broadcast_tx_commit` config var because the http server is started from here:
https://github.com/tendermint/tendermint/blob/dd4fee88ef6e4e0e5cf8eab0bf5a3e078df355c9/internal/rpc/core/env.go#L239

Its actually mentioned in the config file as well
```# WARNING: Using a value larger than 10s will result in increasing the
# global HTTP write timeout, which applies to all connections and endpoints.```

I never realized that that was actually setting the global timeout. Wouldn't it be better to have a distinct timeout for tx broadcasting and a seperate config for global read and write timeouts? (or rename the current variable to match what its actually doing)

**Comment by creachadair** [comment]
> @creachadair thats interesting actually, I just tried but it seems you can actually set the WriteTimeout throught the `timeout_broadcast_tx_commit` config var because the http server is started from here:

That's really just a workaround, we added because there is only one place to set the timeout. We shouldn't put any more weight on that particular hack, though it does happen to have that side-effect. This will all be substantially reworked in v0.37, and my intent is to have timeouts governed per-request rather than per-server (I might keep a safety fallback on the server, but it should be long enough that no one will hit it unless something weird happens).

It's fine to use that as a workaround for now, but we shouldn't rely on it persisting.

**Comment by tyrion70** [comment]
Perfect! It at least solves the current issue at hand and if there's a per-request-timeout in the works that would solve it in a more elegant way. But just for my sanity, there is no other place where we could set this global timeout right now in the config right? I don't think Server.config is actually available in either app.toml or config.toml?

**Comment by creachadair** [comment]
> But just for my sanity, there is no other place where we could set this global timeout right now in the config right? 

Not in the Tendermint `config.toml`, at least.

> I don't think Server.config is actually available in either app.toml or config.toml?

I believe the SDK _could_ set custom values in the RPC config, but I do not know whether it does right now. I am not very familiar with the details of the SDK config, and I expect your interpretation is likely correct.

**Comment by alexanderbez** [comment]
> I believe the SDK could set custom values in the RPC config, but I do not know whether it does right now. I am not very familiar with the details of the SDK config, and I expect your interpretation is likely correct.

This is a Tendermint configuration and responsibility, not the SDK's. The SDK does not start Tendermint's RPC server.
