### ISSUE TITLE
Remove versioning from the PBTS spec files.

### ISSUE THREAD

**Issue by cason** [tendermint/tendermint#8602]
Although this issue is specific for PBTS, I think it is worth a more comprehensive discussion.

On the one hand, we want to keep track of changes in the specification, keep its history, so that anyone is able to follow the process that lead to it. In the specific case of PBTS, this includes the previous solution, BFTTime, as well the first proposal for implementing PBTS.

On the other hand, this repository, specially the content under `spec/`, should ideally contain only updated information, that reflects the current state of the implementation. So, ideally, both BFTTime and the first proposal of implementation of PBTS should not be present in the `master` branch.

Notice that old versions of the documentation, as long as the implementation, are always available in branches. For instance, the BFTTime documentation will remain available in `v0.35.x` branch, as it was the solution adopted in that version of Tendermint. The same is not true for the first proposal for implementing PBTS, which however could be maintained in some other branch.

**Comment by sergio-mena** [comment]
The current approach is the following:

* v0.36 branch will have the current spec minus the same-block execution aspects, since this is not implemented in this version
* the master branch will keep the current spec (with same-block execution)

So the principle is to have a 1:1 match between the implementation and the specification on each release branch.
