### ISSUE TITLE
Very high memory usage resulting in OOM while fastsync

### ISSUE THREAD

**Issue by re7eal** [tendermint/tendermint#8626]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source):
0.34.19

**ABCI app** (name for built-in, URL for self-written if it's publicly available):
https://github.com/ndidplatform/smart-contract

**Environment**:
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 11 (bullseye)
- **Install tools**:
- **Others**: Tendermint+ABCI (single binary) running in docker container. VM has 16GB memory.

**What happened**:
Exit 137 due to OOM while fastsync. There seems to be memory leak when receiving messages from other nodes since memory usage keeps going up without reducing at all. Please see attached go pprof file.

**What you expected to happen**:
Memory usage shouldn't go up boundlessly.

**Have you tried the latest version**:
no (haven't tried 0.35.x)

**How to reproduce it** (as minimally and precisely as possible):
Have a large data (many large size transactions) in multiple blocks and start another node to fastsync.

**Anything else we need to know**:

![pprof001](https://user-images.githubusercontent.com/5270158/170483468-78781936-be47-42af-9e11-fa5f3ae9bb66.svg)

![tendermint pprof top](https://user-images.githubusercontent.com/5270158/170483690-48c4df32-d404-442a-a782-c64435123ee9.png)

Go pprof file
[tendermint.5.pprof.zip](https://github.com/tendermint/tendermint/files/8778699/tendermint.5.pprof.zip)

**Comment by creachadair** [comment]
If the size does not reduce after a GC, then there probably isn't a memory leak in the traditional sense. That could lead the GC to thrash (which would also be unfortunate), but here it looks like those data are all still reachable from the root set.

My guess is that we may not have bounded the concurrency during fastsync, which in the presence of large blocks could explain why a lot of unmarshal buffers are all resident at the same time (I am not as familiar with fastsync, but I believe it processes blocks concurrently).

**Comment by re7eal** [comment]
Hi @creachadair , thank you for your reply. Is there a way to mitigate this issue? Do you have any suggestions?

**Comment by creachadair** [comment]
> Hi @creachadair , thank you for your reply. Is there a way to mitigate this issue? Do you have any suggestions?

I don't know of any simple workarounds, unfortunately. The two places where this process seems to get memory pressure are (a) the rate of blocks received from peers, and (b) the size of the block pool. There does not seem to be an easy way to rate-limit (a), and (b) falls out of that (since it caches a complete block in memory per requester). 

Possibly it might help to configure a smaller set of peers for the node that is trying to catch up, since that might reduce the rate at which those inputs arrive. (It would probably also slow down sync, but that might be OK if the alternative is crashing). This is a guess, though; I'm not super familiar with the internals of fastsync and am basing this suggestion on a cursory look at the hot path on that profile.

**Comment by re7eal** [comment]
After some trial and error, reducing block `max_bytes` in genesis.json file from the default (~21MB) down to around 5MB (or lower) can help avoid this issue. Memory usage on nodes that are catching up with fastsync seems to be stable (around 7GB in my case).
