### ISSUE TITLE
privval: signerEndpoint.GetAvailableConnection incorrectly reports true when given closed channels

### ISSUE THREAD

**Issue by odeke-em** [tendermint/tendermint#8648]
**Tendermint version** (use `tendermint version` or `git rev-parse --verify HEAD` if installed from source): 2e5d53ea9a1022c651c8ed032390ef18e49243c6

**What happened**:
While auditing privval, noticed that I can easily trick signerEndpoint.GetAvailableConnection into returning true given the code isn't cognizant of the fact that closed channels in Go immediately return when selected on and this test below proves it
```go
package privval

import (
    "net"
    "testing"

    "github.com/stretchr/testify/require"
)

func TestInvalidSignerEndpointGetAvailableConnect(t *testing.T) {
    se := new(signerEndpoint)
    ch := make(chan net.Conn)
    close(ch)

    ok := se.GetAvailableConnection(ch)
    require.False(t, ok, "Should not report that there is an available conn")
}
```

which unfortunately prints
```shell
$ go test -run=GetAvailable
--- FAIL: TestInvalidSignerEndpointGetAvailableConnect (0.00s)
    signer_endpoint_test.go:16: 
        	Error Trace:	signer_endpoint_test.go:16
        	Error:      	Should be false
        	Test:       	TestInvalidSignerEndpointGetAvailableConnect
        	Messages:   	Should not report that there is an available conn
FAIL
exit status 1
FAIL	github.com/tendermint/tendermint/privval	0.370s
```

**What you expected to happen**:
It should pass by reporting false

## Remedy
The correct way to select on channels and check if closed should follow the receive operator specification per https://go.dev/ref/spec#Receive_operator
and the following
```diff
diff --git a/privval/signer_endpoint.go b/privval/signer_endpoint.go
index 8810bdf85..4a5f80d0e 100644
--- a/privval/signer_endpoint.go
+++ b/privval/signer_endpoint.go
@@ -41,17 +41,17 @@ func (se *signerEndpoint) IsConnected() bool {
 }
 
 // TryGetConnection retrieves a connection if it is already available
-func (se *signerEndpoint) GetAvailableConnection(connectionAvailableCh chan net.Conn) bool {
+func (se *signerEndpoint) GetAvailableConnection(connectionAvailableCh chan net.Conn) (ok bool) {
        se.connMtx.Lock()
        defer se.connMtx.Unlock()
 
        // Is there a connection ready?
        select {
-       case se.conn = <-connectionAvailableCh:
-               return true
+       case se.conn, ok = <-connectionAvailableCh:
+               return ok
        default:
+               return false
        }
-       return false
 }
```

There are many more selects in the code that have similar assumptions and should be fixed.

**Comment by creachadair** [comment]
It is an unfortunate reality of Tendermint that there are many internal APIs that use channels on the assumption that those channels will never be closed. This is one of those cases—and the (sole) existing usage of these methods never closes the channels passed to this library.

So this proposed change is fine, but does not affect the behaviour of the system. It would be a good idea for us to more systematically fix the APIs that depend on this quirk, but I think we'd be better off doing that as a broader change rather than targeting the specific usage here.

Since there does not appear to be any use of these methods outside the package, it may be worth unexporting them to prevent the damage from spreading any further, but I don't think that's super urgent.
