### ISSUE TITLE
P2P: validator mode

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#865]
- [ ] no incoming connections - only via VPN.
  - Is this just done by setting p2p.laddr in config?
  - This can be modeled and tested using AWS or GCP VPC functionality.
- [ ] some sentry manager that determines connectivity to sentries. 
        - for instance slowly shuffle so we're connected to a random 4 of 7 or so at a time
        - should this be a separate process? we can have a default that just dials all the addresses given in a config, but allow specifying the address of a sentry-manager-proxy that ensures there's a cluster of sentries available and tells you which ones to connect to

**Comment by LeeBlues** [comment]
![proxy](https://user-images.githubusercontent.com/8119644/32924889-4be92cb2-cb82-11e7-9c35-be1ae14ebaa5.jpg)

In order to use above architecture, function NewNetAddressString from netaddress.go should be changed to hold ipset of DNS. currently it held only one ip ( ip = ips[0]). Then StopPeerForError from switch.go should try to reconnect to randomly selected ip address from DNS ip set which excluded previously failed one.
 
It is possible to set proxies to deny ip inbound request  if other proxy already serve inbound ip that included at same Domain.  Then attacker may kill one proxy but cannot kill all of them.

**Comment by mdyring** [comment]
I would argue for keeping it simple. It seems a general case would be that sentries can register themselves via DNS by adding a A/AAAA/CNAME record to some well-known record (say, sentries.myvalidator.com).

The validator node would then periodically do a lookup on sentries.myvalidator.com and update the sentry list from that set.

**Comment by LeeBlues** [comment]
Yeah Tendermint node should be able to communicate through domain name. It should domain query and update its ipset.

**Comment by nickray** [comment]
I suggest keeping in mind that load balancing via registering multiple hosts to the same A record is a bit "ghetto". There are TTLs, DNS server caching, badly behaving clients etc.
There [are reasons](https://kubernetes.io/docs/concepts/services-networking/service/#why-not-use-round-robin-dns) why for instance Kubernetes does this as an internal service.

**Comment by mdyring** [comment]
The multiple A/AAAA records are not intended for load balancing purposes but simply for redundancy. 

For instance,

Name:    gaia.block.finance
Addresses:  35.158.253.181
          52.57.241.111

.. the two IPs each point to different availability zones in AWS (coincidentally, each IP is a load balancer that directs traffic to full nodes on a private subnet). 

Simply to avoid a "too static" configuration of peers, I think it makes sense to support DNS names. The node can then periodically perform the query and, if it succeeds, add/remove peers that changed from the previous query.

Regarding non-public routes that seems like a fine backup plan as well. :-)

**Comment by tarcieri** [comment]
Coming from a more traditional payment network space, the way to solve this is by peering in the traditional AS sense. No ASNs or anything so onerous are needed at first: a much simpler way to get started is for two validators to agree on a common SDN provider (or find two SDNs who can talk to each other), use that to establish a layer 2 circuit, then agree on some subnets and IP addresses and begin sending packets directly between each other.

With an SDN provider one physical fiber could provide a link to several validators, by using trunking and configuring different VLANs for every validator you peer with.

SDNs are, in effect, a sort of VPN, but usually one running on dedicated site-to-site links between datacenters rather than commodity BGP traffic running atop the Internet.

You could additionally use some over-the-Internet transport as a secondary circuit in the event something is wrong with the SDN link, running atop some VPN of sorts. It might be an interesting use case for Tor.

SDN options will vary from datacenter-to-datacenter. [Megaport](https://www.megaport.com/) is one example.

**Comment by ebuchman** [comment]
Thanks @tarcieri that sounds like a sound approach.

So it seems like we don't really need to make any changes to Tendermint itself to support this ?

**Comment by tarcieri** [comment]
Nope, validators would just be reachable at two different IP addresses, one reachable from the Internet and one (or more) in private RFC1918 address space, rather than over the Internet.

Having a private network between the validators should also dramatically reduce latencies, and is I believe how Bitcoin miners presently operate today.

If, some time in the future, validators were to actually get their own ASNs, then you wouldn't need to use RFC1918 address space at all, and they could advertise routes to each other with BGP, with OSPF picking the best available one.

**Comment by adrianbrink** [comment]
@mdyring I think you might be one of the few validators who already has his own ASN. :-)

**Comment by ebuchman** [comment]
Sounds great, will close this then as there's nothing more we need to do on Tendermint :)

**Comment by mdyring** [comment]
Yes it seems almost everything should work today with setting up sentries.

One thing I'd like added is the support for DNS names though. Is that implemented or should I open a separate issue for that?

**Comment by nickray** [comment]
The ticket is closed, but was referenced in the cosmos validator chat. So let me copy-paste my question:

> Since several people are planning to use a setup where a "sentry" is multiple machines running behind a cloud load balancer (ie. only one public IP, possibly even only one port).. if the validator client node marks such an ip:port pair as "bad" in case of an interrupted connection, that would be bad/defeat the purpose ;)

**Comment by amrali** [comment]
Currently a node endlessly tries to redial offline nodes, a more reasonable redial policy should involve a backoff strategy, if it ends up being configurable I'm sure that'll be most friendly.

**Comment by xla** [comment]
@amrali See #1292 would be nice if you can add your expectations there.

**Comment by ebuchman** [comment]
> if the validator client node marks such an ip:port pair as "bad" in case of an interrupted connection, that would be bad/defeat the purpose ;)

The validator should specify the sentry nodes as --persistent_peers, that way they'll be sure to try and reconnect. See https://github.com/tendermint/tendermint/pull/1519 for update in the pex.md
