### ISSUE TITLE
P2P: Sentry Mode

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#866]
Thoughts about potential additions:

- less bias for unvetted peers during book.PickAddress
- use some multiple above 1 for bad behaviour (?)
- evolving random connections to each other (as special subset of total peers)
- special incoming slot for validator and its backups

**Comment by zmanian** [comment]
So I don't know how critical the issues that Bucky called out are.

1. We seem to be good connect node with PEX disabled to nodes with PEX enabled.
2. It would be very helpful to be able to configure PEX nodes so they will not gossip ip addresses in a blacklist/ range of ip
3. It would be good to know that the dialseed RPC call would for connecting to sentries.

**Comment by ebuchman** [comment]
So it seems the only thing we really need to add is a `--p2p.private_peers` flag that takes a list of peer IDs and ensures that these peers are not added to the address book so they are not gossipped about. Note I'd recommend using peer IDs here and not IP addrs.

Then sentry nodes can use `--p2p.persistent_peers` (coming in open PR) to specify other sentry nodes, and `--p2p.private_peers` to specify the validator node. The validator node can use `--p2p.persistent_peers` to specify the sentry nodes. The RPC `/dial_peers` (in open PR) will work as well, with a `persistent` bool flag, allowing the validator to dial newly spun up sentry nodes.

The only other thing that I thought might be nice is for sentry nodes to maintain connections with a randomly changing subset of eachother, rather than persistent connections to all. So you would specify some  `--p2p.sentry_mode` params and then instead of persistent connections with all `--p2p.persistent_peers` you'd constantly cycle through them, but always staying connected to at least 3 of 5 or something.  Is that useful, or too much complexity for now ? 

We may also want to consider what the `/net_info` call returns - if the sentry nodes expose their RPC to the public, everyone will see all the peers they are connected to. Probably the right thing to do is not run a public RPC on sentry nodes, rather than removing the validator from that list. Right ?

**Comment by adrianbrink** [comment]
> We may also want to consider what the /net_info call returns - if the sentry nodes expose their RPC to the public, everyone will see all the peers they are connected to. Probably the right thing to do is not run a public RPC on sentry nodes, rather than removing the validator from that list. Right ?

I would say that they shouldn't expose that endpoint to the public. It's useful into to return all connected peers, since it can be used to check whether you are still connected to the validation node.

> To we want to limit the extent to which sentry nodes gossip about each other? Or anything else about the way they connect to other peers on the network ?

This seems fussy and complex for now. I'd say maybe after launch.

> The only other thing that I thought might be nice is for sentry nodes to maintain connections with a randomly changing subset of eachother, rather than persistent connections to all. So you would specify some --p2p.sentry_mode params and then instead of persistent connections with all --p2p.persistent_peers you'd constantly cycle through them, but always staying connected to at least 3 of 5 or something.  Is that useful, or too much complexity for now ?

I like that idea, but seems to complex without a real need for it.

**Comment by adrianbrink** [comment]
Sentry-node architecture explained:

The sentry-node architecture is designed to hide the validation node's IP address from untrusted peers. If the validation node's IP becomes public, it means that it is much easier to hack as well as DDOS. The overall goal is to have a validation node which participates actively in consensus, but sits behind a couple of sentry (aka proxy) nodes, who are directly connected with other peers on the network.

A simple way to achieve this goal is to spin up a couple of cloud (AWS, DO, GCE, ...) servers. These are now the sentry nodes. They can potentially be DDOSed or hacked and if that is the case should be swapped regurarly. 
Then spin up the validator node. This node should ideally be located in a physically secure datacenter of your choosing, so that you can attach an HSM to it. In the near future we might also support remote HSM calls, so that even the validation node can be in the cloud while still being connected to a physical HSM. In `config.toml` file of the validation node disable the PEX reactor by setting the `--p2p.pex` flag to false and put the sentry nodes' IPs as seed nodes.

**Comment by ebuchman** [comment]
Ok great. Seems like we can close this now in favour of simple concrete issue: https://github.com/tendermint/tendermint/issues/1126

**Comment by zmanian** [comment]
We also need a fix for https://github.com/cosmos/gaia/issues/111#issuecomment-359196452
