### ISSUE TITLE
TenderTee: Secure Tendermint

### ISSUE THREAD

**Issue by robert-zaremba** [tendermint/tendermint#8677]
## Summary

There is a very interesting paper outlining modification of Tendermint, increasing the byzantine tolerance to 1/2 of the network.

Paper: https://eprint.iacr.org/2022/599

## Problem Definition

Tendermint halts if 2/3 of nodes (by power) won't honestly collaborate. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by faddat** [comment]
👀

**Comment by ValarDragon** [comment]
I don't think TenderTee is of much relevance to Tendermint project right now.

Its basically saying "Look we can use a light-weight Trusted Execution Environment (TEE), to improve equivocation bounds"
The lightweight model is "Trusted Append-Only Memory" (they call it attested append only memory, or A2M). This means you can only get a double sign at > 50% faulty collobarating. This model is presumably of interest, because its easier to solve than generic TEE's.

However getting this into a production state would require an insane foundation investment in productionizing Trusted append only memory, and hosting competitions for it. Else, you wouldn't rely on the higher security bound!

I'd recommend closing the issue personally.
