### ISSUE TITLE
P2P: Peer should be able to be accessed through dns rather than only ip address.

### ISSUE THREAD

**Issue by LeeBlues** [tendermint/tendermint#869]
![proxy](https://user-images.githubusercontent.com/8119644/32924889-4be92cb2-cb82-11e7-9c35-be1ae14ebaa5.jpg)
Above scheme enable to set proxies to deny ip inbound request  if other proxy already serve inbound ip that included at same domain.  Then attacker may kill one proxy but extremely hard to kill all of them.

In order to use above architecture, function NewNetAddressString from netaddress.go should be changed to get ip set of domain and save it to NodeInfo RemoteAddr. currently it held only one ip ( ip = ips[0]). Also  function StopPeerForError from switch.go should be changed to try to reconnect to randomly selected ip address from domain ip set which excluded previously failed one.

**Comment by LeeBlues** [comment]
I just changed  function NewNetAddressString which resides at p2p/netaddress.go to randomly reference other ip address of domain then I killed one of two proxies. validaror node switched to other proxy. network works well.

**Comment by mdyring** [comment]
There are some claims that this is working now on Matrix chat:

nickray
mdyring: sure it does. if not, then chris and I may be the culprits of the consensus losses ;)

Kris Pritchard
Yeah I assumed that it's been working?

mdyring
I don't think so.. But haven't tested since I bumped into it not working some months ago.

17:06
I will update the issue and ask

**Comment by melekes** [comment]
Still not clear whenever people want this implemented or not https://github.com/tendermint/tendermint/issues/865.

**Comment by melekes** [comment]
The way [addrbook](https://github.com/tendermint/tendermint/blob/master/p2p/pex/addrbook.go) is designed right now: 1 entry - 1 IP. Changing it  to support multiple IPs will require great deal of time. 

I believe the problem you described can be solved with https://www.haproxy.org or https://traefik.io/ or nginx, which are better at doing this job than Tendermint. They provide simple round-robin, weighted round-robin and other balancing strategies. Should we even attempt to implement this on Tendermint side?

What we probably should do is store domain name along side IP and a) use it everytime we need an IP OR b) use it when current IP is unreachable.

**Comment by krisrp** [comment]
There seems to be some confusion regarding the support for DNS in config files, and it looks like people are mixing up this issue -- requesting round-robin dns, which isn't supported -- with the ability to use dns for seeds in a config.toml file, which is supported, and is what I was referencing weeks ago in chat.

@melekes I personally don't think implementing client-side round-robin is necessary. Better load balancing solutions exist.

**Comment by mdyring** [comment]
For our genesis validator setup, we plan to publish a single DNS record which will point to multiple A/AAAA records.

Behind each IP is a AWS load balancer, the reason there are multiple is because they are in different availability zones (AZs). I need to double check if AWS can do fail-over at DNS level if an AZ fail, but this is a sub-optimal solution since we would then only utilize the servers running in one AZ at a time. Ideally we want to load balance across all AZs/load balancers/sentries.

Without having deep dived into addrbook internals, I believe the following should be sufficient and not require too many changes.

If a DNS name is provided, ***all*** the IPs that it resolves to should be added to the address book. The name resolution should only happen once and not periodically, and there is no need to record the DNS name in the address book.

Now, if one of the associated IPs no longer responds, it should be dropped from the addrbook and not used for PEX (which I imagine is what happens today anyway to handle dead peers).

If one of the IPs change, or a new one is added, any freshly joining node (performing its initial DNS  resolution) will discover this new IP and it will eventually propagate to other nodes via PEX.

**Comment by xla** [comment]
> Behind each IP is a AWS load balancer, the reason there are multiple is because they are in different availability zones (AZs). I need to double check if AWS can do fail-over at DNS level if an AZ fail, but this is a sub-optimal solution since we would then only utilize the servers running in one AZ at a time. Ideally we want to load balance across all AZs/load balancers/sentries.

Route53 supports DNS failover.

> If a DNS name is provided, all the IPs that it resolves to should be added to the address book. The name resolution should only happen once and not periodically, and there is no need to record the DNS name in the address book.

Besides the increased complexity from the bookkeeping it doesn't respect DNS offering of TTL for records. The addressbook would then become yet another cache in an already non-trivial chain of intermediates in the DNS infrastructure. We will have to expect report sof stale entries nad inconsistent views as with every caching layer.

Maybe you can clarify which part of your setup is aiming to address which concern (fault-tolerance, load shedding, etc.) to better understand why the integrating on DNS for all of those is desired.

**Comment by xla** [comment]
Forgot to expand, we just discussed this issue last night in our dev meeting. The solution we were leaning towards was to store the DNS and do the resolution whenever we dial a peer and advertise the IP. This way we push the responsibilities to existing intermediates as @krisrp suggested.

**Comment by mdyring** [comment]
> Route53 supports DNS failover.

Correct, but fail over implies having a standby infrastructure running that is not utilized, with associated cost. I'd like to avoid that.

> Maybe you can clarify which part of your setup is aiming to address which concern (fault-tolerance, load shedding, etc.) to better understand why the integrating on DNS for all of those is desired.

Certainly. First of all, the general desire to support DNS names, especially at genesis validator level, is to allow for evolving infrastructure.

Secondly, having _multiple_ A records associated with a DNS name allows for higher availability by operating in multiple availability zones, which I'd consider best practice for genesis validators.

I don't see DNS as a part of load balancing at all. Load balancing across full nodes (sentries) is handled at a lower level (by haproxy, balanceng, cloud-provider LB etc.) and should not be a concern of Tendermint/addrbook, as it would only see the public facing IP of the loadbalancer.

Therefore, I am arguing for keeping it simple (minimal changes) and not integrating DNS at all levels of Tendermint. The simplest solution that caters for the above, would be that DNS resolution only happen once peers are initially added from config or command line.

I imagine there is already support for expiring dead peers from addrbook, regardless of how they were added (PEX, static IP from config or DNS lookup from config). So no changes here, hopefully.

By adding all resulting IPs from a lookup to addrbook, even if one available zone (and thus load balancer) dies, the other zones would already be in the address book and trivially connected to (if they weren't already).

What you guys discussed at the dev meeting might work as well. But the code should take into consideration what happens if the first (of multiple) resolved IPs is unresponsive, and then try the next one, and so on. I guess it might as well also advertise the DNS name instead of the IP, as they might as well do their own resolution and follow the same logic.

**Comment by xla** [comment]
First of all thanks for all the patience and dedication trying to make your requirements understood, really appreciate it.

> Certainly. First of all, the general desire to support DNS names, especially at genesis validator level, is to allow for evolving infrastructure.
> 
> Secondly, having multiple A records associated with a DNS name allows for higher availability by operating in multiple availability zones, which I'd consider best practice for genesis validators.

These statement are very agreeable but contradict: 

> Correct, but fail over implies having a standby infrastructure running that is not utilized, with associated cost. I'd like to avoid that.

as higher availability is traded with less utilisation and there might be better models than active/passive, guess dynamic checks can be included to dynamically populate the list of records of a rotue53 entry.

> I imagine there is already support for expiring dead peers from addrbook, regardless of how they were added (PEX, static IP from config or DNS lookup from config). So no changes here, hopefully.

Indeed.

> By adding all resulting IPs from a lookup to addrbook, even if one available zone (and thus load balancer) dies, the other zones would already be in the address book and trivially connected to (if they weren't already).

I'd argue this is a concern of the traffic infrastructure by DNS entries being tightly coupled to health checks of the upstream intermediates in combination with aggressive TTLs.

> What you guys discussed at the dev meeting might work as well. But the code should take into consideration what happens if the first (of multiple) resolved IPs is unresponsive, and then try the next one, and so on. I guess it might as well also advertise the DNS name instead of the IP, as they might as well do their own resolution and follow the same logic.

If an IP becomes unresponsive the peer will be re-dialed at some point, where a new lookup is done.

**Comment by ebuchman** [comment]
Closing for https://github.com/tendermint/tendermint/issues/1521. Hope that will be good for folks

**Comment by ethanfrey** [comment]
>> What you guys discussed at the dev meeting might work as well. But the code should take into consideration what happens if the first (of multiple) resolved IPs is unresponsive, and then try the next one, and so on. I guess it might as well also advertise the DNS name instead of the IP, as they might as well do their own resolution and follow the same logic.

> If an IP becomes unresponsive the peer will be re-dialed at some point, where a new lookup is done.

So, we were looking at adding this "feature" (dns names in the address book), but then it seems it was decided against. That is explicitly mentioned in #1521.  

Use case: a set of non-validating (proxy) nodes that sit in front of the validator(s) and serve all rpc requests. They will be killed and restarted by k8 if they crash, get overloaded, etc... The restarted node will have the same node ip and same dns name, but a different IP. (The DNS name is only internal, the IP is what is seen externally, so this lets us restart to move the IP an avoid a DoS attack).

It works decently, and we can use the DNS names in the `--seeds` or `--peers` flags. However, once they are added to the address book, the only information left is the IP address (not the DNS name):
https://github.com/tendermint/tendermint/blob/master/p2p/netaddress.go#L19-L32

Let's imagine all our restart. They have the DNS names as a flag, but they have an address book first, with the resolved IP addresses, and the same node ids, so that takes presidence. And then they all try to dial into the old IP addresses that no longer exist.

Our "quick fix" was to delete the address book on restart to force re-resolution from the DNS names. We thought it would be great if both DNS name and IP are stored in the address book, and if the IP lookup fails (or simply on every reboot), it could re-lookup from DNS. There is not really a security issue as the node_ids are stored and prevents anyone from acting as an imposter. 

We would prioritize this issue in the next sprint or two, but if this is undesired behavior from the tendermint team and a PR with this would not be accepted, then there is no point to work on it (and be forced to maintain a fork of tendermint), but rather we would focus our energy on improving the work-around.

**Comment by ebuchman** [comment]
To clarify a couple things:

- DNS in seed nodes should be preserved and used every time we dial a seed
- DNS in persistent peers should be preserved and used every time we re-dial the peer
- Persistent peers should be connected to right away on startup.

If any of these things are not true, I believe that's a bug.

Given that, do we still really need DNS in the addrbook ? 

In any case, it might not be so bad to do as anton suggested:

> What we probably should do is store domain name along side IP and a) use it everytime we need an IP OR b) use it when current IP is unreachable.

But we should probably move this discussion to #1521 since this issue was actually closed
