### ISSUE TITLE
config: Why is `statesync.fetchers` a string?

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#8736]
In working on https://github.com/informalsystems/tendermint-rs/pull/1144, I see that the `statesync.fetchers` configuration option is [serialized as a string](https://github.com/tendermint/tendermint/blob/8d9d19a11353adf52a59a17e01165d7680b6d8f6/config/toml.go#L441). Does it need to be a string? It seems like it should be an integer value.

**Comment by creachadair** [comment]
For data that are potentially serialized to JSON, a lot of the code in Tendermint follows the original Amino convention of serializing 64-bit integer values as strings. That seems unlikely to be necessary here, but that's likely the reason it was done that way.

That convention, in turn, seems to have been cribbed from protocol buffers, which do so in JSON form so that JS implementations that use IEEE 754 floats for everything won't lose bits in conversion. In TM it isn't always clear which messages are going to get exported via the RPC interface, so basically all of our message types do this by default. 

The config probably doesn't need to.

**Comment by cmwaters** [comment]
I agree. This is something we should probably change

**Comment by musinit** [comment]
@cmwaters seems this issue is already solved, can we close the issue?

**Comment by cmwaters** [comment]
No this issue still remains

**Comment by musinit** [comment]
there is not **fetchers** param in toml.go file in main branch
