### ISSUE TITLE
Persistent memory growth when using the priority mempool

### ISSUE THREAD

**Issue by creachadair** [tendermint/tendermint#8775]
When running a testnet against Tendermint v0.35, the Vega team observed that enabling the new priority mempool feature triggered unexpected memory growth in their nodes as compared to using the legacy (sequential) mempool on a similar workload. In summary, a validator with a 10K mempool with a 2K cache shows moderate growth on a resident heap of between 500MiB and 1GiB using the sequential mempool, but quickly rose to 3GiB (which ran over cap and terminated the process) when using the priority mempool.

**Comment by creachadair** [comment]
I spent some time experimenting with small benchmarks to try to identify the underlying issue behind the memory growht observed by Vega team.

I was able to reproduce the basic issue: When the priority mempool is enabled, memory use on the node climbs over time. Based on memory profiling and some manual GC filtering, the basic problem is fairly clear: We're holding pointers to wrapped transactions indefinitely. But the mechanism by which this happens is subtle, and it's not clear how to fix it cleanly.

The original mempool is essentially just a bounded concurrent list (using the internal/libs/clist package). New items are added to one end and leave either in response to eviction (for exceeding the pool limits), by being completed into a block (and thus released), or by being rejected as invalid (during a re-CheckTx after block completion).

The priority mempool _also_ maintains a concurrent list, but it augments the list with additional slice-based containers, including a heap for the priority queue (using the stdlib container/heap interface), and indexes by height and time order. All of these structures share pointers to the same underlying transaction data, through wrapper objects that maintain per-transaction metadata including priority, height, gas, and so on. The wrapper also pins a pointer to the corresponding clist element which tracks arrival order—this is used to ensure transactions are still gossiped in arrival order, even though block membership is chosen by priority.

Because the slice-based caches work by linear-time reslicing, I at first suspected the problem was that we were pinning pointers to these wrappers in the unused capacity. And we _are_ doing that in one case, but that only accounts for roughly 10% of the memory overhead we observe when loading transactions into the (benchmarked) priority mempool. That's easy to fix and worthwhile, but doesn't fix the underlying problem. (I am not sure how much it will help in the real workload, but shouldn't hurt)/

Even when items are explicitly removed from the mempool, however, we do not see wrappers released to the heap. I tested this by logging wrapper allocations and setting finalizers to log the corresponding releases. There is logical "race" (not an explicit data race, as the operations are mutexed, but an order dependency that changes the results) between evicting/reaping transactions out of the gossip list and processing re-CheckTx batches. Because of this, transactions cannot safely be dropped from the clist when they are "removed".

We correctly release them from the priority queue and the indexes, but cannot drop them from the clist without potentially disrupting gossip and/or recheck. So instead we set a flag on the wrapper and use that to skip over "removed" wrappers during gossip and recheck.

This means, however, that there's no clear point at which we can always safely "unhook" a removed item: The first time a wrapper is removed, its own clist pointer is detached from its predecessor (correctly), but the list is doubly-linked and nothing ever unhooks it from the tail of the list. I think this means once we have any item removed, it will maintain a chain of forward pointers through the entire future of the clist indefinitely.[see note 1] 

We can't unhook the forward pointer until the gossip cursor has passed the item, or we lose the rest of the list. But we also can't unhook it during gossip because a recheck may be pending. Since the recheck cursors and the gossip cursor share the same list elements, recheck might be able to see that the gossip wavefront has passed, but it's subtle. I tried a couple of (what I thought were) obvious tweaks to fix this, but they didn't work: One induced panics (occasionally) and the other didn't solve the problem. So this will need some more experimentation.

We could potentially "fix" the dependency by replacing the clist with a simpler structure and splitting gossip processing from recheck. The main blocker is that the clist isn't just a linked list, it also includes a condition-like notification mechanism to coordinate concurrent producer/consumer accesses (e.g., gossip, recheck, eviction, and ABCI callbacks from the application). Removing that dependency would be a much larger change, and we've already seen this code did not get enough testing as built so I'd be cautious about that given the desire to ship this feature soon.

I think ensuring the application always runs recheck could maybe help (at least it reduces heap sizes somewhat in my benchmark). Likewise, we can PR the tweak to unpin wrappers from the cache slices. But as it's currently implemented, I don't see an easy fix to remove the memory growth at steady state. The main workaround I could see is to occasionally reset the whole priority mempool, e.g., when we detect that there's no pending work. (Or restart the node for the same effect).

All this will affect the backport as well, unfortunately.

[note 1]: We can roughly confirm this by explicitly reconstructing an empty clist during flush: Doing this allows the heap size to drop back to the baseline for GC rather than doubling.

**Comment by alexanderbez** [comment]
@creachadair can you please help clarify the "logical" race condition pls? Notice that `TxMempool#removeTx` removes a `WrappedTx` from all indexes _including_ the clist gossip index. So what exactly is still hanging onto the pointer? 

Are you saying there is some concurrency between `updateReCheckTxs` and when `TxMempool#removeTx` could eventually be called?

**Comment by creachadair** [comment]
Thanks to @williambanfield, the code from #8944 running in a testnet appears to have a stable memory footprint.

![image](https://user-images.githubusercontent.com/19258/177877621-a259e57a-a80a-4822-844d-1f20a79f3105.png)

On that basis I'm going to mark this issue closed, and any further issues that come up we can write new issues for.

**Comment by williambanfield** [comment]
# Experimental Results

To ensure this mempool did not present the same issue of unbounded memory growth, it was run in a large testnet. The tesnet configuration and experimental results are summarized below.

## Testnet Setup
Software Version: 9b0209482736bf012df08ea9633fd542d7e52ceb
124 Total Nodes:
100 Validator Nodes
4 Seed Nodes
20 Full Nodes
Machine: Debian 11 with 4 virtual CPUs and 8 GB of ram.  

## Experimental Runs

4 Experiments were run comparing performance of the v0 and v1 mempool with both without load and with load. 

For load generation the [runner]() load generation command was run on 10 out of the 100 validator nodes, generating a steady transaction load to the validator running on the same machine.

### Title: v0 Mempool with no load
Duration: 10m
Mempool version: v0
Load: None

Memory Usage
![image17](https://user-images.githubusercontent.com/4561443/178028272-f3fcb899-3909-436d-9445-6d8900ba5779.png)

CPU Utilization
![image8](https://user-images.githubusercontent.com/4561443/178029122-0aaf4b02-585c-4f90-aa86-be341561c44b.png)

Mempool Size
![image6](https://user-images.githubusercontent.com/4561443/178029146-d0751598-99c8-4689-b9bc-08488acae38b.png)

Tx Rate
![image3](https://user-images.githubusercontent.com/4561443/178029164-864f28c0-286e-4181-a95d-80151e44f748.png)

Notes:
Once the network begins producing blocks, the process reaches a steady amount of CPU and memory use. 

### Title: v1 Mempool with no load
Duration: 10m
Mempool version: v1
Load: None

Memory Usage
![image16](https://user-images.githubusercontent.com/4561443/178028317-a91eb603-6087-4035-a5a2-4951a2765132.png)

CPU Utilization
![image5](https://user-images.githubusercontent.com/4561443/178029439-d5820b41-6bb1-48c7-8309-ff50dd9a5c76.png)

Mempool Size
![image1](https://user-images.githubusercontent.com/4561443/178029617-b984c4b9-3330-4d08-b033-424889c3dd32.png)


Tx Rate
![image9](https://user-images.githubusercontent.com/4561443/178029551-7ae49f20-c696-43d0-a5c9-889c3d25e8b4.png)

Notes:
- Noise at the beginning of the graph from previous experimental run.
- Similarly to v0, once the network begins producing blocks, the process reaches a stable amount of CPU and memory usage. 

### Title: v0 Mempool with transaction load
Duration: 30m
Mempool version: v0
Load: 10 nodes producing random KV store transactions

Memory Usage
![image7](https://user-images.githubusercontent.com/4561443/178029021-32cc3a38-7d40-437c-9751-975136bbe6ab.png)

CPU Utilization
![image11](https://user-images.githubusercontent.com/4561443/178029731-2333e4fa-2757-47b2-b703-84ccf0bf4ba7.png)

Mempool Size
![image12](https://user-images.githubusercontent.com/4561443/178029803-9f9ebeb6-f7b3-43dc-927a-f16ca4712f3f.png)

Tx Rate
![image15](https://user-images.githubusercontent.com/4561443/178029776-582a6531-05ab-411b-8ca9-7f41bfcd4c39.png)

Notes:
- CPU use stays constant
- Memory grows as mempool size grows.
- Mempool size reflects # Tx in the mempool. Size never reaches max, so it makes sense that it continues to grow.

### Title: v1 Mempool with transaction load
Duration: 30m
Mempool version: v1
Load: 10 nodes producing random KV store transactions

Memory Usage
![image14](https://user-images.githubusercontent.com/4561443/178028350-30cd4302-87ff-450b-aa57-b7ba623db334.png)

CPU Utilization
![image10](https://user-images.githubusercontent.com/4561443/178030046-a75829c6-d6ba-473f-b6b7-dfc6f5d3d3d0.png)

Mempool Size
![image13](https://user-images.githubusercontent.com/4561443/178030000-b14a3cf9-af45-4507-b399-e2f0ee023aa2.png)

Tx Rate
![image9](https://user-images.githubusercontent.com/4561443/178029883-029b8213-b741-45ab-af5b-80650506cf89.png)

Block Part Gossip
![image4](https://user-images.githubusercontent.com/4561443/178030098-9030cc43-ef4a-4847-b3d6-8906cad239b6.png)

Notes:
- Memory grows along with mempool size. Mempool size grows since rate of Tx production by the runners is greater than the rate that they are placed in blocks.
- Mempool never reaches max size so growth is expected.
- Large spike in memory corresponds to large block produced by the network. Observable in both block parts graph as well as in the Tx rate graph.

### Summary
v1 Mempool reaches steady memory usage and does not appear to exhibit unbounded growth. Growth correlates to addition of Tx to the mempool. Tx from v1 mempool are admitted to the chain consistently.
