### ISSUE TITLE
v0.34 Release benchmarks

### ISSUE THREAD

**Issue by williambanfield** [tendermint/tendermint#9006]
We are updating the Tendermint release process. Part of the update involves capturing metrics for the functionality of the release candidate. We do not currently have a baseline for these metrics and should capture one from the current v0.34 release so that we can compare.

The benchmark should run the 200 Node testnet described in the [Releases.md]() document and capture metrics for the following:

```
Tendermint rounds per height
Peers connected
Memory resident set size
CPU utilization
Blocks produced per minute
Seconds for each step of consensus (Propose, Prevote, Precommit, Commit)
Latency to receive block proposals
```

Some of these metrics do not exist in the v0.34 release at the moment and will need to be backported. Any issues that arise during the running of the testnet should be documented and attached to this github issue. Baselines should also be captured and attached to this github issue.

**Comment by sergio-mena** [comment]
Overall, the proposed metrics look good to me. Some minor comments:
* Tendermint rounds per height. We might want to measure the "max", and "median" over a predefined testing period
* Peers connected. It's obvious that measuring this at all peers (and then calculating a median) would be best. However, based on your experience with v0.35.x testing, would it make sense to do this or to limit the measuring to one or a few nodes?
* CPU utilization. Average over the testing period?
* Seconds for each step of consensus. Average? Median?

One more general thought. We might want to explicitly document a tolerance to the non-regression policy. E.g., something like "metrics cannot go below 90% below those of the reference release". Of course, we need to negotiate the "90%" with our users... maybe 95%? I don't know, but folks need to acknowledge that a release that didn't have performance improvement as one of the priorities might have new features that _marginally_ impact performance, and this should be acceptable.

**Comment by JayT106** [comment]
Benchmark these metrics might need to consider the mempool conditions, like the mempool loading and the mempool size. 

Other metrics like 
- tx throughput
- network traffics
also good to evaluate the capabilities of the tendermint project

**Comment by williambanfield** [comment]
@JayT106 Thanks for the comment.

I see the topic of TX throughput come up from time-to-time and I'm not totally sure I understand it concretely. Is this throughput from when a Tx enters the mempool to when it is placed into a block? Or throughput for the mempool to gossip a transaction to other mempools?

In terms of time from when a tx enters the mempool to when it enters a proposed block, this will be very quick _if the transaction lands in the mempool of a proposer_ since the mempool is not really doing much computational work. I wonder if the throughput consideration is really more related to time between when a transaction enters _some_ mempool on the network and when the transaction lands in a block, which has a lot more to do with network dynamics and transaction gossiping etc. 


> network traffics

Would you mind being specific about what's asked for here? Do you mean bandwidth used by the Tendermint process in large networks? 

Thanks!

**Comment by JayT106** [comment]
> @JayT106 Thanks for the comment.
> 
> I see the topic of TX throughput come up from time-to-time and I'm not totally sure I understand it concretely. Is this throughput from when a Tx enters the mempool to when it is placed into a block? Or throughput for the mempool to gossip a transaction to other mempools?

We can measure it like avg transaction has been delivered into blocks per second in a whole network perspective. That will be more clear for the Cosmos App projects to know the limit under this kind of network scale.

> 
> In terms of time from when a tx enters the mempool to when it enters a proposed block, this will be very quick _if the transaction lands in the mempool of a proposer_ since the mempool is not really doing much computational work. I wonder if the throughput consideration is really more related to time between when a transaction enters _some_ mempool on the network and when the transaction lands in a block, which has a lot more to do with network dynamics and transaction gossiping etc.
> 
> > network traffics
> 
> Would you mind being specific about what's asked for here? Do you mean bandwidth used by the Tendermint process in large networks?
> 
> Thanks!

Yes, the network bandwidth. Maybe the p2p send/recv messages per sec or per block?

**Comment by cmwaters** [comment]
So the more concrete definitions I've formulated around consensus engine performance are:
1. Commit latency: the average time it takes a transaction to enter the mempool via RPC till when it is committed in a block. This does seem like a metric we could capture. To better isolate that metric when testing for regression we would need to fix node count, transaction size and transactional load
2. Consensed Throughput: or the amount of bytes agreed upon by n nodes per second (something like Tendermint consensus on 10kb per 100 nodes per second). I've often seen papers quote transactional threshold but this seems arbitrary as there's no information about the size of the transactions themselves. 

These are more user facing metrics that I've heard been talked about in various mediums.

As @williambanfield mentioned in an off-band thread, these high-level metrics can be more "marketing" fodder than provide adequate insight to the actual performance of a system which would require breaking down the metrics into sub-components but I think as simple metrics that provide a good basepoint

**Comment by sergio-mena** [comment]
@cmwaters I find those metrics a good way to assess performance on large testnets (as one of the steps in #8786), which can be combined with those (more internal, more detailed) enumerated at the beginning of this issue

**Comment by cason** [comment]
I agree with the metrics proposed by Callum, these are the typical metrics to evaluate SMRs or consensus protocol in general. A bit of comments regarding them:

1. Commit latency computation requires a client. The appropriate way to compute it, is to compare submission to delivery time for a transaction. The submission time is when the client invokes a broadcast_* RPC method. The delivery time is the time when the client receives a committed block including the submitted transaction. Notice that we are adding two delays to Callum's proposal: one before the transactions enters the mempool, another for the client to learn the committed block.
2. Condensed throughput can be called just throughput. It can be measured in transactions per second of bytes/bits per second. If the size of the submitted transactions is (essentially) constant, they become equivalent. If the size of transactions varies a lot, having both is the ideal.

Observe also that, for both, we need to define how the metrics are measured. Depending on the duration of the experiments, and the complexity of the client, we can just record every latency and information regarding every block (number and size of transactions, delivery time). Based on this information, we can provide essentially all overall performance information needed. For example, the distribution of latencies (maybe even classified by originating client, transaction size, etc.) and both the instantaneous and overall (average) throughput.

Alternatively, we can focus on collecting the minimum amount of data needed to produce specific performance metrics. For instance, we can only maintain the average (and standard deviation, always relevant!) latency, and the "average" throughput (quotes here because throughput is, by definition, a flow metrics, therefore an average).

**Comment by cason** [comment]
A general overall comment here. Since blocks are not committed than often (in my experiments, at most one block every 2 or 2.5s), we can maintain the raw information for all blocks, such all: duration (from the next block), number of transactions include (possibly plus their aggregated size), commit round, duration of each step of consensus for the commit round, etc.

Moreover, the commit of a block appears to be a good determinant of when we measure the metrics reported there, even the ones that are not directly associated to a consensus instance, such as CPU and memory usage.

**Comment by cason** [comment]
Echoing @JayT106, network traffic is a metric that really missed when experimentally evaluated Tendermint.

I would say more, it would be nice to have this information segregated by reactor. From my experience, the mempool is the component that uses the network more extensively, but I could never affirm this with confidence, because this information is not exported by Tendermint.

**Comment by cason** [comment]
Regarding transaction latency, specifically.

Yes, it definitely depends on "where" (which node) the transaction entered the Tendermint network. However, notice that the point of having a mempool is that, from the client point of view, does not matter which node you contact, you know that your transaction will eventually reach a node that is acting as a proposer, therefore, will end up in a committed block.

In terms of performance, I think the behavior of Tendermint that was the hardest to explain is the variation of instant throughput (Figure 5 on this [paper](https://www.inf.usi.ch/faculty/pedone/Paper/2021/srds2021a.pdf)). It is reflected, and a result, of a bimodal latency distribution (Figure 4), which can only be explained by the fact that some transactions "make it" to the next proposed/committed block, while others have to wait for the following block to be proposed/committed.

The overall conclusion of the analysis of this behavior, was that the mempool does not propagate transactions as fast as would be needed to ensure that, when removed the restrictions of block and mempool sizes, they are included in the next proposed block, independently on where (geographical and latency-wise) the proposed is located in the overlay network.

**Comment by williambanfield** [comment]
>  the mempool does not propagate transactions as fast as would be needed to ensure that, when removed the restrictions of block and mempool sizes, they are included in the next proposed block

It seems like this has a high likelihood of being variable upon the speed of the application, no? If the app can checkTx the application quickly, then it will be gossiped more quickly and if it is slower to perform the check, then it will be faster to be gossiped.

All of this to say, it sounds like we are coalescing on two high level metrics to capture tendermint performance, namely those proposed by Callum above. These metrics should give a good overall signal of the speed and performance of Tendermint. From the perspective of v0.34, I prefer these metrics as they should allow us to benchmark Tendermint at any version without too much messy backporting of metrics around. These should be able to be generated without tons of internal changes to Tendermint.

**Comment by cason** [comment]
By the way, I am mentioning this on this issue to highlight the fact that the propagation of txs has a very important impact on the measured end-to-end performance. From our (old) experiments, it has more impact than the consensus latency. With that said, in order to produce good measurements we should tame this effect in the experimental setup, namely, we should give to all transactions the "same opportunity" to be included in the same block, which is not what we observed in the previously mentioned experiments.
