### ISSUE TITLE
v0.37 release plan

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9091]
This issue currently targets the v0.37 release.

In order to ship #9053, we need to do the following:

- [x] #9096 
- [ ] Update documentation, including the roadmap
- [x] Define a release QA plan
   - [x] Define an integration testing plan with the Cosmos SDK (cc @marbar3778)
- [x] #9053 
- [ ] Additionally, we should aim to include as many of the addressed Q3 priorities in this release as possible:
   - [x] #9077 
   - [ ] #9055 
   - [x] #9054
   - [ ] #9076 
   - [x] #9078 
- [x] Identify and forward-port any necessary bug/security fixes from v0.35/v0.36 to v0.37
   - [x] #9176 
   - [x] #5447
   - [x] #6755
   - [x] #5728
   - [x] #9287 
   - [x] #6403
- [x] Cut `v0.37.x` branch
- [x] Cut release candidate
- [x] #9429
- [ ] Execute on the release QA plan and capture the results
   - [x] #9123 
   - [x] #9333
   - [x] Validate that there's no meaningful, substantial regression from v0.34 to v0.37
   - [ ] Execute on the QA plan for integration with the Cosmos SDK
- [ ] Cut final v0.37.0 release
   - [ ] docs: Ensure that the v0.37 version is available in the [Vuepress config](https://github.com/tendermint/tendermint/blob/7feb4847650c8a24bfc09af940229bb0e84b56d4/docs/.vuepress/config.js#L16)
- [ ] Prepare v0.37.1 release by merging all of [these PRs](https://github.com/tendermint/tendermint/pulls?q=is%3Apr+is%3Aopen+base%3Av0.37.x)

Things that still need to be done before we "feature-freeze" v0.37 and cut the `v0.37.x` branch:
- [x] #9300
- [x] #9269 
- [x] #9286 
- [x] Temporarily revert #9175
- [x] #9300
  - [x] #9248 
  - [x] #9244 
  - [x] #9243 
- [x] #9304
- [x] #6403

**Comment by marbar3778** [comment]
somethings that are missing

- https://github.com/tendermint/tendermint/pull/6120
- https://github.com/tendermint/tendermint/pull/7033
- https://github.com/tendermint/tendermint/pull/6785
- https://github.com/tendermint/tendermint/pull/6590
- https://github.com/tendermint/tendermint/pull/6755
- https://github.com/tendermint/tendermint/pull/5447
- https://github.com/tendermint/tendermint/pull/5632
- https://github.com/tendermint/tendermint/pull/6526
- https://github.com/tendermint/tendermint/pull/5728


Not sure who is leading this endeavour but please look at the change log for 0.35 to identify things that are easy lifts to move to main/0.37 as many people are expecting them.

**Comment by tychoish** [comment]
I think the crypto changes are potentially pretty isolated (small), offer some amount of ease, and wouldn't be disruptive to the codebase. (#6120, #5632, #6526) 

I think the blockchain/blocksync changes are good, and not very risky, (e.g. removing all of the versions of blocksync that don't work, and have as far as I know never worked, which is to say v1 and v2, and renaming it blocksync rather than blockchain in the code.) At the same time, I'm not sure that people run into this problem in practice (and it's easily recoverable when they do,) so they seem like good things to cut scope on. (#6755, #5728)

The reset are a bit more delicate and have less clear answers, but I've attempted to annotate:

- https://github.com/tendermint/tendermint/pull/7033 (medium/large, probably not worth doing, unless the corresponding application feature is ready. Unlikely to cause regressions in other areas of the code, but does require reaching deep into tendermint.) 
- https://github.com/tendermint/tendermint/pull/6785 (medium/large, low risk relatively as the change is isolated, but RPC plumbing is enough different in 0.34, that it might be bigger this time.)
- https://github.com/tendermint/tendermint/pull/6590 (small, worth doing, and well aligned with our observability epic) 
- https://github.com/tendermint/tendermint/pull/5447 (small; worth doing but not a clean backport for protobuf compatibility reasons, it seems)

**Comment by marbar3778** [comment]
Theses are some that I saw quickly but I bet there are other low lift things in the changelog that could be upstreamed to main

**Comment by cmwaters** [comment]
Other than the ones already mentioned, I think the following should be considered streaming in the near term:
- https://github.com/tendermint/tendermint/issues/6849
- https://github.com/tendermint/tendermint/pull/7270
- https://github.com/tendermint/tendermint/pull/7338
- https://github.com/tendermint/tendermint/pull/6634

The rollback command (https://github.com/tendermint/tendermint/pull/7033) has already been backported to v0.34

**Comment by williambanfield** [comment]
@marbar3778 I'm confused by https://github.com/tendermint/tendermint/pull/5728, I thought v1 ended up being the only reactor, v2, and that that v2 should be targeted for removal.

**Comment by marbar3778** [comment]
sorry meant the removal of v1 and v2. grabbed that pr as an example

**Comment by hdevalence** [comment]
Tendermint 0.35 deduplicated some proto definitions between `abci` and `types`, notably the `ConsensusParams` and the `BlockParams`.  Not including this deduplication in 0.37 will make modeling domain types more difficult.

**Comment by hdevalence** [comment]
At some point between Tendermint 0.34 and 0.35, the `SetOption` ABCI request was dropped.

**Comment by cmwaters** [comment]
> At some point between Tendermint 0.34 and 0.35, the SetOption ABCI request was dropped. I believe it was unused; it's not documented anywhere.

v0.37 also drops `SetOption` - yes it's unused.

**Comment by cmwaters** [comment]
As to the deduplication of some proto definitions we can and should do that. I have opened a PR here: https://github.com/tendermint/tendermint/pull/9287

**Comment by ashishkhuraishy** [comment]
will the documentation updates also cover fixes to update broken links from the tendermint website? 
eg: [this](https://docs.tendermint.com/v0.34/v0.34/tutorials/go.html) is the link which is currently there on Get Started button which redirects to a `404`
