### ISSUE TITLE
version protobuf files

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#9197]
## Summary

Protobuf in most cases is versioned. In the sdk we have to house our own proto files for tendermint and may need to start versioning tendermint protobuf files ourself. It would be nice if tendermint started versioning their proto files instead

## Problem Definition

Protobuf files are not versioned 

## Proposal

Version protofiles. 

Ideally everything is v1 other than abci which could be v1beta1 until abci++ is fully delivered

**Comment by cmwaters** [comment]
Is versioning just a matter of putting everything under the `/v1/` path in the repo?

**Comment by marbar3778** [comment]
yea and modifying the path in the files themselves

**Comment by mzabaluev** [comment]
Versioning in proto files will simplify the logistics of multi-version Tendermint support in language bindings.

This project need to follow (or come up with?) the best practices of managing breaking changes through proto package paths. Without much experience on this, my suggestion, following a discussion with @thanethomson, is that most of the packages would stay at `.v1`, but ones that had changed message definitions would get a `.v2`, with old definitions still available via `.v1`, and this process would continue as new Tendermint versions are released.

One thorny question is how to manage changes that are not technically breaking in protobuf, but cause breakage in code generated for strongly typed languages. Adding a new field or reserving formerly used field tags (assuming the proto3 semantics of every field being optional) will not break the wire protocol, but the generated structure definitions do change and compiled languages don't like that.

In Rust (specifically, in code generated by `prost-build`), we can mitigate field additions by attributing the generated structs with `#[non_exhaustive]` so that the applications are forced to never exhaustively destructure all fields of the struct, and will keep compiling when a new field is added. But this brings maintainability issues when the new fields **must** be taken care of in the logic.

An application using an extended version of the struct may still consume messages produced for an older definition because the new field values will be defaulted. But when producing messages, it may be important to have a version-accurate structure definition, so that newly added fields could not be inadvertently used in a message sent towards the consumer on an older version.

All this considered, I suggest bumping the version suffix also whenever fields get added or removed-and-reserved in a message.

**Comment by thanethomson** [comment]
> This project need to follow (or come up with?) the best practices of managing breaking changes through proto package paths.

I'd suggest the approach proposed by Buf: https://docs.buf.build/best-practices/module-development#package-versions - this pretty much aligns with what you've suggested @mzabaluev.

There seem to be two major chunks of work toward using our Protos in a more standardized way in Tendermint:
1. Generating the Go code into a separate directory/module that the Cosmos SDK can import, as opposed to having to [generate their own Go code](https://github.com/cosmos/cosmos-sdk/tree/main/api/tendermint).
2. Versioning the `.proto` files and their generated counterparts. Here, each major proto version would correspond to a major Tendermint release (e.g. `v1` -> v0.34.x, `v2` -> v0.37.x, `v3` -> v0.38.x, etc.). We would only bump the version of the protos that actually changed from one major release to the next (e.g. if the [P2P types](https://github.com/tendermint/tendermint/blob/21b2801c6029c6d510d65cc1cc83fbf055ff618f/proto/tendermint/p2p/types.proto) don't change between v0.34.x and v0.37.x, then we just continue using `v1` of those protos).

### Restructuring Go code generation

This may need to be considered as a separate issue, and perhaps a precursor to versioning our protos.

Right now, the way that Tendermint uses its Protobufs is non-standard according to the way that Buf suggests one structure modules. We generate our Go code alongside all the `.proto` files, with the exception of the ABCI types, which we manually move out to the `abci/types` package as per https://github.com/tendermint/tendermint/blob/21b2801c6029c6d510d65cc1cc83fbf055ff618f/Makefile#L167-L172

Buf recommends generating these in a separate folder. Their examples use a `/gen/` folder in the root of the repository. The Cosmos SDK uses an `/api/` submodule to house their generated code (see https://github.com/cosmos/cosmos-sdk/tree/main/api), which aligns with this [standard project layout recommendation](https://github.com/golang-standards/project-layout) for Go projects.

It may be possible to do this in a non-breaking/additive way in Tendermint v0.34 onwards. This would entail:
1. Generating all Go code into an `/api/` directory in the root of the repo.
2. Creating Go files in the `/proto/` directory that exclusively house [type aliases](https://go.dev/blog/go1.9) so that we don't break the Go API. Each of these aliases would reference corresponding types in the `/api/` directory.

In a later version of Tendermint (e.g. v0.38) we could totally remove the type aliases from the `/proto/` directory so that that directory only houses `.proto` files, instead referencing the generated code in `/api/` directly.
