### ISSUE TITLE
Validator set updates should be called 'change' not 'diff'

### ISSUE THREAD

**Issue by rigelrozanski** [tendermint/tendermint#924]
use of the word 'diff' is misleading because validator set updates are not subtractions but simply the subset of validators which have changed

https://github.com/tendermint/tendermint/blob/7682ad9a60162dd17fd6f61aeed7049a8635ac78/state/execution.go#L110

**Comment by jaekwon** [comment]
Wait, it *should* be diff because it *should* be subtractions (new - old).

**Comment by jaekwon** [comment]
Ok, so previously the intent was to capture (new - old) as diff.  So lets change this to update?

I guess update makes more sense because it's probably simpler/safer/better for everyone to return the final voting power for a validator rather than diffs, because w/ aggregated diffs you can get to negative numbers etc.  

So in the SDK, each tx can tell the SDK that some validator's voting power changed to XYZ.  If it gets changed to XYZ+1 in a later transaction in the same block, it will have to return XYZ+1.  No problem.

**Comment by rigelrozanski** [comment]
Awesome yes, your second statement is in line with my thinking
