### ISSUE TITLE
p2p: Scope research regarding the impact of network topology on stability/performance

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9302]
This follows from the conversation in #9123.

The questions we would like to be able to answer in this issue are:
1. What kinds of network topologies form in different sizes of Tendermint networks and with different P2P configurations?
2. What is the impact of these different topologies on network stability and performance?

These are mid- to longer-term research questions that still need clear scoping, as this is something that would need to be understood as the system evolves instead of just for a single Tendermint release.

Therefore the "definition of done" for this issue is: when we have a clear scope of work as to how to go about answering these questions, all captured in follow-up issues on GitHub.

cc @cason, @milosevic

**Comment by jmalicevic** [comment]
One reason that could be in favour of obtaining this information: I believe it was observed that in v0.36 the network tended to be fully connected and nodes would reach the maximum number of connections. This would mean that, when a new node joins the network, everyone refuses to connect to it because they are already fully connected. While I think we resolved this particular issue (at least partially) by leaving always a few free slots to connect to new nodes (as is done in 0.34), I think capturing this behaviour by having information on the network structure would have been useful when deciding on removing this in 0.36.

**Comment by tychoish** [comment]
> One reason that could be in favour of obtaining this information: I believe it was observed that in v0.36 the network tended to be fully connected and nodes would reach the maximum number of connections. This would mean that, when a new node joins the network, everyone refuses to connect to it because they are already fully connected. While I think we resolved this particular issue (at least partially) by leaving always a few free slots to connect to new nodes (as is done in 0.34), I think capturing this behaviour by having information on the network structure would have been useful when deciding on removing this in 0.36.

Just to be clear, this was an implementation with the 0.35/0.36 peer tracking system which was uncovered during testnets. This issue was fixed in that branch by providing some kind of analogue to the behavior in the 0.34 peer stack which tracks incoming and outgoing connections seperatly and sets caps on each independently. I would classify this as a design flaw (that we fixed) in the 0.35 system. 

------

I think more actionably, when running the 0.34/0.35-legacy tests, once the bugs were patched, we noticed a relatively high amount of connection churn noise in the charts around peer connections that simply wasn't present with the new 0.35/0.36 peer stack. Is this churn desirable? (probably not though there could be non-intuitive side effects with good outcomes) Is the churn a testing artifact? (unlikely) I think having baselines so we understand the current behavior and an understanding of what our goals for the gossip/peer layer are, would be helpful in figuring out if there are any changes that we should be targeting. 

There's also the legacy system's resource allocation patterns. Because sending messages always creates a new goroutine, and there's no real discipline over prioritization or load shedding internally in the 0.34 networking stack, it's easy to imagine failure modes where traffic backs up internally and messages are sent out of order and on significant delays. The current implementation doesn't give us the knobs or the tools to control the traffic at this level. While the initial implementation in 0.35 was particularly bad at load shedding, recent changes made this spring/summer significantly improve its performance in this regard. Having said that, it would be good to understand if and how this appears in production systems.

----- 

It might be useful to frame this conversation and research with some high level goals: "support N numbers of peers" or "support validator sets of N size" might allow us to focus the engineering and research prospects.

**Comment by cason** [comment]
I am interested to understand better the scenarios or the possible reasons of the mentioned "churn noise", as it should somehow be addressed.

**Comment by cason** [comment]
> There's also the legacy system's resource allocation patterns.

This is something I haven't covered yet in the p2p specs. Again, it would be valuable to understand the scenarios when this issue is observed and has potential negative effects on the operation of Tendermint.
