### ISSUE TITLE
request: non-surprising default directory

### ISSUE THREAD

**Issue by spacejam** [tendermint/tendermint#935]
feature request

All defaults are likely to be somewhat contentious for this, but in the infrastructure/database worlds something like [`/var/lib/tendermint`](http://www.pathname.com/fhs/2.2/fhs-5.8.html) or the current working directory will surprise fewer people than `$HOME/.tendermint`. It won't be long before a `$HOME`dweller complains that `~/.tendermint` does not follow the [XDG base directory spec](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) :P

**Comment by ebuchman** [comment]
Lol nice. @Greg-Szabo has been saying this for a while ...

It seems like all the new Go tools are taking dumps in home directories these days. Why is that ? Eg. docker.

**Comment by spacejam** [comment]
Dotfiles in `$HOME` are unsurprising for user-specific configuration and data, but for things that support multi-user storage it's usually expected that they will be in `/var/lib`. On a few linux systems I've checked it on, Docker puts all of its container data in `/var/lib` for this reason. Never assume the hoops that things go through to easily install on OSX are the preferred defaults for running on a server.

A few things, like etcd and redis, will just create data in the current working directory if run from a shell. This is nice for playing with a local cluster quickly by just opening a few terminals in different directories and prodding them from a single system. I think most SRE/ops folks really appreciate a simple local cluster experience like this, as it lets them gain experience with a system rapidly without having to throw up a real cluster or a bunch of containers first. Anything installed through a system's package manager / run through the system init should default to `/var/lib` (unless a specific distribution has a different default for this) IMO.

My preference is to default to the current working directory for anything started from the shell, allow everything to be specified through argv and env vars and a conf file, and when starting print out all configurables (ideally with an indication of how the flag was set between default / conf file / env var / argv) to make debugging easier.

**Comment by zramsay** [comment]
related to #928

**Comment by ebuchman** [comment]
> Anything installed through a system's package manager / run through the system init should default to /var/lib

I think Greg has set it up like this. But for a `go install` or just downloading the binary directly from somewhere, should it still go in `/var/lib` ? 

> My preference is to default to the current working directory for anything started from the shell

ie. use `./.tendermint` instead of `~/.tendermint` ?

> allow everything to be specified through argv and env vars and a conf file

We do. We have `$TMHOME` and `--home`. But the conf file is expected to be in the home dir!

> when starting print out all configurables

Good idea

**Comment by adrianbrink** [comment]
In the blockchain space it seems to become the standard to put all files in `$HOME`. I think the basic reason for that is that blockchain software is supposed to be run by less technical folks and `$HOME` is just easier for them.

If a sysadmin really wants to change it to `/var/lib` they can easily do it with `--home`. 

I think to make it easier for the average developer we should just stick with `$HOME`.

@ebuchman What's the verdict? Can we close this one or do we want to change it in Tendermint?

**Comment by spacejam** [comment]
`$HOME` is more confusing for the average developer than `cwd`

**Comment by greg-szabo** [comment]
There is a supported package repository for Debian and CentOS managed packages. It's described here: https://tendermint.readthedocs.io/en/master/deploy-testnets.html#package-deployment-on-linux-for-developers

The Debian/CentOS packages have the following defaults:
- They use systemd services. `service gaia start` will start an installed gaia server.
- Currently they are out-of-process services which means that `tendermint` runs as a separate dependent service. `service gaia start` will start the dependent service `gaia-server` which is really tendermint where gaia and tendermint are configured together. This is in the process of overhaul into an "in-process" service where only one service is running (`gaia` in this case) and `tendermint` is built into it. Most probably the next gaia version will be packaged like that.
- The service runs under the username `gaia`.
- **Configuration for both gaia and tendermint is stored at `/etc/gaia`.** This includes the `genesis.json` and `config.toml` files, which I think are supposed to be there and it includes the `data` folder and the new `addrbook.json` which maybe should belong to `/var/lib/gaia`. When the packages were created, there was no way in separating the data from the configuration. (This might be fixed in a future release but it's not a high priority currently. `/etc/gaia` can be redirected to a different volume the same way as `/var/lib/gaia` without much hassle. It doesn't look nice but it works.)
- In the current "out-of-process" solution, the tendermint log can be reached through `journalctl -u gaia-server.service -f`. In the new "in-process" solution it will be the more straightforward `journalctl -u gaia.service -f`. (Where `-f` is optional for rolling log.)

Raising the point of `/var/lib` is fair. It's really not a developer responsibility, especially because the developer build process should not run as root (which would allow access to `/var/lib`) and it should not try to set up additional users in the OS. (Although the $HOME/.tendermint is really a horrible place because of the XDG specification and maybe the current directory or even $HOME/tendermint might be a better solution). In my view, it's more of a package manager responsibility. This becomes awkward when developers tell everyone to build their own binary for security's sake. The current package repository is a convenience for Linux OS setup but the developers are right: even after installing the packages you should overwrite the binaries (under `/usr/bin`) with your custom built one (preferably SHA256 checked). This is especially true because the security of the package repository is not completely finished. (Check the tendermint.repo file and you'll see that the packages are signed and checked, but the repository is signed but not checked. This will be fixed before launch, though.)

As for the issue at hand, I think the devs made their decision ($HOME/.tendermint) and we have to live with that. The options are there to configure it to your liking and you can always build your own managed RPM/DEB/APK/whatever package. Or you can use our package repository (which should get better day by day). By the way, the package build process is also open-source. Currently it resides in our `tendermint/tools` repository under the `feature/jenkins` branch (eventually it will be merged to master), under the `build` folder. Sorry for hiding it so well, it went through a lot change and it wasn't ready for the `master` branch for a long time. The pleasent news is that this branch is directly picked up by our CI orchestration tool and it is run directly to create new packages. What you see is what you get.

I'll close this ticket with the added note that you are free to discuss further the various places where configuration/data should be on Riot or on our Slack if you have the invite there. If you have a specific change in mind, you can open a ticket on tendermint/tools or even suggest a PR there. (On top of `feature/jenkins` please). The DevOps team is happy to discuss this further but as for the developers, let's leave it to them to figure out if they want/need to change the default folder. Production systems will always have different configuration compared to the developer defaults.
