### ISSUE TITLE
Summary of Header Changes

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#952]
This summarizes the following issues:
- https://github.com/tendermint/tendermint/issues/739
- https://github.com/tendermint/tendermint/issues/495
- https://github.com/tendermint/tendermint/issues/338
- https://github.com/tendermint/tendermint/issues/922

We want to make the following changes:

# Tx Results

- [x] add `LastResultsHash data.Bytes` to the header
- [x] It should be the merkle root of the `{code, data}` of the results from the previous block.
- [x] add extra methods to the `BlockStore` for storing all the results for a given block. 
- [x] Then, to prove a result, we can make one call to the blockstore to load the BlockResults and easily compute the merkle proof
- [x] Expose modifications to RPC to make it easy for users to see which transactions in a block were invalid

Note this means the invalid txs are not accessible directly in the header, they need to be queried from the RPC, but the result of the query is verifiable using the merkle root in the header

# Consensus Params

- [x] add `ConsensusParamsHash data.Bytes` to the header
- [x] allow ConsensusParamsChanges to be returned in ResponseEndBlock (https://github.com/tendermint/tendermint/issues/937)

Note this functions similar to the validator set itself: the hash is always in the header, but the contents are only stored in the `State`, and changes are propagated via ResponseEndBlock

# TotalTx

- [x] add `TotalTx int64` to the header. This is the total number of txs in the blockchain

It's a useful thing to easily be able to know how many transactions have been sent and also provides every transaction a global integer index

# Versioning

- [x] add `TendermintVersion string` to the header - contains the Tendermint version
- [ ] add `AppVersion string` to the header - contains the App version
- [ ] when serializing a block, prefix the go-wire encoding with a version byte. This byte can later be used to determine which data structure we should be deserializing into 

# Evidence

- [x] add `EvidenceHash` to header - but see the open PR that does this (https://github.com/tendermint/tendermint/pull/592)

**Comment by ethanfrey** [comment]
Question about `Expose modifications to RPC to make it easy for users to see which transactions in a block were invalid`

AFAIK, we would have to return all results as you designed above. Requested was a bitmask in the header (which I think is too much for the header). Suggestion is to add a bitmask of tx (1=success, 0=failed) and add this to the merkle tree stored under LastResultsHash.

Not much extra space and allows a separate provable endpoint to return such a bitmask (usecase was to see which were successful, likely to efficiently filter all good tx to be indexed somewhere else).

**Comment by ethanfrey** [comment]
Also, I guess the tx should be indexed by hash? Or by index? 

Index is smaller and only way with SimpleMerkleProof.
Index by txhash (or including it somehow), allows us to prove a tx in one step. 

Otherwise, it is like:
 - get tx proof from txhash to DataHash on height H
 - get result proof from result to LastResultHash on heigth H+1
2 proofs, 2 headers to see it was included and successful

I would suggest to store the txhash in the LastResultsHash values (either in key or value, both of which are part of the merkle proof). Then when calling `/tx?prove=true`, we return *either*:
 - proof -> DataHash (if block H+1 is not committed yet)
 - resultProof -> LastResultHash (if block H+1 is committed)

What do you think?

**Comment by KrzysiekJ** [comment]
What about adding proposer to block header?

**Comment by ethanfrey** [comment]
Re: consensus params (#937), which parameters should be included? This is some subset of the config file, right?

If I had to guess, I would include all these parameters: https://github.com/tendermint/tendermint/blob/develop/config/config.go#L301-L320

Is this right? Can you adjust this list?

**Comment by ebuchman** [comment]
> we would have to return all results as you designed above. 

We can have the RPC just return the bitarray, or a list of the indices and results/codes for invalid txs. It's really up to us how we want to store this efficiently. We could have an endpoint like `/block_results?height=X&invalidOnly=true` and then either return all the results or just the invalid ones, for instance.

> Re: consensus params

No, we're talking about: https://github.com/tendermint/tendermint/blob/develop/types/params.go#L13

These are now part of the Genesis file and saved in State. Very different from config!

> I would suggest to store the txhash in the LastResultsHash

This seems a bit weird to me but I see your point re querying for two headers. Let me think on it. 

> What about adding proposer to block header?

Let me think about this as well. Probably can be done but it's a bit weird since a block might be reproposed by different proposers. I suppose we can just do the "initial" proposer ?

**Comment by ethanfrey** [comment]
> We can have the RPC just return the bitarray, or a list of the indices and results/codes for invalid txs. It's really up to us how we want to store this efficiently. We could have an endpoint like /block_results?height=X&invalidOnly=true and then either return all the results or just the invalid ones, for instance

Sure, we can do anything in the rpc interface. But can we prove it to the client? (I know my obsession ;)

We can provide proofs for all invalid results for example, but we cannot prove there are no other invalid results, without returning a proof for all results, or storing some bitarray. Or some other way?

**Comment by ebuchman** [comment]
I guess if they want to know about all the results they query for the full block results and compute the merkle tree themselves?

**Comment by KrzysiekJ** [comment]
The rationale for putting proposer into header is rewarding online validators. The recently introduced absent validators field doesn’t seem to be suitable for this purpose because, AFAIK, block proposer/leader chooses which signatures will be included in block, so he can easily strip some signatures and retain only a minimum set, reducing rewards for competing validators.

If someone proposes a block but fails to propagate it enough, then I guess that from the utilitarian point of view he should be deemed offline. Therefore maybe it is better to put the successful proposer (the last one) into header?

**Comment by ethanfrey** [comment]
> I guess if they want to know about all the results they query for the full block results and compute the merkle tree themselves?

Related to @t-bast 's comment at 
https://github.com/tendermint/tendermint/issues/922#issuecomment-350200510

**Comment by t-bast** [comment]
Thanks for the interesting discussion guys.
I like @ebuchman's proposal for a block_results RPC endpoint.
I'm completely ok with asking for all results and computing the merkle tree for verification, that's something I'm already doing to verify it correctly links to my AppHash (because my AppHash only includes valid transactions and skips the invalid ones).

**Comment by jaekwon** [comment]
Propose 1: “Updates” instead of “Changes” because it’s imo the more canonical form.  I’m not too worried either way, but lets choose 1 word to refer to the general concept of validator sets changing/updating.

Propose 2: s/BlockSizeParams/BlockSize/g etc.
ConsensusParams.BlockSize.MaxBytes, not
ConsensusParams.BlockSizeParams.MaxBytes.

**Comment by jaekwon** [comment]
@KrzysiekJ 
> The rationale for putting proposer into header is rewarding online validators.

While I agree that we should put the proposer in the header, watch out for using this field in rewarding online validators.  It's better to use the Commit signatures to see which validators are online, because e.g. when 30% of validators happen to be slow, 4% of validators can skip a proposer for profit, so the incentive to censor block proposals become greater.

That said we will still reward the propose a small amount to incentivize proper mempool functioning.

**Comment by jaekwon** [comment]
oops didn't mean to close.

**Comment by KrzysiekJ** [comment]
Thank you @jaekwon for this remark. Actually for some PoS schemes rewarding proposer may not be necessary at all, as improper mempool functioning would diminish currency value, which is typically a disincentive in itself. In such case, #574 would become less important.

**Comment by ebuchman** [comment]
All of this has been implemented except versioning and proposals. I'll open separate issues for them. Thanks all!

Proposals: https://github.com/tendermint/tendermint/issues/1134
Version: https://github.com/tendermint/tendermint/issues/1135
