### ISSUE TITLE
abci: introduce proof verification channel

### ISSUE THREAD

**Issue by tac0turtle** [tendermint/tendermint#9619]
## Summary

Currently tendermint has a proof runtime where applications need to register a proof in order for tendermint to know how to verify proofs, while this is a fair design, tendermint should not need to worry about application based concerns. 

## Problem Definition

Tendermint should ask the application how to verify the proof instead of knowing how to do itself. 

## Proposal

Introduce a new verification abci method which allows applications to specify how to verify proofs for the light client. 

Essentially here https://github.com/tendermint/tendermint/blob/4552cfc2714f774d2f56a9f32e42576a46ed71bb/light/rpc/client.go#L180, tendermint would ask the application how it wants to verify the type of proof. This could help when client decide to write clients in other languages.

**Comment by cmwaters** [comment]
I'd like to add some more context as to what the higher level goal is and why it is important.

Most users of a blockchain don't care about all the transactions in a block nor all of state. They're only interested in a few transactions and some specific areas of state (like my account balance). However, to verify that their transaction made it into a block, that it was executed correctly and to verify what the current state is, they must run a full node that involves following consensus and executing every transaction.

The cosmos ecosystem still runs in a highly trusted environment. We trust Keplr to gossip our transactions and we trust it to tell us what out account balance is. Heading in a direction of greater decentralization (or less single points of failure), users should have the option to verify the information that is important to them with a higher degree of security.

Light clients, which I believe date back originally to the bitcoin whitepaper were an attempt to create a more lightweight alternative. In Tendermint, the light client is used to verify headers (by verifying the signatures of the validators that signed the header). Headers include the data hash and app hash. Tendermint builds a merkle tree for each transaction, the data hash being the root of the tree. The merkle tree allows users to verify that a single transaction was in a block. Therefore to verify that a transaction made it into a block, the light client will query via RPC a full node for the tx and the proof and using the data hash from the header at the height of the transaction verify that it was included. 

With checking the validity of the some subsection of state, a similar process is used: The light client uses RPC to query the existence of some data (by actually using a "path" to that part of state). The full node runs `abci.Query()` and gets the data from the application plus some meta data and a means of proving that the returned data is "on chain". The problem is that the light client doesn't know how the application creates these proofs and how they therefore should be verified. What Tendermint does is that it assumes the same algorithm as done with blocks: i.e. that state is persisted as a merkle tree and so it takes the slice of `ProofOps` returned by the application and validates them alongside the chunk of bytes that represent the part of state against the app hash.

What's been asked here is to make verifying of the existence of state to be more generalizable. I think rather than having this as an ABCI method, the SDK should build out their own light node which wraps the light client and provides the APIs to verify state (and transactions) or more generally we should see the light client as a tool for applications to build their own light node alternative.

The other thing that has been frequently mentioned is moving much of the data transmitted via the RPC layer to the P2P layer such as validator sets, headers and proofs.
