### ISSUE TITLE
Deterministic install for tooling

### ISSUE THREAD

**Issue by ebuchman** [tendermint/tendermint#966]
Makefile uses go get. We should use a script or something to lock certain versions of the tools we install

**Comment by xcthulhu** [comment]
Here's some ideas:

(1) Use [Nix](https://nixos.org/nix/) for builds.  From wikipedia:
> Cryptographic hashes determine the exact build and run-time dependencies of every (Nix) package, and each source or binary package is represented by such a hash.
A place to start is [go2nix](https://github.com/kamilchm/go2nix), which uses git hashes for dependencies.

(2) Use [gx](https://github.com/whyrusleeping/gx);  `gx` is a golang package management system using IPFS.  IPFS dogfoods `gx` all over its codebase whenever it has an external dependency.  On the other hand, it does look from IPFS's Makefile that it doesn't use `gx` for tooling...

It's worth noting that apart from using `gx`, IPFS also has [an official Nix package](https://github.com/NixOS/nixpkgs/blob/cb059d63fde09c1ee2472fd712c75dde584d4960/pkgs/applications/networking/ipfs/default.nix).

**Comment by Greg-Szabo** [comment]
Let me expand on the topic: we need a way to 

1. Deterministically satisfy build and testing using external dependencies
These dependencies need to be **available before the build process starts**, as an executable.
Current best examples are glide and gometalinter or the go binary (we have a version requirement). Others might follow in the future.

2. Deterministically satisfy internal or library dependencies
These dependencies need to be available for the build process as a GitHub repository. They need to be a **specified version** of the repository and they need to be **able to build**.
Current best examples are tmlibs (internally managed), or go-ethereum (externally managed).

3. Deterministically build binaries
Or in plain words: if I execute the command to build, it **should not fail** because of the above. It should _never_ fail on the _develop_ or _master_ branches, since syntax errors and compilation errors were already vetted in the pull request -> CircleCI unit testing.

*When the above three points are met, _then_ we can discuss:*

4. Deterministic packaging process
This includes the binaries ZIP-ped or the RPM/DEB packages and docker images. The current challenge here are the breaking changes we introduce to the code that affect the packaging.

5. Deterministic deployment process
Deploying the binaries to S3 and updating the website is a manual process today. Deploying RPM/DEB is automated. No regular docker deployment happens today.

**Comment by Greg-Szabo** [comment]
One more idea: most of the time the build process suffers because it needs to accommodate every situation. For example it might try to automatically build glide even if it's already built. On a developer's desktop, this is extra time wasted, since the developer already set up the environment. So it's normal to introduce shortcuts to the developer's build process to cut out unnecessary dependency checks.

I'm proposing a fast-track build process for developers that cuts out on some of the dependencies. The separation of the regular build process from this fast-track would enable the developers to build their binary quickly when they're developing but it would keep the regular build process intact and working with the added dependecy checks.

This would cut out the "it works on my computer"-type responses too. If it works with the regular build process, it should work everywhere. If it only works with the fast-track build process, then it's quickly troubleshootable locally. (Most probably new dependencies were introduced.)

**Comment by jaekwon** [comment]
The installation of tools for building should be a separate process from building the code itself.

What we need to do is (1) only require glide and (2) install the remaining tools locally using glide (we don't want to install the tools to ~/gopath/bin, that causes other annoyances.

Otherwise I think it's fine to have a one-liner to install glide, since it's the only one, and its functionality shouldn't change too often.

On a related note, check https://github.com/Masterminds/glide/pull/961 which probably fixes the annoyances we've been having with `glide update`.

Another related note, I'm experimenting with a docker container to use for development: https://github.com/tendermint/devdoc . Search for 'devdoc' in https://github.com/tendermint/abci/blob/sdk2/Makefile .  The usage is:

```
make devdoc_init
make devdoc // throws you in bash, and you can do things like `make get_tools`
> make get_tools
> make get_protoc
> exit
make devdoc_save // saves the last state
make devdoc
> make  // tools and protoc exist.
```

It's just an experiment.  I'm guessing it's not worth it, and that it's better to just enter a docker container with bash and gocode all set up, and just "live" in there, but it's an interesting experiment.  Anybody have better ideas for docker development tooling?

**Comment by jaekwon** [comment]
Reference: https://github.com/tendermint/abci/pull/168

**Comment by Greg-Szabo** [comment]
> install the remaining tools locally using glide (we don't want to install the tools to ~/gopath/bin

This seems mutually exclusive. If we install using glide, glide only has access to `$GOPATH/bin`. We can't expect glide to put files under `/usr/local/bin` or any other existent path.

Bucky said earlier, that he expects $GOPATH/bin in $PATH so the Makefiles are kept clean and easy.

Should we start pinpointing gometalinter in the Makefile as `$(GOPATH)/bin/gometalinter.v2` or should we add $GOPATH/bin to the $PATH?

**Comment by greg-szabo** [comment]
Closing in favor of #1090
