### ISSUE TITLE
Overcome non-deterministic select{}

### ISSUE THREAD

**Issue by musinit** [tendermint/tendermint#9747]
## Problem Definition
There are a lot of select{} statements, which are not deterministic, if two and more channels inside receive messages simultaneously, the message from both of them will be randomly chosen. For example, reactor.poolRoutine() method with it's select{} inside.

## Why do we need this feature? 
It's important to overcome non-determinism for such a system. Determinism is a crucial feature for tendermint, I think.

## Proposal
Implement this 
![image](https://user-images.githubusercontent.com/24373601/203318992-2dfad65a-0b4d-4a68-a167-1ae72b5db9c0.png)
 
## Detailed description of requirements of implementation 
I can implement it for reactor.poolRoutine and propose a PR

**Comment by sergio-mena** [comment]
Thanks @musinit for creating this issue.

The general requirement for determinism applies to applications that are replicated via state-machine replication. In our case, this is mainly the SDK and any chain using Tendermint either via the SDK of directly via ABCI.

Tendermint itself is a consensus algorithm. While the algorithm's (abstract) steps _are_ deterministic because Tendermint belongs to that family of algorithms (there are also probabilistic algorithms to solve consensus too), the various nodes are not required to take _exactly_ the same sequence of steps at every node (which is a requirement for the application!).

So we shouldn't blindly consider any source of determinism inside Tendermint, such as the one raised in this issue, as something to _fix_.

**Comment by musinit** [comment]
ok, understood, thank you for explanation
