### ISSUE TITLE
rpc: Add gRPC support

### ISSUE THREAD

**Issue by thanethomson** [tendermint/tendermint#9751]
At present, we support a flavor of JSON-RPC as one of the primary ways of integrating with a running Tendermint node.

From discussions with users (e.g. @hdevalence), it's clear there's a need for a full gRPC interface to Tendermint. This would dramatically simplify client generation for interaction with Tendermint, and would help get around Tendermint's very odd JSON serialization quirks.

There's some context provided by [ADR-057](https://github.com/tendermint/tendermint/blob/main/docs/architecture/adr-057-RPC.md), but no clear decision was documented in that ADR. Previously, the team had decided to deprecate and remove gRPC support (see #7121 and #9683), but that decision has now been reversed.

## Definition of Done

When Tendermint provides a full gRPC interface that mirrors the functionality provided by the current RPC.

**Comment by webmaster128** [comment]
CosmJS is a happy user of Tendermint RPC which is by far the most relyable and feature complete way for us to connect to a Cosmos node. I second some of the pain points mentioned in the ADR.

When considering a Tendermint RPC successor, it would be great to not loose valuable features that we currently have. Those for me are:
- **Execllect browser support**. gRPC is a HTTP based protocol that cannot be used from a browser client 🙃 ("gRPC's complex use of HTTP/2 makes it impossible to implement a gRPC client in the browser, instead requiring a proxy." [wiki](https://en.wikipedia.org/wiki/GRPC)). Right now it is entirely unclear to me what that proxy is supposed to be and there seem to be so many options that I'm not confident this is mature.
- **RPC batching support** which is standardized, was [implemented in Tendermint in 2019](https://github.com/tendermint/tendermint/issues/3213) and [can now be used with CosmJS](https://twitter.com/CosmWasm/status/1592853559602991106). People love it as it saves many network requests when querying a lot of data at once, like a UI that shows a lot of balances.

I wonder if a custom JSON-RPC implementation is needed long term. The only non-standard functionality I am aware of is subscriptions and [ADR-075 aims to remove those](https://github.com/tendermint/tendermint/blob/main/docs/architecture/adr-075-rpc-subscription.md).

**Comment by hdevalence** [comment]
> gRPC is a HTTP based protocol that cannot be used from a browser client

This isn't really true, `grpc-web` works fine, even on the same endpoint, we use it in Penumbra, and it was a one-line change to enable support in Tonic using [`tonic-web`](https://docs.rs/tonic-web/latest/tonic_web/). Presumably the Go tooling is similar; Tendermint could just enable `grpc-web` by default.

> RPC batching support

Is this actually necessary when using native gRPC, which already multiplexes requests? It seems like a workaround for the limitations of JSON-RPC specifically.

**Comment by webmaster128** [comment]
> gRPC is a HTTP based protocol that cannot be used from a browser client

By that I mean you cannot use it directly without a proxy. This is what [grpc-web](https://github.com/grpc/grpc-web) also says: _gRPC-web clients connect to gRPC services via a special proxy; by default, gRPC-web uses Envoy._

Which was fine if there was one well established way to use gRPC from the web. But as far as I know, there are 3:
- [gRPC gateway](https://github.com/grpc-ecosystem/grpc-gateway)
- [gRPC-web](https://github.com/grpc/grpc-web)
- The [Connect protocol](https://connect.build/docs/protocol) by buf

Now [reading from buf ](https://buf.build/blog/connect-web-protobuf-grpc-in-the-browser)

> TypeScript and Protocol Buffers might seem like a natural pairing, but the gRPC ecosystem has treated the web platform as a distant afterthought. Google's grpc-web made an early attempt to solve gRPC on the web, but developing with grpc-web is miserable: [...]

and

> The [Connect protocol](https://connect.build/docs/protocol) is a simple, POST-only protocol that works over HTTP/1.1 or HTTP/2. It takes the best portions of gRPC and gRPC-Web, including streaming, and packages them into a protocol that's simple enough to debug with the network inspector.

does not exactly give me confidence that the gRPC world has figured this out yet.

> even on the same endpoint

Big if true. But how can this work and why do Cosmos nodes run those services on different ports and grpc and grpc-web endpoints are [listed in different sections in the chain-registry](https://github.com/cosmos/chain-registry/blob/8ebe2e514d0047ea7eaf4c10926e02bcf22623c6/secretnetwork/chain.json#L160-L175)?

> Is this actually necessary when using native gRPC

I'm happy for any solution that more or less allows web app devs to not worry about the number of individual requests (Otherwise they build insane things like proxy smart contracts for querying). But how native is gRPC-web really and does it preserve multiplexing?

-------------

If grpc-web is great and solves all those problems nicely and in a relyable way, I am happy. But for now I have to admit I am not convinced.

**Comment by hdevalence** [comment]
> If grpc-web is great and solves all those problems nicely and in a relyable way, I am happy. But for now I have to admit I am not convinced.

I think there's some kind of confusion. Nobody is suggesting eliminating JSON-RPC. If you like your JSON-RPC, you will be able to keep it. The suggestion is to support gRPC as well.

> > even on the same endpoint
>
> Big if true. But how can this work and why do Cosmos nodes run those services on different ports and grpc and grpc-web endpoints are [listed in different sections in the chain-registry](https://github.com/cosmos/chain-registry/blob/8ebe2e514d0047ea7eaf4c10926e02bcf22623c6/secretnetwork/chain.json#L160-L175)?

I mean, yes, it is true, like I said, we do it in `pd`.  Here are [`tonic-web` docs](https://docs.rs/tonic-web/latest/tonic_web/#enabling-tonic-services) on how to enable `grpc-web` support.  I don't know why Cosmos nodes run those services on different ports, but it's not at all a requirement.

**Comment by webmaster128** [comment]
> I think there's some kind of confusion. Nobody is suggesting eliminating JSON-RPC. If you like your JSON-RPC, you will be able to keep it. The suggestion is to support gRPC as well.

Yeah, maybe. I got the impression from the ADR that was linked but that might be outdated. I have no issue with adding gRPC support. It's actually a great idea. I'm just try to defend JSON-RPC because it actually works very good for many users. Also I'd like to avoid turning the JSON-RPC into a second class wrapper layer around gRPC that breaks things left and right like we have seen with the "LCD"/"REST" API in Cosmos SDK. And I guess such things are tempting as devs usually do not wish to maintain two independent API implementations.

> we do it in `pd`. Here are [`tonic-web` docs](https://docs.rs/tonic-web/latest/tonic_web/#enabling-tonic-services) on how to enable `grpc-web` support. I don't know why Cosmos nodes run those services on different ports, but it's not at all a requirement.

That's great! I also found some ressources on the web stating that you can run gRPC and gRPC-web as one service, sharing one TLS setup. Sounds like some internal switch between the two protocols. Would be great to see that on Cosmos SDK as it will reduce friction for users and node operators.

**Comment by thanethomson** [comment]
> I think there's some kind of confusion. Nobody is suggesting eliminating JSON-RPC. If you like your JSON-RPC, you will be able to keep it. The suggestion is to support gRPC as well.

We intend on making this an additive change, yes - i.e. implementing gRPC support _in addition to_ the JSON-RPC support (the latter of which will be improved by porting across @creachadair's work on implementing ADR-075).

**Comment by webmaster128** [comment]
Sounds great, thanks for the clarification!

**Comment by hdevalence** [comment]
Looks like this was closed automatically?

**Comment by hdevalence** [comment]
Ah, never mind, this is on the dead fork, not the live CometBFT repo, my mistake.
