### ISSUE TITLE
SUICIDE vm opcode should create a tombstone.

### ISSUE THREAD

**Issue by jaekwon** [tendermint/tendermint#98]
'commit a7ecdd10de2acd3a1c14d7b042bc4112075da7b5' 
state/block_cache.go removed the sanity check in UpdateAccount().
Instead of checking the "removed" flag in the BlockCache, I think what we need to do is check a flag in the Account structure, so that the same policy is in effect across blocks.

**Comment by ebuchman** [comment]
I'm not seeing that commit removing the sanity check. So the problem is strictly with a SendTx/CallTx/CALL to the contract after but in the same block as the suicide, yes? What's the intended functionality - should that be explicitly forbidden? So UpdateAccount should return an error (ie this account has been removed and is unrecoverable ... we're helping you avoid shooting yourself in the foot with an inprotocol error)

**Comment by jaekwon** [comment]
Oh you're right. I meant to remove that sanity check.
The problem is that the behavior is different whether a send/call/CALL to it happens in the same block (via two transactions... one suicide, and the next a send/call/CALL) or whether it happens in two blocks (separated by zero or more blocks).

Yeah I think it should return an error or panic after checking a tombstone, e.g. something that persists beyond a suicide.

**Comment by ebuchman** [comment]
ok so I added a partial test for this in https://github.com/tendermint/tendermint/pull/133 - if you CallTx a suicided contract, its as if you're calling a non account, which is a valid tx for which you lose your fee and UpdateAccount is never called.

So really the question is should we allow SendTx/CALL to a suicided address? If no, we add a `tombstone` bool to every account. If yes then we amend UpdateAccount so that if removed is true but the update is for an account with a nil pubkey and 0 nonce then we allow it (ie it was just created by a SendTx or CALL).

The former option may be more user friendly but partially defeats the purpose of suicide since the account hangs around in the tree forever. It will probably also require more complicated changes than the latter option, which is definitely simpler and for which I will include a fix and test in https://github.com/tendermint/tendermint/pull/133
