### ISSUE TITLE
p2p over kcp

### ISSUE THREAD

**Issue by faddat** [tendermint/tendermint#9892]
After some serious grinding, I have kcp working.

* gfw defiant
* faster round trips
* fec support
* more peers with less bandwidth
* drop-in replacement for tcp in tendermint

If we are serious about improving p2p performance, this is a very good path forward, and requires only a little bit more cleanup than what is in the PR.  For practical reasons I did this on the v0.34.x series, but should be pretty easy to apply to main.

**Comment by thanethomson** [comment]
Please expand on this issue with more details so that it's more accessible to a broader audience, e.g. what are "KCP", "GFW", "FEC", etc.

Also, is this purely a transport-layer consideration, or does it have any impact on the logical P2P facets of each sub-protocol implemented in Tendermint? See #9573.
