### ISSUE TITLE
Investigate how to optimize transaction propagation.

### ISSUE THREAD

**Issue by lasarojc** [tendermint/tendermint#9925]
In this task we investigate how to optimize the propagation of transaction information, i.e., transactions in the Mempool.
This task takes as input the results of #9922 and previous discussion, such as #9050

Tasks
- [ ] Investigate solutions used by other protocols
    - Narwhal
    - Solana
    - Celestia
    - Other approaches

DoD:
- We identified alternatives to how to propagate transactions that may be applied to Tendermint and have an initial comparison of pros and cons of each alternative. This data serves as input to an ADR to address the problem.

References:
  - Solana: [gulf-stream: solanas mempool less transaction forwarding protocol](https://medium.com/solana-labs/gulf-stream-solanas-mempool-less-transaction-forwarding-protocol-d342e72186ad)
  - #9050
  - Narwhal
      - https://github.com/MystenLabs/narwhal
      - https://decentralizedthoughts.github.io/2022-06-28-DAG-meets-BFT/
      - https://www.youtube.com/watch?v=K5ph4-7vvHk
   -  Celestia [Content Addressable Transaction Pool](https://github.com/celestiaorg/celestia-core/blob/feature/cat/mempool/cat/spec.md) (see comment by cmwaters below)

**Comment by cmwaters** [comment]
Hey, just came across this issue. Given Celestia's expected transaction load, something I'm working on now is a content addressable transaction pool which looks to improve transaction propagation. You can find a spec on this [here](https://github.com/celestiaorg/celestia-core/blob/feature/cat/mempool/cat/spec.md). It's still in an early prototype phase but we're seeing a reduction on Celestia's 100 node network from 2GB of transactions in a ~10 minute window down to 250MB. It's generally suitable for Celestia because we expect larger transactions but perhaps this is something you can also look into.

**Comment by lasarojc** [comment]
Thank you, @cmwaters!
Added to the list of alternatives to investigate.
